---
title: "RStudio::conf() Presentation on the Data Science in Education Text"
author: "Joshua Rosenberg"
date: "8/29/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Collaboratively Authoring a Text: The Roles of Computational Tools and a Culture of Openness
 
- Ryan Estrellado, San Diego County Office of Education
- Jesse Mostipak, Teaching Trust
- Joshua Rosenberg, University of Tennessee, Knoxville
 
## Objectives

Like scientists and historians, educational researchers aim to do work that is useful and trustworthy. We want for findings from our work--based on qualitative and quantitative analytic approaches--to be the result of a systematic process that educators or policymakers find value in. Lately, there has been a lot of conversation about how reproducible research is (National Research Council, 2018). The objective of this work is to explore the topic of reproducibility through the lens of what has been termed open education science (van der Zee & Reich, 2018) in the context of a design-based effort to collaboratively write an open text.

The topic of reproducibility has been the topic of conversation among psychologists (Zwaan, Etz, Lucas, & Donnellan, 2017), but also of scholars in, for instance, special education research (Cook et al., preprint). To these and other authors, reproducibility is closely tied to the issue of how open the entire research process is--from the planting of the seeds for an initiative for a project to sharing the findings in (open) venues. Thus, scholars have started to talk about open education science as a tenet of work in education that is trustworthy and impactful. This work considers reproducibility from the perspective that it is a consequence (and part) of a broader set of open education science practices.
 
## The Project

A design-based project aiming to develop design guidelines (Edelson, 2002) relating to open education science was carried out. The data sources are open and available to the public and to us contributors: the text and accompanying information are available here: https://github.com/jrosen48/data-science-in-education/. In particular, each of these three data sources were analyzed to generate the design guidelines: a) an issue discussing whether grade books counted as ‘in-scope’, b) planning documents and their changes reflecting changing goals for the text, and c) a chapter illustrating characteristics of literate programming.

Because the text was open the involvement of individuals from a myriad of roles in education (i.e., administrators, data analysts, teachers, and researchers) were able to contribute to the book. Results highlight how the topics include in the text were the result of input from individuals with different expertise into what data science in education is and visions of what a useful text would contain. Through valuing openness and the use of computational tools (literate programming, an open-source package for writing books, and version control), the work was possible and efficient, though not without challenges discussed as part of the presentation.
 
# Significance

This presentation highlights the potential of open educational science. Less writing on the topic has highlighted parts and stages of open science other than reproducibility, including ideals such as collaboration, welcoming contributions from newcomers, and an overarching aim of making the writing process and product widely-used. As this project aims to show, work that is open to the public has implications in terms of both the tools and culture surrounding reproducibility and open science are taken up by those involved in educational research.
 
# References

Cook, B. G., Lloyd, J. W., Nosek, B. A., & Therrien, W. J. (preprint). Promoting Open Science to Increase the Trustworthiness of Evidence in Special Education. Retrieved from https://osf.io/mh2rt/
Edelson, D. C. (2002). Design research: What we learn when we engage in design. The Journal of the Learning sciences, 11(1), 105-121.
National Research Council (2018). Open science by design: Realizing a vision for 21st century research. https://www.nap.edu/catalog/25116/open-science-by-design-realizing-a-vision-for-21st-century
van der Zee, T., & Reich, J. (2018). Open Education Science. AERA Open, 4(3),
Zwaan, R. A., Etz, A., Lucas, R. E., & Donnellan, M. B. (2017). Making replication mainstream. Behavioral and Brain Sciences, 1-50.
