---
title: "Letter to Editor"
output: html_document
---

Dear Editor,

*Data Science in Education* aims to speak about data science to individuals working in education. Particularly in educational research and data analysis settings, there does not yet exist a language for what data science is and what its potential can be. This book aims to provide a language for data science in education through both introductory and background text (i.e., what are the challenges faced by those doing data science in education; chapters 1-4). The book also involves an introduction to the R software for data analysis and a series of walkthroughs for common data and data analysis-related issues for how to address them using data science tools and techniques (chapters 5-9). Finally, the book considers what to do once one has a foundation in using data science, with discussions of how to apply and share techniques (i.e., how can one be strategic about implementing data science in educational settings?) and how educators (at the PK-12 and at the post-secondary level) can prepare others to do data science in education. 

The outline and narrative structure of the book is as-follows:

**Part 1: Chapters 1-5**

- Educators who use data science techniques face unique challenges  
- It takes a lot of people in different roles to create a good learning environment. Different education roles mean different datasets, techniques, and challenges

**Part 2: Chapters 6-10**

- Readers can learn and practice steps in the analysis process  
- The walk-throughs use education datasets that feel familiar to education workers. Readers can work through examples that feel more practical than commonly used datasets like mtcars or iris  
- Resources like R for Data Science, blog posts, and data science forums are part of the ongoing learning process

A note on the purpose of this section: This section can serve the same purpose as blog posts like this one. Readers can get practical instruction, then deepen their learning by reading more in-depth materials.

**Part 3: Chapters 11-15**

- Now that educators are familiar with some data science techniques, it's time to tackle applying and sharing those techniques at work. This is its own skill.  
- Connect the skills taught in Part 2 to the unique challenges discussed in Part 1 
- Explore how to use programming, statistics, and content knowledge in an education workplace that is new to data science  
- Explore how educators can teach today's students to prepare them for using data in future work places

The authors include administrators in K-12 education, higher education researchers and data analysts, non-profit organizations, and individuals working for K-12 education organizations. 

We believe this book has the potential to make a significant contribution to the education field and are interested in discussing publication of this book with [Editor's organization]. Would you be interested in speaking with me and my co-authors further?

Sincerely,

