---
title: "Outline Brainstorm"
author: "Ryan Estrellado"
date: "2/3/2018"
output: html_document
---

This is a place where we can collaborate on an outline and share ideas about the content of the book. 

# Opportunities of Doing Data Science in Education

# Unique Challenges of Doing Data Science in Education 
 - Combining content knowledge, programming, and statistics to solve problems is a fairly new idea
 - Some datasets are public as required by law. Others contained personally identifiable information
 - There are often no procedures in place for school districts to share data with each other in order to build context
 
# The Role of R in Data Science / Educational Data Analysis

# Foundational Skills
- Processing / preparing data
- Plotting data
- Importing / exporting data from various sources
- Modeling data
- Communicating / sharing results

# Advanced Uses
- Multi-level models 
- Text analysis
- Longitudinal analysis
 
# Building The Capacity Of Educational Data Scientists / Data Analysts

# Solutions for the Adoption of Data Science Techniques 
 - The role of listening to clarify meaningful problems that parents, teachers, and administration want to make progress on 
 - Making new datasets by combining student level data with other datasets, like testing, wellness surveys, and transportation data 
 - Developing agreements across organizations for sharing and moving data 
 - Connecting data science tools (Example: R) to tools that teachers are comfortable with (example: Excel) 
 - Building pretend datasets to code against so that projects can be open source 
 - What is an ideal multi-disciplinary analytics team for school districts? 
 
# Students Themselves Doing Data Science / Data Analysis

# Using Data In Education To Inform Policy Change