---
title: "Process Questions"
output:
  html_document:
    df_print: paged
---

This is a place where we can document the purpose, scope, and driving principles of the book. 

# Planning

If the book was successful, what would that look like and what would it do for readers?

Who is the intended audience? Once we have agreement on our audience, we can return to the question of how much content should be about the value of data science in education and how much should be practical techniques for introducing data science into an educational setting. 

Possible audiences were discussed in our Slack chat: 

 - government employees
 - policy Leaders
 - administrators from all levels of education
 - instructors 
 - school service providers 
 - students
 - parents 
 - data scientists working with education data 


Will we be discussing elementary ed, secondary ed, higher education, or some combination? 

What is the existing problem the book is trying to address?  

What are our non-negotiables in our final product? 

Is the make-up of contributors to this book sufficiently representative to respond to the need we want to address?  

Does this book address one or a combination of the following? 
 
 - teaching data science 
 - using data science in elementary, secondary, or higher ed? 
 - using data science in different types of communities/schools?  
    - low- vs. high-income neighborhoods  
    - different racial/ethnic breakdowns
    - varying levels of publicly funded resources
    - public vs. charter vs. private schools
 
# Action Related 
 
What are all the components required to complete before we can call the project "done?" 
 
What is the most efficient order to complete those in? 
 
Who is responsible for each component? 

# Notes / agenda for meeting on 2018-02-21

* Introductions
* Discuss process questions
* Discuss outline 
    * Discuss timeline

Discuss and write about common needs and experiences of three audiences:  

* People who have education backgrounds but are not employed by school systems  
* People who are employed by school systems  
* Graduate students  

Write in a way that guides readers as they progress through the learning process: 

* Reading about the concepts  
* Trying the examples  
* Applying the concepts to their own datasets and daily work  

One problem to solve is facilitating the selection of meaningful datasets for practice that effectively illustrates the concept. One solution might be maintaining a repository of reader submitted datasets that are good examples of education data and lend themselves to effective practice of the concepts. 