---
title: "Rationale"
output: html_notebook
---

# Ideas on the Rationale / Justification for the Book

There are specific opportunities and challenges that make data science in education somewhat distinct from data science more generally:

- The structure and type of data:
    - hierarchical
    - often confidential
    - needs linking to other data sources
    - often not in CSV format
    - often siloed in disparate systems 
    
- The backgrounds of educational data scientists:
    - often used or use other software (more likely SPSS / SAS / Excel but also Python)
    - face organizational challenges to adopting of R
    - have been or are educators themselves 
    - not only administrators, analysts, and researchers but also teachers and students can use data
    
- The approaches / methodologies used:
    - have to deal with messy data
    - need to respond flexibly to potential scarcity of school/community resources
    - need awarness of multiple systems to extract data (using system exports or APIs)
    - should be conscious of potential racial and gender biases in school models, and challenge not reinforce them
    - incorporate existing practices used by districts/states and highlight rationale for either using the same methods or diverging from them
    - multi-level models
    - text data
    - log-trace data
    - network models
    - time series data / longitudinal data
