---
title: "synthesize-dataset"
author: "Joshua Rosenberg"
date: "6/26/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# library(tidyverse)
# library(synthpop)
# 
# d <- haven::read_sav('/Users/joshuarosenberg/Dropbox/1_Research/SciMo/JRST\ MEP\ Paper\ Final\ Docs/esm_data.sav')
# 
# d <- dplyr::select(d, stud_ID, teacher_ID, gender, race, subject, month, day, year, signal, pactivity, enjoy, interest, good_at = good)
# 
# d <- mutate(d, date = lubridate::make_date(str_c(200, year), month, day))
# 
# d <- dplyr::select(d, stud_ID, teacher_ID, date, everything(), -month, -day, -year)
# 
# d <- mutate(d, 
#             teacher_ID = as.factor(teacher_ID), 
#             race = as.factor(race),
#             gender = as.factor(gender),
#             subject = as.factor(subject),
#             signal = as.factor(signal),
#             pactivity = as.factor(pactivity),
#             enjoy = as.vector(enjoy),
#             interest = as.vector(interest),
#             good_at = as.vector(good_at)
#             )
# 
# dd <- slice(d, 1:1000)
# dd <- dplyr::select(dd, -date)
# ddd <- synthpop::syn(dd)
# df <- as_tibble(ddd$syn)
```