# Introduction: Data science in education -- you're invited to the party! {#c01}

**Abstract**

This chapter welcomes readers and gives an overview of the book, its themes, and its structure. It walks through what it means to learn about data science in education and the complex nature of education systems. The chapter describes how we clarify the data scientist role through a series of walkthroughs that introduce foundational skills for those new to learning R, run analysis on student perceptions of learning and student performance data, and describe how to use aggregate data.


Dear Data Scientists, Educators, and Data Scientists who are Educators: 

This book is a warm welcome and an invitation to learn with a great community. If you're a data scientist in education or an educator in data science, your role probably isn't straightforward. This book is our contribution to a growing movement to merge the paths of data analysis and education. We wrote this book to make your first step on that path a clearer and a less scary. 

Whether you're a data scientist using your skills in an education job or an educator who wants to learn data science skills, we invite you to read this book and put these techniques to work in the real world. Your work in the education community will help decide how education and data science come together going forward.

## Learning data science in education

Over the coming chapters, you'll explore examples of what data science in education looks like. But first, let's talk about why data science in education is not easily definable. 

Being a data scientist in education is challenging because there is not a universal vision for that role yet. For starters, education as a field is complex. If education were a building, it would be multi-storied with many rooms. There are privately and publicly funded schools. There are more than 18 possible grade levels. Students can learn alone or with others in a classroom. Students start school, leave school, finish school, and return to school. 

This imaginary building we call education also has rooms most never see---rooms where business and finance staff plan the most efficient use of limited funds. The transportation department plans bus routes across vast spaces. University administrators search for the best way to measure career readiness. Education consultants study how students perform on course work and how they feel about class materials. 

There are many ways one *could* do data science in education, but consensus on ways one *should* do it is just starting. The "data science in education" community is still working out how it all fits together. 

Even if there was consensus, there's still the issue of learning how education systems can best use data science tools. In many education settings, school administrators and their staff have never worked with someone with the data science in education skill set -- education content knowledge, programming, and statistics [@conway2010data].

## Making the path clearer

As data science in education grows, the way we conceptualize it also needs to grow; doing so can help us advance data science in education as a discipline and speak to the unique opportunities that come with analyzing data in our domain.

With this chapter, we begin by offering a primer for data science in education, including a discussion of unique challenges and foundational skills in the programming language R. The primer continues with suggestions for how to use this text ([Chapter 2](#c02)), our definition of the data science process and what it looks like in different education roles ([Chapter 3](#c03)), and a discussion of similarities and differences between data science in education and data science in others fields ([Chapter 4](#c04)).

Next, you'll take what you've learned and apply it in education data analysis walkthroughs. The walkthroughs in this book are meant to be an example-driven approach to learning. They include recognizable and actionable demonstrations. 

The chapters in this book fall into four different themes:

**Build a foundation to use R and RStudio**

* [Getting Started with R and RStudio](#c05)
* [Foundational Skills](#c06)

**Student perceptions of learning**

* [Walkthrough 1: The Education Dataset Science Pipeline](#c07)
* [Walkthrough 5: Text Analysis With Social Media Data](#c16)
* [Walkthrough 7: The Role (and Usefulness) of Multilevel Models](#c13)

**Analyze student performance data**

* [Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective](#c08)
* [Walkthrough 8: Predicting Students' Final Grades Using Machine Learning Methods](#c14)

**Get value from publicly available data**

* [Walkthrough 3: Introduction to Aggregate Data](#c09)
* [Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data](#c10)

We'll end the book by discussing how to bring data science skills into your education role, with strategic considerations for applying data science in your job ([Chapter 15](#c15), an overview of teaching data science ([Chapter 16])(#c16)), and supplemental resources ([Chapter 17](#c17) and [Chapter 18](#c18)). 

We hope after reading this book you'll feel less alone in your journey to learn data science. We hope your experience with this book is the right balance of challenging and fun. Finally, we hope you'll take what you learned and share it with others.

## Conventions used in the book

The following typographical conventions are used in this book:

* Package names are surrounded by curly brackets: {caret}
* Function names are in `constant width` and then parentheses: `clean_names()`
* Variable names are in `constant width`: `var1`
