# Introduction 

We've heard it from fellow data scientists and experienced it many times--learning R, especially if you've never learned a programming language, is hard. Learning a programming language, like learning a foreign language, is not just about mastering vocabulary. It's also about learning norms, the language's underlying structure, and the metaphors that hold the whole thing together.

The beginning of the learning journey is particularly challenging because it can feel slow. If you already have experience as an educator or consultant, you already have efficient solutions you use in your day-to-day work. So learning to code for analysis can sometimes mean moving slowly instead of quickly with a tool you're comfortable with, like your favorite spreadsheet software. But learning how to analyze data using R is like investing in your own personal infrastructure--it takes time while you're building the initial skills, but the investment pays off when you start solving complex problems at an improved speed and scale. One person we spoke with shared this story about their learning journey: 

>"The first six months were hard. I knew how quickly I could do a pivot table in Excel. It took longer in R because I had to go through the syntax and take the book out. I forced myself to do it though. In the long-term, I'd be a better data scientist. I'm so glad I thought that way, but it was hard the first few months."

But we're here to say that learning R for your education job is doable, challenging, and rewarding all at once. We wrote this book for you because we do this work every day. We know that there's some struggle that comes with it. We're not writing as education data science masters. We're writing as people who learned R and data science *after* we chose education. And like you, learning to use R and data science to improve the lives of students, is our daily practice. Join us in enjoying all of what comes with that--both the challenge of learning and the joy of solving problems in creative ways.

# How to Use This Book 

It is really hard to draw clean boundaries around the topic of data science in 
education because people are educated in all kinds of settings and in all kinds 
of age groups. Education organizations require different kinds of staff to 
make it work, which means different kinds of data science uses. A teacher's 
approach to learning from data is different from an administrator's or an 
operations manager.

We also know that very few get paid to learn how to bring data science and R to their education jobs. If we know education and data science, you're more likely an educator working with data and looking to expand your tools. You might even be an educator who **doesn't** work with data, but who's discovered a love for learning about the lives of students through data. Either way, learning data science and R is probalby not in your job description. 

You've got a full work schedule and challenging demands in the name of improving the student experience, and an office culture that doesn't allow for regular professional development time or self-driven learning. You also have a life outside of work, including family, hobbies, and relaxation. We struggle with this ourselves, so we've designed this book to be used in lots of different ways. The important part in learning this materials is to establish a routine that allows you to engage and practice the content every day, even if in small ways that only take a few minutes at a time. That will make the content ever present in your mind and will help you shift your mindset so you begin to see even more opportunities in your daily work that can be chances for practice. 

Since there are many different readers, we believe there should be 
different ways to use the book, both as a reader and as a contributor. Here are 
some ways to use this book:   

## Read the Book Cover to Cover and Try All the Walkthroughs 

We wrote this book assuming you are just starting your journey learning R and using data science in your education job. Writing it this way allowed for a reading experience that takes you from installing R to a chance to see and practice fairly advanced data science skills like text analysis. 

If you've never written a line of R code, we welcome you to the community! We wrote this book for you. Consider reading the book cover to cover and working through the analysis walkthroughs. Remember that you'll get more out of a few minutes of practice every day than you will from long hours of practice every once in awhile. Typing code into your console everyday, even if it doesn't always run properly, is a daily practice that invites learning and a-ha moments. We know how easy it is to avoid coding when it doesn't feel successful, so we've designed the book to deliver frequent small wins to keep the momentum going. But even then, we all inevitably hit a wall in our learning. When that happens, take a break and then come back and keep coding. When daily coding becomes a habit, so does the learning.  

If you get stuck in an advanced chapter and you need a break, try going back to an earlier chapter and reviewing. It's pleasantly surprising to see how much new learning we get from going back to old material with the benefit of new experience. That kind of back-to-basics attitude is sometimes what we need to get fresh perspective on new challenges. 

## Pick a Chapter That is Useful for Your Level of Experience and Start There 

When we interviewed R users in education for this book, we chose people with different levels of experience in R, the education field, and statistics. There's a lot of variety within and across experience levels in those areas! We asked each interviewee to rate their own level of experience on a scale from 1 to 5, with 1 being no experience and 5 being very experienced. You can try this now--rate your level of experience in  

 - Using R  
 - Education as a field  
 - Statistics  

If you rated yourself as a 1 in Using R, we recommend you experience the whole book a few minutes or more as a daily practice. If you rated yourself higher than a 1, we still recommend the daily practice approach, but consider reviewing the table of contents and skimming across all the chapters first. If one or more content areas call to you first, feel free to start your daily practice there. 

For example, you may be trying to solve a specific problem using data in your education job. Some examples are analyzing student quiz scores, evaluating a school program, introducing a data science technique to your teammates, or designing data dashboards. Reflect on the nature of that problem, including the dataset you're working with, the type of data cleaning involved, the people you need to collaborate with, and the statistical techniques you'll be using. Then skim through the chapters in this book to see if any examples act as inspiration or learning for your school data challenge.

## Read Through the Walkthroughs and Run the Code 

If you have a lot of experience working with data in your education job and you have some experience using R, you might be interested in starting with the walkthroughs. Each walkthrough is designed to demonstrate basic analytic routines using datasets that look familiar to educators. 

In this approach, we suggest that readers be intentional about what they want to learn from the walkthroughs. For example, readers might pick a walkthrough that demonstrates use of an aggregated dataset, exploratory data analysis, the `ggplot2` package, or the `gather` function. Then read the walkthrough, copying, pasting, and running the code into your R console as you go. After you get code to run, experiment with the functions and techniques you set out to learn by changing the code and seeing how the results change (or what new error messages appear!). After running the code in the walkthroughs, try reflecting on the datasets, problems, and analytic routines in your education work that resemble the example in the walkthroughs. 

One last note on this way of using the book: we believe that doing data science in R is, at it's heart, an endeavor aimed at improving the student experience. This mission involves complex problems, and complex problems require many people to solve. Be sure to read other areas of the book that give context to why and how we do this work. Chapter twelve in particular explores ways to introduce these skills to your education job and invite others into analytic activities. 

# A Note on Statistics 

It's been said that data science is the intersection between content expertise, programming, and statistics. You'll want to grow all three of these as you learn more about using data science in your education job. Your education knowledge will lead you to the right problems, your statistics skills will bring rigor to your analysis, and your programming skills will scale your analysis to reach more people. A data scientist working in education who is an expert programmer and statistician but has not learned about the real life conditions that generate education data might make analysis decisions that ignore nuances. A data scientist who is an expert statistician and an education veteran won't be able to scale their analysis to have the largest possible influence on improving the student experience. A data scientist who is an expert programmer and an education veteran can only scale surface level analysis and might miss chances to draw causal relationships or predict studentoutcomes.

In this book we will spend the bulk of our time learning R by way of recognizable education data examples. But doing a deep dive into statistics and how to use them responsibly and ethically is better covered by books dedicated solely to the topic. It's hard to understate how important this part of the learning is on the lives of students and educators. One education data scientist we spoke to said this about the difference between building a model for an online retailer and building a model in education: 

>"It’s ok if I get shown 1000 brooms but if I got my model wrong and we close a school that will change someone else’s world." 

We want this book to be your go-to R reference as you start bringing data science tools into your education job. Our aim is to help you learn R by teaching it in two contexts: data science techniques and workaday education datasets. We demonstrate statistics techniques like hypothesis testing and model building. These demonstrations teach you how to run statistics operations in R using education datasets. But the explanations stop short of a complete discussion about the statistics themselves. 

We deliberately wrote within these boundaries because we believe that the technical and ethical use of statistics techniques deserve their own space. We hope that you will take a satisfying leap forward in your learning by successfully using R to run the models and experiencing the model interpretations in our walkthroughs. We encourage you to explore other excellent books like **An Introduction to Statistical Learning** as you learn the required nuances of applying statistical techniques to scenarios outside our walkthroughs.

# Contributing to the Book 

We quickly learned when planning the book that there are many ways to approach 
this topic and still we wanted to write in a way that is directly useful and 
practical for our readers in education. One way to meet this goal is to build 
procedures into the work for readers to directly contribute. We hope that as the 
book evolves it grows to reflect the observable needs of data scientists in 
education.

Our vision for the book is to be the book new data scientists in education have with them as they grow their craft. We can realize this vision best if the stories and examples in the book our based on **your** stories and examples. We've built ways for you to share with us into our process. Here are some ways readers can contribute: 

 - Submit a pull request to our 
 [GitHub site](https://github.com/jrosen48/data-science-in-education) that 
 describes a data science problem that is unique to the education setting 
 - Submit a pull request to share a solution for the problems discussed in the 
 book
 to the education setting
 - Share an anonymized dataset 