Because data science in the school setting is a relatively new phenomenon, it's understandable that school staff may be wary of how data is collected and analyzed. It's common for school staff to question how data is used, particularly if the data is used to describe staff and student performance. One of the biggest challenges that can arise is if individuals begin to feel that they are being evaluated by metrics that they feel are unclear or even unfair. Usually, "data-driven" efforts mean different things to administrators as compared to educators. To an administrator, a data-driven effort might be an endeavor to better understand the strengths and weaknesses of pre-existing systems, with an eye to eventually proposing new systems that are more efficient. To an educator, a data-driven effort might feel like an approach that masks the individuality of students by reducing them to numbers. Perhaps neither approach is exactly correct. Whereas maximizing efficiency and preserving students' individual needs should certainly be goals of educators and educational administrators, data science in education doesn't expressly serve either goal. Instead, data science is a tool that can be leveraged to help answer meaningful questions. 

School systems that want to evolve their data analysis processes into something practical and meaningful to student progress will need to do the difficult work of addressing these worries and helping all stakeholders to understand the benefits of the questions being answered with data. 

# A Reproducible Approach

One way to address concerns of data ambiguity is to build analytic processes that are open about what data is collected, how it is collected, how it is analyzed, and how it is considered alongside other data when used in decision-making conversations. This can be achieved through a number of activities, including regular conversations about analytic methods, written reports describing data collection, and receiving input about analytic goals from staff members. 

One such process for achieiving openess in data collection and analysis is called reproducible research. The concept of [Reproducible work]("https://en.wikipedia.org/wiki/Reproducibility#Reproducible_research") is the idea that a completed analysis should come with all the necessary materials, including a description of methodology and programming code, needed for someone else to run the analysis and achieve the same results. If school staff are apprehensive about how school data is collected and used, it follows that a more transparent method for using data could go some way towards putting school staff--the consumers of school data--at ease. 

An additional benefit of a reproducible approach is that it can ease in transition periods. If a data-science-in-school advocate leaves their original position, ideally, they would leave behind not just descriptions of the analyses that they did, but also the specific files needed to run the analysis again. In this way, the new individual who takes their place will be able to seamlessly transition into the new role. If asked to run "the same report I always got from your predecessor," the new person will understand immediately what files were needed to create that report and will be able to request all necessary data to generate a new version of the report.  

To implement a reproducible approach in your organization, you can start by keeping all files related to each project you do in their own folders. 

# A Self-Driven Analytic Approach 

One challenge of adopting data science strategies in educational contexts is that in some environments, there is a lack of precedent - it is not common, for example, for a teacher to be conducting analyses on data. However, it's not necessary to wait for a district-wide or state-wide initiative to begin to implement the techniques you will learn in this book.

An organization should encourage their staff to do their own data analyses primarily for the purpose of testing their own hypotheses about student learning in their classrooms and to directly guide decisions about how they deliver instruction. There are at least two benefits to this approach. First, staff begin to realize the value of doing data analysis as an ongoing inquiry into their outcomes, instead of a special event once a year ahead of school board presentations. Second--and more important for the idea of reducing apprehension around data analysis in schools--school staff begin to demystify data analysis as a process. When school staff collect and analyze their own data, they know exactly how it is collected and exactly how it is analyzed. The long-term effect of this self-driven analytic approach might be more openess to analysis, whether it is self-driven or conducted by the school district.

Building and establishing data governance that advocates for an open and transparent analytic process is difficult and long-term work, but the result will be less apprehension about how data is used and more channels for school staff to participate in the analysis. Here are more practical steps a school district can take towards building a more open approach to analysis: 

 - Make technical write-ups available so interested parties can learn more about how data was collected and analyzed 
 - Make datasets available to staff within the organization, to the extent that privacy laws and policies allow 
 - Establish an expectation that analysts present their work in a way that is accessible to many levels of data experience 
 - Hold regular forums to discuss how the organization collects and uses data

# Unique challenges

Educational data science is a new domain. It presents opportunities, like those discussed in the [previous chapter](#03-ds-role.Rmd), but also some challenges. These challenges vary a lot: We consider doing data science in education to include not only access, processing, and modeling data, but also social and cultural factors, like the training and support that educational data scientists have available to them. These challenges, then, range from the very general (and common to *all* domains in which data science is carried out) to very particular to educational data science. These are discussed in the remainder of this chapter.

## Challenges common to doing data science in any domain 

One challenge for educational data scientists is common to data scientists in other domains: Combining content knowledge, programming, and statistics to solve problems is a fairly new idea. In particular, the amount of data now available means that programming is often not only helpful, but necessary, for stakeholders to use data in education. Programming is powerful, but challenging; many of us in education do not have prior experience with it. Despite this challenge and the difficulty of writing the first few lines of code, there is good evidence, and many examples, that even those of us without prior programming experience can learn. 

It's not necessary to have a computer science background or even any formal training related to coding. The great thing about entering a field so flexible as data science is that you are joining a vast crowd of individuals who are self-taught. You will find that there is a very supportive online community to help as you learn through this book. 

## Lack of processes and procedures 

Other challenges are more about the process and practice of doing data science in the educational context specifically. Education is a field that is rich with data: survey, assessment, written, and policy and evaluation data, just for a few examples. Nevertheless, sometimes, there is a lack of processes and procedures in place for school districts and those working in them to share data with each other in order to build knowledge and context. Moreover, in academic and research settings, there are not often structures in place to facilitate the analysis of data and sharing of results. This means that there can be silos of information - one group could do a survey, for example, and another group could not hear about the results or even the fact that the survey happened. The good news about this is that many educational organizations are curious and passionate about supporting student success, so it's likely that even if many separate data collection efforts are being implemented (rather than one unified strategy), you will not be dealing with the problem of "I don't have enough data to work with." As a pioneer for data science in your organization, you can help to clarify these redundant processes and can offer your skills to help make sense of the wealth of information already being gathered.
 
## Few guidelines from research and evaluation

While there is a body of past research on *students*' work with data (see Lee & Wilkerson, 2018, for a review), there is limited information from case- or design-based research on how others--teachers, administrators, and data scientists--use data in their work. In other words, we do not have a good idea for what best practices in our field are. This challenge is reflected in part in the variability in the roles of those who work with data. Many districts employ data analysts and research associates; some are now advertising and hiring for data scientist positions. 

## Limited training and educational opportunities for educational data science

Educational data science is new. At the present time, there are limited opportunities for those working in education to build their capabilities in educational data science (though this is changing to an extent; see Anderson and colleagues' work to create an educational data science certificate program at the University of Oregon and Bakers' educational data mining Massive Open Online Course offered through Coursera). 

Many educational data scientists have been trained in fields other than statistics, business analytics, or research. Moreover, the training in terms of particular tools and approaches that educational data scientists are highly varied. However, we believe this diversity of training creates unique opportunities for the development of data science in education as a field. Indeed, educators' diverse training and backgrounds positions them to tackle educational challenges creatively.
    
## The complex and messy nature of educational data

Another challenge concerns the particular nature of educational data. Educational data are often hierarchical, in that data at multiple "levels" is collected. These levels include classrooms, schools, districts, states, and countries - quite the hierarchy! In addition to the hierarchical nature of educational data, by their nature, these data often require linking with other data, such as data that provides context at each of the aforementioned levels. For example, when data is collected on students at the school level, it is often important to know about the training of the teachers in the school; data at the district level needs to be interpreted in the context of the funding provided by the community in terms of per-pupil spending and other, for example. A final aspect concerns the *type* of data collected. Often, educational data is numeric, but just as often, it is not: It involves characteristics of students, teachers, and other individuals that are categorical(<<<explain what categorical means>>>); open-ended responses that are strings (<<<<explain what strings means>>>>); or even recordings that consist of audio and video data. All of these present challenges to the educational data scientist. 
    
## Ethical and legal concerns

Related to the complex and messy nature of educational data is its confidential nature. At the K-12 level, most data requires protections because of its human subjects focus, particularly because the data is about a protected population, youth. A closely related issue concerns the aims of education. Those working in education often seek to improve it and often work to do so with a scarcity of school and community resources. These ethical, legal, and even values-related concerns may become amplified as the role of data in education increases. They should be carefully considered and emphasized from the outset by those involved in educational data science. If you feel resistance in your organization as you begin to adopt the principles you learn in this book, you might begin by offering to analyze "de-identified" (anonymous) data. In this way, you could show your administration what is possible and might foster additional buy-in further down the road.

## Analytic challenges

Due to the challenging nature of educational data, analyzing educational data is hard, too. The data is often not ready to be used: It may be in a format that is difficult to open without specialized software or it may need to be "cleaned" before it is usable. (In data science, "cleaning" data refers to reorganizing or restructuring the dataset to make it easier to analyze. This process would be analogous to if you received an Excel spreadsheet but the columns were in an order that didn't make sense to you, or one column was duplicated in the spreadsheet. The process you'd go through to reorganize the data to make it logical is data cleaning.) Closely related to the ethical and legal challenges, educational data scientists should be conscious of potential racial and gender biases in school models, and challenge not reinforce them. Because of the different *types* of data, the educational data scientist must often use a variety of analytic approaches, such as multi-level models, models for longitudinal data, or even models and analytic approaches for text data. 

## Not just challenges

While there are many challenges to working with educational data, there are many opportunities as well. Once they unlock the power of data science to reveal insights about their organizational context (their students, their teaching, etc.), many educators will become more interested in gathering more data and continuing on this path. Data science becomes a useful tool to help connect with the purpose of your job. Once you begin to rely on data science, it can be hard to stop!

