---
title: "foundational_skills_draft"
author: "Jesse Mostipak"
date: "September 21, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# THOUGHTS
What are we uniquely positioned to provide guidance and insights on, and what is 
best outsourced to an additional resource?   

What does the reader know?  


## For separate chapter?

* Installing R//RStudio
* Environment//pane layout
* Customizing IDE//environment
* Help documentation
* When you come across something new//unfamiliar
* Downloading//accessing the data used in this book

## From audit - foundational skills:

Make an illustration that shows how these are related, highlighting where in the process we are (when talking about a specific component). Help readers develop a mental model.

* Projects
    + What are they?
    + How do I use them?
    + Why should I use them?
    
* Packages
    + What are they?
    + How do I find them?
    + How do I load them?
    + How do I explore them? (CRAN, vignettes, Help docs, blog posts)
    + When should I write my own?

* Functions
    + What are they?
    + Why do I need them?
    + How do I know which arguments to provide?
    + How are they related to packages?
    + When should I write my own?
    + How do I write my own?

* Data (nest in DS workflow) - embed chaining functions
    + How do I import it?
    + How do I explore it? 
    + How do I tidy it? 
    + How do I transform it?
    + How do I visualize it?
    + How do I model it?
    + How do I communicate it?
    + Do data structures matter?
    + Do data types matter?
    + Tidy data



## Chapter overview
This chapter is designed to give you the skills and knowledge necessary to _get started_ in any of the walk through chapters. Our goal is to get you working with R (using the RStudio IDE) through applied examples as quickly as possible.  
Each chapter also has its own supplemental *Foundational Skills* section, which is intended to bridge the gap between material covered in this chapter and the material covered within a specific walk through.  

Please note that this chapter is not intended to be a full and complete introduction to using R for data science. There are many excellent resources available which provide this kind of instruction, and we've listed them for you on page [AAA] in the **Resources** section [link for bookdown version].  

## Mental model

## Data
You're likely reading this book because you have some data - in a spreadsheet, data base, written on a piece of paper, or otherwise - that you'd like to analyze. 

## Project

## Package

## Function



