---
title: ""
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, cache = F)
```

# Background

A common situation encountered when using data for analyzing the education sector, particularly for analysts who are not directly working with schools or districts, is the prevalence of aggregate data. [Aggregate data refers to numerical or non-numerical information that is (1) collected from multiple sources and/or on multiple measures, variables, or individuals and (2) compiled into data summaries or summary reports, typically for the purposes of public reporting or statistical analysis.](https://www.edglossary.org/aggregate-data/) Example of publicly available aggregate data include school-level graduation rates or state test proficiency scores by grade and subject.

These datasets are large, lagging, and often suppressed to protect privacy. Because of their coarseness, they can be difficult to use in decision-making. However, these datasets are available to analysts for gleaning insights about education and can be used for landscape analyses or to supplement other analyses.

# The Data

### Understanding Trends

### Making Comparisons

### Finding Inequities












