# Learning More

While this book aims to serve as an introduction to data science in education, there is much more to learn.

## How to learn more: Work in the open

Sharing one's work in the open is a great way to learn more. We discuss how welcoming others, sharing one's work, asking for and providing help, and taking a growth mindset are ways to learn more

### Welcoming others

One strength of the data science community (at least the corner of it that the authors of this book occupy) is that it can be a welcoming place. To the extent that the data science community is this - a welcoming place - it is due to the hard work of many of the people in the data science community. In order for the data science community to continue to be welcoming - and to be more welcoming to those for whom its currently not - it's important for all of us to continue to build a data science community that is inclusive of those who wish to be involved. Especially to those of us in education, there are many opportunities to welcome others. One thing to be aware of: You may end up liking data science so much that you become an evangelist (and may, if you are like us, on occasion, make people think you are a bit crazy for R!). This is one thing to keep in mind as regards welcoming others: People will want to use data science at different times and for different reasons. Keeping this in mind can keep one's focus on welcoming those who are already interested and ready to learn more. Welcoming others has the side benefit of positioning you as someone with (even if it is still-developing) expertise in data science and R. Teaching others - or even helping others to get started - is a great way to learn more about one's understanding and to learn more in the process.

## Sharing one's work

A great way to learn more is to share one's work in the open. The first concern that many of us have about sharing our work in the open is that it is imperfect. This is a dilemma that everyone manages differently; some data scientist's blog posts are very polished and article-like, whereas others are comfortable sharing ideas-in-progress or shorter posts. Especially for sharing work related to data science, there are blogging platforms that make it easy to publish code, its output, and text. Hill has a great introduction to getting up and running with Blogdown [here](https://alison.rbind.io/post/up-and-running-with-blogdown/).

## Asking for and receiving help

There are a number of platforms for asking for and receiving help that can be a great place to learn more. Questions and answers from sites such as [R Studio Community](https://community.rstudio.com/) and [Stack Overflow](https://stackoverflow.com/) are often among the first items that are returned from a search on a topic. Asking one's own question on these platforms is a great way to get help specific to the problem you are facing; one helpful strategy when asking a question is to include a *reprex*, a reproducible example. See Bryan's page with resources related to reprexes [here](https://community.rstudio.com/t/video-reproducible-examples-and-the-reprex-package/14732). Of course, answering questions is also a great way to help others - and to learn more about the challenges others face or how to approach specific problems in the process.

## Adopting growth mindset

Doing data science and using R are hard. Moreover, both are changing rapidly and it can feel difficult to keep up.

We suggest taking a *growth mindset* to learning data science. In Dweck's characterization, when it comes to our capabilities, we can think of ourselves as *being* (and *not being*) mathematics or reading people, with this being an unchangeable part of who we are. Conversely, we can think of ourselves as being more or less capable depending on how much we want to be, who we are around, and how much effort we exert. The former way of thinking is a *fixed* mindset, whereas the latter is a *growth* mindset. As educators, we would be remiss not to mention some of the critiques (and concerns) about focusing exclusively on a growth mindset (see this post [here](https://www.edweek.org/ew/articles/2015/09/23/carol-dweck-revisits-the-growth-mindset.html)), but it can be a useful idea when used narrowly and as a spark to push further and to learn more. 

We would like to suggest that having a growth mindset is especially helpful for learning more about data science. Partially, this is because what data science is is still being discussed: and so nobody is born a data scientist! More importantly, individuals come to data science - and make contributions to data science - with many different backgrounds, many of them unrelated to STEM (Science, Technology, Engineering, and Mathematics) backgrounds. This is a strength of the data science field as it exists now and we think this should be nurtured.

## Books and Resources

There are some books and resources we recommend.

- [Doing data science with R](https://r4ds.had.co.nz/) by Wickham and Grolemund (2017)
- [Big magic with R: Creating learning beyond fear](https://speakerdeck.com/apreshill/big-magic-with-r-creative-learning-beyond-fear) by Hill (2017)

## Courses and Communities

- [#r4ds](https://medium.com/@kierisi/r4ds-the-next-iteration-d51e0a1b0b82) (see a talk at rstudio::conf() [here](https://resources.rstudio.com/rstudio-conf-2019/r4ds-online-learning-community-improvements-to-self-taught-data-science-and-the-critical-need-for-diversity-equity-and-inclusion-in-data-science-education) by Maegan (2019)) 
- [Data science for social scientists](http://datascience.tntlab.org/) by Landers (2019)
- [University of Oregon Data Science Specialization for the College of Education](https://github.com/uo-datasci-specialization) by Anderson (2019)