# Teaching Data Science

This book is focused on the application of data science to education. In other words, this book focuses on how to apply data science to questions of teaching, learning, and educational systems. The previous chapters have addresses these topics narratively and in the form of walk-throughs for common questions (or problems) and the types of data encountered in education. 

While this book is focused on applying data science to education, an important consideration for data science is how to teach others about it. This is particularly the case for a book that is by a team of authors who are involved in education. Also, we expect readers of this book - many who will also be involved in education - will be interested in teaching others about data science.

This chapter, then, focuses on teaching data science to others. This chapter is organized around three topics, which progress from concrete and specific (with reference to pedagogical approach we used to guide how we wrote this book) to more general ideas and findings from educational research about teaching and learning.

<!-- Not sure this organization works - may want to move general strategies first or second, and have teaching data science be last? -->

1. The pedagogical principles this book is based upon
1. Strategies for teaching data science
1. General strategies related to teaching and learning

## The pedagogical principles this book is based upon

As the authors of a book about data science in education - and readers of books that taught us about data science - we considered what would make it effective for our readers when we set out to write it. The result of this process was a pedagogical framework that consists of three principles: problem-based learning, differentiation, and universal design. We consider each of these in turn.

### Problem-based learning 

Problem-based learning (PBL) is a method of instruction that presents learners with a real-world challenge in which they must apply their skills and knowledge to solve. We applied this principle to the design of this book through including walk-throughs for common questions with respect to data science and education. Whereas some topics may benefit less from such an approach (and the inclusion of walk-throughs), for data science, we believe this is important because we do not have all of the right answers in this text. Moreover, there is not one right statistical model or algorithm, a technique to write code or even software and tools to utilize. 

Thus, the text features walkthroughs that reflect the types of challenges that educational data scientists may encounter in the course of their work: readers may choose to go about approaching the analysis of the data used in each walkthrough differently. At the end of walkthrough, there exist exercises that provide the opportunity for readers to extend and apply the ideas presented in the chapter. Moreover, the challenges are structured in such a way that readers return to some of them, but with different aims, over the course of the book.

<!-- To what extent do we need to change the walkthroughs or their order to make this accurate? -->

<!-- Wonder if we add another paragraph about how others can apply problem-based learning in any setting? -->

### Differentiation

Differentiation is a method for providing multiple pathways for learners to engage with, understand, and ultimately apply new content and new skills. To differentiate this text, we first created personas for who we expected to be common groups of readers of the book (see [Wilson, 2019](http://teachtogether.tech), for an example). We then differentiate the book by recognizing and providing background content/skills (either explicitly or through reference to other resources), embedded checks for understanding, and recommendations for where to begin based upon prior expertise. We also provide screenshots that are annotated and reflective of the content in the text to help to show readers how they are able to use what they are reading about.

<!-- Say more about this - specifically how we use the user personas? -->

Part of differentiating this book concerns for whom we are differentiating it. We consider inclusivity (in terms of who belongs as a part of the audience for this text and how this broader view of who participates in data science implies the types of challenges, topics, and data that we include in the book) and accessibility (technically, in terms of how a wide audience of readers is able to access and use the book, as well as in terms of the ways in which the content is written based on the unique assets that those in education bring) along with how we differentiate the book. 

<!-- Same as above - do we say more about how other teachers can differentiate their instruction? -->

### Universal Design 

Universal design is a series of principles which guide the creation of spaces that are inclusive and accessible to individuals from all walks of life regardless of age, size, ability, or disability. While traditionally applied to physical spaces, we have extended these principles to the creation of this book in such a way that the text and accompanying materials will be designed for individuals from all walks of life, regardless of educational level, background, ability, or disability. 

Many of the seven guiding principles of Universal Design are readily transferable to the creation of a text, such as equitable use, flexibility in use (aided in large part through differentiation), simple and intuitive use, perceptible information, and tolerance for error.

<!-- Say more regarding how we apply these? -->

<!-- Also say how this can be applied more generally? -->

### Working in the Open

We started writing this book in the open, on [GitHub](https://github.com/data-edu/data-science-in-education). This allowed us to share the book as it developed. Writing the book in the open also allowed others from the wider educational data science and data science community to contribute. These contributions included writing sections of the book in which contributors had specific expertise, asking clarifying questions, and, even, creating a logo for the book which informed our choice of a color palette. We decided to write this book in the open after witnessing the success of other books on data science (such as Wickham's (2019) [Advanced R](https://adv-r.hadley.nz/) book.

## Strategies for teaching data science

You may be interested in teaching others' data science. You may be doing this informally (such as by teaching a colleague with whom you work in your school district or organization), in a formal environment (such as a class on data science for educational data scientists or analysts), or in some setting in-between (such as a workshop you are asked to provide). There is some research on teaching data science, as well as practical advice from experienced instructors that can inform these efforts, which we detail in this section.

### When it comes to writing code, think early and often

It is important to get learners to start writing code early and often in learning activities.

### Don't touch that keyboard!

Resist helping learners to the point of hindering their learning.

### Anticipate issues (and sacrifice accuracy for clarity)

Don't worry about being perfectly accurate early on.

### Start lessons or activities with visualizing data

There are examples from data science books (Wickham & Grolemund, 2017) and past research (e.g., Lehrer, Kim, & Schauble, 2007; see Lehrer & Schauble, 2015, for more examples) that suggests that starting with visualizing data can be benefician in terms of learners' ability to work with data. Wickham and Grolemund (2017) write that they begin their book, *Data Science Using R*, with a chapter on visualization, because doing so allows learners to create something that they can share immediately, whereas tasks such as loading data can be rife with issues - and does not immediately lead learners to have a product they can share. Lehrer, Kim, and Schauble (2007) show how providing students with an opportunity to invent statistics by displaying the data in new ways. This led to (productive) critique among fifth- and sixth-grade students and their teacher.

### Involve students in both sides of the coin: Collecting and analyzing data - or discuss how the data was collected

This can open up critique

### Push students to explain variation in data (and to generate models) of data

Often, learners are content to simply present data.

### Consider representation and inclusivity in your teaching

This includes examples, data sets.

### Provide a home base for learners to access resources (and to learn more)

Hyperlinks are powerful.

### Draw on other resources

Other resources include the following and the general strategies discussed in the next section. 

- [GAISE Guidelines](https://www.amstat.org/asa/education/Guidelines-for-Assessment-and-Instruction-in-Statistics-Education-Reports.aspx)
- [Ten Quick Tips for Teaching Programming](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006023)
- [Teaching Tech Together](http://teachtogether.tech/#the-rules)
- [Data Science for Undergraduates](https://www.nap.edu/catalog/25104/data-science-for-undergraduates-opportunities-and-options)

## General strategies related to teaching and learning

- [How People Learn](https://www.nap.edu/catalog/24783/how-people-learn-ii-learners-contexts-and-cultures)
- [Small Teaching](https://www.amazon.com/Small-Teaching-Everyday-Lessons-Learning/dp/1118944496)