If you're reading this book cover to cover, by now you've been through quite a journey. 
You've learned about the unique challenges of doing data science in education, you've built up some basic coding and statistic techniques to begin developing and using an analytic routine, you've practiced your skills on education datasets, and you've worked out a plan to introduce data science into your education organization over time. So what's next? 

Like most industries, education and data science are constantly evolving moving through trends and new knowledge. That means that today's tools and best practices are tomorrow's old way. To keep up with changes, it is important develop and get comfortable with a learning routine. Sometimes this is about learning something new, sometimes this is about deepening expertise in an area you're just starting in, and other times it's about revisiting a skill you've mastered long ago. 

You'll need to use your intuition to find the areas you want to deepend your knowledge. When you feel it, go there and dive in. Remember that learning is a combination of reading, doing, talking about, walking away, and coming back. Here are more resources to help you continue on your journey: 

# Resources used in the creation of this text

Penuel et al (2016, April). *Findings from a national study on research use among school and district leaders*. Retrieved from [http://ncrpp.org/assets/documents/NCRPP_Technical-Report-1_National-Survey-of-Research-Use.pdf](http://ncrpp.org/assets/documents/NCRPP_Technical-Report-1_National-Survey-of-Research-Use.pdf). A survey of 733 school principals and district leaders within US mid-sized and large school districts, focused on how educational leaders use research to inform their decision-making.

# Statistics 

James et al (2015). *An introduction to statistical learning with applications in R*. New York, NY: Springer.
Bruce, P. & Bruce, A. (2017). *Practical statistics for data scientists*. Sebastopol, CA: O'Reilly.

# Programming With R

Wickham, H. & Grolemund, G. (2017). *R for data science*. Sebastopol, CA: O'Reilly.
Teetor, P. (2011). *R cookbook*. Sebastopol, CA: O'Reilly.
Bryan, J. & Hestor, J. *Happy git and github for the useR*. Retrieved from [https://happygitwithr.com](https://happygitwithr.com)

# Data Visualization 

Tufte, E. (2006). *Beautiful evidence*. Cheshire, CT: Graphics Press LLC. 
Healy, K. (2018). *Data visualization: A practical introduction*. Princeton, NJ: Princeton University Press.
Chang, W. (2013). *R graphics cookbook*. Sebastopol, CA: O'Reilly.

# Package Vignettes

*Introduction to dplyr*. Retreived from [https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html)
*A short introduction to the caret package*. Retrieved from [https://cran.r-project.org/web/packages/caret/vignettes/caret.html]([https://cran.r-project.org/web/packages/caret/vignettes/caret.html)

# Online Communities

#rstats
#tidyverse
#RLadies
*RStudio community*. Retrieved from [https://community.rstudio.com](https://community.rstudio.com)

# Education Books

Applying data science in education, because it's new, requires that you look for best practices that can be acclerated by the tools of data science. 

Bryk et al (2015). *Learning to improve: How America's schools can get better at getting bettere*. Cambridge, MA: Harvard Education Press. 