# Introduction 

If you're reading this book cover to cover, you've been through quite a journey! So far, you have:

 - Learned about the unique challenges of doing data science in education  
 - Experimented with some basic coding and statistics techniques 
 - Seen examples of analytic routines for education datasets
 - Worked out a plan to introduce data science into your education organization over time 
 
Further, you may have found that this book sparked an interest in data and education that you want nurture. This interest can manifest itself in many forms, but we believe the common thread in readers of this book is that they all want to use data to improve education systems. 

So what's next? It's time to surround yourself with learning experiences that can take that spark and over time turn it into a specialization that turns your ideas for data and education into something real. There are three reasons why we feel these learning experiences are essential to realizing your vision for using data in education. 

First, developing technical skills is an ongoing process. The learning mindset is the same whether you are taking your first steps towards using data science techniques or you are a seasoned data scientist trying to make a bigger impact in education: there is always something new to learn about the programming and statistics tools you seek to master. To be an expert in your craft, you need to set regular time aside to experiment with new ideas and techniques. 

Second, education and data science are like most industries--they are constantly evolving in response to new trends and new knowledge. That means that today's tools and best practices might be tomorrow's outdated techniques. To keep up with changes, it is important to develop a learning routine that that regularly exposes you to the pulse of these fields. Sometimes this is means learning a new technique, sometimes it means deepening expertise in a technique you've already started learning, and other times it means revisiting a skill you've mastered long ago. 

And lastly, when you regularly surround yourself with learning experiences, you surround yourself with others who are learning. Along your learning journey, you'll interact with folks who are struggling through the same concepts as you are, folks who are struggling through more complex concepts, and folks who are struggling with concepts you've already mastered. Participating in a community of learners has magical properties--it's a place to learn, teach, inspire, and get inspired all at once. In his book *Creative Calling* (2019), Chase Jarvis touches on this very point: 

>Whether online or in person, connecting with a community will support your learning efforts. It will also expose you to a diverse set of ideas that will dramatically enrich your perspective on what you're learning. If you weren't in love with your new skill before, this step can tip the balance. Passion is infectious.

You'll need to use your intuition to find the areas you want to deepend your knowledge. When you feel it, go there and dive in. Remember that learning is a combination of reading, doing, talking about, walking away, and coming back. Here are some tips to keep in mind as you create your own system of learning. 

# Adopt a growth mindset

Doing data science and using R can be difficult. It feels overwhelming to learn while the field itself grows and evolves. 

Adopting a *growth mindset* when learning data science is one antidote to feeling overwhelmed or self-critical. [Carol Dweck's](https://mindsetonline.com/abouttheauthor/)
argues that we sometimes think of ourselves as *being* or *not being* a type of person. We might think of ourselves as "math people" or "reading people". Crucially, we may also believe that this identity is unchangeable. On the other hand, we can choose to think of these identities as changeable. With this mindeset, we can adopt a desire to learn, choose to be around people who help us learn, and put forth the required effort to learn. When we move from a *fixed* mindset to a *growth* mindset, we create the possibility of mastering new techniques and realizing our vision for using data in education. As with most perspectives, there is [more nuanced discussion about the growth mindset argument](https://www.edweek.org/ew/articles/2015/09/23/carol-dweck-revisits-the-growth-mindset.html)).

We encourage you to adopt a growth mindset in the right doses as a way to inspire learning and belief that you can introduce data science in your education job. In doing so, you'll be joining other data scientists who created a way to contribute to their fields. 

# Discover new information 

Continuous learning about data science comes from consuming high quality books, blog posts, journals, journalism, and talks. It also means creating new systems to discover content to learn from. In his book *Steal Like An Artist*, author Austin Kleon encourages people to surround themselves with great content: 

>“There’s an economic theory out there that if you take the incomes of your five closest friends and average them, the resulting number will be pretty close to your own income. I think the same thing is true of our idea incomes. You’re only going to be as good as the stuff you surround yourself with.”

In our Resources chapter, we share books and online resources that inspired us and helped us learn. Use these as a starting point and build on these by seeking out authors, data scientists, and educators that inspire you to learn and master your craft. Some folks follow data scientists on social media and take note of articles or talks that are getting attention. Others read data informed publications like Fivethirtyeight, The Economist, or The Upshot in the New York Times. Whichever you choose, make sure to stick with something that you're drawn to and you just might find yourself with a new learning habit that is rewarding and fun. 

# Ask for help

So far, we've discussed learning activities you can do on your own. Data science is a team sport, so at some point your learning will lead you to interacting with others in the data science community. You can do this in many ways, both virtual and in real life. Here are a few examples you can try online. Try these and learn about what you're comfortable with. Then build on that to surround yourself with multiple access points for asking and answering questions. 

## Discussion forums 

Visiting discussion forums is a commonly used way to learn and participate in the R community. Websites sites like [R Studio Community](https://community.rstudio.com/) and [Stack Overflow](https://stackoverflow.com/) are very popular discussion forums. These forums have accumulated many years of discussion through many versions of R and R packages. It's quite unusual to search these and not find something useful for getting you unstuck. Many discussions include a reproducible example of code that you can copy and paste into your own R console. This is a fantastic way to learn!

One final note about forums is about asking your own question. When asking a question, including a reproducible example to facilitate problem-solving, or *reprex*, is a widely-accepted norm. This post about asking Stack Overflow questions on r-bloggers and [Jenny Bryan's video](https://community.rstudio.com/t/video-reproducible-examples-and-the-reprex-package/14732) about making reproducible examples are great places to learn more.

## GitHub repositories

An R package's website and GitHub repository are great placees to look for answers and engage the GitHub community to learn more. You can look at *dplyr*'s Github repository [https://github.com/tidyverse/dplyr](https://github.com/tidyverse/dplyr) for a good example. The README and vignettes contain descriptions of the package's functions. You can even browse the code on GitHub to learn more about how the packages work. Don't worry, you won't break anything! 

When you're ready to see how the community interacts with a package's authors, you can read through the [Issues](https://github.com/tidyverse/dplyr/issues) page. Each respository's Issues page contains questions, feature requests, and bugs submitted by the programming community. Visit this page when you want to see if the coding challenge you're working through is a known issue. If you run into an issue that doesn't seem to have a solution, you can contribute by adding an issue. And finally, you can contribute to the development of packages by submitting code to the respository--this process is called a pull request. To learn more about contributing to packages, check out Kara Woo's talk [Anyone can play git/R: Tips for first-time contributions to R packages](https://speakerdeck.com/karawoo/r-tips-for-first-time-contributions-to-r-packages)

# Share what you've learned

If you keep asking questions and reading about the questions others have asked, you will soon find yourself in a position where you help others who are just getting started. The adage of learning by teaching applies here--answering someone else's question also helps you deepen your learning. And the more questions hear and answer, the more empathy you build up for others trying to learn. 

One way to get create a learning by teaching environment for yourself is to adopt a regular sharing routine. A sharing routine encourages participation in the community, invites feedback for improvement, and calls on you build your craft in a way that others can understand it. 

So what can you share? Really, what can't you share? If you've built a cool function or visualization that took your projecto to the next level, you just might help or inspire someone else by sharing it. Maybe you've found a resource and R package that really helped you--chances are it will help others. Sharing isn't always about the output of your work, it can also be about *how* you work. Consider sharing a workflow you've developed your experience at a recent data science conference. Anything that you learned or found interesting will be relevant to others too!

What you share doesn't always have to be perfect. You can decide when you're ready to share. Some data scientist's blogs are very polished and others are ideas-in-progress or shorter posts. Regardless of whether your work is refined or not, it is valuable to share your work with the data science community. If you share enough, a collection of your online work can act as a portfolio.

## Where to share 

There are many ways to share your work, including social media sites like Twitter (consider using the hashtag #rstats to reach more data scientists). For longer form sharing, consider posting to your own a data science blog. David Robinson's blog post [Advice to aspiring data scientists: start a blog](http://varianceexplained.org/r/start-blog/) is wonderful inspiration for getting started. 

If you decide to post to a blog, there are tools to help you post data science content regularly. The R package *[blogdown]*(https://bookdown.org/yihui/blogdown/) is designed to help you create websites using R Markdown and a static website creator called Hugo. Blogdown makes it easy to create, run, and publish code directly from R Studio. Alison Hill at Oregon Health & Science University (OHSU) has a [great introduction on getting started with with Blogdown](https://alison.rbind.io/post/up-and-running-with-blogdown/).

When you do share a blog post or a tweet, broadcast what you have to say! On Twitter, you can use the hashtag #rstats or "at" other community members to include them in the Tweet. There are also blog aggregators that help share your blogposts to a wider audience. Here are two to get you started: 

* R Weekly newsletter [https://rweekly.org/](https://rweekly.org/)
* R Bloggers [https://www.r-bloggers.com](https://www.r-bloggers.com)

Finally, share the love! Retweet others, leave comments, and interact with the vibrant data science and R communities online.

# Welcome others

One strength of the data science community (at least the corner of it that the
authors of this book occupy) is that it can be a welcoming place. This is due to the
hard work of many of the members of the data science community, who actively participate, react, and praise others. In order for the data science community to continue to be welcoming - and to be more welcoming to those for whom it is currently not - it's important for all of us to continue to work toward a data science community that is inclusive of those who wish to be involved.

Particularly for those of us in education, there are many opportunities to bring others in our field into the community. Welcoming others has the benefit of positioning you as someone with (even if it is still-developing) expertise in data science and R. Teaching others, or even helping others to get started, is a great way to learn more about one's understanding and to learn more in the process. Showing the analyses that you've done and the decisions you've influenced can showcase the value that data science and programming can bring.

One thing to be aware of: You may end up liking data science so much that you become an evangelist (and may, if you are like us, on occasion, make people think you are a bit crazy for R!). This is one thing to keep in mind in regard to welcoming others: People will want to use data science at different times and for different reasons. Focus on welcoming those who are curious and ready to learn more. For those who are skeptical, be patient and open to hearing their concerns and hesitations. 

# References 

Jarvis, C. (2019). *Creative calling*. New York, NY: HarperCollins Publishers. 

*RStudio community* Retrieved from [https://community.rstudio.com](https://community.rstudio.com)

*Stack Overflow questions tagged [r]*. Retrieved from [https://stackoverflow.com/questions/tagged/r](https://stackoverflow.com/questions/tagged/r)

*dplyr on github*. Retrieved from [https://github.com/tidyverse/dplyr](https://github.com/tidyverse/dplyr)

Bryan, J. (2018). *[Video] reproducible examples and the `reprex` package*. Retrieved from [https://community.rstudio.com/t/video-reproducible-examples-and-the-reprex-package/14732](https://community.rstudio.com/t/video-reproducible-examples-and-the-reprex-package/14732)

Woo, K. (2018). *Anyone can play git/R: tips for first-time contributions to R packages*. Retrieved from [https://speakerdeck.com/karawoo/r-tips-for-first-time-contributions-to-r-packages](https://speakerdeck.com/karawoo/r-tips-for-first-time-contributions-to-r-packages)

Robinson, D. (2017). *Advice to aspiring data scientists: start a blog*. Retrieved from [http://varianceexplained.org/r/start-blog/](http://varianceexplained.org/r/start-blog/)

Hill, A. (2017). *Up & Running with blogdown.* Retrieved from [https://alison.rbind.io/post/up-and-running-with-blogdown/](https://alison.rbind.io/post/up-and-running-with-blogdown/)