## Data science courses

[Data science for social scientists](http://datascience.tntlab.org/) by Landers (2019)

[University of Oregon Data Science Specialization for the College of Education](https://github.com/uo-datasci-specialization) by Anderson (2019)

## Education resources 

Bryk et al (2015). *Learning to improve: How America's schools can get better at getting better*. Cambridge, MA: Harvard Education Press. 

Penuel et al (2016, April). *Findings from a national study on research use among school and district leaders*. Retrieved from [http://ncrpp.org/assets/documents/NCRPP_Technical-Report-1_National-Survey-of-Research-Use.pdf](http://ncrpp.org/assets/documents/NCRPP_Technical-Report-1_National-Survey-of-Research-Use.pdf). A survey of 733 school principals and district leaders within US mid-sized and large school districts, focused on how educational leaders use research to inform their decision-making.

## Data visualization 

Tufte, E. (2006). *Beautiful evidence*. Cheshire, CT: Graphics Press LLC. 

Healy, K. (2018). *Data visualization: A practical introduction*. Princeton, NJ: Princeton University Press. 

Chang, W. (2013). *R graphics cookbook*. Sebastopol, CA: O'Reilly.

## Programming with R

Wickham, H. & Grolemund, G. (2017). *R for data science*. Sebastopol, CA: O'Reilly.

Teetor, P. (2011). *R cookbook*. Sebastopol, CA: O'Reilly.

Bryan, J. & Hestor, J. *Happy git and github for the useR*. Retrieved from [https://happygitwithr.com](https://happygitwithr.com) 

Hill, A. (2017). *Big magic with R: Creating learning beyond fear*. Retrieved from [https://speakerdeck.com/apreshill/big-magic-with-r-creative-learning-beyond-fear](https://speakerdeck.com/apreshill/big-magic-with-r-creative-learning-beyond-fear)

## Package vignettes

*Introduction to dplyr*. Retreived from [https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html)

*A short introduction to the caret package*. Retrieved from [https://cran.r-project.org/web/packages/caret/vignettes/caret.html]([https://cran.r-project.org/web/packages/caret/vignettes/caret.html)

## Statistics 

James et al (2015). *An introduction to statistical learning with applications in R*. New York, NY: Springer.

Bruce, P. & Bruce, A. (2017). *Practical statistics for data scientists*. Sebastopol, CA: O'Reilly.

## Places to share your work

Twitter: [twitter.com](twitter.com)

LinkedIn: [linkedin.com](linkedin.com)

Medium : [medium.com](medium.com)

## Learning communities

Here some online communities and community resources we recommend: 

 - #rstats
 - #tidyverse
 - #RLadies
 - *RStudio community*. Retrieved from [https://community.rstudio.com](https://community.rstudio.com) 
 - Mostipak, J. (2017). *R4DS: the next iteration*. Retrieved from[https://medium.com/@kierisi/r4ds-the-next-iteration-d51e0a1b0b82](https://medium.com/@kierisi/r4ds-the-next-iteration-d51e0a1b0b82)
 - Mostipak, J. (2019). *R4DS online learning community Improvements to self-taught data science & the critical need for diversity, equity, and inclusion*. Retrieved from [https://resources.rstudio.com/rstudio-conf-2019/r4ds-online-learning-community-improvements-to-self-taught-data-science-and-the-critical-need-for-diversity-equity-and-inclusion-in-data-science-education](https://resources.rstudio.com/rstudio-conf-2019/r4ds-online-learning-community-improvements-to-self-taught-data-science-and-the-critical-need-for-diversity-equity-and-inclusion-in-data-science-education) RStudio::conf 2019.