# What's new in this edition? {#c00}

When we worked on the first edition of *Data Science in Education Using R*, the world was very different. We completed the book entirely in a time well before the widespread use of Artificial Intelligence. All of us changed jobs and several of us moved and changed life circumstances. We welcomed a few new "collaborators" (children!) onto our collective team. And, of course, what we call educational data science has changed, too.

And yet a great deal is the same. We used the same Slack channel that supported and even galvanized the first edition. We still use R (though many of us use Positron, in addition to or even instead of our steady partner, RStudio!). And we still see the value in developing the knowledge and skill to do data science in authentic educational settings, from K-12 classrooms to in the context of higher education research.

In this book, then, we worked to maintain what was good about the first edition, and to update the book to reflect some of the changes both in data science and educational data science and in our practice as educational data scientists. Namely, we updated several walkthroughs to reflect new developments (e.g., using the {tidymodels} collection of packages for modeling and machine learning), swapped out data sources that were no longer relevant (i.e., Bluesky for Twitter data accessed through their respective Application Programming Interfaces), and, generally, spruced up the code and prose with the aim of producing a more cohesive, clear text for those doing data science in educational settings.

There are some topics we did not address, namely, the role of Artificial Intelligence in the work of data scientists; we believe the audience of this book is best served by its original focus, and we point readers to the growing collection of tutorials and guides that show how to use Artificial Intelligence techniques and models alongside your educational data science toolkit.

We hope that Data Science in Education Using R serves as an accessible yet rigorous support for your educational data science work now and well into the future.