<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective | Data Science in Education Using R</title>
  <meta name="description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective | Data Science in Education Using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="github-repo" content="data-edu/data-science-in-education" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective | Data Science in Education Using R" />
  
  <meta name="twitter:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  

<meta name="author" content="Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c07.html"/>
<link rel="next" href="c09.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-156454511-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-156454511-1');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science in Education Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction: Data Science in Education - You’re Invited!</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#c01"><i class="fa fa-check"></i><b>1.1</b> Learning Data Science in Education</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#making-the-path-a-little-clearer"><i class="fa fa-check"></i><b>1.2</b> Making the Path a Little Clearer</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#about-the-book"><i class="fa fa-check"></i><b>1.3</b> About the Book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02.html"><a href="c02.html"><i class="fa fa-check"></i><b>2</b> How to Use this Book</a><ul>
<li class="chapter" data-level="2.1" data-path="c02.html"><a href="c02.html#different-strokes-for-different-data-scientists-in-education"><i class="fa fa-check"></i><b>2.1</b> Different Strokes for Different Data Scientists in Education</a><ul>
<li class="chapter" data-level="2.1.1" data-path="c02.html"><a href="c02.html#read-the-book-cover-to-cover-and-how-to-keep-going"><i class="fa fa-check"></i><b>2.1.1</b> Read the Book Cover to Cover (and How to Keep Going)</a></li>
<li class="chapter" data-level="2.1.2" data-path="c02.html"><a href="c02.html#pick-a-chapter-of-interest-and-start-there"><i class="fa fa-check"></i><b>2.1.2</b> Pick a Chapter of Interest and Start There</a></li>
<li class="chapter" data-level="2.1.3" data-path="c02.html"><a href="c02.html#read-through-the-walkthroughs-and-run-the-code"><i class="fa fa-check"></i><b>2.1.3</b> Read Through the Walkthroughs and Run the Code</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="c02.html"><a href="c02.html#a-note-on-statistics"><i class="fa fa-check"></i><b>2.2</b> A Note on Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="c02.html"><a href="c02.html#what-this-book-is-not-about"><i class="fa fa-check"></i><b>2.3</b> What This Book Is Not About</a></li>
<li class="chapter" data-level="2.4" data-path="c02.html"><a href="c02.html#supporting-the-book"><i class="fa fa-check"></i><b>2.4</b> Supporting the Book</a></li>
<li class="chapter" data-level="2.5" data-path="c02.html"><a href="c02.html#contributing-to-the-book"><i class="fa fa-check"></i><b>2.5</b> Contributing to the Book</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03.html"><a href="c03.html"><i class="fa fa-check"></i><b>3</b> What is a Data Scientist in Education?</a><ul>
<li class="chapter" data-level="3.1" data-path="c03.html"><a href="c03.html#data-roles-in-education"><i class="fa fa-check"></i><b>3.1</b> Data Roles in Education</a><ul>
<li class="chapter" data-level="3.1.1" data-path="c03.html"><a href="c03.html#building-systems-that-get-data-to-the-right-people"><i class="fa fa-check"></i><b>3.1.1</b> Building Systems That Get Data to the Right People</a></li>
<li class="chapter" data-level="3.1.2" data-path="c03.html"><a href="c03.html#measuring-the-impact-of-our-work-on-the-student-experience"><i class="fa fa-check"></i><b>3.1.2</b> Measuring the Impact of Our Work on the Student Experience</a></li>
<li class="chapter" data-level="3.1.3" data-path="c03.html"><a href="c03.html#looking-for-patterns-in-student-data"><i class="fa fa-check"></i><b>3.1.3</b> Looking for Patterns in Student Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="c03.html"><a href="c03.html#improving-how-we-use-statistical-models-in-education"><i class="fa fa-check"></i><b>3.1.4</b> Improving How We Use Statistical Models in Education</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="c03.html"><a href="c03.html#common-activities-of-data-scientists"><i class="fa fa-check"></i><b>3.2</b> Common Activities of Data Scientists</a><ul>
<li class="chapter" data-level="3.2.1" data-path="c03.html"><a href="c03.html#processing-data"><i class="fa fa-check"></i><b>3.2.1</b> Processing Data</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03.html"><a href="c03.html#doing-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Doing Analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03.html"><a href="c03.html#sharing-results"><i class="fa fa-check"></i><b>3.2.3</b> Sharing Results</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03.html"><a href="c03.html#who-we-are-and-what-we-do"><i class="fa fa-check"></i><b>3.3</b> Who We Are and What We Do</a></li>
<li class="chapter" data-level="3.4" data-path="c03.html"><a href="c03.html#next-steps-for-data-science-in-education"><i class="fa fa-check"></i><b>3.4</b> Next Steps for Data Science in Education</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04.html"><a href="c04.html"><i class="fa fa-check"></i><b>4</b> Special Considerations</a><ul>
<li class="chapter" data-level="4.1" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-any-domain"><i class="fa fa-check"></i><b>4.1</b> Things to Consider when Doing Data Science in any Domain</a><ul>
<li class="chapter" data-level="4.1.1" data-path="c04.html"><a href="c04.html#learning-to-code"><i class="fa fa-check"></i><b>4.1.1</b> Learning to code</a></li>
<li class="chapter" data-level="4.1.2" data-path="c04.html"><a href="c04.html#addressing-ambiguity-a-reproducible-approach"><i class="fa fa-check"></i><b>4.1.2</b> Addressing Ambiguity: A Reproducible Approach</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-education"><i class="fa fa-check"></i><b>4.2</b> Things to Consider when Doing Data Science in Education</a><ul>
<li class="chapter" data-level="4.2.1" data-path="c04.html"><a href="c04.html#addressing-organizational-resistance-a-self-driven-analytic-approach"><i class="fa fa-check"></i><b>4.2.1</b> Addressing organizational resistance: A self-driven analytic approach</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04.html"><a href="c04.html#lack-of-processes-and-guidelines"><i class="fa fa-check"></i><b>4.2.2</b> Lack of Processes and Guidelines</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04.html"><a href="c04.html#limited-training-and-educational-opportunities"><i class="fa fa-check"></i><b>4.2.3</b> Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="4.2.4" data-path="c04.html"><a href="c04.html#advancing-equity"><i class="fa fa-check"></i><b>4.2.4</b> Advancing Equity</a></li>
<li class="chapter" data-level="4.2.5" data-path="c04.html"><a href="c04.html#the-complex-nature-of-education-data"><i class="fa fa-check"></i><b>4.2.5</b> The Complex Nature of Education Data</a></li>
<li class="chapter" data-level="4.2.6" data-path="c04.html"><a href="c04.html#ethical-and-legal-concerns"><i class="fa fa-check"></i><b>4.2.6</b> Ethical and Legal Concerns</a></li>
<li class="chapter" data-level="4.2.7" data-path="c04.html"><a href="c04.html#analytic-considerations"><i class="fa fa-check"></i><b>4.2.7</b> Analytic Considerations</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04.html"><a href="c04.html#conclusion"><i class="fa fa-check"></i><b>4.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05.html"><a href="c05.html"><i class="fa fa-check"></i><b>5</b> Getting Started with R and RStudio</a><ul>
<li class="chapter" data-level="5.1" data-path="c05.html"><a href="c05.html#chapter-overview"><i class="fa fa-check"></i><b>5.1</b> Chapter overview</a></li>
<li class="chapter" data-level="5.2" data-path="c05.html"><a href="c05.html#getting-started"><i class="fa fa-check"></i><b>5.2</b> Getting Started</a></li>
<li class="chapter" data-level="5.3" data-path="c05.html"><a href="c05.html#downloading-r-and-rstudio"><i class="fa fa-check"></i><b>5.3</b> Downloading R and RStudio</a><ul>
<li class="chapter" data-level="5.3.1" data-path="c05.html"><a href="c05.html#to-download-r"><i class="fa fa-check"></i><b>5.3.1</b> To download R:</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05.html"><a href="c05.html#to-download-rstudio"><i class="fa fa-check"></i><b>5.3.2</b> To download RStudio:</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05.html"><a href="c05.html#getting-to-know-r-through-rstudio"><i class="fa fa-check"></i><b>5.4</b> Getting to know R through RStudio</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06.html"><a href="c06.html"><i class="fa fa-check"></i><b>6</b> Foundational Skills</a><ul>
<li class="chapter" data-level="6.1" data-path="c06.html"><a href="c06.html#chapter-overview-1"><i class="fa fa-check"></i><b>6.1</b> Chapter overview</a></li>
<li class="chapter" data-level="6.2" data-path="c06.html"><a href="c06.html#foundational-skills-framework"><i class="fa fa-check"></i><b>6.2</b> Foundational Skills Framework</a><ul>
<li class="chapter" data-level="6.2.1" data-path="c06.html"><a href="c06.html#data"><i class="fa fa-check"></i><b>6.2.1</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="c06.html"><a href="c06.html#projects"><i class="fa fa-check"></i><b>6.3</b> Projects</a><ul>
<li class="chapter" data-level="6.3.1" data-path="c06.html"><a href="c06.html#setting-up-your-project"><i class="fa fa-check"></i><b>6.3.1</b> Setting up your Project</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06.html"><a href="c06.html#packages"><i class="fa fa-check"></i><b>6.4</b> Packages</a></li>
<li class="chapter" data-level="6.5" data-path="c06.html"><a href="c06.html#exploring-r-quickly-with-swirl"><i class="fa fa-check"></i><b>6.5</b> Exploring R quickly with <code>swirl</code></a></li>
<li class="chapter" data-level="6.6" data-path="c06.html"><a href="c06.html#introduction-to-help-documentation"><i class="fa fa-check"></i><b>6.6</b> Introduction to Help Documentation</a></li>
<li class="chapter" data-level="6.7" data-path="c06.html"><a href="c06.html#code-for-foundational-skills"><i class="fa fa-check"></i><b>6.7</b> Code for Foundational Skills</a></li>
<li class="chapter" data-level="6.8" data-path="c06.html"><a href="c06.html#packages-and-functions"><i class="fa fa-check"></i><b>6.8</b> Packages and Functions</a></li>
<li class="chapter" data-level="6.9" data-path="c06.html"><a href="c06.html#installing-and-loading-a-package"><i class="fa fa-check"></i><b>6.9</b> Installing and loading a package</a><ul>
<li class="chapter" data-level="6.9.1" data-path="c06.html"><a href="c06.html#recognizing-a-function"><i class="fa fa-check"></i><b>6.9.1</b> Recognizing a function</a></li>
<li class="chapter" data-level="6.9.2" data-path="c06.html"><a href="c06.html#running-code-in-r"><i class="fa fa-check"></i><b>6.9.2</b> Running code in R</a></li>
<li class="chapter" data-level="6.9.3" data-path="c06.html"><a href="c06.html#run-this-code"><i class="fa fa-check"></i><b>6.9.3</b> Run this code</a></li>
<li class="chapter" data-level="6.9.4" data-path="c06.html"><a href="c06.html#function-conflicts-between-packages"><i class="fa fa-check"></i><b>6.9.4</b> Function conflicts between packages</a></li>
<li class="chapter" data-level="6.9.5" data-path="c06.html"><a href="c06.html#how-to-find-a-package"><i class="fa fa-check"></i><b>6.9.5</b> How to find a package</a></li>
<li class="chapter" data-level="6.9.6" data-path="c06.html"><a href="c06.html#how-to-learn-more-about-a-package"><i class="fa fa-check"></i><b>6.9.6</b> How to learn more about a package</a></li>
<li class="chapter" data-level="6.9.7" data-path="c06.html"><a href="c06.html#commenting-in-r"><i class="fa fa-check"></i><b>6.9.7</b> Commenting in R</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="c06.html"><a href="c06.html#using-functions-to-import-data"><i class="fa fa-check"></i><b>6.10</b> Using functions to import data</a><ul>
<li class="chapter" data-level="6.10.1" data-path="c06.html"><a href="c06.html#downloading-and-accessing-the-data-sets-used-in-this-book"><i class="fa fa-check"></i><b>6.10.1</b> Downloading and accessing the data sets used in this book</a></li>
<li class="chapter" data-level="6.10.2" data-path="c06.html"><a href="c06.html#run-this-code-1"><i class="fa fa-check"></i><b>6.10.2</b> Run this code</a></li>
<li class="chapter" data-level="6.10.3" data-path="c06.html"><a href="c06.html#the-assignment-operator"><i class="fa fa-check"></i><b>6.10.3</b> The assignment operator</a></li>
<li class="chapter" data-level="6.10.4" data-path="c06.html"><a href="c06.html#the-here-package"><i class="fa fa-check"></i><b>6.10.4</b> The <code>here</code> package</a></li>
<li class="chapter" data-level="6.10.5" data-path="c06.html"><a href="c06.html#data-types"><i class="fa fa-check"></i><b>6.10.5</b> Data types</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="c06.html"><a href="c06.html#reading-code-and-writing-functions"><i class="fa fa-check"></i><b>6.11</b> Reading code and writing functions</a><ul>
<li class="chapter" data-level="6.11.1" data-path="c06.html"><a href="c06.html#run-this-code-2"><i class="fa fa-check"></i><b>6.11.1</b> Run this code</a></li>
<li class="chapter" data-level="6.11.2" data-path="c06.html"><a href="c06.html#common-errors"><i class="fa fa-check"></i><b>6.11.2</b> Common errors</a></li>
<li class="chapter" data-level="6.11.3" data-path="c06.html"><a href="c06.html#the-operator"><i class="fa fa-check"></i><b>6.11.3</b> The <code>$</code> operator</a></li>
</ul></li>
<li class="chapter" data-level="6.12" data-path="c06.html"><a href="c06.html#the-pipe-operator"><i class="fa fa-check"></i><b>6.12</b> The pipe operator</a><ul>
<li class="chapter" data-level="6.12.1" data-path="c06.html"><a href="c06.html#run-this-code-3"><i class="fa fa-check"></i><b>6.12.1</b> Run this code</a></li>
<li class="chapter" data-level="6.12.2" data-path="c06.html"><a href="c06.html#piping-practices"><i class="fa fa-check"></i><b>6.12.2</b> Piping practices</a></li>
<li class="chapter" data-level="6.12.3" data-path="c06.html"><a href="c06.html#closing-your-parentheses"><i class="fa fa-check"></i><b>6.12.3</b> Closing your parentheses</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="c06.html"><a href="c06.html#functions-and-equality"><i class="fa fa-check"></i><b>6.13</b> Functions and equality</a><ul>
<li class="chapter" data-level="6.13.1" data-path="c06.html"><a href="c06.html#run-this-code-4"><i class="fa fa-check"></i><b>6.13.1</b> Run this code</a></li>
<li class="chapter" data-level="6.13.2" data-path="c06.html"><a href="c06.html#reading-code"><i class="fa fa-check"></i><b>6.13.2</b> “Reading” code</a></li>
<li class="chapter" data-level="6.13.3" data-path="c06.html"><a href="c06.html#verb-based-functions"><i class="fa fa-check"></i><b>6.13.3</b> Verb-based functions</a></li>
<li class="chapter" data-level="6.13.4" data-path="c06.html"><a href="c06.html#when-functions-need-arguments-and-when-they-dont"><i class="fa fa-check"></i><b>6.13.4</b> When functions need arguments and when they don’t</a></li>
<li class="chapter" data-level="6.13.5" data-path="c06.html"><a href="c06.html#functions-within-functions"><i class="fa fa-check"></i><b>6.13.5</b> Functions within functions</a></li>
<li class="chapter" data-level="6.13.6" data-path="c06.html"><a href="c06.html#the-difference-between-and"><i class="fa fa-check"></i><b>6.13.6</b> The difference between <code>=</code> and <code>==</code></a></li>
<li class="chapter" data-level="6.13.7" data-path="c06.html"><a href="c06.html#writing-your-own-functions"><i class="fa fa-check"></i><b>6.13.7</b> Writing your own functions</a></li>
</ul></li>
<li class="chapter" data-level="6.14" data-path="c06.html"><a href="c06.html#basics-of-names"><i class="fa fa-check"></i><b>6.14</b> Basics of names</a><ul>
<li class="chapter" data-level="6.14.1" data-path="c06.html"><a href="c06.html#run-this-code-5"><i class="fa fa-check"></i><b>6.14.1</b> Run this code</a></li>
</ul></li>
<li class="chapter" data-level="6.15" data-path="c06.html"><a href="c06.html#conclusion-1"><i class="fa fa-check"></i><b>6.15</b> Conclusion</a><ul>
<li class="chapter" data-level="6.15.1" data-path="c06.html"><a href="c06.html#still-need-to-incorporate-the-following"><i class="fa fa-check"></i><b>6.15.1</b> STILL NEED TO INCORPORATE THE FOLLOWING</a></li>
<li class="chapter" data-level="6.15.2" data-path="c06.html"><a href="c06.html#track-two-welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>6.15.2</b> Track Two: Welcome to the Tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="6.16" data-path="c06.html"><a href="c06.html#include-at-end-of-chapter"><i class="fa fa-check"></i><b>6.16</b> Include at end of chapter!</a></li>
<li class="chapter" data-level="6.17" data-path="c06.html"><a href="c06.html#loading-data-from-excel-sav-and-google-sheets"><i class="fa fa-check"></i><b>6.17</b> Loading Data from Excel, SAV, and Google Sheets</a><ul>
<li class="chapter" data-level="6.17.1" data-path="c06.html"><a href="c06.html#loading-excel-files"><i class="fa fa-check"></i><b>6.17.1</b> Loading Excel Files</a></li>
<li class="chapter" data-level="6.17.2" data-path="c06.html"><a href="c06.html#loading-sav-files"><i class="fa fa-check"></i><b>6.17.2</b> Loading SAV Files</a></li>
<li class="chapter" data-level="6.17.3" data-path="c06.html"><a href="c06.html#google-sheets"><i class="fa fa-check"></i><b>6.17.3</b> Google Sheets</a></li>
<li class="chapter" data-level="6.17.4" data-path="c06.html"><a href="c06.html#saving-a-file-from-the-web"><i class="fa fa-check"></i><b>6.17.4</b> Saving a File from the Web</a></li>
<li class="chapter" data-level="6.17.5" data-path="c06.html"><a href="c06.html#loading-a-.csv-file"><i class="fa fa-check"></i><b>6.17.5</b> Loading a <code>.csv</code> File</a></li>
<li class="chapter" data-level="6.17.6" data-path="c06.html"><a href="c06.html#saving-files"><i class="fa fa-check"></i><b>6.17.6</b> Saving Files</a></li>
<li class="chapter" data-level="6.17.7" data-path="c06.html"><a href="c06.html#conclusion-2"><i class="fa fa-check"></i><b>6.17.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6.18" data-path="c06.html"><a href="c06.html#processing-data-1"><i class="fa fa-check"></i><b>6.18</b> Processing Data</a></li>
<li class="chapter" data-level="6.19" data-path="c06.html"><a href="c06.html#communicating-sharing-results"><i class="fa fa-check"></i><b>6.19</b> Communicating / Sharing Results</a></li>
<li class="chapter" data-level="6.20" data-path="c06.html"><a href="c06.html#may-not-need"><i class="fa fa-check"></i><b>6.20</b> May not need</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07.html"><a href="c07.html"><i class="fa fa-check"></i><b>7</b> Walkthrough 1: The Education Dataset Science Pipeline With Online Science Class Data</a><ul>
<li class="chapter" data-level="7.1" data-path="c07.html"><a href="c07.html#vocabulary"><i class="fa fa-check"></i><b>7.1</b> Vocabulary</a></li>
<li class="chapter" data-level="7.2" data-path="c07.html"><a href="c07.html#introduction"><i class="fa fa-check"></i><b>7.2</b> Introduction</a><ul>
<li class="chapter" data-level="7.2.1" data-path="c07.html"><a href="c07.html#background"><i class="fa fa-check"></i><b>7.2.1</b> Background</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07.html"><a href="c07.html#data-sources"><i class="fa fa-check"></i><b>7.2.2</b> Data Sources</a></li>
<li class="chapter" data-level="7.2.3" data-path="c07.html"><a href="c07.html#data-source-2-log-trace-data"><i class="fa fa-check"></i><b>7.2.3</b> Data source #2: Log-trace data</a></li>
<li class="chapter" data-level="7.2.4" data-path="c07.html"><a href="c07.html#data-source-3-achievement-related-and-gradebook-data"><i class="fa fa-check"></i><b>7.2.4</b> Data source #3: Achievement-related and gradebook data</a></li>
<li class="chapter" data-level="7.2.5" data-path="c07.html"><a href="c07.html#data-source-4-discussion-board-data"><i class="fa fa-check"></i><b>7.2.5</b> Data source #4: Discussion board data</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07.html"><a href="c07.html#methods"><i class="fa fa-check"></i><b>7.3</b> Methods</a></li>
<li class="chapter" data-level="7.4" data-path="c07.html"><a href="c07.html#load-packages"><i class="fa fa-check"></i><b>7.4</b> Load Packages</a></li>
<li class="chapter" data-level="7.5" data-path="c07.html"><a href="c07.html#import-data"><i class="fa fa-check"></i><b>7.5</b> Import Data</a></li>
<li class="chapter" data-level="7.6" data-path="c07.html"><a href="c07.html#view-data"><i class="fa fa-check"></i><b>7.6</b> View data</a></li>
<li class="chapter" data-level="7.7" data-path="c07.html"><a href="c07.html#process-data"><i class="fa fa-check"></i><b>7.7</b> Process data</a><ul>
<li class="chapter" data-level="7.7.1" data-path="c07.html"><a href="c07.html#processing-the-course-data"><i class="fa fa-check"></i><b>7.7.1</b> Processing the course data</a></li>
<li class="chapter" data-level="7.7.2" data-path="c07.html"><a href="c07.html#joining-the-data"><i class="fa fa-check"></i><b>7.7.2</b> Joining the data</a></li>
<li class="chapter" data-level="7.7.3" data-path="c07.html"><a href="c07.html#finding-distinct-cases-at-the-student-level"><i class="fa fa-check"></i><b>7.7.3</b> Finding distinct cases at the student-level</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="c07.html"><a href="c07.html#analysis"><i class="fa fa-check"></i><b>7.8</b> Analysis</a><ul>
<li class="chapter" data-level="7.8.1" data-path="c07.html"><a href="c07.html#about-ggplot2"><i class="fa fa-check"></i><b>7.8.1</b> About ggplot2</a></li>
<li class="chapter" data-level="7.8.2" data-path="c07.html"><a href="c07.html#the-relationship-between-time-spent-on-course-and-percentage-of-points-earned"><i class="fa fa-check"></i><b>7.8.2</b> The relationship between time spent on course and percentage of points earned</a></li>
<li class="chapter" data-level="7.8.3" data-path="c07.html"><a href="c07.html#linear-model-regression"><i class="fa fa-check"></i><b>7.8.3</b> Linear model (regression)</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="c07.html"><a href="c07.html#results"><i class="fa fa-check"></i><b>7.9</b> Results</a></li>
<li class="chapter" data-level="7.10" data-path="c07.html"><a href="c07.html#conclusion-3"><i class="fa fa-check"></i><b>7.10</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08.html"><a href="c08.html"><i class="fa fa-check"></i><b>8</b> Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective</a><ul>
<li class="chapter" data-level="8.1" data-path="c08.html"><a href="c08.html#vocabulary-1"><i class="fa fa-check"></i><b>8.1</b> Vocabulary</a></li>
<li class="chapter" data-level="8.2" data-path="c08.html"><a href="c08.html#introduction-1"><i class="fa fa-check"></i><b>8.2</b> Introduction</a><ul>
<li class="chapter" data-level="8.2.1" data-path="c08.html"><a href="c08.html#background-1"><i class="fa fa-check"></i><b>8.2.1</b> Background</a></li>
<li class="chapter" data-level="8.2.2" data-path="c08.html"><a href="c08.html#data-sources-1"><i class="fa fa-check"></i><b>8.2.2</b> Data Sources</a></li>
<li class="chapter" data-level="8.2.3" data-path="c08.html"><a href="c08.html#method"><i class="fa fa-check"></i><b>8.2.3</b> Method</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="c08.html"><a href="c08.html#load-packages-1"><i class="fa fa-check"></i><b>8.3</b> Load Packages</a></li>
<li class="chapter" data-level="8.4" data-path="c08.html"><a href="c08.html#import-data-1"><i class="fa fa-check"></i><b>8.4</b> Import Data</a><ul>
<li class="chapter" data-level="8.4.1" data-path="c08.html"><a href="c08.html#import-using-a-file-path"><i class="fa fa-check"></i><b>8.4.1</b> Import Using a File Path</a></li>
<li class="chapter" data-level="8.4.2" data-path="c08.html"><a href="c08.html#import-using-here"><i class="fa fa-check"></i><b>8.4.2</b> Import Using <code>here()</code></a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="c08.html"><a href="c08.html#process-data-1"><i class="fa fa-check"></i><b>8.5</b> Process data</a><ul>
<li class="chapter" data-level="8.5.1" data-path="c08.html"><a href="c08.html#tidy-data"><i class="fa fa-check"></i><b>8.5.1</b> Tidy Data</a></li>
<li class="chapter" data-level="8.5.2" data-path="c08.html"><a href="c08.html#create-new-variables-and-further-process-the-data"><i class="fa fa-check"></i><b>8.5.2</b> Create new variables and further process the data</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="c08.html"><a href="c08.html#analysis-and-results"><i class="fa fa-check"></i><b>8.6</b> Analysis and results</a><ul>
<li class="chapter" data-level="8.6.1" data-path="c08.html"><a href="c08.html#visualize-data"><i class="fa fa-check"></i><b>8.6.1</b> Visualize Data</a></li>
<li class="chapter" data-level="8.6.2" data-path="c08.html"><a href="c08.html#model-data"><i class="fa fa-check"></i><b>8.6.2</b> Model Data</a></li>
<li class="chapter" data-level="8.6.3" data-path="c08.html"><a href="c08.html#correlation-analysis"><i class="fa fa-check"></i><b>8.6.3</b> Correlation Analysis</a></li>
<li class="chapter" data-level="8.6.4" data-path="c08.html"><a href="c08.html#building-a-linear-model"><i class="fa fa-check"></i><b>8.6.4</b> Building a Linear Model</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="c08.html"><a href="c08.html#conclusion-4"><i class="fa fa-check"></i><b>8.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09.html"><a href="c09.html"><i class="fa fa-check"></i><b>9</b> Walkthrough 3: Introduction to Aggregate Data</a><ul>
<li class="chapter" data-level="9.1" data-path="c09.html"><a href="c09.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a><ul>
<li class="chapter" data-level="9.1.1" data-path="c09.html"><a href="c09.html#background-2"><i class="fa fa-check"></i><b>9.1.1</b> Background</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="c09.html"><a href="c09.html#data-sources-2"><i class="fa fa-check"></i><b>9.2</b> Data Sources</a><ul>
<li class="chapter" data-level="9.2.1" data-path="c09.html"><a href="c09.html#methods-1"><i class="fa fa-check"></i><b>9.2.1</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="c09.html"><a href="c09.html#load-packages-2"><i class="fa fa-check"></i><b>9.3</b> Load Packages</a></li>
<li class="chapter" data-level="9.4" data-path="c09.html"><a href="c09.html#import-data-2"><i class="fa fa-check"></i><b>9.4</b> Import Data</a></li>
<li class="chapter" data-level="9.5" data-path="c09.html"><a href="c09.html#view-data-1"><i class="fa fa-check"></i><b>9.5</b> View Data</a><ul>
<li class="chapter" data-level="9.5.1" data-path="c09.html"><a href="c09.html#discovering-distributions"><i class="fa fa-check"></i><b>9.5.1</b> Discovering Distributions</a></li>
<li class="chapter" data-level="9.5.2" data-path="c09.html"><a href="c09.html#analyzing-spread"><i class="fa fa-check"></i><b>9.5.2</b> Analyzing Spread</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="c09.html"><a href="c09.html#analysis-1"><i class="fa fa-check"></i><b>9.6</b> Analysis</a><ul>
<li class="chapter" data-level="9.6.1" data-path="c09.html"><a href="c09.html#creating-categories"><i class="fa fa-check"></i><b>9.6.1</b> Creating Categories</a></li>
<li class="chapter" data-level="9.6.2" data-path="c09.html"><a href="c09.html#reveal-relationships"><i class="fa fa-check"></i><b>9.6.2</b> Reveal Relationships</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="c09.html"><a href="c09.html#results-1"><i class="fa fa-check"></i><b>9.7</b> Results</a></li>
<li class="chapter" data-level="9.8" data-path="c09.html"><a href="c09.html#conclusion-5"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="c10.html"><a href="c10.html"><i class="fa fa-check"></i><b>10</b> Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data</a><ul>
<li class="chapter" data-level="10.1" data-path="c10.html"><a href="c10.html#vocabulary-2"><i class="fa fa-check"></i><b>10.1</b> Vocabulary</a></li>
<li class="chapter" data-level="10.2" data-path="c10.html"><a href="c10.html#introduction-3"><i class="fa fa-check"></i><b>10.2</b> Introduction</a><ul>
<li class="chapter" data-level="10.2.1" data-path="c10.html"><a href="c10.html#background-3"><i class="fa fa-check"></i><b>10.2.1</b> Background</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10.html"><a href="c10.html#methods-2"><i class="fa fa-check"></i><b>10.2.2</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10.html"><a href="c10.html#load-packages-3"><i class="fa fa-check"></i><b>10.3</b> Load Packages</a></li>
<li class="chapter" data-level="10.4" data-path="c10.html"><a href="c10.html#import-data-3"><i class="fa fa-check"></i><b>10.4</b> Import Data</a><ul>
<li class="chapter" data-level="10.4.1" data-path="c10.html"><a href="c10.html#reading-in-one-dataset"><i class="fa fa-check"></i><b>10.4.1</b> Reading In One Dataset</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10.html"><a href="c10.html#reading-in-many-datasets"><i class="fa fa-check"></i><b>10.4.2</b> Reading In Many Datasets</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10.html"><a href="c10.html#process-data-2"><i class="fa fa-check"></i><b>10.5</b> Process Data</a><ul>
<li class="chapter" data-level="10.5.1" data-path="c10.html"><a href="c10.html#fix-the-variable-names-in-the-2016-data"><i class="fa fa-check"></i><b>10.5.1</b> Fix the variable names in the 2016 data</a></li>
<li class="chapter" data-level="10.5.2" data-path="c10.html"><a href="c10.html#pick-variables"><i class="fa fa-check"></i><b>10.5.2</b> Pick variables</a></li>
<li class="chapter" data-level="10.5.3" data-path="c10.html"><a href="c10.html#combine-six-datasets-into-one"><i class="fa fa-check"></i><b>10.5.3</b> Combine six datasets into one</a></li>
<li class="chapter" data-level="10.5.4" data-path="c10.html"><a href="c10.html#filter-for-the-desired-disabilities-and-age-groups"><i class="fa fa-check"></i><b>10.5.4</b> Filter for the desired disabilities and age groups</a></li>
<li class="chapter" data-level="10.5.5" data-path="c10.html"><a href="c10.html#rename-the-variables"><i class="fa fa-check"></i><b>10.5.5</b> Rename the variables</a></li>
<li class="chapter" data-level="10.5.6" data-path="c10.html"><a href="c10.html#clean-state-names"><i class="fa fa-check"></i><b>10.5.6</b> Clean state names</a></li>
<li class="chapter" data-level="10.5.7" data-path="c10.html"><a href="c10.html#tidy-the-dataset"><i class="fa fa-check"></i><b>10.5.7</b> Tidy the dataset</a></li>
<li class="chapter" data-level="10.5.8" data-path="c10.html"><a href="c10.html#convert-data-types"><i class="fa fa-check"></i><b>10.5.8</b> Convert data types</a></li>
<li class="chapter" data-level="10.5.9" data-path="c10.html"><a href="c10.html#explore-and-address-nas"><i class="fa fa-check"></i><b>10.5.9</b> Explore and address NAs</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="c10.html"><a href="c10.html#analysis-how-have-child-counts-changed-over-time"><i class="fa fa-check"></i><b>10.6</b> Analysis: How Have Child Counts Changed Over Time?</a><ul>
<li class="chapter" data-level="10.6.1" data-path="c10.html"><a href="c10.html#visualize-the-dataset"><i class="fa fa-check"></i><b>10.6.1</b> Visualize the Dataset</a></li>
<li class="chapter" data-level="10.6.2" data-path="c10.html"><a href="c10.html#model-the-dataset"><i class="fa fa-check"></i><b>10.6.2</b> Model the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="c10.html"><a href="c10.html#results-2"><i class="fa fa-check"></i><b>10.7</b> Results</a></li>
<li class="chapter" data-level="10.8" data-path="c10.html"><a href="c10.html#conclusion-aggregate-data-as-context-for-student-data"><i class="fa fa-check"></i><b>10.8</b> Conclusion: Aggregate Data as Context for Student Data</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11.html"><a href="c11.html"><i class="fa fa-check"></i><b>11</b> Walkthrough 5: Text Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="11.1" data-path="c11.html"><a href="c11.html#vocabulary-3"><i class="fa fa-check"></i><b>11.1</b> Vocabulary</a></li>
<li class="chapter" data-level="11.2" data-path="c11.html"><a href="c11.html#introduction-4"><i class="fa fa-check"></i><b>11.2</b> Introduction</a><ul>
<li class="chapter" data-level="11.2.1" data-path="c11.html"><a href="c11.html#background-4"><i class="fa fa-check"></i><b>11.2.1</b> Background</a></li>
<li class="chapter" data-level="11.2.2" data-path="c11.html"><a href="c11.html#data-source"><i class="fa fa-check"></i><b>11.2.2</b> Data Source</a></li>
<li class="chapter" data-level="11.2.3" data-path="c11.html"><a href="c11.html#methods-3"><i class="fa fa-check"></i><b>11.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="c11.html"><a href="c11.html#load-packages-4"><i class="fa fa-check"></i><b>11.3</b> Load Packages</a></li>
<li class="chapter" data-level="11.4" data-path="c11.html"><a href="c11.html#import-data-4"><i class="fa fa-check"></i><b>11.4</b> Import Data</a><ul>
<li class="chapter" data-level="11.4.1" data-path="c11.html"><a href="c11.html#using-an-api"><i class="fa fa-check"></i><b>11.4.1</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="c11.html"><a href="c11.html#view-data-2"><i class="fa fa-check"></i><b>11.5</b> View Data</a></li>
<li class="chapter" data-level="11.6" data-path="c11.html"><a href="c11.html#process-data-3"><i class="fa fa-check"></i><b>11.6</b> Process Data</a></li>
<li class="chapter" data-level="11.7" data-path="c11.html"><a href="c11.html#analysis-counting-words"><i class="fa fa-check"></i><b>11.7</b> Analysis: Counting Words</a></li>
<li class="chapter" data-level="11.8" data-path="c11.html"><a href="c11.html#analysis-sentiment-analysis"><i class="fa fa-check"></i><b>11.8</b> Analysis: Sentiment analysis</a><ul>
<li class="chapter" data-level="11.8.1" data-path="c11.html"><a href="c11.html#count-positive-words"><i class="fa fa-check"></i><b>11.8.1</b> Count positive words</a></li>
<li class="chapter" data-level="11.8.2" data-path="c11.html"><a href="c11.html#dataviz-and-other-positive-words"><i class="fa fa-check"></i><b>11.8.2</b> Dataviz and other positive words</a></li>
<li class="chapter" data-level="11.8.3" data-path="c11.html"><a href="c11.html#close-read-of-randomly-selected-tweets"><i class="fa fa-check"></i><b>11.8.3</b> Close read of randomly selected tweets</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="c11.html"><a href="c11.html#conclusion-6"><i class="fa fa-check"></i><b>11.9</b> Conclusion</a></li>
<li class="chapter" data-level="11.10" data-path="c11.html"><a href="c11.html#technical-appendix-on-accessing-twitter-data"><i class="fa fa-check"></i><b>11.10</b> Technical Appendix on Accessing Twitter data</a><ul>
<li class="chapter" data-level="11.10.1" data-path="c11.html"><a href="c11.html#accessing-historical-twitter-data-using-already-collected-status-urls"><i class="fa fa-check"></i><b>11.10.1</b> Accessing historical Twitter data using already-collected status URLs</a></li>
<li class="chapter" data-level="11.10.2" data-path="c11.html"><a href="c11.html#accessing-historical-data-when-you-do-not-have-access-to-status-urls"><i class="fa fa-check"></i><b>11.10.2</b> Accessing historical data when you do not have access to status URLs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="c12.html"><a href="c12.html"><i class="fa fa-check"></i><b>12</b> Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="12.1" data-path="c12.html"><a href="c12.html#vocabulary-4"><i class="fa fa-check"></i><b>12.1</b> Vocabulary</a></li>
<li class="chapter" data-level="12.2" data-path="c12.html"><a href="c12.html#introduction-5"><i class="fa fa-check"></i><b>12.2</b> Introduction</a><ul>
<li class="chapter" data-level="12.2.1" data-path="c12.html"><a href="c12.html#background-5"><i class="fa fa-check"></i><b>12.2.1</b> Background</a></li>
<li class="chapter" data-level="12.2.2" data-path="c12.html"><a href="c12.html#packages-data-sources-and-import-and-methods"><i class="fa fa-check"></i><b>12.2.2</b> Packages, Data Sources and Import, and Methods</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="c12.html"><a href="c12.html#view-data-3"><i class="fa fa-check"></i><b>12.3</b> View Data</a></li>
<li class="chapter" data-level="12.4" data-path="c12.html"><a href="c12.html#process-data-4"><i class="fa fa-check"></i><b>12.4</b> Process Data</a><ul>
<li class="chapter" data-level="12.4.1" data-path="c12.html"><a href="c12.html#extracting-mentions"><i class="fa fa-check"></i><b>12.4.1</b> Extracting mentions</a></li>
<li class="chapter" data-level="12.4.2" data-path="c12.html"><a href="c12.html#putting-the-edgelist-together"><i class="fa fa-check"></i><b>12.4.2</b> Putting the edgelist together</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="c12.html"><a href="c12.html#analysis-and-results-1"><i class="fa fa-check"></i><b>12.5</b> Analysis and Results</a><ul>
<li class="chapter" data-level="12.5.1" data-path="c12.html"><a href="c12.html#plotting-the-network"><i class="fa fa-check"></i><b>12.5.1</b> Plotting the network</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="c12.html"><a href="c12.html#conclusion-7"><i class="fa fa-check"></i><b>12.6</b> Conclusion</a></li>
<li class="chapter" data-level="12.7" data-path="c12.html"><a href="c12.html#technical-appendix-influence-and-selection-models"><i class="fa fa-check"></i><b>12.7</b> Technical Appendix: Influence and selection models</a><ul>
<li class="chapter" data-level="12.7.1" data-path="c12.html"><a href="c12.html#an-example-of-influence"><i class="fa fa-check"></i><b>12.7.1</b> An example of influence</a></li>
<li class="chapter" data-level="12.7.2" data-path="c12.html"><a href="c12.html#joining-the-data-1"><i class="fa fa-check"></i><b>12.7.2</b> Joining the data</a></li>
<li class="chapter" data-level="12.7.3" data-path="c12.html"><a href="c12.html#an-example-of-selection"><i class="fa fa-check"></i><b>12.7.3</b> An example of selection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="c14.html"><a href="c14.html"><i class="fa fa-check"></i><b>13</b> Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data</a><ul>
<li class="chapter" data-level="13.1" data-path="c14.html"><a href="c14.html#vocabulary-5"><i class="fa fa-check"></i><b>13.1</b> Vocabulary</a></li>
<li class="chapter" data-level="13.2" data-path="c14.html"><a href="c14.html#introduction-6"><i class="fa fa-check"></i><b>13.2</b> Introduction</a><ul>
<li class="chapter" data-level="13.2.1" data-path="c14.html"><a href="c14.html#background-6"><i class="fa fa-check"></i><b>13.2.1</b> Background</a></li>
<li class="chapter" data-level="13.2.2" data-path="c14.html"><a href="c14.html#data-sources-3"><i class="fa fa-check"></i><b>13.2.2</b> Data Sources</a></li>
<li class="chapter" data-level="13.2.3" data-path="c14.html"><a href="c14.html#methods-4"><i class="fa fa-check"></i><b>13.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="c14.html"><a href="c14.html#random-forests"><i class="fa fa-check"></i><b>13.3</b> Random forests</a></li>
<li class="chapter" data-level="13.4" data-path="c14.html"><a href="c14.html#load-packages-5"><i class="fa fa-check"></i><b>13.4</b> Load Packages</a></li>
<li class="chapter" data-level="13.5" data-path="c14.html"><a href="c14.html#import-and-view-data"><i class="fa fa-check"></i><b>13.5</b> Import and View Data</a></li>
<li class="chapter" data-level="13.6" data-path="c14.html"><a href="c14.html#process-data-5"><i class="fa fa-check"></i><b>13.6</b> Process Data</a></li>
<li class="chapter" data-level="13.7" data-path="c14.html"><a href="c14.html#analysis-2"><i class="fa fa-check"></i><b>13.7</b> Analysis</a><ul>
<li class="chapter" data-level="13.7.1" data-path="c14.html"><a href="c14.html#use-of-caret"><i class="fa fa-check"></i><b>13.7.1</b> Use of caret</a></li>
<li class="chapter" data-level="13.7.2" data-path="c14.html"><a href="c14.html#tuning-the-random-forest-model"><i class="fa fa-check"></i><b>13.7.2</b> Tuning the random forest model</a></li>
<li class="chapter" data-level="13.7.3" data-path="c14.html"><a href="c14.html#examining-predictive-accuracy-on-the-test-data-set"><i class="fa fa-check"></i><b>13.7.3</b> Examining predictive accuracy on the test data set</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="c14.html"><a href="c14.html#results-3"><i class="fa fa-check"></i><b>13.8</b> Results</a><ul>
<li class="chapter" data-level="13.8.1" data-path="c14.html"><a href="c14.html#variable-importance-measures"><i class="fa fa-check"></i><b>13.8.1</b> Variable importance measures</a></li>
<li class="chapter" data-level="13.8.2" data-path="c14.html"><a href="c14.html#comparing-a-random-forest-to-a-regression"><i class="fa fa-check"></i><b>13.8.2</b> Comparing a random forest to a regression</a></li>
</ul></li>
<li class="chapter" data-level="13.9" data-path="c14.html"><a href="c14.html#conclusion-8"><i class="fa fa-check"></i><b>13.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c15.html"><a href="c15.html"><i class="fa fa-check"></i><b>14</b> Introducing Data Science Tools To Your Education Job</a><ul>
<li class="chapter" data-level="14.1" data-path="c15.html"><a href="c15.html#introduction-7"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="c15.html"><a href="c15.html#the-gift-of-speed-and-scale"><i class="fa fa-check"></i><b>14.2</b> The Gift of Speed and Scale</a><ul>
<li class="chapter" data-level="14.2.1" data-path="c15.html"><a href="c15.html#working-with-data-faster"><i class="fa fa-check"></i><b>14.2.1</b> Working With Data Faster</a></li>
<li class="chapter" data-level="14.2.2" data-path="c15.html"><a href="c15.html#working-with-more-data"><i class="fa fa-check"></i><b>14.2.2</b> Working With More Data</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="c15.html"><a href="c15.html#other-ways-to-reimagine-the-scale-of-your-work"><i class="fa fa-check"></i><b>14.3</b> Other Ways to Reimagine the Scale of Your Work</a><ul>
<li class="chapter" data-level="14.3.1" data-path="c15.html"><a href="c15.html#reflect-on-your-current-scale-then-push-to-the-next-level"><i class="fa fa-check"></i><b>14.3.1</b> Reflect on your current scale, then push to the next level</a></li>
<li class="chapter" data-level="14.3.2" data-path="c15.html"><a href="c15.html#look-for-lots-of-similarly-structured-data"><i class="fa fa-check"></i><b>14.3.2</b> Look for lots of similarly structured data</a></li>
<li class="chapter" data-level="14.3.3" data-path="c15.html"><a href="c15.html#cleaning-data"><i class="fa fa-check"></i><b>14.3.3</b> Cleaning data</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="c15.html"><a href="c15.html#solving-problems-together"><i class="fa fa-check"></i><b>14.4</b> Solving Problems Together</a><ul>
<li class="chapter" data-level="14.4.1" data-path="c15.html"><a href="c15.html#data-science-in-education-and-empathy"><i class="fa fa-check"></i><b>14.4.1</b> Data Science in Education and Empathy</a></li>
<li class="chapter" data-level="14.4.2" data-path="c15.html"><a href="c15.html#create-a-daily-practice-commitment-that-answers-someone-elses-question"><i class="fa fa-check"></i><b>14.4.2</b> Create a Daily Practice Commitment That Answers Someone Else’s Question</a></li>
<li class="chapter" data-level="14.4.3" data-path="c15.html"><a href="c15.html#build-your-network"><i class="fa fa-check"></i><b>14.4.3</b> Build Your Network</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="c15.html"><a href="c15.html#for-k-12-teachers"><i class="fa fa-check"></i><b>14.5</b> For K-12 Teachers</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="c16.html"><a href="c16.html"><i class="fa fa-check"></i><b>15</b> Teaching Data Science</a><ul>
<li class="chapter" data-level="15.1" data-path="c16.html"><a href="c16.html#the-pedagogical-principles-this-book-is-based-upon"><i class="fa fa-check"></i><b>15.1</b> The pedagogical principles this book is based upon</a><ul>
<li class="chapter" data-level="15.1.1" data-path="c16.html"><a href="c16.html#problem-based-learning"><i class="fa fa-check"></i><b>15.1.1</b> Problem-based learning</a></li>
<li class="chapter" data-level="15.1.2" data-path="c16.html"><a href="c16.html#differentiation"><i class="fa fa-check"></i><b>15.1.2</b> Differentiation</a></li>
<li class="chapter" data-level="15.1.3" data-path="c16.html"><a href="c16.html#universal-design"><i class="fa fa-check"></i><b>15.1.3</b> Universal Design</a></li>
<li class="chapter" data-level="15.1.4" data-path="c16.html"><a href="c16.html#working-in-the-open"><i class="fa fa-check"></i><b>15.1.4</b> Working in the Open</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="c16.html"><a href="c16.html#strategies-for-teaching-data-science"><i class="fa fa-check"></i><b>15.2</b> Strategies for teaching data science</a><ul>
<li class="chapter" data-level="15.2.1" data-path="c16.html"><a href="c16.html#provide-a-home-base-for-learners-to-access-resources-and-to-learn-more"><i class="fa fa-check"></i><b>15.2.1</b> Provide a home base for learners to access resources (and to learn more)</a></li>
<li class="chapter" data-level="15.2.2" data-path="c16.html"><a href="c16.html#when-it-comes-to-writing-code-think-early-and-often"><i class="fa fa-check"></i><b>15.2.2</b> When it comes to writing code, think early and often</a></li>
<li class="chapter" data-level="15.2.3" data-path="c16.html"><a href="c16.html#dont-touch-that-keyboard"><i class="fa fa-check"></i><b>15.2.3</b> Don’t touch that keyboard!</a></li>
<li class="chapter" data-level="15.2.4" data-path="c16.html"><a href="c16.html#anticipate-issues-and-sacrifice-accuracy-for-clarity"><i class="fa fa-check"></i><b>15.2.4</b> Anticipate issues (and sacrifice accuracy for clarity)</a></li>
<li class="chapter" data-level="15.2.5" data-path="c16.html"><a href="c16.html#start-lessons-or-activities-with-visualizing-data"><i class="fa fa-check"></i><b>15.2.5</b> Start lessons or activities with visualizing data</a></li>
<li class="chapter" data-level="15.2.6" data-path="c16.html"><a href="c16.html#consider-representation-in-the-data-and-examples-you-use"><i class="fa fa-check"></i><b>15.2.6</b> Consider representation in the data and examples you use</a></li>
<li class="chapter" data-level="15.2.7" data-path="c16.html"><a href="c16.html#draw-on-other-resources"><i class="fa fa-check"></i><b>15.2.7</b> Draw on other resources</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="c16.html"><a href="c16.html#general-strategies-related-to-teaching-and-learning"><i class="fa fa-check"></i><b>15.3</b> General strategies related to teaching and learning</a><ul>
<li class="chapter" data-level="15.3.1" data-path="c16.html"><a href="c16.html#teaching-and-learning-are-complex"><i class="fa fa-check"></i><b>15.3.1</b> Teaching and learning are complex</a></li>
<li class="chapter" data-level="15.3.2" data-path="c16.html"><a href="c16.html#learners-learn-many-different-things-consciously-and-unconsciously"><i class="fa fa-check"></i><b>15.3.2</b> Learners learn many different things (consciously and unconsciously)</a></li>
<li class="chapter" data-level="15.3.3" data-path="c16.html"><a href="c16.html#metacognition-is-important-even-though-it-sounds-more-sophisticated-than-it-is"><i class="fa fa-check"></i><b>15.3.3</b> Metacognition is important (even though it sounds more sophisticated than it is!)</a></li>
<li class="chapter" data-level="15.3.4" data-path="c16.html"><a href="c16.html#learning-strategies-matter"><i class="fa fa-check"></i><b>15.3.4</b> Learning strategies matter</a></li>
<li class="chapter" data-level="15.3.5" data-path="c16.html"><a href="c16.html#educators-can-help-students-to-learn"><i class="fa fa-check"></i><b>15.3.5</b> Educators can help students to learn</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="c16.html"><a href="c16.html#summary"><i class="fa fa-check"></i><b>15.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="c17.html"><a href="c17.html"><i class="fa fa-check"></i><b>16</b> Learning More</a><ul>
<li class="chapter" data-level="16.1" data-path="c17.html"><a href="c17.html#introduction-8"><i class="fa fa-check"></i><b>16.1</b> Introduction</a></li>
<li class="chapter" data-level="16.2" data-path="c17.html"><a href="c17.html#adopt-a-growth-mindset"><i class="fa fa-check"></i><b>16.2</b> Adopt a growth mindset</a></li>
<li class="chapter" data-level="16.3" data-path="c17.html"><a href="c17.html#discover-new-information"><i class="fa fa-check"></i><b>16.3</b> Discover new information</a></li>
<li class="chapter" data-level="16.4" data-path="c17.html"><a href="c17.html#ask-for-help"><i class="fa fa-check"></i><b>16.4</b> Ask for help</a><ul>
<li class="chapter" data-level="16.4.1" data-path="c17.html"><a href="c17.html#discussion-forums"><i class="fa fa-check"></i><b>16.4.1</b> Discussion forums</a></li>
<li class="chapter" data-level="16.4.2" data-path="c17.html"><a href="c17.html#github-repositories"><i class="fa fa-check"></i><b>16.4.2</b> GitHub repositories</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="c17.html"><a href="c17.html#share-what-youve-learned"><i class="fa fa-check"></i><b>16.5</b> Share what you’ve learned</a><ul>
<li class="chapter" data-level="16.5.1" data-path="c17.html"><a href="c17.html#where-to-share"><i class="fa fa-check"></i><b>16.5.1</b> Where to share</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="c17.html"><a href="c17.html#welcome-others"><i class="fa fa-check"></i><b>16.6</b> Welcome others</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="c18.html"><a href="c18.html"><i class="fa fa-check"></i><b>17</b> Additional Resources</a><ul>
<li class="chapter" data-level="17.1" data-path="c18.html"><a href="c18.html#data-science-courses"><i class="fa fa-check"></i><b>17.1</b> Data science courses</a></li>
<li class="chapter" data-level="17.2" data-path="c18.html"><a href="c18.html#workshop-materials"><i class="fa fa-check"></i><b>17.2</b> Workshop materials</a></li>
<li class="chapter" data-level="17.3" data-path="c18.html"><a href="c18.html#education-resources"><i class="fa fa-check"></i><b>17.3</b> Education resources</a></li>
<li class="chapter" data-level="17.4" data-path="c18.html"><a href="c18.html#data-visualization"><i class="fa fa-check"></i><b>17.4</b> Data visualization</a></li>
<li class="chapter" data-level="17.5" data-path="c18.html"><a href="c18.html#books-related-to-data-science-in-education"><i class="fa fa-check"></i><b>17.5</b> Books related to data science in education</a></li>
<li class="chapter" data-level="17.6" data-path="c18.html"><a href="c18.html#articles-related-to-data-science-in-education"><i class="fa fa-check"></i><b>17.6</b> Articles related to data science in education</a></li>
<li class="chapter" data-level="17.7" data-path="c18.html"><a href="c18.html#programming-with-r"><i class="fa fa-check"></i><b>17.7</b> Programming with R</a></li>
<li class="chapter" data-level="17.8" data-path="c18.html"><a href="c18.html#helpful-package-vignettes-and-descriptions-of-packages"><i class="fa fa-check"></i><b>17.8</b> Helpful package vignettes and descriptions of packages</a></li>
<li class="chapter" data-level="17.9" data-path="c18.html"><a href="c18.html#statistics"><i class="fa fa-check"></i><b>17.9</b> Statistics</a><ul>
<li class="chapter" data-level="17.9.1" data-path="c18.html"><a href="c18.html#introductory"><i class="fa fa-check"></i><b>17.9.1</b> Introductory</a></li>
<li class="chapter" data-level="17.9.2" data-path="c18.html"><a href="c18.html#advanced"><i class="fa fa-check"></i><b>17.9.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="17.10" data-path="c18.html"><a href="c18.html#software-and-r-packages"><i class="fa fa-check"></i><b>17.10</b> Software and R Packages</a></li>
<li class="chapter" data-level="17.11" data-path="c18.html"><a href="c18.html#a-career-in-data-science"><i class="fa fa-check"></i><b>17.11</b> A career in data science</a></li>
<li class="chapter" data-level="17.12" data-path="c18.html"><a href="c18.html#places-to-share-your-work"><i class="fa fa-check"></i><b>17.12</b> Places to share your work</a></li>
<li class="chapter" data-level="17.13" data-path="c18.html"><a href="c18.html#cheat-sheets"><i class="fa fa-check"></i><b>17.13</b> Cheat Sheets</a></li>
<li class="chapter" data-level="17.14" data-path="c18.html"><a href="c18.html#learning-communities"><i class="fa fa-check"></i><b>17.14</b> Learning communities</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="c19.html"><a href="c19.html"><i class="fa fa-check"></i><b>18</b> Conclusion: To where next?</a><ul>
<li class="chapter" data-level="18.1" data-path="c19.html"><a href="c19.html#take-on-challenges"><i class="fa fa-check"></i><b>18.1</b> Take on challenges</a></li>
<li class="chapter" data-level="18.2" data-path="c19.html"><a href="c19.html#know-when-to-turn-to-something-else"><i class="fa fa-check"></i><b>18.2</b> Know when to turn to something else</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.emilybovee.com/">Emily A. Bovee</a></li>
<li><a href="https://ryanestrellado.netlify.com/">Ryan A. Estrellado</a></li>
<li><a href="https://www.jessemaegan.com/">Jesse Mostipak</a></li>
<li><a href="https://joshuamrosenberg.com/">Joshua M. Rosenberg</a></li>
<li><a href="https://ivelasq.rbind.io/">Isabella C. Velásquez</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science in Education Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c08" class="section level1">
<h1><span class="header-section-number">8</span> Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective</h1>
<div id="vocabulary-1" class="section level2">
<h2><span class="header-section-number">8.1</span> Vocabulary</h2>
<ul>
<li>directory<br />
</li>
<li>environment<br />
</li>
<li>pivot<br />
</li>
<li>linearity<br />
</li>
<li>correlation<br />
</li>
<li>outliers<br />
</li>
<li>linear model</li>
</ul>
</div>
<div id="introduction-1" class="section level2">
<h2><span class="header-section-number">8.2</span> Introduction</h2>
<p>There are a variety of data sources to explore in the education field. Student assessment scores can be examined for progress towards goals. The text from a teacher’s written classroom observation notes about a particular learner’s in-class behavior or emotional status can be analyzed for trends. We can tap into the exportable data available from common learning software or platforms popular in the K-12 education space.</p>
<div id="background-1" class="section level3">
<h3><span class="header-section-number">8.2.1</span> Background</h3>
<p>This walkthrough goes through a series of analyses using the data science framework. The first analysis centers around a ubiquitous K-12 classroom tool: the gradebook. While gradebook data is nearly ubiquitious in education, it is sometimes ignored in favor of data collected by evaluators and researchers or data from state-wide tests. Nevertheless, it represents an important, occasionally untapped data source, and one for which a data science approach can reveal the potential of the data science framework for analyzing a range of educational data sources.</p>
</div>
<div id="data-sources-1" class="section level3">
<h3><span class="header-section-number">8.2.2</span> Data Sources</h3>
<p>We use an Excel gradebook template, <a href="https://web.mit.edu/jabbott/www/excelgradetracker.html"><em>Assessment Types - Points</em></a>, coupled with simulated student data. On your first read through this section try using our simulated dataset found in this book’s <code>data/</code> folder.</p>
</div>
<div id="method" class="section level3">
<h3><span class="header-section-number">8.2.3</span> Method</h3>
<p>This analysis uses a linear model, which relates one or more X, or independent variables, to a Y, or dependent variable, and a correlation analysis.</p>
</div>
</div>
<div id="load-packages-1" class="section level2">
<h2><span class="header-section-number">8.3</span> Load Packages</h2>
<p>As mentioned in the Foundational Skills chapter, begin by loading the libraries that will be used. We will load the {tidyverse} package used in <a href="06-wt-multilevel-models-1">Walkthrough 1</a>. This chapter has an example of using the {readxl} package to read and import Excel spreadsheets, file types are very common in the education field.</p>
<p>Make sure you have installed the packages in R on your computer before starting (see Foundational Skills chapter). Load the libraries, as they must be loaded each time we start a new project.</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb105-1" title="1"><span class="co"># Load libraries</span></a>
<a class="sourceLine" id="cb105-2" title="2"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb105-3" title="3"><span class="kw">library</span>(here)</a>
<a class="sourceLine" id="cb105-4" title="4"><span class="kw">library</span>(readxl)</a>
<a class="sourceLine" id="cb105-5" title="5"><span class="kw">library</span>(janitor)</a>
<a class="sourceLine" id="cb105-6" title="6"><span class="kw">library</span>(dataedu)</a></code></pre></div>
</div>
<div id="import-data-1" class="section level2">
<h2><span class="header-section-number">8.4</span> Import Data</h2>
<p>Recall how the Foundational Skills chapter recommended favoring CSV files, or comma-separated values files, when working with datasets in R? This is because CSV files, with the .csv file extension, are common in the digital world. However, data won’t always come in the preferred file format. Fortunately, R can import a variety of data file types. This walkthrough imports an Excel file because these file types, with the .xlsx or .xls extensions, are very likely to be encountered in the K-12 education world. We’ll show you two ways to import the gradebook dataset: The first is uses a file path. The second uses the <code>here()</code> function from the {here} package. We recommend using <code>here()</code>, but it’s worthwhile to review both methods.</p>
<div id="import-using-a-file-path" class="section level3">
<h3><span class="header-section-number">8.4.1</span> Import Using a File Path</h3>
<p>First let’s look at importing the dataset using a file path. This code uses the <code>read_excel()</code> function of the {readxl} package to find and read the data of the desired file. Note the file path that <code>read_excel()</code> takes to find the simulated dataset file named <code>ExcelGradeBook.xlsx</code> which sits in a folder on your computer if you have downloaded it. The function <code>getwd()</code> will help locate your current working directory. This tells where on the computer R is currently working with files.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb106-1" title="1"><span class="co"># See the current working directory</span></a>
<a class="sourceLine" id="cb106-2" title="2"><span class="kw">getwd</span>()</a></code></pre></div>
<p>For example, an R user on Linux or Mac might see their working directory as: <code>/home/username/Desktop</code>. A Windows user might see their working directory as: <code>C:\Users\Username\Desktop</code>.</p>
<p>From this location go deeper into files to find the desired file. For example, if you downloaded the <a href="https://github.com/data-edu/data-science-in-education">book repository</a> from Github to your Desktop the path to the Excel file might look like one of these below:</p>
<ul>
<li><code>/home/username/Desktop/data-science-in-education/data/gradebooks/ExcelGradeBook.xlsx</code> (on Linux &amp; Mac)</li>
<li><code>C:\Users\Username\Desktop\data-science-in-education\data\gradebooks\ExcelGradeBook.xlsx</code> (on Windows)</li>
</ul>
<p>After locating the sample Excel file, use the code below to run the function <code>read_excel()</code> which reads and saves the data from <code>ExcelGradeBook.xlsx</code> to an object also called <code>ExcelGradeBook</code>. Note the two arguments specified in this code <code>sheet = 1</code> and <code>skip = 10</code>. This Excel file is similar to one you might encounter in real life with superfluous features that we are not interested in. This file has 3 different sheets and the first 10 rows contain things we won’t need. Thus, <code>sheet = 1</code> tells <code>read_excel()</code> to just read the first sheet in the file and disregard the rest. While <code>skip = 10</code> tells <code>read_excel()</code> to skip reading the first 10 rows of the sheet and start reading from row 11 which is where the column headers and data actually start inside the Excel file. Remember to replace <code>path/to/file.xlsx</code> your own path to the file you want to import.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb107-1" title="1">ExcelGradeBook &lt;-<span class="st"> </span><span class="kw">read_excel</span>(<span class="st">&quot;path/to/file.xlsx&quot;</span>, <span class="dt">sheet =</span> <span class="dv">1</span>, <span class="dt">skip =</span> <span class="dv">10</span>)</a></code></pre></div>
</div>
<div id="import-using-here" class="section level3">
<h3><span class="header-section-number">8.4.2</span> Import Using <code>here()</code></h3>
<p>Whenever possible, we prefer to use <code>here()</code> from the {here} package because it conveniently guesses at the correct file path based on the working directory. In you working directory, place the <code>ExcelGradeBook.xlsx</code> file in a folder called <code>gradebooks</code>. Then place the <code>gradebooks</code> folder in a folder called <code>data</code>. The last step is to make sure your new <code>data</code> folder and all its contents are in your working directory. Following those steps, use this code to read the data in:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb108-1" title="1"><span class="co"># Use readxl package to read and import file and assign it a name</span></a>
<a class="sourceLine" id="cb108-2" title="2">ExcelGradeBook &lt;-</a>
<a class="sourceLine" id="cb108-3" title="3"><span class="st">  </span><span class="kw">read_excel</span>(</a>
<a class="sourceLine" id="cb108-4" title="4">    here<span class="op">::</span><span class="kw">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;gradebooks&quot;</span>, <span class="st">&quot;ExcelGradeBook.xlsx&quot;</span>),</a>
<a class="sourceLine" id="cb108-5" title="5">    <span class="dt">sheet =</span> <span class="dv">1</span>,</a>
<a class="sourceLine" id="cb108-6" title="6">    <span class="dt">skip =</span> <span class="dv">10</span></a>
<a class="sourceLine" id="cb108-7" title="7">  )</a></code></pre></div>
<p>The <code>ExcelGradeBook</code> file has been imported into RStudio. Next, assign the data frame to a new name using the code below. Renaming cumbersome filenames can improve the readability of the code and make is easier for the user to call on the dataset later on in the code.</p>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb109-1" title="1"><span class="co"># Rename data frame</span></a>
<a class="sourceLine" id="cb109-2" title="2">gradebook &lt;-<span class="st"> </span>ExcelGradeBook</a></code></pre></div>
<p>Your environment will now have two versions of the dataset. There is <code>ExcelGradeBook</code> which was the original dataset imported. There is also <code>gradebook</code> which is currently a copy of <code>ExcelGradeBook</code>. As you progress through this section, we will work primarily with the <code>gradebook</code> dataset. Additionally, while working onward in this section of the book, if you make a mistake and mess up the <code>gradebook</code> data frame and are not able to fix it, you can reset the data frame to return to the same state as the original <code>ExcelGradeBook</code> data frame by running <code>gradebook &lt;- ExcelGradeBook</code> again. This will overwrite any errors in the <code>gradebook</code> data frame with the originally imported <code>ExcelGradeBook</code> data frame. Afterwards, just continue running code from this point in the text.</p>
</div>
</div>
<div id="process-data-1" class="section level2">
<h2><span class="header-section-number">8.5</span> Process data</h2>
<div id="tidy-data" class="section level3">
<h3><span class="header-section-number">8.5.1</span> Tidy Data</h3>
<p>This walkthrough uses an Excel data file because it is one that we are likely to encounter. Moreover, the messy state of this file mirrors what might be encountered in real life. The Excel file contains more than one sheet, has rows we don’t need, and uses column names that have spaces between words. All these things make the data tough to work with. The data is <strong>not</strong> tidy. We can begin to overcome these challenges before importing the file into RStudio by deleting the unnecessary parts of the Excel file then saving it as a .csv file. However, if you clean the file outside of R, this means if you ever have to clean it up (say, if the dataset is accidentally deleted and you need to redownload it from the original source) you would have to do everything from the beginning, and may not recall exactly what you did in Excel prior to importing the data to R. We recommend cleaning the original data in R so that you can recreate all the steps necessary for your analysis. Also, the untidy Excel file provides realistic practice for tidying up the data programmatically using R itself.</p>
<p>First, modify the column names of the <code>gradebook</code> data frame to remove any spaces and replace them with an underscore. Using spaces as column names in R can present difficulties later on when working with the data.</p>
<p>Second, we want the column names of our data to be easy to use and understand. The original dataset has column names with uppercase letters and spaces. We can use the {janitor} package to quickly change them to a more useable format.</p>
<p>First, let’s have a look at the original column names. The output will be long, so let’s just look at the first ten by using <code>head()</code></p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb110-1" title="1"><span class="co"># look at original column names</span></a>
<a class="sourceLine" id="cb110-2" title="2"><span class="kw">head</span>(<span class="kw">colnames</span>(gradebook)) </a></code></pre></div>
<pre><code>## [1] &quot;Class&quot;           &quot;Name&quot;            &quot;Race&quot;            &quot;Gender&quot;         
## [5] &quot;Age&quot;             &quot;Repeated Grades&quot;</code></pre>
<p>You can look at the full output by removing the call to <code>head()</code></p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb112-1" title="1"><span class="co"># look at original column names</span></a>
<a class="sourceLine" id="cb112-2" title="2"><span class="kw">colnames</span>(gradebook)</a></code></pre></div>
<p>Now let’s look at the cleaned names</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb113-1" title="1">gradebook &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb113-2" title="2"><span class="st">  </span>gradebook <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb113-3" title="3"><span class="st">  </span><span class="kw">clean_names</span>()</a>
<a class="sourceLine" id="cb113-4" title="4"></a>
<a class="sourceLine" id="cb113-5" title="5"><span class="co"># look at cleaned column names</span></a>
<a class="sourceLine" id="cb113-6" title="6"><span class="kw">head</span>(<span class="kw">colnames</span>(gradebook) )</a></code></pre></div>
<pre><code>## [1] &quot;class&quot;           &quot;name&quot;            &quot;race&quot;            &quot;gender&quot;         
## [5] &quot;age&quot;             &quot;repeated_grades&quot;</code></pre>
<p>Review what the <code>gradebook</code> data frame looks like now. It shows 25 students and their individual values in various columns like <code>projects</code> or <code>formative_assessments</code>.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb115-1" title="1"><span class="kw">view</span>(gradebook)</a></code></pre></div>
<p>The data frame looks cleaner now but there still are some things we can remove. For example, there are rows without any names in them. Also, there are entire columns that are unused and contain no data (such as gender). These are called missing values and are denoted by <em>NA</em>. Since our simulated classroom only has 25 learners and doesn’t use all the columns for demographic information, we can safely remove these to tidy our dataset up even more.</p>
<p>We can remove the extra columns rows that have no data using the janitor package. The handy <code>remove_empty()</code> removes columns, rows, or both that have no information in them.</p>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb116-1" title="1"><span class="co"># Removing rows with nothing but missing data</span></a>
<a class="sourceLine" id="cb116-2" title="2">gradebook &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb116-3" title="3"><span class="st">  </span>gradebook <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb116-4" title="4"><span class="st">  </span><span class="kw">remove_empty</span>(<span class="kw">c</span>(<span class="st">&quot;rows&quot;</span>, <span class="st">&quot;cols&quot;</span>))</a></code></pre></div>
<p>Now that the empty rows and columns have been removed, notice there are two columns, <code>absent</code> and <code>late</code>, where it seems someone started putting data into but then decided to stop. These two columns didn’t get removed by the last chunk of code because they technically contained some data in those columns. Since the simulated data enterer of this simulated class decided to abandon using the <code>absent</code> and <code>late</code> columns in this gradebook, we can remove it from our data frame as well.</p>
<p>In the foundational skills chapter we introduced the <code>select()</code> function, which tells R which columns we want to keep. Let’s do that again here. This time we’ll use negative signs to say we want the dataset without <code>absent</code> and <code>late</code>.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb117-1" title="1"><span class="co"># Remove a targeted column because we don&#39;t use absent and late at this school.</span></a>
<a class="sourceLine" id="cb117-2" title="2">gradebook &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb117-3" title="3"><span class="st">  </span>gradebook <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb117-4" title="4"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span>absent, <span class="op">-</span>late)</a></code></pre></div>
<p>At last, the formerly untidy Excel sheet has been turned into a useful data frame. Inspect it once more to see the difference.</p>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb118-1" title="1"><span class="kw">view</span>(gradebook)</a></code></pre></div>
</div>
<div id="create-new-variables-and-further-process-the-data" class="section level3">
<h3><span class="header-section-number">8.5.2</span> Create new variables and further process the data</h3>
<p>R users transform data to facilitate working with the data during later phases of visualization and analysis. A few examples of data transformation include creating new variables, grouping data, and more. This code chunk first creates a new data frame named <code>classwork_df</code>, then selects particular variables from our gradebook dataset using <code>select()</code>, and finally gathers all the homework data under new variables into new columns.</p>
<p>As mentioned previously, <code>select()</code> is very powerful. In addition to explicitly writing out the columns you want to keep, you can also use functions from the package {stringr} within <code>select()</code>. The {stringr} package is contained within the {tidyverse} meta-package. Here, we’ll use the function <code>contains()</code> to tell R to select columns that contain a certain string (that is, text). Here, it searches for any column with the string <code>classwork_</code>. The underscore makes sure the variables from <code>classwork_1</code> all the way to <code>classwork_17</code> are included in <code>classwork_df</code>.</p>
<p><code>pivot_longer()</code> transforms the dataset into tidy data.</p>
<p>Note that <code>scores</code> are in character format. We use <code>mutate()</code> to transform them to numerical format.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb119-1" title="1"><span class="co"># Creates new data frame, selects desired variables from gradebook, and gathers all classwork scores into key/value pairs</span></a>
<a class="sourceLine" id="cb119-2" title="2">classwork_df &lt;-</a>
<a class="sourceLine" id="cb119-3" title="3"><span class="st">  </span>gradebook <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb119-4" title="4"><span class="st">  </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb119-5" title="5">    name,</a>
<a class="sourceLine" id="cb119-6" title="6">    running_average,</a>
<a class="sourceLine" id="cb119-7" title="7">    letter_grade,</a>
<a class="sourceLine" id="cb119-8" title="8">    homeworks,</a>
<a class="sourceLine" id="cb119-9" title="9">    classworks,</a>
<a class="sourceLine" id="cb119-10" title="10">    formative_assessments,</a>
<a class="sourceLine" id="cb119-11" title="11">    projects,</a>
<a class="sourceLine" id="cb119-12" title="12">    summative_assessments,</a>
<a class="sourceLine" id="cb119-13" title="13">    <span class="kw">contains</span>(<span class="st">&quot;classwork_&quot;</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb119-14" title="14"><span class="st">  </span><span class="kw">mutate_at</span>(<span class="kw">vars</span>(<span class="kw">contains</span>(<span class="st">&quot;classwork_&quot;</span>)), <span class="kw">list</span>(<span class="op">~</span><span class="st"> </span><span class="kw">as.numeric</span>(.))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb119-15" title="15"><span class="st">  </span><span class="kw">pivot_longer</span>(</a>
<a class="sourceLine" id="cb119-16" title="16">    <span class="dt">cols =</span> <span class="kw">contains</span>(<span class="st">&quot;classwork_&quot;</span>),</a>
<a class="sourceLine" id="cb119-17" title="17">    <span class="dt">names_to =</span> <span class="st">&quot;classwork_number&quot;</span>,</a>
<a class="sourceLine" id="cb119-18" title="18">    <span class="dt">values_to =</span> <span class="st">&quot;score&quot;</span></a>
<a class="sourceLine" id="cb119-19" title="19">  )</a></code></pre></div>
<p>View the new data frame and note which columns were selected for this new data frame. Also, note how all the classwork scores were gathered under new columns <code>classwork_number</code> and <code>score</code>. The <code>contains()</code> function. We will use this <code>classwork_df</code> data frame later.</p>
<div class="sourceCode" id="cb120"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb120-1" title="1"><span class="kw">view</span>(classwork_df)</a></code></pre></div>
</div>
</div>
<div id="analysis-and-results" class="section level2">
<h2><span class="header-section-number">8.6</span> Analysis and results</h2>
<div id="visualize-data" class="section level3">
<h3><span class="header-section-number">8.6.1</span> Visualize Data</h3>
<p>Visual representations of data are more human friendly than just looking at numbers alone. This next line of code shows a simple summary of the data by each column similar to what we did in Walkthrough 1.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb121-1" title="1"><span class="co"># Summary of the data by columns</span></a>
<a class="sourceLine" id="cb121-2" title="2"><span class="kw">summary</span>(gradebook)</a></code></pre></div>
<p>But R can do more than just print numbers to a screen. We’ll use the {ggplot} package from within {tidyverse} to graph some of the data to help get a better grasp of what the data looks like. This code uses {ggplot} to graph categorical variables into a bar graph. Here we can see the variable <code>Letter_grade</code> is plotted on the x-axis showing the counts of each letter grade on the y-axis.</p>
<div class="sourceCode" id="cb122"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb122-1" title="1"><span class="co"># Bar graph for categorical variable</span></a>
<a class="sourceLine" id="cb122-2" title="2">gradebook <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb122-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> letter_grade,</a>
<a class="sourceLine" id="cb122-4" title="4">             <span class="dt">fill =</span> running_average <span class="op">&gt;</span><span class="st"> </span><span class="dv">90</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb122-5" title="5"><span class="st">  </span><span class="kw">geom_bar</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb122-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Bar Graph of Student Grades&quot;</span>,</a>
<a class="sourceLine" id="cb122-7" title="7">       <span class="dt">x =</span> <span class="st">&quot;Letter Grades&quot;</span>,</a>
<a class="sourceLine" id="cb122-8" title="8">       <span class="dt">y =</span> <span class="st">&quot;Count&quot;</span>,</a>
<a class="sourceLine" id="cb122-9" title="9">       <span class="dt">fill =</span> <span class="st">&quot;A or Better&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb122-10" title="10"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb122-11" title="11"><span class="st">  </span><span class="kw">scale_fill_dataedu</span>()</a></code></pre></div>
<p><img src="08-wt-gradebook_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Using {ggplot} we can create many types of graphs. Using our <code>classwork_df</code> from earlier, we can see the distribution of scores and how they differ from classwork to classwork using boxplots. We are able to do this because we have made the <code>classworks</code> and <code>scores</code> columns into tidy formats.</p>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb123-1" title="1"><span class="co"># Scatterplot of continuous variable</span></a>
<a class="sourceLine" id="cb123-2" title="2">classwork_df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb123-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> classwork_number,</a>
<a class="sourceLine" id="cb123-4" title="4">             <span class="dt">y =</span> score,</a>
<a class="sourceLine" id="cb123-5" title="5">             <span class="dt">fill =</span> classwork_number)) <span class="op">+</span></a>
<a class="sourceLine" id="cb123-6" title="6"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb123-7" title="7"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb123-8" title="8">    <span class="dt">title =</span> <span class="st">&quot;Distribution of Classwork Scores&quot;</span>,</a>
<a class="sourceLine" id="cb123-9" title="9">    <span class="dt">x =</span> <span class="st">&quot;Classwork&quot;</span>,</a>
<a class="sourceLine" id="cb123-10" title="10">    <span class="dt">y =</span> <span class="st">&quot;Scores&quot;</span></a>
<a class="sourceLine" id="cb123-11" title="11">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb123-12" title="12"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb123-13" title="13"><span class="st">  </span><span class="kw">scale_fill_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb123-14" title="14"><span class="st">  </span><span class="kw">theme</span>(</a>
<a class="sourceLine" id="cb123-15" title="15">    <span class="co"># removes legend</span></a>
<a class="sourceLine" id="cb123-16" title="16">    <span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>,</a>
<a class="sourceLine" id="cb123-17" title="17">    <span class="co"># angles the x axis labels</span></a>
<a class="sourceLine" id="cb123-18" title="18">    <span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">angle =</span> <span class="dv">45</span>, <span class="dt">hjust =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb123-19" title="19">    ) </a></code></pre></div>
<p><img src="08-wt-gradebook_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
<div id="model-data" class="section level3">
<h3><span class="header-section-number">8.6.2</span> Model Data</h3>
<div id="deciding-an-an-analysis" class="section level4">
<h4><span class="header-section-number">8.6.2.1</span> Deciding an an Analysis</h4>
<p>Using this spreadsheet, we can start to form hypotheses about the data. For example, we can ask ourselves, “Can we predict overall grade using formative assessment scores?” For this, we will try to predict a response variable Y (overall grade) as a function of a predictor variable Y (formative assessment scores). The goal is to create a mathematical equation for overall grade as a function of formative assessment scores when only formative assessment scores are known.</p>
</div>
<div id="visualize-data-to-check-assumptions" class="section level4">
<h4><span class="header-section-number">8.6.2.2</span> Visualize Data to Check Assumptions</h4>
<p>It’s important to visualize data to see any distributions, trends, or patterns before building a model. We use {ggplot} to understand these variables graphically.</p>
<div id="linearity" class="section level5">
<h5><span class="header-section-number">8.6.2.2.1</span> Linearity</h5>
<p>First, we plot X and Y to determine if we can see a linear relationship between the predictor and response. The x-axis shows the formative assessment scores while the y-axis shows the overall grades. The graph suggests a correlation between overall class grade and formative assessment scores. As the formative scores goes up, the overall grade goes up too.</p>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb124-1" title="1"><span class="co"># Scatterplot between formative assessment and grades by percent</span></a>
<a class="sourceLine" id="cb124-2" title="2"><span class="co"># To determine linear relationship</span></a>
<a class="sourceLine" id="cb124-3" title="3">gradebook <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb124-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> formative_assessments,</a>
<a class="sourceLine" id="cb124-5" title="5">             <span class="dt">y =</span> running_average)) <span class="op">+</span></a>
<a class="sourceLine" id="cb124-6" title="6"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color =</span> <span class="kw">dataedu_cols</span>(<span class="st">&quot;green&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb124-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Relationship Between Overall Grade and Formative Assessments&quot;</span>,</a>
<a class="sourceLine" id="cb124-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Formative Assessment Score&quot;</span>,</a>
<a class="sourceLine" id="cb124-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;Overall Grade in Percentage&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb124-10" title="10"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="08-wt-gradebook_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>We can layer different types of plots on top of each other in {ggplot}. Here the scatterplot is layered with a line of best fit, suggesting a positive linear relationship.</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb125-1" title="1"><span class="co"># Scatterplot between formative assessment and grades by percent</span></a>
<a class="sourceLine" id="cb125-2" title="2"><span class="co"># To determine linear relationship</span></a>
<a class="sourceLine" id="cb125-3" title="3"><span class="co"># With line of best fit</span></a>
<a class="sourceLine" id="cb125-4" title="4">gradebook <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb125-5" title="5"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> formative_assessments,</a>
<a class="sourceLine" id="cb125-6" title="6">             <span class="dt">y =</span> running_average)) <span class="op">+</span></a>
<a class="sourceLine" id="cb125-7" title="7"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">color =</span> <span class="kw">dataedu_cols</span>(<span class="st">&quot;green&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb125-8" title="8"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>,</a>
<a class="sourceLine" id="cb125-9" title="9">              <span class="dt">se =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb125-10" title="10"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Relationship Between Overall Grade and Formative Assessments&quot;</span>,</a>
<a class="sourceLine" id="cb125-11" title="11">       <span class="dt">x =</span> <span class="st">&quot;Formative Assessment Score&quot;</span>,</a>
<a class="sourceLine" id="cb125-12" title="12">       <span class="dt">y =</span> <span class="st">&quot;Overall Grade in Percentage&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb125-13" title="13"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="08-wt-gradebook_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
</div>
<div id="outliers" class="section level5">
<h5><span class="header-section-number">8.6.2.2.2</span> Outliers</h5>
<p>Now we use boxplots to determine if there are any outliers in formative assessment scores or overall grades. As we would like to conduct a linear regression, we’re hoping to see no outliers in the data. We don’t see any for these two variables, so we can proceed with the model.</p>
<div class="sourceCode" id="cb126"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb126-1" title="1"><span class="co"># Boxplot of formative assessment scores</span></a>
<a class="sourceLine" id="cb126-2" title="2"><span class="co"># To determine if there are any outliers</span></a>
<a class="sourceLine" id="cb126-3" title="3">gradebook <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb126-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</a>
<a class="sourceLine" id="cb126-5" title="5">             <span class="dt">y =</span> formative_assessments)) <span class="op">+</span></a>
<a class="sourceLine" id="cb126-6" title="6"><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">fill =</span> <span class="kw">dataedu_cols</span>(<span class="st">&quot;yellow&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb126-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Formative Assessment Scores&quot;</span>,</a>
<a class="sourceLine" id="cb126-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Formative Assessment&quot;</span>,</a>
<a class="sourceLine" id="cb126-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;Score&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb126-10" title="10"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="08-wt-gradebook_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb127-1" title="1"><span class="co"># Boxplot of overall grade scores in percentage</span></a>
<a class="sourceLine" id="cb127-2" title="2"><span class="co"># To determine if there are any outliers</span></a>
<a class="sourceLine" id="cb127-3" title="3">gradebook <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb127-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</a>
<a class="sourceLine" id="cb127-5" title="5">             <span class="dt">y =</span> running_average)) <span class="op">+</span></a>
<a class="sourceLine" id="cb127-6" title="6"><span class="st">  </span><span class="kw">geom_boxplot</span>(<span class="dt">fill =</span> <span class="kw">dataedu_cols</span>(<span class="st">&quot;darkblue&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb127-7" title="7"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Distribution of Overall Grade Scores&quot;</span>,</a>
<a class="sourceLine" id="cb127-8" title="8">       <span class="dt">x =</span> <span class="st">&quot;Overall Grade&quot;</span>,</a>
<a class="sourceLine" id="cb127-9" title="9">       <span class="dt">y =</span> <span class="st">&quot;Score in Percentage&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb127-10" title="10"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="08-wt-gradebook_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
</div>
</div>
<div id="correlation-analysis" class="section level3">
<h3><span class="header-section-number">8.6.3</span> Correlation Analysis</h3>
<p>We want to know the strength of the relationship between the two variables, formative assessment scores and overall grade percentage. The strength is denoted by the “correlation coefficient.” The correlation coefficient goes from -1 to 1. If one variable consistently increases with the increasing value of the other, then they have a positive correlation (towards 1). If one variable consistently decreases with the increasing value of the other, then they have a negative correlation (towards -1). If the correlation coefficient is 0, then there is no relationship between the two variables.</p>
<p>Correlation is good for finding relationships but it does <em>not</em> imply that one variable causes the other (correlation does not mean causation).</p>
<div class="sourceCode" id="cb128"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb128-1" title="1"><span class="kw">cor</span>(gradebook<span class="op">$</span>formative_assessments, gradebook<span class="op">$</span>running_average)</a></code></pre></div>
<pre><code>## [1] 0.6632553</code></pre>
</div>
<div id="building-a-linear-model" class="section level3">
<h3><span class="header-section-number">8.6.4</span> Building a Linear Model</h3>
<p>In chapter 7, we introduced the concept of linear models. Let’s use that same technique here. Now that you’ve checked your assumptions and seen a linear relationship, we can build a linear model, that is, a mathematical formula that calculates your running average as a function of your formative assessment score. This is done using the <code>lm()</code> function, where the arguments are:</p>
<ul>
<li>Your predictor (formative_assessments)</li>
<li>Your response (running_average)</li>
<li>The data (gradebook)</li>
</ul>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb130-1" title="1">linear_mod &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb130-2" title="2"><span class="st">  </span><span class="kw">lm</span>(running_average <span class="op">~</span><span class="st"> </span>formative_assessments, <span class="dt">data =</span> gradebook)</a>
<a class="sourceLine" id="cb130-3" title="3"></a>
<a class="sourceLine" id="cb130-4" title="4"><span class="kw">summary</span>(linear_mod)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = running_average ~ formative_assessments, data = gradebook)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.2814 -2.7925 -0.0129  3.3179  8.5353 
## 
## Coefficients:
##                       Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           50.11511    8.54774   5.863 5.64e-06 ***
## formative_assessments  0.42136    0.09914   4.250 0.000302 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.657 on 23 degrees of freedom
## Multiple R-squared:  0.4399, Adjusted R-squared:  0.4156 
## F-statistic: 18.06 on 1 and 23 DF,  p-value: 0.0003018</code></pre>
<p>When you fit a model to two variables, you create an equation that describes the relationship between those two variables on average. This equation uses the <code>(Intercept)</code>, which is 50.11511, and the coefficient for <code>formative_assessments</code>, which is .42136. The equation reads like this:</p>
<pre><code>running_average = 50.11511 + 0.42136*formative_assessments</code></pre>
<p>We interpret these results by saying “For every one unit increase in formative assessment scores, we can expect a .421 unit increase in running average scores”. This equation estimates the relationship between formative assessment scores and running average scores in the student population. Think of it as an educated guess about any one particular student’s running average, if all you had was their formative assessment scores.</p>
<p><em>More on interpreting models</em></p>
<p>Challenge yourself to apply your education knowledge to the way you communicate a model’s output to your audience. Consider the difference between describing the relationship between formative assessment scores and running averages for a large group of students and for an individual student.</p>
<p>If you were describing the formatives assessment system to stakeholders, you might say something like, “We can generally expect our students to show a .421 increase in their running average score for every one point increase in their formative assessment scores.” That makes sense, because your goal is to explain what happens <strong>in general</strong>.</p>
<p>But we can rarely expect every prediction about individual students to be correct, even with a reliable model. So when using this equation to inform how you support an individual student, it’s important to consider all the real-life factors, visible and invisible, that influence an individual student outcome.</p>
<p>To illustrate this concept, consider predicting how long it takes for you to run around the block right outside your office. Imagine you ran around the block five times and after each lap you jotted your time down on a post-it. After the fifth lap you do a calculation on your cell phone and see that your average lap time is five minutes. If you were to guess how long your sixth lap would take, you’d be smart to guess five minutes. But intuitively you know there’s no guarantee the sixth lap time will land right on your average. Maybe you’ll trip on a crack in the sidewalk and lose a few seconds, or maybe your favorite song pops into your head and gives you a thirty second advantage. Statisticians would call the difference between your predicted lap time and your actual lap time a “residual” value. Residuals are the differences between predicted values and actual values that aren’t explained by your linear model equation.</p>
<p>It takes practice to interpret and communicate these concepts well. A good start is exploring model outputs in two contexts: first as a general description of a population and second as a practical tool for helping invidivual student performance.</p>
</div>
</div>
<div id="conclusion-4" class="section level2">
<h2><span class="header-section-number">8.7</span> Conclusion</h2>
<p>This walkthrough chapter followed the basic steps of a data analysis project.
We first <em>imported</em> our data, then <em>cleaned and transformed</em> it.
Once we had the data in a tidy format, we were able to <em>explore</em> the data using data visualization before <em>modeling</em> the data using linear regression.
The only remaining step in this analysis would be to communicate our findings using a tool such as <a href="https://rmarkdown.rstudio.com/">RMarkdown</a>.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c07.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c09.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/data-edu/data-science-in-education/edit/master/08-wt-gradebook.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
