<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>10 Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data | Data Science in Education Using R</title>
  <meta name="description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="generator" content="bookdown 0.16.5 and GitBook 2.6.7" />

  <meta property="og:title" content="10 Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data | Data Science in Education Using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="github-repo" content="data-edu/data-science-in-education" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="10 Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data | Data Science in Education Using R" />
  
  <meta name="twitter:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  

<meta name="author" content="Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="c09.html"/>
<link rel="next" href="c11.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction: Data Science in Education–You’re Invited!</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#c01"><i class="fa fa-check"></i><b>1.1</b> Learning Data Science in Education</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#making-the-path-a-little-clearer"><i class="fa fa-check"></i><b>1.2</b> Making the Path a Little Clearer</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02.html"><a href="c02.html"><i class="fa fa-check"></i><b>2</b> How to Use this Book</a><ul>
<li class="chapter" data-level="2.1" data-path="c02.html"><a href="c02.html#different-strokes-for-different-data-scientists-in-education"><i class="fa fa-check"></i><b>2.1</b> Different Strokes for Different Data Scientists in Education</a><ul>
<li class="chapter" data-level="2.1.1" data-path="c02.html"><a href="c02.html#read-the-book-cover-to-cover-and-how-to-keep-going"><i class="fa fa-check"></i><b>2.1.1</b> Read the Book Cover to Cover (and How to Keep Going)</a></li>
<li class="chapter" data-level="2.1.2" data-path="c02.html"><a href="c02.html#pick-a-chapter-of-interest-and-start-there"><i class="fa fa-check"></i><b>2.1.2</b> Pick a Chapter of Interest and Start There</a></li>
<li class="chapter" data-level="2.1.3" data-path="c02.html"><a href="c02.html#read-through-the-walkthroughs-and-run-the-code"><i class="fa fa-check"></i><b>2.1.3</b> Read Through the Walkthroughs and Run the Code</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="c02.html"><a href="c02.html#a-note-on-statistics"><i class="fa fa-check"></i><b>2.2</b> A Note on Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="c02.html"><a href="c02.html#what-this-book-is-not-about"><i class="fa fa-check"></i><b>2.3</b> What This Book Is Not About</a></li>
<li class="chapter" data-level="2.4" data-path="c02.html"><a href="c02.html#contributing-to-the-book"><i class="fa fa-check"></i><b>2.4</b> Contributing to the Book</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03.html"><a href="c03.html"><i class="fa fa-check"></i><b>3</b> What is a Data Scientist in Education?</a><ul>
<li class="chapter" data-level="3.1" data-path="c03.html"><a href="c03.html#data-roles-in-education"><i class="fa fa-check"></i><b>3.1</b> Data Roles in Education</a><ul>
<li class="chapter" data-level="3.1.1" data-path="c03.html"><a href="c03.html#building-systems-that-get-data-to-the-right-people"><i class="fa fa-check"></i><b>3.1.1</b> Building Systems That Get Data to the Right People</a></li>
<li class="chapter" data-level="3.1.2" data-path="c03.html"><a href="c03.html#measuring-the-impact-of-our-work-on-the-student-experience"><i class="fa fa-check"></i><b>3.1.2</b> Measuring the Impact of Our Work on the Student Experience</a></li>
<li class="chapter" data-level="3.1.3" data-path="c03.html"><a href="c03.html#looking-for-patterns-in-student-data"><i class="fa fa-check"></i><b>3.1.3</b> Looking for Patterns in Student Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="c03.html"><a href="c03.html#improving-how-we-use-statistical-models-in-education"><i class="fa fa-check"></i><b>3.1.4</b> Improving How We Use Statistical Models in Education</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="c03.html"><a href="c03.html#common-activities-of-data-scientists"><i class="fa fa-check"></i><b>3.2</b> Common Activities of Data Scientists</a><ul>
<li class="chapter" data-level="3.2.1" data-path="c03.html"><a href="c03.html#processing-data"><i class="fa fa-check"></i><b>3.2.1</b> Processing Data</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03.html"><a href="c03.html#doing-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Doing Analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03.html"><a href="c03.html#sharing-results"><i class="fa fa-check"></i><b>3.2.3</b> Sharing Results</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03.html"><a href="c03.html#who-we-are-and-what-we-do"><i class="fa fa-check"></i><b>3.3</b> Who We Are and What We Do</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04.html"><a href="c04.html"><i class="fa fa-check"></i><b>4</b> Special Considerations</a><ul>
<li class="chapter" data-level="4.1" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-any-domain"><i class="fa fa-check"></i><b>4.1</b> Things to Consider when Doing Data Science in any Domain</a><ul>
<li class="chapter" data-level="4.1.1" data-path="c04.html"><a href="c04.html#a-new-field"><i class="fa fa-check"></i><b>4.1.1</b> A New Field</a></li>
<li class="chapter" data-level="4.1.2" data-path="c04.html"><a href="c04.html#addressing-ambiguity-a-reproducible-approach"><i class="fa fa-check"></i><b>4.1.2</b> Addressing Ambiguity: A Reproducible Approach</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-education"><i class="fa fa-check"></i><b>4.2</b> Things to Consider when Doing Data Science in Education</a><ul>
<li class="chapter" data-level="4.2.1" data-path="c04.html"><a href="c04.html#addressing-organizational-resistance-a-self-driven-analytic-approach"><i class="fa fa-check"></i><b>4.2.1</b> Addressing organizational resistance: A self-driven analytic approach</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04.html"><a href="c04.html#lack-of-processes-and-guidelines"><i class="fa fa-check"></i><b>4.2.2</b> Lack of Processes and Guidelines</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04.html"><a href="c04.html#limited-training-and-educational-opportunities"><i class="fa fa-check"></i><b>4.2.3</b> Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="4.2.4" data-path="c04.html"><a href="c04.html#advancing-equity"><i class="fa fa-check"></i><b>4.2.4</b> Advancing Equity</a></li>
<li class="chapter" data-level="4.2.5" data-path="c04.html"><a href="c04.html#the-complex-and-messy-nature-of-education-data"><i class="fa fa-check"></i><b>4.2.5</b> The Complex and Messy Nature of Education Data</a></li>
<li class="chapter" data-level="4.2.6" data-path="c04.html"><a href="c04.html#ethical-and-legal-concerns"><i class="fa fa-check"></i><b>4.2.6</b> Ethical and Legal Concerns</a></li>
<li class="chapter" data-level="4.2.7" data-path="c04.html"><a href="c04.html#analytic-considerations"><i class="fa fa-check"></i><b>4.2.7</b> Analytic Considerations</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04.html"><a href="c04.html#conclusion"><i class="fa fa-check"></i><b>4.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05.html"><a href="c05.html"><i class="fa fa-check"></i><b>5</b> Getting Started with R and RStudio</a><ul>
<li class="chapter" data-level="5.1" data-path="c05.html"><a href="c05.html#chapter-overview"><i class="fa fa-check"></i><b>5.1</b> Chapter overview</a></li>
<li class="chapter" data-level="5.2" data-path="c05.html"><a href="c05.html#getting-started"><i class="fa fa-check"></i><b>5.2</b> Getting Started</a></li>
<li class="chapter" data-level="5.3" data-path="c05.html"><a href="c05.html#downloading-r-and-rstudio"><i class="fa fa-check"></i><b>5.3</b> Downloading R and RStudio</a><ul>
<li class="chapter" data-level="5.3.1" data-path="c05.html"><a href="c05.html#to-download-r"><i class="fa fa-check"></i><b>5.3.1</b> To download R:</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05.html"><a href="c05.html#to-download-rstudio"><i class="fa fa-check"></i><b>5.3.2</b> To download RStudio:</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05.html"><a href="c05.html#getting-to-know-r-through-rstudio"><i class="fa fa-check"></i><b>5.4</b> Getting to know R through RStudio</a><ul>
<li class="chapter" data-level="5.4.1" data-path="c05.html"><a href="c05.html#getting-to-know-r-challenge-questions"><i class="fa fa-check"></i><b>5.4.1</b> Getting to Know R: Challenge Questions</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05.html"><a href="c05.html#diving-a-little-deeper-into-r-with-swirl"><i class="fa fa-check"></i><b>5.5</b> Diving a little deeper into R with <code>swirl</code></a></li>
<li class="chapter" data-level="5.6" data-path="c05.html"><a href="c05.html#introduction-to-help-documentation"><i class="fa fa-check"></i><b>5.6</b> Introduction to Help Documentation</a></li>
<li class="chapter" data-level="5.7" data-path="c05.html"><a href="c05.html#downloading-and-accessing-the-data-sets-used-in-this-book"><i class="fa fa-check"></i><b>5.7</b> Downloading and accessing the data sets used in this book</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06.html"><a href="c06.html"><i class="fa fa-check"></i><b>6</b> Foundational Skills</a><ul>
<li class="chapter" data-level="6.1" data-path="c06.html"><a href="c06.html#chapter-overview-1"><i class="fa fa-check"></i><b>6.1</b> Chapter overview</a></li>
<li class="chapter" data-level="6.2" data-path="c06.html"><a href="c06.html#foundational-skills-framework"><i class="fa fa-check"></i><b>6.2</b> Foundational Skills Framework</a></li>
<li class="chapter" data-level="6.3" data-path="c06.html"><a href="c06.html#setting-up-your-project"><i class="fa fa-check"></i><b>6.3</b> Setting up your Project</a><ul>
<li class="chapter" data-level="6.3.1" data-path="c06.html"><a href="c06.html#coding-in-rstudio"><i class="fa fa-check"></i><b>6.3.1</b> Coding in RStudio</a></li>
<li class="chapter" data-level="6.3.2" data-path="c06.html"><a href="c06.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>6.3.2</b> Installing and Loading Packages</a></li>
<li class="chapter" data-level="6.3.3" data-path="c06.html"><a href="c06.html#running-functions-from-packages"><i class="fa fa-check"></i><b>6.3.3</b> Running Functions from Packages</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="c06.html"><a href="c06.html#code-for-foundational-skills"><i class="fa fa-check"></i><b>6.4</b> Code for Foundational Skills</a><ul>
<li class="chapter" data-level="6.4.1" data-path="c06.html"><a href="c06.html#see-ryans-work-on-prefacing-functions---need-to-preface-dplyrarrange"><i class="fa fa-check"></i><b>6.4.1</b> See Ryan’s work on prefacing functions - need to preface dplyr::arrange()!</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06.html"><a href="c06.html#packages-and-functions"><i class="fa fa-check"></i><b>6.5</b> Packages and Functions</a></li>
<li class="chapter" data-level="6.6" data-path="c06.html"><a href="c06.html#installing-and-loading-a-package"><i class="fa fa-check"></i><b>6.6</b> Installing and loading a package</a><ul>
<li class="chapter" data-level="6.6.1" data-path="c06.html"><a href="c06.html#recognizing-a-function"><i class="fa fa-check"></i><b>6.6.1</b> Recognizing a function</a></li>
<li class="chapter" data-level="6.6.2" data-path="c06.html"><a href="c06.html#running-code-in-r"><i class="fa fa-check"></i><b>6.6.2</b> Running code in R</a></li>
<li class="chapter" data-level="6.6.3" data-path="c06.html"><a href="c06.html#run-this-code"><i class="fa fa-check"></i><b>6.6.3</b> Run this code</a></li>
<li class="chapter" data-level="6.6.4" data-path="c06.html"><a href="c06.html#how-to-find-a-package"><i class="fa fa-check"></i><b>6.6.4</b> How to find a package</a></li>
<li class="chapter" data-level="6.6.5" data-path="c06.html"><a href="c06.html#how-to-learn-more-about-a-package"><i class="fa fa-check"></i><b>6.6.5</b> How to learn more about a package</a></li>
<li class="chapter" data-level="6.6.6" data-path="c06.html"><a href="c06.html#function-conflicts-between-packages-between-base-r-and-loaded-packages"><i class="fa fa-check"></i><b>6.6.6</b> Function conflicts: between packages, between base R and loaded packages</a></li>
<li class="chapter" data-level="6.6.7" data-path="c06.html"><a href="c06.html#commenting-in-r"><i class="fa fa-check"></i><b>6.6.7</b> Commenting in R</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="c06.html"><a href="c06.html#using-functions-to-import-data"><i class="fa fa-check"></i><b>6.7</b> Using functions to import data</a><ul>
<li class="chapter" data-level="6.7.1" data-path="c06.html"><a href="c06.html#run-this-code-1"><i class="fa fa-check"></i><b>6.7.1</b> Run this code</a></li>
<li class="chapter" data-level="6.7.2" data-path="c06.html"><a href="c06.html#the-assignment-operator"><i class="fa fa-check"></i><b>6.7.2</b> The assignment operator</a></li>
<li class="chapter" data-level="6.7.3" data-path="c06.html"><a href="c06.html#the-here-package"><i class="fa fa-check"></i><b>6.7.3</b> The <code>here</code> package</a></li>
<li class="chapter" data-level="6.7.4" data-path="c06.html"><a href="c06.html#data-types"><i class="fa fa-check"></i><b>6.7.4</b> Data types</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="c06.html"><a href="c06.html#datasets-and-variables"><i class="fa fa-check"></i><b>6.8</b> Datasets and variables</a><ul>
<li class="chapter" data-level="6.8.1" data-path="c06.html"><a href="c06.html#run-the-following-code"><i class="fa fa-check"></i><b>6.8.1</b> Run the following code</a></li>
<li class="chapter" data-level="6.8.2" data-path="c06.html"><a href="c06.html#tibbles-and-dataframes-oh-my"><i class="fa fa-check"></i><b>6.8.2</b> Tibbles and dataframes, oh my!</a></li>
<li class="chapter" data-level="6.8.3" data-path="c06.html"><a href="c06.html#the-operator"><i class="fa fa-check"></i><b>6.8.3</b> The <code>$</code> operator</a></li>
<li class="chapter" data-level="6.8.4" data-path="c06.html"><a href="c06.html#spaces-in-variable-names"><i class="fa fa-check"></i><b>6.8.4</b> Spaces in variable names</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="c06.html"><a href="c06.html#the-pipe-operator"><i class="fa fa-check"></i><b>6.9</b> The pipe operator</a><ul>
<li class="chapter" data-level="6.9.1" data-path="c06.html"><a href="c06.html#piping-practices"><i class="fa fa-check"></i><b>6.9.1</b> Piping practices</a></li>
<li class="chapter" data-level="6.9.2" data-path="c06.html"><a href="c06.html#closing-your-parentheses"><i class="fa fa-check"></i><b>6.9.2</b> Closing your parentheses</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="c06.html"><a href="c06.html#finicky-functions-rename-this-section"><i class="fa fa-check"></i><b>6.10</b> Finicky functions (rename this section)</a><ul>
<li class="chapter" data-level="6.10.1" data-path="c06.html"><a href="c06.html#when-functions-need-arguments-and-when-they-dont"><i class="fa fa-check"></i><b>6.10.1</b> When functions need arguments and when they don’t</a></li>
<li class="chapter" data-level="6.10.2" data-path="c06.html"><a href="c06.html#functions-within-functions"><i class="fa fa-check"></i><b>6.10.2</b> Functions within functions</a></li>
<li class="chapter" data-level="6.10.3" data-path="c06.html"><a href="c06.html#the-difference-between-and"><i class="fa fa-check"></i><b>6.10.3</b> The difference between <code>=</code> and <code>==</code></a></li>
<li class="chapter" data-level="6.10.4" data-path="c06.html"><a href="c06.html#writing-your-own-functions"><i class="fa fa-check"></i><b>6.10.4</b> Writing your own functions</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="c06.html"><a href="c06.html#section-on-c-and-in"><i class="fa fa-check"></i><b>6.11</b> SECTION ON c() and %in%</a></li>
<li class="chapter" data-level="6.12" data-path="c06.html"><a href="c06.html#creating-objects"><i class="fa fa-check"></i><b>6.12</b> Creating objects</a><ul>
<li class="chapter" data-level="6.12.1" data-path="c06.html"><a href="c06.html#object-oriented-programming-oop"><i class="fa fa-check"></i><b>6.12.1</b> Object-oriented programming (OOP)</a></li>
<li class="chapter" data-level="6.12.2" data-path="c06.html"><a href="c06.html#analysis-vs.-development"><i class="fa fa-check"></i><b>6.12.2</b> Analysis vs. development</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="c06.html"><a href="c06.html#creating-projects"><i class="fa fa-check"></i><b>6.13</b> Creating Projects</a><ul>
<li class="chapter" data-level="6.13.1" data-path="c06.html"><a href="c06.html#track-two-welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>6.13.1</b> Track Two: Welcome to the Tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="6.14" data-path="c06.html"><a href="c06.html#include-at-end-of-chapter"><i class="fa fa-check"></i><b>6.14</b> Include at end of chapter!</a></li>
<li class="chapter" data-level="6.15" data-path="c06.html"><a href="c06.html#loading-data-from-excel-sav-and-google-sheets"><i class="fa fa-check"></i><b>6.15</b> Loading Data from Excel, SAV, and Google Sheets</a><ul>
<li class="chapter" data-level="6.15.1" data-path="c06.html"><a href="c06.html#loading-excel-files"><i class="fa fa-check"></i><b>6.15.1</b> Loading Excel Files</a></li>
<li class="chapter" data-level="6.15.2" data-path="c06.html"><a href="c06.html#loading-sav-files"><i class="fa fa-check"></i><b>6.15.2</b> Loading SAV Files</a></li>
<li class="chapter" data-level="6.15.3" data-path="c06.html"><a href="c06.html#google-sheets"><i class="fa fa-check"></i><b>6.15.3</b> Google Sheets</a></li>
<li class="chapter" data-level="6.15.4" data-path="c06.html"><a href="c06.html#saving-a-file-from-the-web"><i class="fa fa-check"></i><b>6.15.4</b> Saving a File from the Web</a></li>
<li class="chapter" data-level="6.15.5" data-path="c06.html"><a href="c06.html#loading-a-.csv-file"><i class="fa fa-check"></i><b>6.15.5</b> Loading a <code>.csv</code> File</a></li>
<li class="chapter" data-level="6.15.6" data-path="c06.html"><a href="c06.html#saving-files"><i class="fa fa-check"></i><b>6.15.6</b> Saving Files</a></li>
<li class="chapter" data-level="6.15.7" data-path="c06.html"><a href="c06.html#conclusion-1"><i class="fa fa-check"></i><b>6.15.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6.16" data-path="c06.html"><a href="c06.html#processing-data-1"><i class="fa fa-check"></i><b>6.16</b> Processing Data</a></li>
<li class="chapter" data-level="6.17" data-path="c06.html"><a href="c06.html#communicating-sharing-results"><i class="fa fa-check"></i><b>6.17</b> Communicating / Sharing Results</a><ul>
<li class="chapter" data-level="6.17.1" data-path="c06.html"><a href="c06.html#miscellaneous-from-import"><i class="fa fa-check"></i><b>6.17.1</b> miscellaneous from import</a></li>
</ul></li>
<li class="chapter" data-level="6.18" data-path="c06.html"><a href="c06.html#old-text---keep-until-reincorporatedreaddressed"><i class="fa fa-check"></i><b>6.18</b> Old text - keep until reincorporated//readdressed</a></li>
<li class="chapter" data-level="6.19" data-path="c06.html"><a href="c06.html#may-not-need"><i class="fa fa-check"></i><b>6.19</b> May not need</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07.html"><a href="c07.html"><i class="fa fa-check"></i><b>7</b> Walkthrough 1: The Education Dataset Science Pipeline With Online Science Class Data</a><ul>
<li class="chapter" data-level="7.1" data-path="c07.html"><a href="c07.html#vocabulary"><i class="fa fa-check"></i><b>7.1</b> Vocabulary</a></li>
<li class="chapter" data-level="7.2" data-path="c07.html"><a href="c07.html#introduction"><i class="fa fa-check"></i><b>7.2</b> Introduction</a><ul>
<li class="chapter" data-level="7.2.1" data-path="c07.html"><a href="c07.html#background"><i class="fa fa-check"></i><b>7.2.1</b> Background</a></li>
<li class="chapter" data-level="7.2.2" data-path="c07.html"><a href="c07.html#data-sources"><i class="fa fa-check"></i><b>7.2.2</b> Data Sources</a></li>
<li class="chapter" data-level="7.2.3" data-path="c07.html"><a href="c07.html#data-source-2-log-trace-data"><i class="fa fa-check"></i><b>7.2.3</b> Data source #2: Log-trace data</a></li>
<li class="chapter" data-level="7.2.4" data-path="c07.html"><a href="c07.html#data-source-3-achievement-related-and-gradebook-data"><i class="fa fa-check"></i><b>7.2.4</b> Data source #3: Achievement-related and gradebook data</a></li>
<li class="chapter" data-level="7.2.5" data-path="c07.html"><a href="c07.html#data-source-4-discussion-board-data"><i class="fa fa-check"></i><b>7.2.5</b> Data source #4: Discussion board data</a></li>
<li class="chapter" data-level="7.2.6" data-path="c07.html"><a href="c07.html#methods"><i class="fa fa-check"></i><b>7.2.6</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="c07.html"><a href="c07.html#load-packages"><i class="fa fa-check"></i><b>7.3</b> Load Packages</a></li>
<li class="chapter" data-level="7.4" data-path="c07.html"><a href="c07.html#import-data"><i class="fa fa-check"></i><b>7.4</b> Import Data</a></li>
<li class="chapter" data-level="7.5" data-path="c07.html"><a href="c07.html#view-data"><i class="fa fa-check"></i><b>7.5</b> View data</a></li>
<li class="chapter" data-level="7.6" data-path="c07.html"><a href="c07.html#process-data"><i class="fa fa-check"></i><b>7.6</b> Process data</a><ul>
<li class="chapter" data-level="7.6.1" data-path="c07.html"><a href="c07.html#processing-the-course-data"><i class="fa fa-check"></i><b>7.6.1</b> Processing the course data</a></li>
<li class="chapter" data-level="7.6.2" data-path="c07.html"><a href="c07.html#joining-the-data"><i class="fa fa-check"></i><b>7.6.2</b> Joining the data</a></li>
<li class="chapter" data-level="7.6.3" data-path="c07.html"><a href="c07.html#finding-distinct-cases-at-the-student-level"><i class="fa fa-check"></i><b>7.6.3</b> Finding distinct cases at the student-level</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="c07.html"><a href="c07.html#analysis"><i class="fa fa-check"></i><b>7.7</b> Analysis</a><ul>
<li class="chapter" data-level="7.7.1" data-path="c07.html"><a href="c07.html#the-relationship-between-time-spent-on-course-and-percentage-of-points-earned"><i class="fa fa-check"></i><b>7.7.1</b> The relationship between time spent on course and percentage of points earned</a></li>
<li class="chapter" data-level="7.7.2" data-path="c07.html"><a href="c07.html#linear-model-regression"><i class="fa fa-check"></i><b>7.7.2</b> Linear model (regression)</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="c07.html"><a href="c07.html#results"><i class="fa fa-check"></i><b>7.8</b> Results</a></li>
<li class="chapter" data-level="7.9" data-path="c07.html"><a href="c07.html#conclusion-2"><i class="fa fa-check"></i><b>7.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08.html"><a href="c08.html"><i class="fa fa-check"></i><b>8</b> Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective</a><ul>
<li class="chapter" data-level="8.1" data-path="c08.html"><a href="c08.html#introduction-1"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="c08.html"><a href="c08.html#data-sources-1"><i class="fa fa-check"></i><b>8.2</b> Data Sources</a></li>
<li class="chapter" data-level="8.3" data-path="c08.html"><a href="c08.html#load-packages-1"><i class="fa fa-check"></i><b>8.3</b> Load Packages</a></li>
<li class="chapter" data-level="8.4" data-path="c08.html"><a href="c08.html#import-data-1"><i class="fa fa-check"></i><b>8.4</b> Import Data</a></li>
<li class="chapter" data-level="8.5" data-path="c08.html"><a href="c08.html#tidy-data"><i class="fa fa-check"></i><b>8.5</b> Tidy Data</a></li>
<li class="chapter" data-level="8.6" data-path="c08.html"><a href="c08.html#process-data-1"><i class="fa fa-check"></i><b>8.6</b> Process Data</a></li>
<li class="chapter" data-level="8.7" data-path="c08.html"><a href="c08.html#visualize-data"><i class="fa fa-check"></i><b>8.7</b> Visualize Data</a></li>
<li class="chapter" data-level="8.8" data-path="c08.html"><a href="c08.html#model-data"><i class="fa fa-check"></i><b>8.8</b> Model Data</a><ul>
<li class="chapter" data-level="8.8.1" data-path="c08.html"><a href="c08.html#deciding-an-analysis"><i class="fa fa-check"></i><b>8.8.1</b> Deciding an Analysis</a></li>
<li class="chapter" data-level="8.8.2" data-path="c08.html"><a href="c08.html#visualize-data-to-check-assumptions"><i class="fa fa-check"></i><b>8.8.2</b> Visualize Data to Check Assumptions</a></li>
<li class="chapter" data-level="8.8.3" data-path="c08.html"><a href="c08.html#correlation-analysis"><i class="fa fa-check"></i><b>8.8.3</b> Correlation Analysis</a></li>
<li class="chapter" data-level="8.8.4" data-path="c08.html"><a href="c08.html#build-linear-model"><i class="fa fa-check"></i><b>8.8.4</b> Build Linear Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09.html"><a href="c09.html"><i class="fa fa-check"></i><b>9</b> Walkthrough 3: Introduction to Aggregate Data</a><ul>
<li class="chapter" data-level="9.1" data-path="c09.html"><a href="c09.html#introduction-2"><i class="fa fa-check"></i><b>9.1</b> Introduction</a><ul>
<li class="chapter" data-level="9.1.1" data-path="c09.html"><a href="c09.html#background-1"><i class="fa fa-check"></i><b>9.1.1</b> Background</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="c09.html"><a href="c09.html#data-sources-2"><i class="fa fa-check"></i><b>9.2</b> Data Sources</a><ul>
<li class="chapter" data-level="9.2.1" data-path="c09.html"><a href="c09.html#methods-1"><i class="fa fa-check"></i><b>9.2.1</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="c09.html"><a href="c09.html#load-packages-2"><i class="fa fa-check"></i><b>9.3</b> Load Packages</a></li>
<li class="chapter" data-level="9.4" data-path="c09.html"><a href="c09.html#import-data-2"><i class="fa fa-check"></i><b>9.4</b> Import Data</a></li>
<li class="chapter" data-level="9.5" data-path="c09.html"><a href="c09.html#view-data-1"><i class="fa fa-check"></i><b>9.5</b> View Data</a><ul>
<li class="chapter" data-level="9.5.1" data-path="c09.html"><a href="c09.html#discovering-distributions"><i class="fa fa-check"></i><b>9.5.1</b> Discovering Distributions</a></li>
<li class="chapter" data-level="9.5.2" data-path="c09.html"><a href="c09.html#anayzing-spread"><i class="fa fa-check"></i><b>9.5.2</b> Anayzing Spread</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="c09.html"><a href="c09.html#analysis-1"><i class="fa fa-check"></i><b>9.6</b> Analysis</a><ul>
<li class="chapter" data-level="9.6.1" data-path="c09.html"><a href="c09.html#creating-categories"><i class="fa fa-check"></i><b>9.6.1</b> Creating Categories</a></li>
<li class="chapter" data-level="9.6.2" data-path="c09.html"><a href="c09.html#reveal-relationships"><i class="fa fa-check"></i><b>9.6.2</b> Reveal Relationships</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="c09.html"><a href="c09.html#results-1"><i class="fa fa-check"></i><b>9.7</b> Results</a></li>
<li class="chapter" data-level="9.8" data-path="c09.html"><a href="c09.html#conclusion-3"><i class="fa fa-check"></i><b>9.8</b> Conclusion</a></li>
<li class="chapter" data-level="9.9" data-path="c09.html"><a href="c09.html#references"><i class="fa fa-check"></i><b>9.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="c10.html"><a href="c10.html"><i class="fa fa-check"></i><b>10</b> Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data</a><ul>
<li class="chapter" data-level="10.1" data-path="c10.html"><a href="c10.html#vocabulary-1"><i class="fa fa-check"></i><b>10.1</b> Vocabulary</a></li>
<li class="chapter" data-level="10.2" data-path="c10.html"><a href="c10.html#introduction-3"><i class="fa fa-check"></i><b>10.2</b> Introduction</a><ul>
<li class="chapter" data-level="10.2.1" data-path="c10.html"><a href="c10.html#background-2"><i class="fa fa-check"></i><b>10.2.1</b> Background</a></li>
<li class="chapter" data-level="10.2.2" data-path="c10.html"><a href="c10.html#methods-2"><i class="fa fa-check"></i><b>10.2.2</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="c10.html"><a href="c10.html#load-packages-3"><i class="fa fa-check"></i><b>10.3</b> Load Packages</a></li>
<li class="chapter" data-level="10.4" data-path="c10.html"><a href="c10.html#import-data-3"><i class="fa fa-check"></i><b>10.4</b> Import Data</a><ul>
<li class="chapter" data-level="10.4.1" data-path="c10.html"><a href="c10.html#reading-in-one-dataset"><i class="fa fa-check"></i><b>10.4.1</b> Reading In One Dataset</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10.html"><a href="c10.html#reading-in-many-datasets"><i class="fa fa-check"></i><b>10.4.2</b> Reading In Many Datasets</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10.html"><a href="c10.html#process-data-2"><i class="fa fa-check"></i><b>10.5</b> Process Data</a><ul>
<li class="chapter" data-level="10.5.1" data-path="c10.html"><a href="c10.html#fix-the-variable-names-in-the-2016-data"><i class="fa fa-check"></i><b>10.5.1</b> Fix the variable names in the 2016 data</a></li>
<li class="chapter" data-level="10.5.2" data-path="c10.html"><a href="c10.html#pick-variables"><i class="fa fa-check"></i><b>10.5.2</b> Pick variables</a></li>
<li class="chapter" data-level="10.5.3" data-path="c10.html"><a href="c10.html#combine-six-datasets-into-one"><i class="fa fa-check"></i><b>10.5.3</b> Combine six datasets into one</a></li>
<li class="chapter" data-level="10.5.4" data-path="c10.html"><a href="c10.html#filter-for-the-desired-disabilities-and-age-groups"><i class="fa fa-check"></i><b>10.5.4</b> Filter for the desired disabilities and age groups</a></li>
<li class="chapter" data-level="10.5.5" data-path="c10.html"><a href="c10.html#rename-the-variables"><i class="fa fa-check"></i><b>10.5.5</b> Rename the variables</a></li>
<li class="chapter" data-level="10.5.6" data-path="c10.html"><a href="c10.html#clean-state-names"><i class="fa fa-check"></i><b>10.5.6</b> Clean state names</a></li>
<li class="chapter" data-level="10.5.7" data-path="c10.html"><a href="c10.html#tidy-the-dataset"><i class="fa fa-check"></i><b>10.5.7</b> Tidy the dataset</a></li>
<li class="chapter" data-level="10.5.8" data-path="c10.html"><a href="c10.html#convert-data-types"><i class="fa fa-check"></i><b>10.5.8</b> Convert data types</a></li>
<li class="chapter" data-level="10.5.9" data-path="c10.html"><a href="c10.html#explore-and-address-nas"><i class="fa fa-check"></i><b>10.5.9</b> Explore and address NAs</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="c10.html"><a href="c10.html#analysis-how-have-child-counts-changed-over-time"><i class="fa fa-check"></i><b>10.6</b> Analysis: How Have Child Counts Changed Over Time?</a><ul>
<li class="chapter" data-level="10.6.1" data-path="c10.html"><a href="c10.html#visualize-the-dataset"><i class="fa fa-check"></i><b>10.6.1</b> Visualize the Dataset</a></li>
<li class="chapter" data-level="10.6.2" data-path="c10.html"><a href="c10.html#model-the-dataset"><i class="fa fa-check"></i><b>10.6.2</b> Model the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="c10.html"><a href="c10.html#results-2"><i class="fa fa-check"></i><b>10.7</b> Results</a></li>
<li class="chapter" data-level="10.8" data-path="c10.html"><a href="c10.html#conclusion-aggregate-data-as-context-for-student-data"><i class="fa fa-check"></i><b>10.8</b> Conclusion: Aggregate Data as Context for Student Data</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11.html"><a href="c11.html"><i class="fa fa-check"></i><b>11</b> Walkthrough 5: Text Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="11.1" data-path="c11.html"><a href="c11.html#vocabulary-2"><i class="fa fa-check"></i><b>11.1</b> Vocabulary</a></li>
<li class="chapter" data-level="11.2" data-path="c11.html"><a href="c11.html#introduction-4"><i class="fa fa-check"></i><b>11.2</b> Introduction</a><ul>
<li class="chapter" data-level="11.2.1" data-path="c11.html"><a href="c11.html#background-3"><i class="fa fa-check"></i><b>11.2.1</b> Background</a></li>
<li class="chapter" data-level="11.2.2" data-path="c11.html"><a href="c11.html#data-source"><i class="fa fa-check"></i><b>11.2.2</b> Data Source</a></li>
<li class="chapter" data-level="11.2.3" data-path="c11.html"><a href="c11.html#methods-3"><i class="fa fa-check"></i><b>11.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="c11.html"><a href="c11.html#load-packages-4"><i class="fa fa-check"></i><b>11.3</b> Load Packages</a></li>
<li class="chapter" data-level="11.4" data-path="c11.html"><a href="c11.html#import-data-4"><i class="fa fa-check"></i><b>11.4</b> Import Data</a><ul>
<li class="chapter" data-level="11.4.1" data-path="c11.html"><a href="c11.html#using-an-api"><i class="fa fa-check"></i><b>11.4.1</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="c11.html"><a href="c11.html#view-data-2"><i class="fa fa-check"></i><b>11.5</b> View Data</a></li>
<li class="chapter" data-level="11.6" data-path="c11.html"><a href="c11.html#process-data-3"><i class="fa fa-check"></i><b>11.6</b> Process Data</a></li>
<li class="chapter" data-level="11.7" data-path="c11.html"><a href="c11.html#analysis-counting-words"><i class="fa fa-check"></i><b>11.7</b> Analysis: Counting Words</a></li>
<li class="chapter" data-level="11.8" data-path="c11.html"><a href="c11.html#analysis-sentiment-analysis"><i class="fa fa-check"></i><b>11.8</b> Analysis: Sentiment analysis</a><ul>
<li class="chapter" data-level="11.8.1" data-path="c11.html"><a href="c11.html#tweets-associated-with-positive"><i class="fa fa-check"></i><b>11.8.1</b> Tweets associated with positive</a></li>
<li class="chapter" data-level="11.8.2" data-path="c11.html"><a href="c11.html#dataviz-and-other-positive-words"><i class="fa fa-check"></i><b>11.8.2</b> Dataviz and other positive words</a></li>
<li class="chapter" data-level="11.8.3" data-path="c11.html"><a href="c11.html#close-read-of-randomly-selected-tweets"><i class="fa fa-check"></i><b>11.8.3</b> Close read of randomly selected tweets</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="c11.html"><a href="c11.html#conclusion-4"><i class="fa fa-check"></i><b>11.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="c12.html"><a href="c12.html"><i class="fa fa-check"></i><b>12</b> Walkthrough 6: Exploring Relationships Using Social Network Analysis Models and Methods</a><ul>
<li class="chapter" data-level="12.1" data-path="c12.html"><a href="c12.html#accessing-data"><i class="fa fa-check"></i><b>12.1</b> Accessing data</a></li>
<li class="chapter" data-level="12.2" data-path="c12.html"><a href="c12.html#preparing-the-data-for-the-analysis"><i class="fa fa-check"></i><b>12.2</b> Preparing the data for the analysis</a></li>
<li class="chapter" data-level="12.3" data-path="c12.html"><a href="c12.html#extracting-mentions"><i class="fa fa-check"></i><b>12.3</b> Extracting mentions</a></li>
<li class="chapter" data-level="12.4" data-path="c12.html"><a href="c12.html#putting-the-edgelist-together"><i class="fa fa-check"></i><b>12.4</b> Putting the edgelist together</a></li>
<li class="chapter" data-level="12.5" data-path="c12.html"><a href="c12.html#plotting-the-network"><i class="fa fa-check"></i><b>12.5</b> Plotting the network</a></li>
<li class="chapter" data-level="12.6" data-path="c12.html"><a href="c12.html#selection-and-influence-models"><i class="fa fa-check"></i><b>12.6</b> Selection and influence models</a></li>
<li class="chapter" data-level="12.7" data-path="c12.html"><a href="c12.html#appendix-a"><i class="fa fa-check"></i><b>12.7</b> Appendix A</a><ul>
<li class="chapter" data-level="12.7.1" data-path="c12.html"><a href="c12.html#accessing-historical-data-using-status-urls"><i class="fa fa-check"></i><b>12.7.1</b> Accessing historical data using status URLs</a></li>
<li class="chapter" data-level="12.7.2" data-path="c12.html"><a href="c12.html#accessing-historical-data-when-you-do-not-have-access-to-status-urls"><i class="fa fa-check"></i><b>12.7.2</b> Accessing historical data when you do not have access to status URLs</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="c12.html"><a href="c12.html#appendix-b"><i class="fa fa-check"></i><b>12.8</b> Appendix B</a><ul>
<li class="chapter" data-level="12.8.1" data-path="c12.html"><a href="c12.html#an-example-of-influence"><i class="fa fa-check"></i><b>12.8.1</b> An example of influence</a></li>
<li class="chapter" data-level="12.8.2" data-path="c12.html"><a href="c12.html#joining-the-data-1"><i class="fa fa-check"></i><b>12.8.2</b> Joining the data</a></li>
<li class="chapter" data-level="12.8.3" data-path="c12.html"><a href="c12.html#an-example-of-selection"><i class="fa fa-check"></i><b>12.8.3</b> An example of selection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="c13.html"><a href="c13.html"><i class="fa fa-check"></i><b>13</b> Walkthrough 7: The Role (and Usefulness) of Multi-Level Models</a><ul>
<li class="chapter" data-level="13.1" data-path="c13.html"><a href="c13.html#but-what-about-different-courses"><i class="fa fa-check"></i><b>13.1</b> But what about different courses?</a><ul>
<li class="chapter" data-level="13.1.1" data-path="c13.html"><a href="c13.html#the-role-of-dummy-codes"><i class="fa fa-check"></i><b>13.1.1</b> The role of dummy codes</a></li>
<li class="chapter" data-level="13.1.2" data-path="c13.html"><a href="c13.html#using-dummy-codes"><i class="fa fa-check"></i><b>13.1.2</b> Using dummy codes</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="c13.html"><a href="c13.html#toward-multi-level-models"><i class="fa fa-check"></i><b>13.2</b> Toward multi-level models</a></li>
<li class="chapter" data-level="13.3" data-path="c13.html"><a href="c13.html#other-groups"><i class="fa fa-check"></i><b>13.3</b> Other groups</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c14.html"><a href="c14.html"><i class="fa fa-check"></i><b>14</b> Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods</a><ul>
<li class="chapter" data-level="14.1" data-path="c14.html"><a href="c14.html#background-4"><i class="fa fa-check"></i><b>14.1</b> Background</a></li>
<li class="chapter" data-level="14.2" data-path="c14.html"><a href="c14.html#information-about-the-dataset"><i class="fa fa-check"></i><b>14.2</b> Information about the dataset</a></li>
<li class="chapter" data-level="14.3" data-path="c14.html"><a href="c14.html#selecting-an-analysis"><i class="fa fa-check"></i><b>14.3</b> Selecting an analysis</a><ul>
<li class="chapter" data-level="14.3.1" data-path="c14.html"><a href="c14.html#defining-our-research-question"><i class="fa fa-check"></i><b>14.3.1</b> Defining our research question</a></li>
<li class="chapter" data-level="14.3.2" data-path="c14.html"><a href="c14.html#predictive-analytics-and-machine-learning"><i class="fa fa-check"></i><b>14.3.2</b> Predictive analytics and machine learning</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="c14.html"><a href="c14.html#information-on-random-forests"><i class="fa fa-check"></i><b>14.4</b> Information on random forests</a></li>
<li class="chapter" data-level="14.5" data-path="c14.html"><a href="c14.html#analysis-2"><i class="fa fa-check"></i><b>14.5</b> Analysis</a><ul>
<li class="chapter" data-level="14.5.1" data-path="c14.html"><a href="c14.html#use-of-caret"><i class="fa fa-check"></i><b>14.5.1</b> Use of caret</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="c14.html"><a href="c14.html#examining-predictive-accuracy-on-the-test-data-set"><i class="fa fa-check"></i><b>14.6</b> Examining predictive accuracy on the test data set</a><ul>
<li class="chapter" data-level="14.6.1" data-path="c14.html"><a href="c14.html#variable-importance-measures"><i class="fa fa-check"></i><b>14.6.1</b> Variable importance measures</a></li>
<li class="chapter" data-level="14.6.2" data-path="c14.html"><a href="c14.html#comparing-a-random-forest-to-a-regression"><i class="fa fa-check"></i><b>14.6.2</b> Comparing a random forest to a regression</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="c15.html"><a href="c15.html"><i class="fa fa-check"></i><b>15</b> Introducing Data Science Tools To Your Education Job</a><ul>
<li class="chapter" data-level="15.1" data-path="c15.html"><a href="c15.html#introduction-5"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="c15.html"><a href="c15.html#the-gift-of-speed-and-scale"><i class="fa fa-check"></i><b>15.2</b> The Gift of Speed and Scale</a><ul>
<li class="chapter" data-level="15.2.1" data-path="c15.html"><a href="c15.html#working-with-data-faster"><i class="fa fa-check"></i><b>15.2.1</b> Working With Data Faster</a></li>
<li class="chapter" data-level="15.2.2" data-path="c15.html"><a href="c15.html#working-with-more-data"><i class="fa fa-check"></i><b>15.2.2</b> Working With More Data</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="c15.html"><a href="c15.html#other-ways-to-reimagine-the-scale-of-your-work"><i class="fa fa-check"></i><b>15.3</b> Other Ways to Reimagine the Scale of Your Work</a><ul>
<li class="chapter" data-level="15.3.1" data-path="c15.html"><a href="c15.html#reflect-on-your-current-scale-then-push-to-the-next-level"><i class="fa fa-check"></i><b>15.3.1</b> Reflect on your current scale, then push to the next level</a></li>
<li class="chapter" data-level="15.3.2" data-path="c15.html"><a href="c15.html#look-for-lots-of-similarly-structured-data"><i class="fa fa-check"></i><b>15.3.2</b> Look for lots of similarly structured data</a></li>
<li class="chapter" data-level="15.3.3" data-path="c15.html"><a href="c15.html#cleaning-data"><i class="fa fa-check"></i><b>15.3.3</b> Cleaning data</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="c15.html"><a href="c15.html#solving-problems-together"><i class="fa fa-check"></i><b>15.4</b> Solving Problems Together</a><ul>
<li class="chapter" data-level="15.4.1" data-path="c15.html"><a href="c15.html#data-science-in-education-and-empathy"><i class="fa fa-check"></i><b>15.4.1</b> Data Science in Education and Empathy</a></li>
<li class="chapter" data-level="15.4.2" data-path="c15.html"><a href="c15.html#create-a-daily-practice-commitment-that-answers-someone-elses-question"><i class="fa fa-check"></i><b>15.4.2</b> Create a Daily Practice Commitment That Answers Someone Else’s Question</a></li>
<li class="chapter" data-level="15.4.3" data-path="c15.html"><a href="c15.html#build-your-network"><i class="fa fa-check"></i><b>15.4.3</b> Build Your Network</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="c15.html"><a href="c15.html#for-k-12-teachers"><i class="fa fa-check"></i><b>15.5</b> For K-12 Teachers</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="c16.html"><a href="c16.html"><i class="fa fa-check"></i><b>16</b> Teaching Data Science</a><ul>
<li class="chapter" data-level="16.1" data-path="c16.html"><a href="c16.html#the-pedagogical-principles-this-book-is-based-upon"><i class="fa fa-check"></i><b>16.1</b> The pedagogical principles this book is based upon</a><ul>
<li class="chapter" data-level="16.1.1" data-path="c16.html"><a href="c16.html#problem-based-learning"><i class="fa fa-check"></i><b>16.1.1</b> Problem-based learning</a></li>
<li class="chapter" data-level="16.1.2" data-path="c16.html"><a href="c16.html#differentiation"><i class="fa fa-check"></i><b>16.1.2</b> Differentiation</a></li>
<li class="chapter" data-level="16.1.3" data-path="c16.html"><a href="c16.html#universal-design"><i class="fa fa-check"></i><b>16.1.3</b> Universal Design</a></li>
<li class="chapter" data-level="16.1.4" data-path="c16.html"><a href="c16.html#working-in-the-open"><i class="fa fa-check"></i><b>16.1.4</b> Working in the Open</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="c16.html"><a href="c16.html#strategies-for-teaching-data-science"><i class="fa fa-check"></i><b>16.2</b> Strategies for teaching data science</a><ul>
<li class="chapter" data-level="16.2.1" data-path="c16.html"><a href="c16.html#provide-a-home-base-for-learners-to-access-resources-and-to-learn-more"><i class="fa fa-check"></i><b>16.2.1</b> Provide a home base for learners to access resources (and to learn more)</a></li>
<li class="chapter" data-level="16.2.2" data-path="c16.html"><a href="c16.html#when-it-comes-to-writing-code-think-early-and-often"><i class="fa fa-check"></i><b>16.2.2</b> When it comes to writing code, think early and often</a></li>
<li class="chapter" data-level="16.2.3" data-path="c16.html"><a href="c16.html#dont-touch-that-keyboard"><i class="fa fa-check"></i><b>16.2.3</b> Don’t touch that keyboard!</a></li>
<li class="chapter" data-level="16.2.4" data-path="c16.html"><a href="c16.html#anticipate-issues-and-sacrifice-accuracy-for-clarity"><i class="fa fa-check"></i><b>16.2.4</b> Anticipate issues (and sacrifice accuracy for clarity)</a></li>
<li class="chapter" data-level="16.2.5" data-path="c16.html"><a href="c16.html#start-lessons-or-activities-with-visualizing-data"><i class="fa fa-check"></i><b>16.2.5</b> Start lessons or activities with visualizing data</a></li>
<li class="chapter" data-level="16.2.6" data-path="c16.html"><a href="c16.html#consider-representation-in-the-data-and-examples-you-use"><i class="fa fa-check"></i><b>16.2.6</b> Consider representation in the data and examples you use</a></li>
<li class="chapter" data-level="16.2.7" data-path="c16.html"><a href="c16.html#draw-on-other-resources"><i class="fa fa-check"></i><b>16.2.7</b> Draw on other resources</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="c16.html"><a href="c16.html#general-strategies-related-to-teaching-and-learning"><i class="fa fa-check"></i><b>16.3</b> General strategies related to teaching and learning</a><ul>
<li class="chapter" data-level="16.3.1" data-path="c16.html"><a href="c16.html#teaching-and-learning-are-complex"><i class="fa fa-check"></i><b>16.3.1</b> Teaching and learning are complex</a></li>
<li class="chapter" data-level="16.3.2" data-path="c16.html"><a href="c16.html#learners-learn-many-different-things-consciously-and-unconsciously"><i class="fa fa-check"></i><b>16.3.2</b> Learners learn many different things (consciously and unconsciously)</a></li>
<li class="chapter" data-level="16.3.3" data-path="c16.html"><a href="c16.html#metacognition-is-important-even-though-it-sounds-more-sophisticated-than-it-is"><i class="fa fa-check"></i><b>16.3.3</b> Metacognition is important (even though it sounds more sophisticated than it is!)</a></li>
<li class="chapter" data-level="16.3.4" data-path="c16.html"><a href="c16.html#learning-strategies-matter"><i class="fa fa-check"></i><b>16.3.4</b> Learning strategies matter</a></li>
<li class="chapter" data-level="16.3.5" data-path="c16.html"><a href="c16.html#educators-can-help-students-to-learn"><i class="fa fa-check"></i><b>16.3.5</b> Educators can help students to learn</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="c16.html"><a href="c16.html#summary"><i class="fa fa-check"></i><b>16.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="c17.html"><a href="c17.html"><i class="fa fa-check"></i><b>17</b> Learning More</a><ul>
<li class="chapter" data-level="17.1" data-path="c17.html"><a href="c17.html#introduction-6"><i class="fa fa-check"></i><b>17.1</b> Introduction</a></li>
<li class="chapter" data-level="17.2" data-path="c17.html"><a href="c17.html#adopt-a-growth-mindset"><i class="fa fa-check"></i><b>17.2</b> Adopt a growth mindset</a></li>
<li class="chapter" data-level="17.3" data-path="c17.html"><a href="c17.html#discover-new-information"><i class="fa fa-check"></i><b>17.3</b> Discover new information</a></li>
<li class="chapter" data-level="17.4" data-path="c17.html"><a href="c17.html#ask-for-help"><i class="fa fa-check"></i><b>17.4</b> Ask for help</a><ul>
<li class="chapter" data-level="17.4.1" data-path="c17.html"><a href="c17.html#discussion-forums"><i class="fa fa-check"></i><b>17.4.1</b> Discussion forums</a></li>
<li class="chapter" data-level="17.4.2" data-path="c17.html"><a href="c17.html#github-repositories"><i class="fa fa-check"></i><b>17.4.2</b> GitHub repositories</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="c17.html"><a href="c17.html#share-what-youve-learned"><i class="fa fa-check"></i><b>17.5</b> Share what you’ve learned</a><ul>
<li class="chapter" data-level="17.5.1" data-path="c17.html"><a href="c17.html#where-to-share"><i class="fa fa-check"></i><b>17.5.1</b> Where to share</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="c17.html"><a href="c17.html#welcome-others"><i class="fa fa-check"></i><b>17.6</b> Welcome others</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="c18.html"><a href="c18.html"><i class="fa fa-check"></i><b>18</b> Additional Resources</a><ul>
<li class="chapter" data-level="18.1" data-path="c18.html"><a href="c18.html#data-science-courses"><i class="fa fa-check"></i><b>18.1</b> Data science courses</a></li>
<li class="chapter" data-level="18.2" data-path="c18.html"><a href="c18.html#workshop-materials"><i class="fa fa-check"></i><b>18.2</b> Workshop materials</a></li>
<li class="chapter" data-level="18.3" data-path="c18.html"><a href="c18.html#education-resources"><i class="fa fa-check"></i><b>18.3</b> Education resources</a></li>
<li class="chapter" data-level="18.4" data-path="c18.html"><a href="c18.html#data-visualization"><i class="fa fa-check"></i><b>18.4</b> Data visualization</a></li>
<li class="chapter" data-level="18.5" data-path="c18.html"><a href="c18.html#books-related-to-data-science-in-education"><i class="fa fa-check"></i><b>18.5</b> Books related to data science in education</a></li>
<li class="chapter" data-level="18.6" data-path="c18.html"><a href="c18.html#articles-related-to-data-science-in-education"><i class="fa fa-check"></i><b>18.6</b> Articles related to data science in education</a></li>
<li class="chapter" data-level="18.7" data-path="c18.html"><a href="c18.html#programming-with-r"><i class="fa fa-check"></i><b>18.7</b> Programming with R</a></li>
<li class="chapter" data-level="18.8" data-path="c18.html"><a href="c18.html#helpful-package-vignettes-and-descriptions-of-packages"><i class="fa fa-check"></i><b>18.8</b> Helpful package vignettes and descriptions of packages</a></li>
<li class="chapter" data-level="18.9" data-path="c18.html"><a href="c18.html#statistics"><i class="fa fa-check"></i><b>18.9</b> Statistics</a><ul>
<li class="chapter" data-level="18.9.1" data-path="c18.html"><a href="c18.html#introductory"><i class="fa fa-check"></i><b>18.9.1</b> Introductory</a></li>
<li class="chapter" data-level="18.9.2" data-path="c18.html"><a href="c18.html#advanced"><i class="fa fa-check"></i><b>18.9.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="18.10" data-path="c18.html"><a href="c18.html#software-and-r-packages"><i class="fa fa-check"></i><b>18.10</b> Software and R Packages</a></li>
<li class="chapter" data-level="18.11" data-path="c18.html"><a href="c18.html#a-career-in-data-science"><i class="fa fa-check"></i><b>18.11</b> A career in data science</a></li>
<li class="chapter" data-level="18.12" data-path="c18.html"><a href="c18.html#places-to-share-your-work"><i class="fa fa-check"></i><b>18.12</b> Places to share your work</a></li>
<li class="chapter" data-level="18.13" data-path="c18.html"><a href="c18.html#cheat-sheets"><i class="fa fa-check"></i><b>18.13</b> Cheat Sheets</a></li>
<li class="chapter" data-level="18.14" data-path="c18.html"><a href="c18.html#learning-communities"><i class="fa fa-check"></i><b>18.14</b> Learning communities</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="c19.html"><a href="c19.html"><i class="fa fa-check"></i><b>19</b> Conclusion: To where next?</a><ul>
<li class="chapter" data-level="19.1" data-path="c19.html"><a href="c19.html#take-on-challenges"><i class="fa fa-check"></i><b>19.1</b> Take on challenges</a></li>
<li class="chapter" data-level="19.2" data-path="c19.html"><a href="c19.html#know-when-to-turn-to-something-else"><i class="fa fa-check"></i><b>19.2</b> Know when to turn to something else</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science in Education Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c10" class="section level1">
<h1><span class="header-section-number">10</span> Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data</h1>
<div id="vocabulary-1" class="section level2">
<h2><span class="header-section-number">10.1</span> Vocabulary</h2>
<ul>
<li>Read in</li>
<li>Aggregate data</li>
<li>Vector</li>
<li>List</li>
<li>Tidy format</li>
<li>Subset</li>
<li><code>select_at</code></li>
<li><code>mutate</code></li>
<li>Statistical model</li>
<li>Aggregate data</li>
<li>Student-level data</li>
</ul>
</div>
<div id="introduction-3" class="section level2">
<h2><span class="header-section-number">10.2</span> Introduction</h2>
<div id="background-2" class="section level3">
<h3><span class="header-section-number">10.2.1</span> Background</h3>
<p>Data scientists working in education don’t always have access to student level data, so knowing how to work with publicly available datasets is a useful skill. This walkthrough has two goals. First, we’ll be learning some ways to explore data over time. Second, we’ll be learning how to explore a publicly available dataset. Like most public datasets, this one contains aggregate data. This means that someone totaled up the student counts so it doesn’t reveal any private information.</p>
<p>You can download the datasets for this walkthrough on the United States Department of Education website (see <span class="citation">of Education (<a href="#ref-usdoe2019">2020</a>)</span>)<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a>. This walkthrough uses datasets of student with disabilities counts in each state.</p>
</div>
<div id="methods-2" class="section level3">
<h3><span class="header-section-number">10.2.2</span> Methods</h3>
<p>In this walkthrough, we’ll learn how to read multiple datasets in using the <code>map()</code> function. Next, we’ll prepare our data for analysis by cleaning the variable names. Finally, we’ll explore this dataset by visualizing student counts and comparing male to female ratios over time.</p>
</div>
</div>
<div id="load-packages-3" class="section level2">
<h2><span class="header-section-number">10.3</span> Load Packages</h2>
<p>For this walkthrough, we’ll be using four packages: <code>tidyverse</code>, <code>here</code>, <code>dataedu</code>, and <code>lubridate</code>. You can load those packages by running this code:</p>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb139-1" title="1"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<pre><code>## ── Attaching packages ──────────────</code></pre>
<pre><code>## ✓ ggplot2 3.2.1     ✓ purrr   0.3.3
## ✓ tibble  2.1.3     ✓ dplyr   0.8.3
## ✓ tidyr   1.0.0     ✓ stringr 1.4.0
## ✓ readr   1.3.1     ✓ forcats 0.4.0</code></pre>
<pre><code>## ── Conflicts ───────────────────────
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb143-1" title="1"><span class="kw">library</span>(here)</a></code></pre></div>
<pre><code>## here() starts at /Users/shortessay/data-science-in-education</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb145-1" title="1"><span class="kw">library</span>(dataedu)</a>
<a class="sourceLine" id="cb145-2" title="2"><span class="kw">library</span>(lubridate)</a></code></pre></div>
<pre><code>## 
## Attaching package: &#39;lubridate&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:here&#39;:
## 
##     here</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     date</code></pre>
</div>
<div id="import-data-3" class="section level2">
<h2><span class="header-section-number">10.4</span> Import Data</h2>
<p>In this analysis we’ll be importing and combining six datasets that describe the number of students with disabilities in a given year. Let’s spend some time carefully reviewing how to get the CSVs we’ll need downloaded and stored on your computer. If you want to run the code exactly as written here, you’ll need to store the same datasets in the right location. It’s possible to use this walkthrough on different datasets or to store them in different locations on your computer, but you’ll need to make adjustments to your code based on the datasets you used and where you stored them. We suggest only doing this if you already have some experience using R.</p>
<p><em>What to download</em></p>
<p>In this walkthrough, we’ll be using six separate datasets of child counts, one for each year between 2012 and 2017. If you’re copying and pasting the code in this walkthrough, we recommend downloading the datasets from our GitHub repository for the most reliable results. Here’s a link to each file:</p>
<ul>
<li><p><a href="https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2012.csv">https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2012.csv</a></p></li>
<li><p><a href="https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2013.csv">https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2013.csv</a></p></li>
<li><p><a href="https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2014.csv">https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2014.csv</a></p></li>
<li><p><a href="https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2015.csv">https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2015.csv</a></p></li>
<li><p><a href="https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2016.csv">https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2016.csv</a></p></li>
<li><p><a href="https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2017-18.csv">https://github.com/data-edu/data-science-in-education/raw/master/data/longitudinal_data/bchildcountandedenvironments2017-18.csv</a></p></li>
</ul>
<p>You can also find these files on the United States Department of Education website: <a href="https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/index.html">https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/index.html</a></p>
<p><em>A note on file paths</em></p>
<p>When you download these files, be sure to store them in a folder in your working directory. To get to the data in this walkthrough, we’ll be using this file path in our working directory: “data/longitudinal_data”. We’ll be using the <code>here</code> package, which convenieniently fills in all the folders in the file path of your working directory all the way up to the folders you specify in the arguments. So when referencing the file path “data/longitudinal_data”, we’ll use code like this:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb149-1" title="1">here<span class="op">::</span><span class="kw">here</span>(</a>
<a class="sourceLine" id="cb149-2" title="2">  <span class="st">&quot;data&quot;</span>,</a>
<a class="sourceLine" id="cb149-3" title="3">  <span class="st">&quot;longitudinal_data&quot;</span>,</a>
<a class="sourceLine" id="cb149-4" title="4">  <span class="st">&quot;bchildcountandedenvironments2012.csv&quot;</span></a>
<a class="sourceLine" id="cb149-5" title="5">)</a></code></pre></div>
<pre><code>## [1] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2012.csv&quot;</code></pre>
<p>You can use a different file path if you like, just take note of where your downloaded files are so you can use the correct file path when writing your code to import the data.</p>
<div id="reading-in-one-dataset" class="section level3">
<h3><span class="header-section-number">10.4.1</span> Reading In One Dataset</h3>
<p>We’ll be learning how to read in more than one dataset using the <code>map()</code> function. Let’s try it first with one dataset, then we’ll scale our solution up to multiple datasets. When you are analyzing multiple datasets that all have the same structure, you can read in each dataset using one code chunk. This code chunk will store each dataset as an element of a list.</p>
<p>Before doing that, you should explore one of the datasets to see what you can learn about its structure. Clues from this exploration inform how you read in all the datasets at once later on. For example, we can see that the first dataset has some lines at the top that contain no data:</p>
<pre><code>## # A tibble: 16,234 x 31
##    `Extraction Dat… `6/12/2013` X3    X4    X5    X6    X7    X8    X9    X10  
##    &lt;chr&gt;            &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
##  1 Updated:         2/12/2014   &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt; 
##  2 Revised:         &lt;NA&gt;        &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt; 
##  3 &lt;NA&gt;             &lt;NA&gt;        &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt;  &lt;NA&gt; 
##  4 Year             State Name  SEA … SEA … Amer… Asia… Blac… Hisp… Nati… Two …
##  5 2012             ALABAMA     Corr… All … -     -     -     -     -     -    
##  6 2012             ALABAMA     Home  All … 1     1     57    12    0     2    
##  7 2012             ALABAMA     Home… All … -     -     -     -     -     -    
##  8 2012             ALABAMA     Insi… All … -     -     -     -     -     -    
##  9 2012             ALABAMA     Insi… All … -     -     -     -     -     -    
## 10 2012             ALABAMA     Insi… All … -     -     -     -     -     -    
## # … with 16,224 more rows, and 21 more variables: X11 &lt;chr&gt;, X12 &lt;chr&gt;,
## #   X13 &lt;chr&gt;, X14 &lt;chr&gt;, X15 &lt;chr&gt;, X16 &lt;chr&gt;, X17 &lt;chr&gt;, X18 &lt;chr&gt;,
## #   X19 &lt;chr&gt;, X20 &lt;chr&gt;, X21 &lt;chr&gt;, X22 &lt;chr&gt;, X23 &lt;chr&gt;, X24 &lt;chr&gt;,
## #   X25 &lt;chr&gt;, X26 &lt;chr&gt;, X27 &lt;chr&gt;, X28 &lt;chr&gt;, X29 &lt;chr&gt;, X30 &lt;chr&gt;, X31 &lt;chr&gt;</code></pre>
<p>The rows containing “Extraction Date:”, “Updated:” and “Revised:” aren’t actually rows. They’re notes the authors left at the top of the dataset to show when the dataset was changed.</p>
<p><code>read_csv</code> uses the first row as the variable names unless told otherwise, so we need to tell <code>read_csv</code> to skip those lines using the <code>skip</code> argument. If we don’t, <code>read_csv</code> assumes the very first line–the one that says “Extraction Date:”–is the correct row of variable names. That’s why calling <code>read_csv</code> without the <code>skip</code> argument results in column names like <code>X4</code>. When there’s no obvious column name to read in, <code>read_csv</code> names them <code>X[...]</code> and let’s you know in a warning message.</p>
<p>Try using <code>skip = 4</code> in your call to <code>read_csv</code>:</p>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_character(),
##   Year = col_double()
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<pre><code>## Warning: 3 parsing failures.
##   row  col expected                                    actual                                                                                                      file
## 16228 Year a double -------------------                       &#39;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2012.csv&#39;
## 16229 Year a double -   Data not available                    &#39;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2012.csv&#39;
## 16230 Year a double x   Data supressed due to small cell size &#39;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2012.csv&#39;</code></pre>
<pre><code>## # A tibble: 16,230 x 31
##     Year `State Name` `SEA Education … `SEA Disability… `American India…
##    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;           
##  1  2012 ALABAMA      Correctional Fa… All Disabilities -               
##  2  2012 ALABAMA      Home             All Disabilities 1               
##  3  2012 ALABAMA      Homebound/Hospi… All Disabilities -               
##  4  2012 ALABAMA      Inside regular … All Disabilities -               
##  5  2012 ALABAMA      Inside regular … All Disabilities -               
##  6  2012 ALABAMA      Inside regular … All Disabilities -               
##  7  2012 ALABAMA      Other Location … All Disabilities 7               
##  8  2012 ALABAMA      Other Location … All Disabilities 1               
##  9  2012 ALABAMA      Parentally Plac… All Disabilities -               
## 10  2012 ALABAMA      Residential Fac… All Disabilities 0               
## # … with 16,220 more rows, and 26 more variables: `Asian Age 3-5` &lt;chr&gt;, `Black
## #   or African American Age 3-5` &lt;chr&gt;, `Hispanic/Latino Age 3-5` &lt;chr&gt;,
## #   `Native Hawaiian or Other Pacific Islander Age 3-5` &lt;chr&gt;, `Two or More
## #   Races Age 3-5` &lt;chr&gt;, `White Age 3-5` &lt;chr&gt;, `Female Age 3 to 5` &lt;chr&gt;,
## #   `Male Age 3 to 5` &lt;chr&gt;, `LEP Yes Age 3 to 5` &lt;chr&gt;, `LEP No Age 3 to
## #   5` &lt;chr&gt;, `Age 3 to 5` &lt;chr&gt;, `Age 6-11` &lt;chr&gt;, `Age 12-17` &lt;chr&gt;, `Age
## #   18-21` &lt;chr&gt;, `Ages 6-21` &lt;chr&gt;, `LEP Yes Age 6 to 21` &lt;chr&gt;, `LEP No Age 6
## #   to 21` &lt;chr&gt;, `Female Age 6 to 21` &lt;chr&gt;, `Male Age 6 to 21` &lt;chr&gt;,
## #   `American Indian or Alaska Native Age 6 to21` &lt;chr&gt;, `Asian Age 6
## #   to21` &lt;chr&gt;, `Black or African American Age 6 to21` &lt;chr&gt;, `Hispanic/Latino
## #   Age 6 to21` &lt;chr&gt;, `Native Hawaiian or Other Pacific Islander Age 6
## #   to21` &lt;chr&gt;, `Two or more races Age 6 to21` &lt;chr&gt;, `White Age 6 to21` &lt;chr&gt;</code></pre>
<p>The <code>skip</code> argument told <code>read_csv</code> to make the line containing “Year”, “State Name”, and so on as the first line. The result is a dataset that has “Year”, “State Name”, and so on as variable names.</p>
</div>
<div id="reading-in-many-datasets" class="section level3">
<h3><span class="header-section-number">10.4.2</span> Reading In Many Datasets</h3>
<p>Will the <code>read_csv</code> and <code>skip = 4</code> combination work on all our datasets? To find out, we’ll use this strategy:</p>
<ul>
<li>Store a vector of filenames and paths in a list. These paths point to our datasets</li>
<li>Pass the list of filenames as arguments to <code>read_csv</code> using <code>purrr::map</code>, including <code>skip = 4</code>, in our <code>read_csv</code> call</li>
<li>Examine the new list of datasets to see if the variable names are correct</li>
</ul>
<p>Imagine a widget-making machine that works by acting on raw materials it receives on a conveyer belt. This machine executes one set of instructions on each of the raw materials it receives. You are the operator of the machine and you design instructions to get a widget out of the raw materials. Your plan might look something like this:</p>
<ul>
<li><em>Raw materials</em>: a list of filenames and their paths</li>
<li><em>Widget-making machine</em>: <code>purrr:map()</code></li>
<li><em>Widget-making instructions</em>: `read_csv(path, skip = 4)</li>
<li><em>Expected widgets</em>: a list of datasets</li>
</ul>
<p>Let’s create the raw materials first. Our raw materials will be file paths to each of the CSVs we want to read. Use <code>list.files</code> to make a vector of filename paths and name that vector <code>filenames</code>. <code>list.files</code> returns a vector of file names in the folder specified in the <code>path</code> argument. When we set the <code>full.names</code> argument to “TRUE”, we get a full path of these filenames. This will be useful later when we need the file names and their paths to read our data in.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb156-1" title="1"><span class="co"># Get filenames from the data folder </span></a>
<a class="sourceLine" id="cb156-2" title="2">filenames &lt;-</a>
<a class="sourceLine" id="cb156-3" title="3"><span class="st">  </span><span class="kw">list.files</span>(<span class="dt">path =</span> here<span class="op">::</span><span class="kw">here</span>(<span class="st">&quot;data&quot;</span>, <span class="st">&quot;longitudinal_data&quot;</span>),</a>
<a class="sourceLine" id="cb156-4" title="4">             <span class="dt">full.names =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb156-5" title="5"></a>
<a class="sourceLine" id="cb156-6" title="6"><span class="co"># A list of filenames and paths</span></a>
<a class="sourceLine" id="cb156-7" title="7">filenames</a></code></pre></div>
<pre><code>## [1] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2012.csv&quot;   
## [2] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2013.csv&quot;   
## [3] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2014.csv&quot;   
## [4] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2015.csv&quot;   
## [5] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2016.csv&quot;   
## [6] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2017-18.csv&quot;</code></pre>
<p>That made a vector of six filenames, one for each year of child count data stored in the data folder. Now pass our raw materials, the vector called <code>filenames</code>, to our widget-making machine called <code>map</code> and give the machine the instructions <code>read_csv(., skip = 4)</code>. Name the list of widgets it cranks out <code>all_files</code>:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb158-1" title="1"><span class="co"># Pass filenames to map and read_csv</span></a>
<a class="sourceLine" id="cb158-2" title="2">all_files &lt;-</a>
<a class="sourceLine" id="cb158-3" title="3"><span class="st">  </span>filenames <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb158-4" title="4"><span class="st">  </span><span class="kw">map</span>(., <span class="op">~</span><span class="st"> </span><span class="kw">read_csv</span>(., <span class="dt">skip =</span> <span class="dv">4</span>))</a></code></pre></div>
<p>It is important to think ahead here. The goal is to combine the datasets in <code>all_files</code> into one dataset using <code>bind_rows</code>. But that will only work if all the datasets in our list have the same number of columns and the same column names. We can check our column names by using <code>map</code> and <code>names</code>:</p>
<p>We can use <code>identical</code> to see if the variables from two datasets match. We see that the variable names of the first and second datasets don’t match, but the variables from the second and third do.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb159-1" title="1"><span class="co"># Variables of first and second dataset don&#39;t match</span></a>
<a class="sourceLine" id="cb159-2" title="2"><span class="kw">identical</span>(<span class="kw">names</span>(all_files[[<span class="dv">1</span>]]), <span class="kw">names</span>(all_files[[<span class="dv">2</span>]]))</a></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb161-1" title="1"><span class="co"># Variables of third and second files match</span></a>
<a class="sourceLine" id="cb161-2" title="2"><span class="kw">identical</span>(<span class="kw">names</span>(all_files[[<span class="dv">2</span>]]), <span class="kw">names</span>(all_files[[<span class="dv">3</span>]]))</a></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>And we can check the number of columns by using <code>map</code> and <code>ncol</code>:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb163-1" title="1">all_files <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb163-2" title="2"><span class="st">  </span><span class="kw">map</span>(ncol)</a></code></pre></div>
<pre><code>## [[1]]
## [1] 31
## 
## [[2]]
## [1] 50
## 
## [[3]]
## [1] 50
## 
## [[4]]
## [1] 50
## 
## [[5]]
## [1] 50
## 
## [[6]]
## [1] 50</code></pre>
<p>Congratulations on finding an extremely common problem in education data! You’ve discovered that niehter the number of columns nor the column names match. This is a problem because we won’t be able to combine the datasets into one. When we try, <code>bind_rows</code> returns a dataet with 100 columns instead of the expected 50.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb165-1" title="1"><span class="kw">bind_rows</span>(all_files)</a></code></pre></div>
<pre><code>## # A tibble: 97,386 x 100
##     Year `State Name` `SEA Education … `SEA Disability… `American India…
##    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;           
##  1  2012 ALABAMA      Correctional Fa… All Disabilities -               
##  2  2012 ALABAMA      Home             All Disabilities 1               
##  3  2012 ALABAMA      Homebound/Hospi… All Disabilities -               
##  4  2012 ALABAMA      Inside regular … All Disabilities -               
##  5  2012 ALABAMA      Inside regular … All Disabilities -               
##  6  2012 ALABAMA      Inside regular … All Disabilities -               
##  7  2012 ALABAMA      Other Location … All Disabilities 7               
##  8  2012 ALABAMA      Other Location … All Disabilities 1               
##  9  2012 ALABAMA      Parentally Plac… All Disabilities -               
## 10  2012 ALABAMA      Residential Fac… All Disabilities 0               
## # … with 97,376 more rows, and 95 more variables: `Asian Age 3-5` &lt;chr&gt;, `Black
## #   or African American Age 3-5` &lt;chr&gt;, `Hispanic/Latino Age 3-5` &lt;chr&gt;,
## #   `Native Hawaiian or Other Pacific Islander Age 3-5` &lt;chr&gt;, `Two or More
## #   Races Age 3-5` &lt;chr&gt;, `White Age 3-5` &lt;chr&gt;, `Female Age 3 to 5` &lt;chr&gt;,
## #   `Male Age 3 to 5` &lt;chr&gt;, `LEP Yes Age 3 to 5` &lt;chr&gt;, `LEP No Age 3 to
## #   5` &lt;chr&gt;, `Age 3 to 5` &lt;chr&gt;, `Age 6-11` &lt;chr&gt;, `Age 12-17` &lt;chr&gt;, `Age
## #   18-21` &lt;chr&gt;, `Ages 6-21` &lt;chr&gt;, `LEP Yes Age 6 to 21` &lt;chr&gt;, `LEP No Age 6
## #   to 21` &lt;chr&gt;, `Female Age 6 to 21` &lt;chr&gt;, `Male Age 6 to 21` &lt;chr&gt;,
## #   `American Indian or Alaska Native Age 6 to21` &lt;chr&gt;, `Asian Age 6
## #   to21` &lt;chr&gt;, `Black or African American Age 6 to21` &lt;chr&gt;, `Hispanic/Latino
## #   Age 6 to21` &lt;chr&gt;, `Native Hawaiian or Other Pacific Islander Age 6
## #   to21` &lt;chr&gt;, `Two or more races Age 6 to21` &lt;chr&gt;, `White Age 6
## #   to21` &lt;chr&gt;, `Age 3` &lt;chr&gt;, `Age 4` &lt;chr&gt;, `Age 5` &lt;chr&gt;, `Age 6` &lt;chr&gt;,
## #   `Age 7` &lt;chr&gt;, `Age 8` &lt;chr&gt;, `Age 9` &lt;chr&gt;, `Age 10` &lt;chr&gt;, `Age
## #   11` &lt;chr&gt;, `Age 12` &lt;chr&gt;, `Age 13` &lt;chr&gt;, `Age 14` &lt;chr&gt;, `Age 15` &lt;chr&gt;,
## #   `Age 16` &lt;chr&gt;, `Age 17` &lt;chr&gt;, `Age 18` &lt;chr&gt;, `Age 19` &lt;chr&gt;, `Age
## #   20` &lt;chr&gt;, `Age 21` &lt;chr&gt;, `2016` &lt;dbl&gt;, Alabama &lt;chr&gt;, `Correctional
## #   Facilities` &lt;chr&gt;, `All Disabilities` &lt;chr&gt;, `-` &lt;chr&gt;, `-_1` &lt;chr&gt;,
## #   `-_2` &lt;chr&gt;, `-_3` &lt;chr&gt;, `-_4` &lt;chr&gt;, `-_5` &lt;chr&gt;, `-_6` &lt;chr&gt;,
## #   `-_7` &lt;chr&gt;, `-_8` &lt;chr&gt;, `-_9` &lt;chr&gt;, `-_10` &lt;chr&gt;, `-_11` &lt;chr&gt;,
## #   `-_12` &lt;chr&gt;, `-_13` &lt;chr&gt;, `-_14` &lt;chr&gt;, `0` &lt;chr&gt;, `0_1` &lt;chr&gt;,
## #   `0_2` &lt;chr&gt;, `0_3` &lt;chr&gt;, `0_4` &lt;chr&gt;, `0_5` &lt;chr&gt;, `0_6` &lt;chr&gt;,
## #   `0_7` &lt;chr&gt;, `0_8` &lt;chr&gt;, `1` &lt;chr&gt;, `2` &lt;chr&gt;, `4` &lt;chr&gt;, `14` &lt;chr&gt;,
## #   `22` &lt;chr&gt;, `30` &lt;chr&gt;, `4_1` &lt;chr&gt;, `0_9` &lt;chr&gt;, `7` &lt;chr&gt;, `70` &lt;chr&gt;,
## #   `77` &lt;chr&gt;, `0_10` &lt;chr&gt;, `77_1` &lt;chr&gt;, `1_1` &lt;chr&gt;, `76` &lt;chr&gt;,
## #   `0_11` &lt;chr&gt;, `0_12` &lt;chr&gt;, `68` &lt;chr&gt;, `0_13` &lt;chr&gt;, `0_14` &lt;chr&gt;,
## #   `0_15` &lt;chr&gt;, `9` &lt;chr&gt;</code></pre>
<p>We’ll correct this in the next section by selecting and renaming our variables, but it’s good to notice this problem early in the process so you know to work on it later.</p>
</div>
</div>
<div id="process-data-2" class="section level2">
<h2><span class="header-section-number">10.5</span> Process Data</h2>
<p>Transforming your dataset before visualizing it and fitting models is critical. It’s easier to write code when variable names are concise and informative. Many functions in R, especially those in the <code>ggplot2</code> package, work best when datsets are in a “tidy” format. It’s easier to do an analysis when you have just the variables you need. Any unused variables can confuse your thought process.</p>
<p>Let’s preview the steps we’ll be taking:</p>
<ol style="list-style-type: decimal">
<li>Fix the variable names in the 2016 data</li>
<li>Combine the datasets</li>
<li>Pick variables</li>
<li>Filter for the desired categories</li>
<li>Rename the variables</li>
<li>Standardize the state names</li>
<li>Transform the column formats from wide to narrow using <code>gather</code></li>
<li>Change the data types of variables</li>
<li>Explore NAs</li>
</ol>
<p>In real life, data scientists don’t always know the cleaning steps until they dive into the work. Learning what cleaning steps are needed requires exploration, trial and error, and clarity on the analytic questions you want to answer.</p>
<p>After a lot of exploring, we settled on these steps for this analysis. When you do your own, you will find different things to transform. As you do more and more data analysis, your instincts for what to transform will improve.</p>
<div id="fix-the-variable-names-in-the-2016-data" class="section level3">
<h3><span class="header-section-number">10.5.1</span> Fix the variable names in the 2016 data</h3>
<p>When we print the 2016 dataset, we notice that the variable names are incorrect. Let’s verify that by looking at the 2016 dataset, which is the fifth element of <code>all_files</code>:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb167-1" title="1"><span class="kw">names</span>(all_files[[<span class="dv">5</span>]])</a></code></pre></div>
<pre><code>##  [1] &quot;2016&quot;                    &quot;Alabama&quot;                
##  [3] &quot;Correctional Facilities&quot; &quot;All Disabilities&quot;       
##  [5] &quot;-&quot;                       &quot;-_1&quot;                    
##  [7] &quot;-_2&quot;                     &quot;-_3&quot;                    
##  [9] &quot;-_4&quot;                     &quot;-_5&quot;                    
## [11] &quot;-_6&quot;                     &quot;-_7&quot;                    
## [13] &quot;-_8&quot;                     &quot;-_9&quot;                    
## [15] &quot;-_10&quot;                    &quot;-_11&quot;                   
## [17] &quot;-_12&quot;                    &quot;-_13&quot;                   
## [19] &quot;-_14&quot;                    &quot;0&quot;                      
## [21] &quot;0_1&quot;                     &quot;0_2&quot;                    
## [23] &quot;0_3&quot;                     &quot;0_4&quot;                    
## [25] &quot;0_5&quot;                     &quot;0_6&quot;                    
## [27] &quot;0_7&quot;                     &quot;0_8&quot;                    
## [29] &quot;1&quot;                       &quot;2&quot;                      
## [31] &quot;4&quot;                       &quot;14&quot;                     
## [33] &quot;22&quot;                      &quot;30&quot;                     
## [35] &quot;4_1&quot;                     &quot;0_9&quot;                    
## [37] &quot;7&quot;                       &quot;70&quot;                     
## [39] &quot;77&quot;                      &quot;0_10&quot;                   
## [41] &quot;77_1&quot;                    &quot;1_1&quot;                    
## [43] &quot;76&quot;                      &quot;0_11&quot;                   
## [45] &quot;0_12&quot;                    &quot;68&quot;                     
## [47] &quot;0_13&quot;                    &quot;0_14&quot;                   
## [49] &quot;0_15&quot;                    &quot;9&quot;</code></pre>
<p>We want the variable names to be <code>Year</code> and <code>State Name</code>. But first, let’s go back and review how to get at the 2016 dataset from <code>all_files</code>. The order of the list elements was set all the way back when we fed <code>map</code> our list of filenames. If we look at <code>filenames</code> again, we see that the 2016 dataset was stored in the fifth element:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb169-1" title="1">filenames</a></code></pre></div>
<pre><code>## [1] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2012.csv&quot;   
## [2] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2013.csv&quot;   
## [3] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2014.csv&quot;   
## [4] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2015.csv&quot;   
## [5] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2016.csv&quot;   
## [6] &quot;/Users/shortessay/data-science-in-education/data/longitudinal_data/bchildcountandedenvironments2017-18.csv&quot;</code></pre>
<p>Once we know the 2016 dataset is the fifth element of our list, we can pluck it out by using double brackets:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb171-1" title="1">all_files[[<span class="dv">5</span>]]</a></code></pre></div>
<pre><code>## # A tibble: 16,230 x 50
##    `2016` Alabama `Correctional F… `All Disabiliti… `-`   `-_1` `-_2` `-_3`
##     &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt; &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
##  1   2016 Alabama Home             All Disabilities 43    30    35    0    
##  2   2016 Alabama Homebound/Hospi… All Disabilities -     -     -     -    
##  3   2016 Alabama Inside regular … All Disabilities -     -     -     -    
##  4   2016 Alabama Inside regular … All Disabilities -     -     -     -    
##  5   2016 Alabama Inside regular … All Disabilities -     -     -     -    
##  6   2016 Alabama Parentally Plac… All Disabilities -     -     -     -    
##  7   2016 Alabama Residential Fac… All Disabilities 5     3     4     0    
##  8   2016 Alabama Residential Fac… All Disabilities -     -     -     -    
##  9   2016 Alabama Separate Class   All Disabilities 58    58    98    0    
## 10   2016 Alabama Separate School… All Disabilities 11    20    19    0    
## # … with 16,220 more rows, and 42 more variables: `-_4` &lt;chr&gt;, `-_5` &lt;chr&gt;,
## #   `-_6` &lt;chr&gt;, `-_7` &lt;chr&gt;, `-_8` &lt;chr&gt;, `-_9` &lt;chr&gt;, `-_10` &lt;chr&gt;,
## #   `-_11` &lt;chr&gt;, `-_12` &lt;chr&gt;, `-_13` &lt;chr&gt;, `-_14` &lt;chr&gt;, `0` &lt;chr&gt;,
## #   `0_1` &lt;chr&gt;, `0_2` &lt;chr&gt;, `0_3` &lt;chr&gt;, `0_4` &lt;chr&gt;, `0_5` &lt;chr&gt;,
## #   `0_6` &lt;chr&gt;, `0_7` &lt;chr&gt;, `0_8` &lt;chr&gt;, `1` &lt;chr&gt;, `2` &lt;chr&gt;, `4` &lt;chr&gt;,
## #   `14` &lt;chr&gt;, `22` &lt;chr&gt;, `30` &lt;chr&gt;, `4_1` &lt;chr&gt;, `0_9` &lt;chr&gt;, `7` &lt;chr&gt;,
## #   `70` &lt;chr&gt;, `77` &lt;chr&gt;, `0_10` &lt;chr&gt;, `77_1` &lt;chr&gt;, `1_1` &lt;chr&gt;,
## #   `76` &lt;chr&gt;, `0_11` &lt;chr&gt;, `0_12` &lt;chr&gt;, `68` &lt;chr&gt;, `0_13` &lt;chr&gt;,
## #   `0_14` &lt;chr&gt;, `0_15` &lt;chr&gt;, `9` &lt;chr&gt;</code></pre>
<p>We used <code>skip = 4</code> when we read in those datasets. That worked for all datasets except the fifth one. In that one, skipping four lines left out the variable name row. To fix it, we’ll read the 2016 dataset again using <code>read_csv</code> and the fifth element of <code>filenames</code>. We’ll assign the newly read dataset to the fifth element of the <code>all_files</code> list:</p>
<p>Try printing <code>all_files</code> now. You can confirm we fixed the problem by checking that the variable names are correct.</p>
</div>
<div id="pick-variables" class="section level3">
<h3><span class="header-section-number">10.5.2</span> Pick variables</h3>
<p>Now that we know all our datasets have the correct variable names, we simplify our datasets by picking the variables we need. This is a good place to think carefully about which variables to pick. This usually requires a fair amount of trial and error, but here is what we found we needed:</p>
<ul>
<li>Our analytic questions are about gender, so let’s pick the gender variable</li>
<li>Later, we’ll need to filter our dataset by disability category and program location so we’ll want <code>SEA Education Environment</code> and <code>SEA Disability Category</code></li>
<li>We want to make comparisons by state and reporting year, so we’ll also pick <code>State Name</code> and <code>Year</code></li>
</ul>
<p>Combining <code>select</code> and <code>contains</code> is a convenient way to pick these variables without writing a lot of code. Knowing that we want variables that contain the acronym “SEA” and variables that contain “male” in their names, we can pass those characters to <code>contains</code>:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb173-1" title="1">all_files[[<span class="dv">1</span>]] <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb173-2" title="2"><span class="st">  </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb173-3" title="3">    Year,</a>
<a class="sourceLine" id="cb173-4" title="4">    <span class="kw">contains</span>(<span class="st">&quot;State&quot;</span>, <span class="dt">ignore.case =</span> <span class="ot">FALSE</span>),</a>
<a class="sourceLine" id="cb173-5" title="5">    <span class="kw">contains</span>(<span class="st">&quot;SEA&quot;</span>, <span class="dt">ignore.case =</span> <span class="ot">FALSE</span>),</a>
<a class="sourceLine" id="cb173-6" title="6">    <span class="kw">contains</span>(<span class="st">&quot;male&quot;</span>)</a>
<a class="sourceLine" id="cb173-7" title="7">  ) </a></code></pre></div>
<pre><code>## # A tibble: 16,230 x 8
##     Year `State Name` `SEA Education … `SEA Disability… `Female Age 3 t…
##    &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt;           
##  1  2012 ALABAMA      Correctional Fa… All Disabilities -               
##  2  2012 ALABAMA      Home             All Disabilities 63              
##  3  2012 ALABAMA      Homebound/Hospi… All Disabilities -               
##  4  2012 ALABAMA      Inside regular … All Disabilities -               
##  5  2012 ALABAMA      Inside regular … All Disabilities -               
##  6  2012 ALABAMA      Inside regular … All Disabilities -               
##  7  2012 ALABAMA      Other Location … All Disabilities 573             
##  8  2012 ALABAMA      Other Location … All Disabilities 81              
##  9  2012 ALABAMA      Parentally Plac… All Disabilities -               
## 10  2012 ALABAMA      Residential Fac… All Disabilities 6               
## # … with 16,220 more rows, and 3 more variables: `Male Age 3 to 5` &lt;chr&gt;,
## #   `Female Age 6 to 21` &lt;chr&gt;, `Male Age 6 to 21` &lt;chr&gt;</code></pre>
<p>That code chunk verifies that we got the variables we want, so now we will turn the code chunk into a function called <code>pick_vars</code>. We will then use <code>map</code> to feed our list of datasets, <code>all_files</code>, to the function. In this function, we’ll use a special version of <code>select()</code> called <code>select_at()</code>, which conveniently picks variables based on criteria we give it. The argument <code>vars(Year, contains("State", ignore.case = FALSE), contains("SEA", ignore.case = FALSE), contains("male"))</code> tells R we want to keep any column whose name has “State” in upper or lower case letters, has “SEA” in the title, and has “male” in the title. This will result in a newly transformed <code>all_files</code> list that contains six datasets, all with the desired variables.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb175-1" title="1">pick_vars &lt;-</a>
<a class="sourceLine" id="cb175-2" title="2"><span class="st">  </span><span class="cf">function</span>(df) {</a>
<a class="sourceLine" id="cb175-3" title="3">    df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb175-4" title="4"><span class="st">      </span><span class="kw">select_at</span>(<span class="kw">vars</span>(</a>
<a class="sourceLine" id="cb175-5" title="5">        Year,</a>
<a class="sourceLine" id="cb175-6" title="6">        <span class="kw">contains</span>(<span class="st">&quot;State&quot;</span>, <span class="dt">ignore.case =</span> <span class="ot">FALSE</span>),</a>
<a class="sourceLine" id="cb175-7" title="7">        <span class="kw">contains</span>(<span class="st">&quot;SEA&quot;</span>, <span class="dt">ignore.case =</span> <span class="ot">FALSE</span>),</a>
<a class="sourceLine" id="cb175-8" title="8">        <span class="kw">contains</span>(<span class="st">&quot;male&quot;</span>)</a>
<a class="sourceLine" id="cb175-9" title="9">      ))</a>
<a class="sourceLine" id="cb175-10" title="10">  }</a>
<a class="sourceLine" id="cb175-11" title="11"></a>
<a class="sourceLine" id="cb175-12" title="12">all_files &lt;-</a>
<a class="sourceLine" id="cb175-13" title="13"><span class="st">  </span>all_files <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb175-14" title="14"><span class="st">  </span><span class="kw">map</span>(pick_vars)</a></code></pre></div>
</div>
<div id="combine-six-datasets-into-one" class="section level3">
<h3><span class="header-section-number">10.5.3</span> Combine six datasets into one</h3>
<p>Now we’ll turn our attention to combining the datasets in our list <code>all_files</code> into one. We’ll use <code>bind_rows</code>, which combines datasets by adding each one to the bottom of the one before it. The first step is to check and see if our datasets have the same number of variables and the same variable names. When we use <code>names</code> on our list of newly changed datasets, we see that each dataset’s variable names are the same:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb176-1" title="1">all_files <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb176-2" title="2"><span class="st">  </span><span class="kw">map</span>(names)</a></code></pre></div>
<pre><code>## [[1]]
## [1] &quot;Year&quot;                      &quot;State Name&quot;               
## [3] &quot;SEA Education Environment&quot; &quot;SEA Disability Category&quot;  
## [5] &quot;Female Age 3 to 5&quot;         &quot;Male Age 3 to 5&quot;          
## [7] &quot;Female Age 6 to 21&quot;        &quot;Male Age 6 to 21&quot;         
## 
## [[2]]
## [1] &quot;Year&quot;                      &quot;State Name&quot;               
## [3] &quot;SEA Education Environment&quot; &quot;SEA Disability Category&quot;  
## [5] &quot;Female Age 3 to 5&quot;         &quot;Male Age 3 to 5&quot;          
## [7] &quot;Female Age 6 to 21&quot;        &quot;Male Age 6 to 21&quot;         
## 
## [[3]]
## [1] &quot;Year&quot;                      &quot;State Name&quot;               
## [3] &quot;SEA Education Environment&quot; &quot;SEA Disability Category&quot;  
## [5] &quot;Female Age 3 to 5&quot;         &quot;Male Age 3 to 5&quot;          
## [7] &quot;Female Age 6 to 21&quot;        &quot;Male Age 6 to 21&quot;         
## 
## [[4]]
## [1] &quot;Year&quot;                      &quot;State Name&quot;               
## [3] &quot;SEA Education Environment&quot; &quot;SEA Disability Category&quot;  
## [5] &quot;Female Age 3 to 5&quot;         &quot;Male Age 3 to 5&quot;          
## [7] &quot;Female Age 6 to 21&quot;        &quot;Male Age 6 to 21&quot;         
## 
## [[5]]
## [1] &quot;Year&quot;                      &quot;State Name&quot;               
## [3] &quot;SEA Education Environment&quot; &quot;SEA Disability Category&quot;  
## [5] &quot;Female Age 3 to 5&quot;         &quot;Male Age 3 to 5&quot;          
## [7] &quot;Female Age 6 to 21&quot;        &quot;Male Age 6 to 21&quot;         
## 
## [[6]]
## [1] &quot;Year&quot;                      &quot;State Name&quot;               
## [3] &quot;SEA Education Environment&quot; &quot;SEA Disability Category&quot;  
## [5] &quot;Female Age 3 to 5&quot;         &quot;Male Age 3 to 5&quot;          
## [7] &quot;Female Age 6 to 21&quot;        &quot;Male Age 6 to 21&quot;</code></pre>
<p>That means that we can combine all six datasets into one using <code>bind_rows</code>. We’ll call this newly combined dataset <code>child_counts</code>:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb178-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb178-2" title="2"><span class="st">  </span>all_files <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb178-3" title="3"><span class="st">  </span><span class="kw">bind_rows</span>()</a></code></pre></div>
<p>Since we know that a) each of our six datasets had eight variables and b) our combined dataset also has eight variables, we can conclude that all our rows combined together correctly. But let’s use <code>str</code> to verify:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb179-1" title="1"><span class="kw">str</span>(child_counts)</a></code></pre></div>
<pre><code>## Classes &#39;spec_tbl_df&#39;, &#39;tbl_df&#39;, &#39;tbl&#39; and &#39;data.frame&#39;: 97387 obs. of  8 variables:
##  $ Year                     : num  2012 2012 2012 2012 2012 ...
##  $ State Name               : chr  &quot;ALABAMA&quot; &quot;ALABAMA&quot; &quot;ALABAMA&quot; &quot;ALABAMA&quot; ...
##  $ SEA Education Environment: chr  &quot;Correctional Facilities&quot; &quot;Home&quot; &quot;Homebound/Hospital&quot; &quot;Inside regular class 40% through 79% of day&quot; ...
##  $ SEA Disability Category  : chr  &quot;All Disabilities&quot; &quot;All Disabilities&quot; &quot;All Disabilities&quot; &quot;All Disabilities&quot; ...
##  $ Female Age 3 to 5        : chr  &quot;-&quot; &quot;63&quot; &quot;-&quot; &quot;-&quot; ...
##  $ Male Age 3 to 5          : chr  &quot;-&quot; &quot;174&quot; &quot;-&quot; &quot;-&quot; ...
##  $ Female Age 6 to 21       : chr  &quot;4&quot; &quot;-&quot; &quot;104&quot; &quot;1590&quot; ...
##  $ Male Age 6 to 21         : chr  &quot;121&quot; &quot;-&quot; &quot;130&quot; &quot;3076&quot; ...</code></pre>
</div>
<div id="filter-for-the-desired-disabilities-and-age-groups" class="section level3">
<h3><span class="header-section-number">10.5.4</span> Filter for the desired disabilities and age groups</h3>
<p>We want to explore gender related variables, but our dataset has additional aggregate data for other subgroups. For example, we can use <code>count</code> to explore all the different disability groups in the dataset:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb181-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb181-2" title="2"><span class="st">  </span><span class="kw">count</span>(<span class="st">`</span><span class="dt">SEA Disability Category</span><span class="st">`</span>)</a></code></pre></div>
<pre><code>## # A tibble: 16 x 2
##    `SEA Disability Category`                                                   n
##    &lt;chr&gt;                                                                   &lt;int&gt;
##  1 All Disabilities                                                         6954
##  2 Autism                                                                   6954
##  3 Deaf-blindness                                                           6954
##  4 Developmental delay                                                      4636
##  5 Developmental delay (valid only for children ages 3-9 when defined by …  2318
##  6 Emotional disturbance                                                    6954
##  7 Hearing impairment                                                       6954
##  8 Intellectual disability                                                  6954
##  9 Multiple disabilities                                                    6954
## 10 Orthopedic impairment                                                    6954
## 11 Other health impairment                                                  6954
## 12 Specific learning disability                                             6954
## 13 Speech or language impairment                                            6954
## 14 Traumatic brain injury                                                   6954
## 15 Visual impairment                                                        6954
## 16 &lt;NA&gt;                                                                       31</code></pre>
<p>Since we will be visualizing and modeling gender variables for all students in the dataset, we’ll filter out all subgoups except “All Disabilities” and the age totals:</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb183-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb183-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb183-3" title="3"><span class="st">  </span><span class="kw">filter</span>(</a>
<a class="sourceLine" id="cb183-4" title="4">    <span class="st">`</span><span class="dt">SEA Disability Category</span><span class="st">`</span> <span class="op">==</span><span class="st"> &quot;All Disabilities&quot;</span>,</a>
<a class="sourceLine" id="cb183-5" title="5">    <span class="st">`</span><span class="dt">SEA Education Environment</span><span class="st">`</span> <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Total, Age 3-5&quot;</span>, <span class="st">&quot;Total, Age 6-21&quot;</span>)</a>
<a class="sourceLine" id="cb183-6" title="6">  ) </a></code></pre></div>
</div>
<div id="rename-the-variables" class="section level3">
<h3><span class="header-section-number">10.5.5</span> Rename the variables</h3>
<p>In the next section we’ll prepare the dataset for visualization and modeling by “tidying” it. When we write code to transform datasets, we’ll be typing the column names a lot, so it’s useful to change them to ones with more convenient names.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb184-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb184-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb184-3" title="3"><span class="st">  </span><span class="kw">rename</span>(</a>
<a class="sourceLine" id="cb184-4" title="4">    <span class="dt">year =</span> Year,</a>
<a class="sourceLine" id="cb184-5" title="5">    <span class="dt">state =</span> <span class="st">&quot;State Name&quot;</span>,</a>
<a class="sourceLine" id="cb184-6" title="6">    <span class="dt">age =</span> <span class="st">&quot;SEA Education Environment&quot;</span>,</a>
<a class="sourceLine" id="cb184-7" title="7">    <span class="dt">disability =</span> <span class="st">&quot;SEA Disability Category&quot;</span>,</a>
<a class="sourceLine" id="cb184-8" title="8">    <span class="dt">f_3_5 =</span> <span class="st">&quot;Female Age 3 to 5&quot;</span>,</a>
<a class="sourceLine" id="cb184-9" title="9">    <span class="dt">m_3_5 =</span> <span class="st">&quot;Male Age 3 to 5&quot;</span>,</a>
<a class="sourceLine" id="cb184-10" title="10">    <span class="dt">f_6_21 =</span> <span class="st">&quot;Female Age 6 to 21&quot;</span>,</a>
<a class="sourceLine" id="cb184-11" title="11">    <span class="dt">m_6_21 =</span> <span class="st">&quot;Male Age 6 to 21&quot;</span></a>
<a class="sourceLine" id="cb184-12" title="12">  )</a></code></pre></div>
</div>
<div id="clean-state-names" class="section level3">
<h3><span class="header-section-number">10.5.6</span> Clean state names</h3>
<p>You might have noticed that some state names in our dataset are in upper case letters and some are in lower case letters:</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb185-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb185-2" title="2"><span class="st">  </span><span class="kw">count</span>(state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb185-3" title="3"><span class="st">  </span><span class="kw">head</span>()</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   state              n
##   &lt;chr&gt;          &lt;int&gt;
## 1 Alabama            8
## 2 ALABAMA            4
## 3 Alaska             8
## 4 ALASKA             4
## 5 American Samoa     8
## 6 AMERICAN SAMOA     4</code></pre>
<p>If we leave it like this, R will treat state values like “CALIFORNIA” and “California” as two different states. We can use <code>mutate</code> and <code>tolower</code> to transform all the state names to lowercase letters.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb187-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb187-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb187-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">state =</span> <span class="kw">tolower</span>(state)) </a></code></pre></div>
</div>
<div id="tidy-the-dataset" class="section level3">
<h3><span class="header-section-number">10.5.7</span> Tidy the dataset</h3>
<p>Visualizing and modeling our data will be much easier if our dataset is in a “tidy” format. In his paper <em>Tidy Data</em> (2014), Hadley Wickham defines tidy datasets where</p>
<blockquote>
<ol style="list-style-type: decimal">
<li>Each variable forms a column.</li>
<li>Each observation forms a row.</li>
<li>Each type of observational unit forms a table.</li>
</ol>
</blockquote>
<p><em>A note on the gender variable in this dataset</em></p>
<p><em>This dataset uses a binary approach to data collection about gender. Students are described as either male or female. The need for an inclusive approach to documenting gender identity is discussed in a paper by <span class="citation">(“Reachable: Data Collection Methods for Sexual Orientation and Gender Identity” <a href="#ref-park2016">2016</a>)</span> of The Williams Institute at UCLA.</em></p>
<p>The gender variables in our dataset are spread across four columns, with each one representing a combination of gender and age range. We can use <code>gather</code> to bring the gender variable into one column. In this transformation, we create two new columns: a <code>gender</code> column and a <code>total</code> column. The <code>total</code> column will contain the number of students in each row’s gender and age category.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb188-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb188-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb188-3" title="3"><span class="st">  </span><span class="kw">gather</span>(gender, total, f_<span class="dv">3</span>_<span class="dv">5</span><span class="op">:</span>m_<span class="dv">6</span>_<span class="dv">21</span>)</a></code></pre></div>
<p>To make the values of the <code>gender</code> column more intuitive, we’ll use <code>case_when</code> to transform the values to either “f” or “m”:</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb189-1" title="1">child_counts &lt;-<span class="st"> </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb189-2" title="2"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb189-3" title="3">    <span class="dt">gender =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb189-4" title="4">      gender <span class="op">==</span><span class="st"> &quot;f_3_5&quot;</span> <span class="op">~</span><span class="st"> &quot;f&quot;</span>,</a>
<a class="sourceLine" id="cb189-5" title="5">      gender <span class="op">==</span><span class="st"> &quot;m_3_5&quot;</span> <span class="op">~</span><span class="st"> &quot;m&quot;</span>,</a>
<a class="sourceLine" id="cb189-6" title="6">      gender <span class="op">==</span><span class="st"> &quot;f_6_21&quot;</span> <span class="op">~</span><span class="st"> &quot;f&quot;</span>,</a>
<a class="sourceLine" id="cb189-7" title="7">      gender <span class="op">==</span><span class="st"> &quot;m_6_21&quot;</span> <span class="op">~</span><span class="st"> &quot;m&quot;</span>,</a>
<a class="sourceLine" id="cb189-8" title="8">      <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="kw">as.character</span>(gender)</a>
<a class="sourceLine" id="cb189-9" title="9">    )</a>
<a class="sourceLine" id="cb189-10" title="10">  )</a></code></pre></div>
</div>
<div id="convert-data-types" class="section level3">
<h3><span class="header-section-number">10.5.8</span> Convert data types</h3>
<p>The values in the <code>total</code> column represent the number of students from a specific year, state, gender, and age group. We know from the <code>chr</code> under their variable names that R is treating these values like characters instead of numbers. While R does a decent job of treating numbers like numbers when needed, it’s much safer to prepare the dataset by changing these character columns to number columns. We’ll use <code>dplyr::mutate_at</code> to change the count columns.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb190-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb190-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb190-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">total =</span> <span class="kw">as.numeric</span>(total))</a></code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb192-1" title="1">child_counts</a></code></pre></div>
<pre><code>## # A tibble: 2,928 x 6
##     year state          age             disability       gender total
##    &lt;dbl&gt; &lt;chr&gt;          &lt;chr&gt;           &lt;chr&gt;            &lt;chr&gt;  &lt;dbl&gt;
##  1  2012 alabama        Total, Age 3-5  All Disabilities f       2228
##  2  2012 alabama        Total, Age 6-21 All Disabilities f         NA
##  3  2012 alaska         Total, Age 3-5  All Disabilities f        676
##  4  2012 alaska         Total, Age 6-21 All Disabilities f         NA
##  5  2012 american samoa Total, Age 3-5  All Disabilities f         45
##  6  2012 american samoa Total, Age 6-21 All Disabilities f         NA
##  7  2012 arizona        Total, Age 3-5  All Disabilities f       4743
##  8  2012 arizona        Total, Age 6-21 All Disabilities f         NA
##  9  2012 arkansas       Total, Age 3-5  All Disabilities f       4605
## 10  2012 arkansas       Total, Age 6-21 All Disabilities f         NA
## # … with 2,918 more rows</code></pre>
<p>Converting these count columns from character classes to number classes resulted in two changes. First, the <code>chr</code> under these variable names has now changed to <code>dbl</code>, short for “double-precision”. This lets us know that R recognizes these values as numbers with decimal points. Second, the blank values changed to <code>NA</code>. When R sees a character class value like <code>"4"</code>, it knows to change it to numeric class <code>4</code>. But there is no obvious number represented by a character class like <code>""</code>, so it changes it to <code>NA</code>:</p>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb194-1" title="1"><span class="co"># Convert a character to a number </span></a>
<a class="sourceLine" id="cb194-2" title="2"><span class="kw">as.numeric</span>(<span class="st">&quot;4&quot;</span>)</a></code></pre></div>
<pre><code>## [1] 4</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb196-1" title="1"><span class="co"># Convert a blank character to number</span></a>
<a class="sourceLine" id="cb196-2" title="2"><span class="kw">as.numeric</span>(<span class="st">&quot;&quot;</span>)</a></code></pre></div>
<pre><code>## [1] NA</code></pre>
<p>Similarly, the variable <code>year</code> needs to be changed from the character format to the date format. Doing so will make sure R treats this variable like a point in time when we plot our dataset. The package <code>lubridate</code> has a handy function called <code>ymd</code> that can help us. We just have to use the <code>truncated</code> argument to let R know we don’t have a month and date to convert.</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb198-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb198-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb198-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">ymd</span>(year, <span class="dt">truncated =</span> <span class="dv">2</span>))</a></code></pre></div>
</div>
<div id="explore-and-address-nas" class="section level3">
<h3><span class="header-section-number">10.5.9</span> Explore and address NAs</h3>
<p>You’ll notice that some rows in the <code>total</code> column contain an <code>NA</code>. When we used <code>gather</code> to create a <code>gender</code> column, R created unique rows for every year, state, age, disability, and gender combination. Since the original dataset had both gender and age range stored in a column like <code>Female Age 3 to 5</code>, R made rows where the <code>total</code> value is NA . For example, there is no student count for the <code>age</code> value “Total, Age 3-5” that also has the <code>gender</code> value for female students who were age 6-21. You can see that more clearly by sorting the dataset by year, state, and gender.</p>
<p>In our foundational skills chapter, we introduced a <code>dplyr</code> function called <code>arrange</code> to sort the rows of a dataset by the values in a column. Let’s use <code>arrange</code> here to sort the dataset by the <code>year</code>, <code>state</code> and <code>gender</code> columns. When you pass <code>arrange</code> a variable, it will sort by the order of the values in that variable. If you pass it multiple variables, <code>arrange</code> will sort by the first variable, then by the second, and so on. Let’s see what it does on <code>child_counts</code> when we pass it the <code>year</code>, <code>state</code>, and <code>gender</code> variables:</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb199-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb199-2" title="2"><span class="st">  </span><span class="kw">arrange</span>(year, state, gender)</a></code></pre></div>
<pre><code>## # A tibble: 2,928 x 6
##    year       state   age             disability       gender total
##    &lt;date&gt;     &lt;chr&gt;   &lt;chr&gt;           &lt;chr&gt;            &lt;chr&gt;  &lt;dbl&gt;
##  1 2012-01-01 alabama Total, Age 3-5  All Disabilities f       2228
##  2 2012-01-01 alabama Total, Age 6-21 All Disabilities f         NA
##  3 2012-01-01 alabama Total, Age 3-5  All Disabilities f         NA
##  4 2012-01-01 alabama Total, Age 6-21 All Disabilities f      23649
##  5 2012-01-01 alabama Total, Age 3-5  All Disabilities m       5116
##  6 2012-01-01 alabama Total, Age 6-21 All Disabilities m         NA
##  7 2012-01-01 alabama Total, Age 3-5  All Disabilities m         NA
##  8 2012-01-01 alabama Total, Age 6-21 All Disabilities m      48712
##  9 2012-01-01 alaska  Total, Age 3-5  All Disabilities f        676
## 10 2012-01-01 alaska  Total, Age 6-21 All Disabilities f         NA
## # … with 2,918 more rows</code></pre>
<p>We can simplify our dataset by removing these rows, leaving us with one row for each category:</p>
<ul>
<li>females age 3-5</li>
<li>females age 6-21</li>
<li>males age 3-5</li>
<li>males age 6-21</li>
</ul>
<p>Each of these categories will be associated with a state and reporting year:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb201-1" title="1">child_counts &lt;-</a>
<a class="sourceLine" id="cb201-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb201-3" title="3"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(total)) </a></code></pre></div>
<p>We can verify we have the categories we want by sorting again:</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb202-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb202-2" title="2"><span class="st">  </span><span class="kw">arrange</span>(year, state, gender)</a></code></pre></div>
<pre><code>## # A tibble: 1,390 x 6
##    year       state          age             disability       gender total
##    &lt;date&gt;     &lt;chr&gt;          &lt;chr&gt;           &lt;chr&gt;            &lt;chr&gt;  &lt;dbl&gt;
##  1 2012-01-01 alabama        Total, Age 3-5  All Disabilities f       2228
##  2 2012-01-01 alabama        Total, Age 6-21 All Disabilities f      23649
##  3 2012-01-01 alabama        Total, Age 3-5  All Disabilities m       5116
##  4 2012-01-01 alabama        Total, Age 6-21 All Disabilities m      48712
##  5 2012-01-01 alaska         Total, Age 3-5  All Disabilities f        676
##  6 2012-01-01 alaska         Total, Age 6-21 All Disabilities f       5307
##  7 2012-01-01 alaska         Total, Age 3-5  All Disabilities m       1440
##  8 2012-01-01 alaska         Total, Age 6-21 All Disabilities m      10536
##  9 2012-01-01 american samoa Total, Age 3-5  All Disabilities f         45
## 10 2012-01-01 american samoa Total, Age 6-21 All Disabilities f        208
## # … with 1,380 more rows</code></pre>
</div>
</div>
<div id="analysis-how-have-child-counts-changed-over-time" class="section level2">
<h2><span class="header-section-number">10.6</span> Analysis: How Have Child Counts Changed Over Time?</h2>
<p>In the last section we focused on importing our dataset. In this section, we will turn to exploring it. First, we’ll use visualization to explore the number of students in special education over time. In particular, we’ll compare the count of male and female students. Next, we’ll use what we learn from our visualizations to quantify any differences that we see.</p>
<div id="visualize-the-dataset" class="section level3">
<h3><span class="header-section-number">10.6.1</span> Visualize the Dataset</h3>
<p>Showing this many states in a plot can be overwhelming, so to start we’ll make a subset of the dataset. We can use a function in the <code>dplyr</code> package called <code>top_n()</code> to help us learn which states have the highest average count of special education students:</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb204-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb204-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb204-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_count =</span> <span class="kw">mean</span>(total)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb204-4" title="4"><span class="st">  </span><span class="kw">top_n</span>(<span class="dv">6</span>, mean_count)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   state                                            mean_count
##   &lt;chr&gt;                                                 &lt;dbl&gt;
## 1 california                                          180879.
## 2 florida                                              92447.
## 3 new york                                            121751.
## 4 pennsylvania                                         76080.
## 5 texas                                               115593.
## 6 us, outlying areas, and freely associated states   1671931.</code></pre>
<p>These six states have the highest mean count of students in special education over the six years we are examining. For reasons we will see in a later visualization, we are going to exclude outlying areas and freely associated states. That leaves us us with five states: California, Florida, New York, Pennsylvania, and Texas. We can remove all other states but these by using <code>filter()</code>. We’ll call this new dataset <code>high_count</code>:</p>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb206-1" title="1">high_count &lt;-</a>
<a class="sourceLine" id="cb206-2" title="2"><span class="st">  </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb206-3" title="3"><span class="st">  </span><span class="kw">filter</span>(state <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;california&quot;</span>, <span class="st">&quot;florida&quot;</span>, <span class="st">&quot;new york&quot;</span>, <span class="st">&quot;pennsylvania&quot;</span>, <span class="st">&quot;texas&quot;</span>))</a></code></pre></div>
<p>Now we can use <code>high_count</code> to do some initial exploration. Our analysis is about comparing counts of male and female students in special education, but visualization is also a great way to explore related curiosities. You may surprise yourself with what you find when visualizing your datasets. You might come up with more interesting hypotheses, find that your initial hypothesis requires more data transformation, or find interesting subsets of the data–we saw a little of that in the surprisingly high <code>mean_count</code> of freely associated states in the <code>state</code> column. Let your curiosity and intuition drive this part of the analysis. It’s one of the activities that makes data analysis a creative process.</p>
<p>In that spirit, we’ll start by visualizing specific genders and age groups. Feel free to try these, but also try the other student groups for practice and more exploration.</p>
<p>Start by copying and running this code in your console to see what it does:</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb207-1" title="1">high_count <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb207-2" title="2"><span class="st">  </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;f&quot;</span>, age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb207-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> total, <span class="dt">color =</span> state)) <span class="op">+</span></a>
<a class="sourceLine" id="cb207-4" title="4"><span class="st">  </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb207-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Count of female students in special education over time&quot;</span>,</a>
<a class="sourceLine" id="cb207-6" title="6">       <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb207-7" title="7"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb207-8" title="8"><span class="st">  </span><span class="kw">scale_color_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/total%20female%20students%20over%20time-1.png" width="672" /></p>
<p>That gives us a plot that has the years in the x-axis and a count of female students in the y-axis. Each line takes a different color based on the state it represents.</p>
<p>Let’s look at that closer: We used <code>filter</code> to subset our dataset for students who are female and ages 6 to 21. We used <code>aes</code> to connect visual elements of our plot to our data. We connected the x-axis to <code>year</code>, the y-axis to <code>total</code>, and the color of the line to <code>state</code>.</p>
<p>It’s worth calling out one more thing, since it’s a technique we’ll be using as we explore further. Note here that, instead of storing our new dataset in a new variable, we filter the dataset then use the pipe operator <code>%&gt;%</code> to feed it to <code>ggplot</code>. Since we’re exploring freely, we don’t need to create a lot of new variables we probably won’t need later.</p>
<p>We can also try the same plot, but subsetting for male students instead. We can use the same code we used for the last plot, but filter for the value “m” in the <code>gender</code> field:</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb208-1" title="1">high_count <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb208-2" title="2"><span class="st">  </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;m&quot;</span>, age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb208-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> total, <span class="dt">color =</span> state)) <span class="op">+</span></a>
<a class="sourceLine" id="cb208-4" title="4"><span class="st">  </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb208-5" title="5"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Count of male students in special education over time&quot;</span>,</a>
<a class="sourceLine" id="cb208-6" title="6">       <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb208-7" title="7"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb208-8" title="8"><span class="st">  </span><span class="kw">scale_color_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/total%20male%20students%20over%20time-1.png" width="672" /></p>
<p>We’ve looked at each gender separately. What do these lines look like if we visualized the total amount of students each year per state? To do that, we’ll need to add both gender values together and both age group values together. We’ll do this using a very common combination of functions: <code>group_by</code> and <code>summarise</code>.</p>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb209-1" title="1">high_count <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb209-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(year, state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb209-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb209-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> n, <span class="dt">color =</span> state)) <span class="op">+</span></a>
<a class="sourceLine" id="cb209-5" title="5"><span class="st">  </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb209-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Total count of students in special education over time&quot;</span>,</a>
<a class="sourceLine" id="cb209-7" title="7">       <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb209-8" title="8"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb209-9" title="9"><span class="st">  </span><span class="kw">scale_color_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/total%20students%20over%20time-1.png" width="672" /></p>
<p>So far we’ve looked at a few ways to count students over time. In each plot, we see that while counts have grown overall for all states, each state has different sized populations. Let’s see if we can summarize that difference by looking at the median student count for each state over the years:</p>
<div class="sourceCode" id="cb210"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb210-1" title="1">high_count <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb210-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(year, state) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb210-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb210-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> state, <span class="dt">y =</span> n)) <span class="op">+</span></a>
<a class="sourceLine" id="cb210-5" title="5"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb210-6" title="6"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Median student count&quot;</span>,</a>
<a class="sourceLine" id="cb210-7" title="7">       <span class="dt">subtitle =</span> <span class="st">&quot;All ages and genders&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb210-8" title="8"><span class="st">  </span><span class="kw">theme_dataedu</span>() </a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/median%20total%20per%20state-1.png" width="672" /></p>
<p>The boxplots show us what we might have expected from our <code>freqpoly</code> plots before it. The highest median student count over time is California and the lowest is Pennsylvania.</p>
<p>What have we learned about our data so far? The five states in the US with the highest total student counts (not including outlying areas and freely associated states) do not have similar counts to each other. The student counts for each state also appear to have grown over time.</p>
<p>But how can we start comparing the male student count to the female student count? One way is to use a ratio:</p>
<blockquote>
<p>In mathematics, a ratio is a relationship between two numbers indicating how many times the first number contains the second.
Wikpedia</p>
</blockquote>
<p>We can use the count of male students in each state and divide it by the count of each female student. The result is the number of times male students are in special education more or less than the female students in the same state and year. Our coding strategy will be to</p>
<ul>
<li>Use <code>spread</code> to create separate columns for male and female students.</li>
<li>Use <code>mutate</code> to create a new variable called <code>ratio</code>. The values in this column will be the result of dividing the count of male students by the count of female students</li>
</ul>
<p>Note here that we can also accomplish this comparison by dividing the number of female students by the number of male students. In this case, the result would be the number of times female students are in special education more or less than male students.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb211-1" title="1">high_count <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb211-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(year, state, gender) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb211-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">total =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb211-4" title="4"><span class="st">  </span><span class="co"># Create new columns for male and female student counts</span></a>
<a class="sourceLine" id="cb211-5" title="5"><span class="st">  </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb211-6" title="6"><span class="st">  </span><span class="co"># Create a new ratio column</span></a>
<a class="sourceLine" id="cb211-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ratio =</span> m <span class="op">/</span><span class="st"> </span>f) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb211-8" title="8"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> ratio, <span class="dt">color =</span> state)) <span class="op">+</span></a>
<a class="sourceLine" id="cb211-9" title="9"><span class="st">  </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb211-10" title="10"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="fl">1.5</span>, <span class="fl">2.5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb211-11" title="11"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Male student to female student ratio over time&quot;</span>,</a>
<a class="sourceLine" id="cb211-12" title="12">       <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb211-13" title="13"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb211-14" title="14"><span class="st">  </span><span class="kw">scale_color_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/male%20to%20female%20ratio%20over%20time-1.png" width="672" /></p>
<p>By visually inspecting, we can hypothesize that there was no significant change in the male to female ratio between the years 2012 and 2017. But very often we want to understand the underlying properties of our education dataset. We can do this by quantifying the relationship between two variables. In the next section, we’ll explore ways to quantify the relationship between male student counts and female student counts.</p>
</div>
<div id="model-the-dataset" class="section level3">
<h3><span class="header-section-number">10.6.2</span> Model the Dataset</h3>
<p>When you visualize your datasets, you are exploring possible relationships between variables. But sometimes visualizations can be misleading because of the way we perceive graphics. In his book <em>Data Visuzliation: A Practical Introduction</em>, <span class="citation">Healy (<a href="#ref-healy2019">2019</a>)</span> teaches us that</p>
<blockquote>
<p>Visualizations encode numbers in lines, shapes, and colors. That means that our interpretation of these encodings is partly conditional on how we perceive geometric shapes and relationships generally.</p>
</blockquote>
<p>What are some ways we can combat these errors of perception and at the same time draw substantive conclusions about our education dataset? When you spot a possible relationship between variables, the relationship between female and male counts for example, you’ll want to quantify that relationship by fitting a statisitcal model. Practically speaking, this means you are selecting a distribution that represents your dataset reasonably well. This distribution will help you quantify and predict relationships between variables. This is an important step in the analytic process, because it acts as a check on what you saw in your exploratory visualizations.</p>
<p>In this example, we’ll follow our intuition about the relationship between male and female student counts in our special education dataset. In particular, we’ll test the hypothesis that this ratio has decreased over the years. Fitting a linear regression model that estimates the year as a predictor of the male to female ratio will help us do just that.</p>
<p><em>Do we have enough information for our model?</em></p>
<p>At the start of this section, we chose to exclude outlying areas and freely associated states. This visualization suggests that there are some states that have a child count so high it leaves a gap in the x-axis values. This can be problematic when we try to interpret our model later. Here’s a plot of female students compared to male students. Note that the relationship appears linear, but there is a large gap in the distribution of female student counts somewhere bewteen the values of 250,000 and 1,750,000:</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb212-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb212-2" title="2"><span class="st">  </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb212-3" title="3"><span class="st">  </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb212-4" title="4"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> f, <span class="dt">y =</span> m)) <span class="op">+</span></a>
<a class="sourceLine" id="cb212-5" title="5"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> <span class="fl">.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb212-6" title="6"><span class="st">  </span><span class="kw">geom_smooth</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb212-7" title="7"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb212-8" title="8">    <span class="dt">title =</span> <span class="st">&quot;Comparison of female students to male students in special education&quot;</span>,</a>
<a class="sourceLine" id="cb212-9" title="9">    <span class="dt">subtitle =</span> <span class="st">&quot;Counts of students in each state, ages 6-21&quot;</span>,</a>
<a class="sourceLine" id="cb212-10" title="10">    <span class="dt">x =</span> <span class="st">&quot;Female students&quot;</span>,</a>
<a class="sourceLine" id="cb212-11" title="11">    <span class="dt">y =</span> <span class="st">&quot;Male students&quot;</span>,</a>
<a class="sourceLine" id="cb212-12" title="12">    <span class="dt">caption =</span> <span class="st">&quot;Data: US Dept of Education&quot;</span></a>
<a class="sourceLine" id="cb212-13" title="13">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb212-14" title="14"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/plot%20female%20students%20to%20male%20students-1.png" width="672" /></p>
<p>If you think of each potential point on the linear regression line as a ratio of male to female students, you’ll notice that we don’t know a whole lot about what happens in states where there are between 250,000 and 1,750,000 female students in any given year.</p>
<p>To learn more about what’s happening in our dataset, we can filter it for only states that have more than 500,000 female students in any year:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb214-2" title="2"><span class="st">  </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb214-3" title="3"><span class="st">  </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb214-4" title="4"><span class="st">  </span><span class="kw">filter</span>(f <span class="op">&gt;</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb214-5" title="5"><span class="st">  </span><span class="kw">select</span>(year, state, age, f, m)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   year       state                                  age                 f      m
##   &lt;date&gt;     &lt;chr&gt;                                  &lt;chr&gt;           &lt;dbl&gt;  &lt;dbl&gt;
## 1 2012-01-01 us, outlying areas, and freely associ… Total, Age 6… 1933619 3.89e6
## 2 2013-01-01 us, outlying areas, and freely associ… Total, Age 6… 1937726 3.88e6
## 3 2014-01-01 us, outlying areas, and freely associ… Total, Age 6… 1965204 3.92e6
## 4 2015-01-01 us, outlying areas, and freely associ… Total, Age 6… 2007174 3.98e6
## 5 2016-01-01 us, outlying areas, and freely associ… Total, Age 6… 2014120 3.97e6
## 6 2017-01-01 us, outlying areas, and freely associ… Total, Age 6… 2051438 4.02e6</code></pre>
<p>This is where we discover that each of the data points in the upper right hand corner of the plot are from the state value “us, us, outlying areas, and freely associated states”. If we remove these outliers, we have a distribution of female students that looks more complete.</p>
<div class="sourceCode" id="cb216"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb216-1" title="1">child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb216-2" title="2"><span class="st">  </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb216-3" title="3"><span class="st">  </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb216-4" title="4"><span class="st">  </span><span class="co"># Filter for female student counts less than 500,000</span></a>
<a class="sourceLine" id="cb216-5" title="5"><span class="st">  </span><span class="kw">filter</span>(f <span class="op">&lt;=</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb216-6" title="6"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> f, <span class="dt">y =</span> m)) <span class="op">+</span></a>
<a class="sourceLine" id="cb216-7" title="7"><span class="st">  </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> <span class="fl">.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb216-8" title="8"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb216-9" title="9">    <span class="dt">title =</span> <span class="st">&quot;Comparison of female students to male students in special education&quot;</span>,</a>
<a class="sourceLine" id="cb216-10" title="10">    <span class="dt">subtitle =</span> <span class="st">&quot;Counts of students in each state, ages 6-21.</span><span class="ch">\n</span><span class="st">Does not include outlying areas and freely associated states&quot;</span>,</a>
<a class="sourceLine" id="cb216-11" title="11">    <span class="dt">x =</span> <span class="st">&quot;Female students&quot;</span>,</a>
<a class="sourceLine" id="cb216-12" title="12">    <span class="dt">y =</span> <span class="st">&quot;Male students&quot;</span>,</a>
<a class="sourceLine" id="cb216-13" title="13">    <span class="dt">caption =</span> <span class="st">&quot;Data: US Dept of Education&quot;</span></a>
<a class="sourceLine" id="cb216-14" title="14">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb216-15" title="15"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/plot%20without%20outliers-1.png" width="672" /></p>
<p>This should allow us to fit a better model for the relationship between male and female student counts, albeit only the ones where the count of female students takes a value between 0 and 500,000.</p>
<p><em>Male to Female Ratio Over Time</em></p>
<p>Earlier we asked the question Do we have enough data points for the count of female students to learn about the ratio of female to male students? Similarly, we should ask the question Do we have enough data points across our year variable to learn about how this ratio has changed over time?</p>
<p>To answer that question, let’s start by making a new dataset that excludes any rows where the <code>f</code> variables has a value that is less than or equal to 500000. We’ll convert the <code>year</code> variable to a factor data type–we’ll see how this helps in a bit. We’ll also add a column called <code>ratio</code> that contains the male to female count ratio.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb217-1" title="1">model_data &lt;-<span class="st"> </span>child_counts <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-2" title="2"><span class="st">  </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">as.factor</span>(<span class="kw">year</span>(year))) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-4" title="4"><span class="st">  </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-5" title="5"><span class="st">  </span><span class="co"># Exclude outliers</span></a>
<a class="sourceLine" id="cb217-6" title="6"><span class="st">  </span><span class="kw">filter</span>(f <span class="op">&lt;=</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-7" title="7"><span class="st">  </span><span class="co"># Compute male student to female student ratio</span></a>
<a class="sourceLine" id="cb217-8" title="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">ratio =</span> m <span class="op">/</span><span class="st"> </span>f) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb217-9" title="9"><span class="st">  </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(age, disability))</a></code></pre></div>
<p>We can see how much data we have per year by using <code>count</code>:</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb218-1" title="1">model_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb218-2" title="2"><span class="st">  </span><span class="kw">count</span>(year)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year      n
##   &lt;fct&gt; &lt;int&gt;
## 1 2012     59
## 2 2013     56
## 3 2014     56
## 4 2015     58
## 5 2016     57
## 6 2017     55</code></pre>
<p>Let’s visualize the ratio values across all years as an additional check. Note the use of <code>geom_jitter</code> to spread the points horizontally so we can estimate the quantities better:</p>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb220-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> model_data, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> ratio)) <span class="op">+</span></a>
<a class="sourceLine" id="cb220-2" title="2"><span class="st">  </span><span class="kw">geom_jitter</span>(<span class="dt">alpha =</span> <span class="fl">.5</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb220-3" title="3"><span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Male to female ratio across years (jittered)&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb220-4" title="4"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/ratios%20across%20years-1.png" width="672" /></p>
<p>Each year seems to have data points that can be considered when we fit the model. This means that there are enough data points to help us learn how the year variable predicts the ratio variable.</p>
<p>We fit the linear regression model by passing the argument <code>ratio ~ year</code> to the function <code>lm</code>. In R, the <code>~</code> usually indicates a formula. In this case, the formula is the variable <code>year</code> as a predictor of the variable <code>ratio</code>. The final argument we pass to <code>lm</code> is <code>data = model_data</code>, which tells R to look for the variables <code>ratio</code> and <code>year</code> in the dataset <code>model_data</code>. The results of the model are called a “model object.” We’ll store the model object in <code>ratio_year</code>:</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb221-1" title="1">ratio_year &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb221-2" title="2"><span class="st">  </span><span class="kw">lm</span>(ratio <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> model_data)</a></code></pre></div>
<p>Each model object is filled with all sorts of model information. We can look at this information using the fuction <code>summary</code>:</p>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb222-1" title="1"><span class="kw">summary</span>(ratio_year)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ratio ~ year, data = model_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.44025 -0.10138 -0.02810  0.05343  0.75737 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.03356    0.02200  92.418   &lt;2e-16 ***
## year2013    -0.01205    0.03153  -0.382   0.7027    
## year2014    -0.02372    0.03153  -0.752   0.4524    
## year2015    -0.03104    0.03125  -0.993   0.3213    
## year2016    -0.03964    0.03139  -1.263   0.2075    
## year2017    -0.05760    0.03168  -1.818   0.0699 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.169 on 335 degrees of freedom
## Multiple R-squared:  0.01215,    Adjusted R-squared:  -0.002594 
## F-statistic: 0.8241 on 5 and 335 DF,  p-value: 0.5332</code></pre>
<p>Here’s how we can interpret the <code>Estimate</code> column: The estimate of the <code>(Intercept)</code> is 2.03356, which is the estimated value of the <code>ratio</code> variable when the <code>year</code> variable is “2012”. Note that the value <code>year2012</code> isn’t present in the in the list of rownames. That’s because the <code>(Intercept)</code> row represents <code>year2012</code>. In linear regression models that use factor variables as predictors, the first level of the factor is the intercept. Sometimes this level is called a “dummy variable”. The remaining rows of the model output show how much each year differs from the intercept, 2012. For example, <code>year2013</code> has an estimate of -0.01205, which suggests that on average the value of <code>ratio</code> is .01205 less than 2.03356. On average, the ratio of <code>year2014</code> is .02372 less than 2.03356. The <code>t value</code> column tells us the size of difference between the estimated value of the ratio for each year and the estimated value of the ratio of the intercept. Generally speaking, the larger the t value, the larger the chance that any difference between the coefficient of a factor level and the intercept are significant.</p>
<p>Though the relationship between <code>year</code> as a preditor of <code>ratio</code> is not linear (recall our previous plot), the linear regression model still gives us useful information. We fit a linear regression model to a factor variable, like <code>year</code>, as a predictor of a continuous variable, like<code>ratio</code>. In doing so, we got the average <code>ratio</code> at every value of <code>year</code>. We can verify this by taking the mean <code>ratio</code> of ever <code>year</code>:</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb224-1" title="1">model_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb224-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb224-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_ratio =</span> <span class="kw">mean</span>(ratio))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year  mean_ratio
##   &lt;fct&gt;      &lt;dbl&gt;
## 1 2012        2.03
## 2 2013        2.02
## 3 2014        2.01
## 4 2015        2.00
## 5 2016        1.99
## 6 2017        1.98</code></pre>
<p>This verifies that our intercept, the value of <code>ratio</code> during the year 2012, is 2.033563 and the value of <code>ratio</code> for 2013 is .01205 less than that of 2012 on average. Fitting the model gives us more details about these mean ratio scores– namely the coefficient, t value, and p value. These values help us apply judgement when deciding if differences in <code>ratio</code> values suggest an underlying difference between years or simply differences you can expect from randomness. In this case, the absence of "*" in all rows except the Intercept row suggest that any differences occuring between years are within the range you’d expect by chance.</p>
<p>If we use <code>summary</code> on our <code>model_data</code> dataset, we can verify the intercept again:</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb226-1" title="1">model_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb226-2" title="2"><span class="st">  </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> &quot;2012&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb226-3" title="3"><span class="st">  </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##    year       state                 f                m              ratio      
##  2012:59   Length:59          Min.   :   208   Min.   :   443   Min.   :1.710  
##  2013: 0   Class :character   1st Qu.:  5606   1st Qu.: 11467   1st Qu.:1.927  
##  2014: 0   Mode  :character   Median : 22350   Median : 44110   Median :1.994  
##  2015: 0                      Mean   : 32773   Mean   : 65934   Mean   :2.034  
##  2016: 0                      3rd Qu.: 38552   3rd Qu.: 77950   3rd Qu.:2.093  
##  2017: 0                      Max.   :198595   Max.   :414466   Max.   :2.692</code></pre>
<p>The mean value of the <code>ratio</code> column when the <code>year</code> column is 2012 is 2.034, just like in the model output’s intercept row.</p>
<p>Lastly, we may want to communicate to a larger audience that there were roughly twice amount of male students in this datset than female students and that this did not change significantly between the years 2012 and 2017. When you are not communicating to an audience of other data scientists, it’s helpful to illustrate your point without the technical details of the model output. Think of yourself as an interpreter: since you can speak the language of model outputs and the language of data visualization, your challenge is to take what you learned from the model output and tell that story in a way that is meaningful to your non-data scientist audience.</p>
<p>There are many ways to do this, but we’ll choose boxplots to show our audience that there was roughly twice as many male students in special education than female students between 2012 and 2017. For our purposes, let’s verify this by looking at the median male to female ratio for each year:</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb228-1" title="1">model_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb228-2" title="2"><span class="st">  </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb228-3" title="3"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">median_ratio =</span> <span class="kw">median</span>(ratio))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year  median_ratio
##   &lt;fct&gt;        &lt;dbl&gt;
## 1 2012          1.99
## 2 2013          1.99
## 3 2014          1.98
## 4 2015          1.98
## 5 2016          1.97
## 6 2017          1.96</code></pre>
<p>Now let’s visualize this using our boxplots:</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb230-1" title="1">model_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb230-2" title="2"><span class="st">  </span><span class="kw">gather</span>(gender, students, <span class="kw">c</span>(f, m)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb230-3" title="3"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> students, <span class="dt">color =</span> gender)) <span class="op">+</span></a>
<a class="sourceLine" id="cb230-4" title="4"><span class="st">  </span><span class="kw">geom_boxplot</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb230-5" title="5"><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>comma) <span class="op">+</span></a>
<a class="sourceLine" id="cb230-6" title="6"><span class="st">  </span><span class="kw">labs</span>(</a>
<a class="sourceLine" id="cb230-7" title="7">    <span class="dt">title =</span> <span class="st">&quot;Median male and female student counts in special education&quot;</span>,</a>
<a class="sourceLine" id="cb230-8" title="8">    <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21. Does not include outlying areas and freely associated states&quot;</span>,</a>
<a class="sourceLine" id="cb230-9" title="9">    <span class="dt">x =</span> <span class="st">&quot;&quot;</span>,</a>
<a class="sourceLine" id="cb230-10" title="10">    <span class="dt">y =</span> <span class="st">&quot;&quot;</span>,</a>
<a class="sourceLine" id="cb230-11" title="11">    <span class="dt">caption =</span> <span class="st">&quot;Data: US Dept of Education&quot;</span></a>
<a class="sourceLine" id="cb230-12" title="12">  ) <span class="op">+</span></a>
<a class="sourceLine" id="cb230-13" title="13"><span class="st">  </span><span class="kw">theme_dataedu</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb230-14" title="14"><span class="st">  </span><span class="kw">scale_color_dataedu</span>()</a></code></pre></div>
<p><img src="10-wt-longitudinal-analysis_files/figure-html/visualize%20female%20to%20male%20ratio-1.png" width="672" /></p>
<p>Once we learned from our model that male to female ratios did not change in any meaningful way from 2012 to 2017 and that the median ratio across states was about 2 male students to every female student, we can present these two ideas using this plot. When discussing the plot, it helps to have your model output in your notes so you can reference specific coefficient estimates when needed.</p>
</div>
</div>
<div id="results-2" class="section level2">
<h2><span class="header-section-number">10.7</span> Results</h2>
<p>We learned that each state has a different count of students with disabilities–so different that we need to use statistics like ratios or visualizations to compare across states. Even when we narrow our focus to the five states with the highest counts of students with disabilities, we see that there are differences in these counts.</p>
<p>When we look at these five states over time, we see that despite the differences in total count each year, all five states have increased their student counts. We also learned that though the male to female ratios for students with disabilities appears to have gone down slightly over time, our model suggests that these decreases do not represent a big difference.</p>
<p>The comparison of student counts across each state is tricky because there is a lot of variation in total enrollment across all fifty states. While we explored student counts across each state and verified that there is variation in the counts, a good next step would be to combine these data with total enrollment data. This would allow us to compare counts of students with disabilities as a percentage of total enrollment. Comparing proportions like this is a common way to compare subgroups of a population across states when each state’s population varies in size.</p>
</div>
<div id="conclusion-aggregate-data-as-context-for-student-data" class="section level2">
<h2><span class="header-section-number">10.8</span> Conclusion: Aggregate Data as Context for Student Data</h2>
<p>Education data science is about using data science tools to learn about and improve the lives of our students. So why choose a publicly available aggregate dataset instead of a student-level dataset? We chose to use an aggregate dataset because it reflects an analysis that an education data scientist would typically do.</p>
<p>Using student-level data requires that the data scientist is either an employee of the school agency or that works under a memorandum of understanding (MOU) that allows her to access this data. Without either of these conditions, the education data scientist learns about the student experience by working on publicly available datasets, almost all of which are aggregated student-level datasets.</p>
<p>Before we discuss the benefits of aggregate data, let’s take some time to understand the differences between aggregate and student-level data. Publicly available data–like the US Federal Government special education student count we used in this walkthrough–is a summary of student-level data. That means that student-level data is totaled up to protect the identities of students before making them publicly available. We can use R to demonstrate this concept.</p>
<p>Here are rows in a student-level dataset:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb231-1" title="1"><span class="co"># student-level data </span></a>
<a class="sourceLine" id="cb231-2" title="2"><span class="kw">tibble</span>(</a>
<a class="sourceLine" id="cb231-3" title="3">  <span class="dt">student =</span> letters[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>],</a>
<a class="sourceLine" id="cb231-4" title="4">  <span class="dt">school =</span> <span class="kw">rep</span>(letters[<span class="dv">11</span><span class="op">:</span><span class="dv">15</span>], <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb231-5" title="5">  <span class="dt">test_score =</span> <span class="kw">sample</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">100</span>, <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb231-6" title="6">)</a></code></pre></div>
<pre><code>## # A tibble: 10 x 3
##    student school test_score
##    &lt;chr&gt;   &lt;chr&gt;       &lt;int&gt;
##  1 a       k              22
##  2 b       l              16
##  3 c       m              14
##  4 d       n              35
##  5 e       o              12
##  6 f       k              11
##  7 g       l              60
##  8 h       m               3
##  9 i       n              98
## 10 j       o              18</code></pre>
<p>Aggregate data totals up a variable–the variable <code>test_score</code> in this case–to “hide” the student-level information. The rows of the resulting dataset represent a group. The group in our example is the <code>school</code> variable:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb233-1" title="1"><span class="kw">tibble</span>(</a>
<a class="sourceLine" id="cb233-2" title="2">  <span class="dt">student =</span> letters[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>],</a>
<a class="sourceLine" id="cb233-3" title="3">  <span class="dt">school =</span> <span class="kw">rep</span>(letters[<span class="dv">11</span><span class="op">:</span><span class="dv">15</span>], <span class="dv">2</span>),</a>
<a class="sourceLine" id="cb233-4" title="4">  <span class="dt">test_score =</span> <span class="kw">sample</span>(<span class="dv">0</span><span class="op">:</span><span class="dv">100</span>, <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb233-5" title="5">) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb233-6" title="6"><span class="st">  </span><span class="co"># Aggregate by school</span></a>
<a class="sourceLine" id="cb233-7" title="7"><span class="st">  </span><span class="kw">group_by</span>(school) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb233-8" title="8"><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_score =</span> <span class="kw">mean</span>(test_score))</a></code></pre></div>
<pre><code>## # A tibble: 5 x 2
##   school mean_score
##   &lt;chr&gt;       &lt;dbl&gt;
## 1 k            74  
## 2 l            22  
## 3 m            78.5
## 4 n            36  
## 5 o            91.5</code></pre>
<p>Notice here that this dataset no longer identifies individual students.</p>
<p><em>Student-level data for analysis of local populations. Aggregate data for base rate and context.</em></p>
<p>Longitudinal analysis is typically done with student-level data because educators are interested in what happens to students over time. So if you cannot access student-level data, how do we use aggregate data to offer value to the analytic conversation?</p>
<p>Aggregate data is valuable because it allows us to learn from populations that are larger or different from the local student-level population. Think of it as an opportunity to learn from totaled up student data from other states or the whole country.</p>
<p>In the book <em>Thinking Fast and Slow</em>, <span class="citation">Kahneman (<a href="#ref-kahneman2011">2011</a>)</span> discusses the importance of learning from larger populations, a context he refers to as the base rate. The base rate fallacy is the tendency to only focus on conclusions we can draw from immediately available information. It’s the difference between computing how often a student at one school is identified for special education services (student-level data) and how often students are identified for special educations services nationally (base rate data). We can use aggregate data to combat the baserate fallacy by putting what we learn from local student data in the context of surrounding populations.</p>
<p>For example, consider an analysis of student-level data in a school district over time. Student-level data allows us to ask questions about our local population: One such question is: Are the rates of special education identification for male students different from other gender identitites <em>in our district</em>? This style of question looks <em>inward</em> at your own educational system.</p>
<p>Taking a cue from Daniel Kahneman, we should also ask what this pattern looks like in other states or in the country. Aggregate data allows us to ask questions about a larger population: One such question is Are the rates of special education identification for male students different from other gender identities <em>in the United States</em>? This style of question looks for answers <em>outside</em> your own educational system. The combination of the two lines of inquiry are powerful way to generate new knowledge about the student experience.</p>
<p>So education data scientists should not despair in situations where they cannot access student-level data. Aggregate data is a powerful way to learn from state level or national level data when an MOU for student-level data is not possible. In situations where student-level data <em>is</em> available, including aggregate data is an excellent way to combat the base rate fallacy.</p>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-healy2019">
<p>Healy, Kieran. 2019. <em>Data Visualization: A Practical Introduction</em>. Princeton University Press.</p>
</div>
<div id="ref-kahneman2011">
<p>Kahneman, Daniel. 2011. <em>Thinking Fast and Slow</em>.</p>
</div>
<div id="ref-usdoe2019">
<p>of Education, United States Department. 2020. <a href="https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/index.html#bccee">https://www2.ed.gov/programs/osepidea/618-data/state-level-data-files/index.html#bccee</a>.</p>
</div>
<div id="ref-park2016">
<p>“Reachable: Data Collection Methods for Sexual Orientation and Gender Identity.” 2016. <a href="https://williamsinstitute.law.ucla.edu/wp-content/uploads/Reachable-Data-collection-methods-for-sexual-orientation-gender-identity-March-2016.pdf](https://williamsinstitute.law.ucla.edu/wp-content/uploads/Reachable-Data-collection-methods-for-sexual-orientation-gender-identity-March-2016.pdf">https://williamsinstitute.law.ucla.edu/wp-content/uploads/Reachable-Data-collection-methods-for-sexual-orientation-gender-identity-March-2016.pdf](https://williamsinstitute.law.ucla.edu/wp-content/uploads/Reachable-Data-collection-methods-for-sexual-orientation-gender-identity-March-2016.pdf</a>.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The documentation for the dataset is available here: <a href="https://www2.ed.gov/programs/osepidea/618-data/collection-documentation/data-documentation-files/part-b/child-count-and-educational-environment/idea-partb-childcountandedenvironment-2017-18.pdf" class="uri">https://www2.ed.gov/programs/osepidea/618-data/collection-documentation/data-documentation-files/part-b/child-count-and-educational-environment/idea-partb-childcountandedenvironment-2017-18.pdf</a><a href="c10.html#fnref1" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c09.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c11.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
