<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data | Data Science in Education Using R</title>
  <meta name="description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="generator" content="bookdown 0.17 and GitBook 2.6.7" />

  <meta property="og:title" content="Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data | Data Science in Education Using R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="datascienceineducation.com/" />
  
  <meta property="og:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="github-repo" content="data-edu/data-science-in-education" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data | Data Science in Education Using R" />
  
  <meta name="twitter:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  

<meta name="author" content="Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="c11.html"/>
<link rel="next" href="c13.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-156454511-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-156454511-1');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science in Education Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prologue"><i class="fa fa-check"></i>Prologue</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citation"><i class="fa fa-check"></i>Citation</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="introduction-data-science-in-education-youre-invited-to-the-party.html"><a href="introduction-data-science-in-education-youre-invited-to-the-party.html"><i class="fa fa-check"></i>Introduction: Data Science in Education - You’re Invited to the Party!</a><ul>
<li class="chapter" data-level="" data-path="introduction-data-science-in-education-youre-invited-to-the-party.html"><a href="introduction-data-science-in-education-youre-invited-to-the-party.html#c01"><i class="fa fa-check"></i>Learning Data Science in Education</a></li>
<li class="chapter" data-level="" data-path="introduction-data-science-in-education-youre-invited-to-the-party.html"><a href="introduction-data-science-in-education-youre-invited-to-the-party.html#making-the-path-a-little-clearer"><i class="fa fa-check"></i>Making the Path a Little Clearer</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html"><i class="fa fa-check"></i>How to Use this Book</a><ul>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#different-strokes-for-different-data-scientists-in-education"><i class="fa fa-check"></i>Different Strokes for Different Data Scientists in Education</a><ul>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#read-the-book-cover-to-cover-and-how-to-keep-going"><i class="fa fa-check"></i>Read the Book Cover to Cover (and How to Keep Going)</a></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#pick-a-chapter-of-interest-and-start-there"><i class="fa fa-check"></i>Pick a Chapter of Interest and Start There</a></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#read-through-the-walkthroughs-and-run-the-code"><i class="fa fa-check"></i>Read Through the Walkthroughs and Run the Code</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#a-note-on-statistics"><i class="fa fa-check"></i>A Note on Statistics</a></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#what-this-book-is-not-about"><i class="fa fa-check"></i>What This Book Is Not About</a></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#supporting-the-book"><i class="fa fa-check"></i>Supporting the Book</a></li>
<li class="chapter" data-level="" data-path="c02.html"><a href="c02.html#contributing-to-the-book"><i class="fa fa-check"></i>Contributing to the Book</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html"><i class="fa fa-check"></i>What Does Data Science in Education Look Like?</a><ul>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#data-roles-in-education"><i class="fa fa-check"></i>Data Roles in Education</a><ul>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#building-systems-that-get-data-to-the-right-people"><i class="fa fa-check"></i>Building Systems That Get Data to the Right People</a></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#measuring-the-impact-of-our-work-on-the-student-experience"><i class="fa fa-check"></i>Measuring the Impact of Our Work on the Student Experience</a></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#looking-for-patterns-in-student-data"><i class="fa fa-check"></i>Looking for Patterns in Student Data</a></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#improving-how-we-use-statistical-models-in-education"><i class="fa fa-check"></i>Improving How We Use Statistical Models in Education</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#common-activities-of-data-scientists"><i class="fa fa-check"></i>Common Activities of Data Scientists</a><ul>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#processing-data"><i class="fa fa-check"></i>Processing Data</a></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#doing-analysis"><i class="fa fa-check"></i>Doing Analysis</a></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#sharing-results"><i class="fa fa-check"></i>Sharing Results</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#who-we-are-and-what-we-do"><i class="fa fa-check"></i>Who We Are and What We Do</a></li>
<li class="chapter" data-level="" data-path="c03.html"><a href="c03.html#next-steps-for-data-science-in-education"><i class="fa fa-check"></i>Next Steps for Data Science in Education</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html"><i class="fa fa-check"></i>Special Considerations</a><ul>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-any-domain"><i class="fa fa-check"></i>Things to Consider when Doing Data Science in any Domain</a><ul>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#learning-to-code"><i class="fa fa-check"></i>Learning to Code</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#addressing-ambiguity-a-reproducible-approach"><i class="fa fa-check"></i>Addressing Ambiguity: A Reproducible Approach</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-education"><i class="fa fa-check"></i>Things to Consider when Doing Data Science in Education</a><ul>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#addressing-organizational-resistance-a-self-driven-analytic-approach"><i class="fa fa-check"></i>Addressing Organizational Resistance: A Self-Driven Analytic Approach</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#lack-of-processes-and-guidelines"><i class="fa fa-check"></i>Lack of Processes and Guidelines</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#limited-training-and-educational-opportunities"><i class="fa fa-check"></i>Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#advancing-equity"><i class="fa fa-check"></i>Advancing Equity</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#the-complex-nature-of-education-data"><i class="fa fa-check"></i>The Complex Nature of Education Data</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#ethical-and-legal-concerns"><i class="fa fa-check"></i>Ethical and Legal Concerns</a></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#analytic-considerations"><i class="fa fa-check"></i>Analytic Considerations</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c04.html"><a href="c04.html#conclusion"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html"><i class="fa fa-check"></i>Getting Started with R and RStudio</a><ul>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#chapter-overview"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#downloading-r-and-rstudio"><i class="fa fa-check"></i>Downloading R and RStudio</a><ul>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#to-download-r"><i class="fa fa-check"></i>To Download R:</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#to-download-rstudio"><i class="fa fa-check"></i>To Download RStudio:</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#rstudio-layout-and-customization-getting-to-know-r-through-rstudio"><i class="fa fa-check"></i>RStudio Layout and Customization: Getting to Know R through RStudio</a><ul>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#rstudio-layout"><i class="fa fa-check"></i>RStudio layout</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#customizing-rstudio"><i class="fa fa-check"></i>Customizing RStudio</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#minimized-and-missing-panes"><i class="fa fa-check"></i>Minimized and Missing Panes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#writing-and-running-code-in-rstudio"><i class="fa fa-check"></i>Writing and Running Code in RStudio</a><ul>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#writing-code-in-the-console"><i class="fa fa-check"></i>Writing Code in the Console</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#writing-code-in-an-r-script"><i class="fa fa-check"></i>Writing Code in an R Script</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#commenting-your-code-in-r"><i class="fa fa-check"></i>Commenting Your Code in R</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#installing-the-dataedu-package"><i class="fa fa-check"></i>Installing the {dataedu} package</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#exploring-r-with-the-swirl-package"><i class="fa fa-check"></i>Exploring R with the {swirl} package</a></li>
<li class="chapter" data-level="" data-path="c05.html"><a href="c05.html#conclusion-1"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html"><i class="fa fa-check"></i>Foundational Skills</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#chapter-overview-1"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#foundational-skills-framework"><i class="fa fa-check"></i>Foundational Skills Framework</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#projects"><i class="fa fa-check"></i>Projects</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#the-here-package"><i class="fa fa-check"></i>The {here} package</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#packages"><i class="fa fa-check"></i>Packages</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#installing-and-loading-a-package"><i class="fa fa-check"></i>Installing and Loading a package</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#how-to-find-a-package"><i class="fa fa-check"></i>How to Find a Package</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#how-to-learn-more-about-a-package"><i class="fa fa-check"></i>How to Learn More About a Package</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#functions"><i class="fa fa-check"></i>Functions</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#the-relationship-between-packages-and-functions"><i class="fa fa-check"></i>The Relationship Between Packages and Functions</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#verb-based-functions"><i class="fa fa-check"></i>Verb-Based Functions</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#when-functions-need-arguments-and-when-they-dont"><i class="fa fa-check"></i>When Functions Need Arguments and When They Don’t</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#functions-within-functions"><i class="fa fa-check"></i>Functions within Functions</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#writing-your-own-functions"><i class="fa fa-check"></i>Writing Your Own Functions</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#data"><i class="fa fa-check"></i>Data</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#data-types"><i class="fa fa-check"></i>Data Types</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#introduction-to-help-documentation"><i class="fa fa-check"></i>Introduction to Help Documentation</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#steps-for-working-through-new-and-unfamiliar-content"><i class="fa fa-check"></i>Steps for working through new and unfamiliar content</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#code-walkthrough"><i class="fa fa-check"></i>CODE WALKTHROUGH</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#run-this-code"><i class="fa fa-check"></i>Run This Code</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#function-conflicts-between-packages"><i class="fa fa-check"></i>Function Conflicts between Packages</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#installing-the-dataedu-package-using-devtools"><i class="fa fa-check"></i>Installing the {dataedu} package using {devtools}</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#mass-installation-of-packages"><i class="fa fa-check"></i>Mass Installation of Packages</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#downloading-and-accessing-the-datasets-used-in-this-book"><i class="fa fa-check"></i>Downloading and Accessing the Datasets Used in this Book</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#assigning-data-to-a-variableeverythings-an-object"><i class="fa fa-check"></i>Assigning Data to a Variable//Everything’s An Object!</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#run-this-code-1"><i class="fa fa-check"></i>Run this Code</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#the-assignment-operator"><i class="fa fa-check"></i>The Assignment Operator</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#reading-code-and-writing-functions---this-is-a-bad-title"><i class="fa fa-check"></i>Reading Code and Writing Functions - THIS IS A BAD TITLE</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#run-this-code-2"><i class="fa fa-check"></i>Run This Code</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#common-errors-typos-spaces-and-parentheses"><i class="fa fa-check"></i>Common Errors: Typos, Spaces, and Parentheses</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#closing-your-parentheses"><i class="fa fa-check"></i>Closing your parentheses</a></li>
<li><a href="c06.html#the-operator">The <code>$</code> Operator</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#the-pipe-operator"><i class="fa fa-check"></i>The Pipe Operator</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#run-this-code-3"><i class="fa fa-check"></i>Run This Code</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#reading-code"><i class="fa fa-check"></i>“Reading” Code</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#assignment-vs.-equality"><i class="fa fa-check"></i>Assignment vs. Equality</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#run-this-code-4"><i class="fa fa-check"></i>Run This Code</a></li>
<li><a href="c06.html#the-difference-between-and">The Difference Between <code>=</code> and <code>==</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#basics-of-names"><i class="fa fa-check"></i>Basics of Names</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#run-this-code-5"><i class="fa fa-check"></i>Run This Code</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#conclusion-2"><i class="fa fa-check"></i>Conclusion</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#technical-appendix-a"><i class="fa fa-check"></i>Technical Appendix A</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#using-functions-to-import-data"><i class="fa fa-check"></i>Using Functions to Import Data</a><ul>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#saving-a-file-from-the-web"><i class="fa fa-check"></i>Saving a File from the Web</a></li>
<li><a href="c06.html#loading-a-.csv-file">Loading a <code>.csv</code> File</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#saving-files"><i class="fa fa-check"></i>Saving Files</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#loading-excel-files"><i class="fa fa-check"></i>Loading Excel Files</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#loading-sav-files"><i class="fa fa-check"></i>Loading SAV Files</a></li>
<li class="chapter" data-level="" data-path="c06.html"><a href="c06.html#google-sheets"><i class="fa fa-check"></i>Google Sheets</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html"><i class="fa fa-check"></i>Walkthrough 1: The Education Data Science Pipeline With Online Science Class Data</a><ul>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#introduction-to-the-walkthroughs"><i class="fa fa-check"></i>Introduction to the walkthroughs</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#vocabulary"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#chapter-overview-2"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#background"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#data-sources"><i class="fa fa-check"></i>Data Sources</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#data-source-2-log-trace-data"><i class="fa fa-check"></i>Data Source #2: Log-Trace Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#data-source-3-achievement-related-and-gradebook-data"><i class="fa fa-check"></i>Data Source #3: Achievement-Related and Gradebook Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#data-source-4-discussion-board-data"><i class="fa fa-check"></i>Data Source #4: Discussion Board Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#methods"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#load-packages"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#import-data"><i class="fa fa-check"></i>Import Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#view-data"><i class="fa fa-check"></i>View Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#process-data"><i class="fa fa-check"></i>Process Data</a><ul>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#processing-the-course-data"><i class="fa fa-check"></i>Processing the Course Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#joining-the-data"><i class="fa fa-check"></i>Joining the Data</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#finding-distinct-cases-at-the-student-level"><i class="fa fa-check"></i>Finding Distinct Cases at the Student-Level</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#analysis"><i class="fa fa-check"></i>Analysis</a><ul>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#about-ggplot2"><i class="fa fa-check"></i>About {ggplot2}</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#the-relationship-between-time-spent-on-course-and-percentage-of-points-earned"><i class="fa fa-check"></i>The Relationship between Time Spent on Course and Percentage of Points Earned</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#linear-model-regression"><i class="fa fa-check"></i>Linear Model (Regression)</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#results"><i class="fa fa-check"></i>Results</a></li>
<li class="chapter" data-level="" data-path="c07.html"><a href="c07.html#conclusion-3"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html"><i class="fa fa-check"></i>Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective</a><ul>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#vocabulary-1"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#chapter-overview-3"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#background-1"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#data-sources-1"><i class="fa fa-check"></i>Data Sources</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#methods-1"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#load-packages-1"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#import-data-1"><i class="fa fa-check"></i>Import Data</a><ul>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#import-using-a-file-path"><i class="fa fa-check"></i>Import Using a File Path</a></li>
<li><a href="c08.html#import-using-here">Import Using <code>here()</code></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#process-data-1"><i class="fa fa-check"></i>Process Data</a><ul>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#tidy-data"><i class="fa fa-check"></i>Tidy Data</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#about-janitor"><i class="fa fa-check"></i>About {janitor}</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#create-new-variables-and-further-process-the-data"><i class="fa fa-check"></i>Create new variables and further process the data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#analysis-1"><i class="fa fa-check"></i>Analysis</a><ul>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#visualize-data"><i class="fa fa-check"></i>Visualize Data</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#model-data"><i class="fa fa-check"></i>Model Data</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#correlation-analysis"><i class="fa fa-check"></i>Correlation Analysis</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#results-1"><i class="fa fa-check"></i>Results</a></li>
<li class="chapter" data-level="" data-path="c08.html"><a href="c08.html#conclusion-4"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html"><i class="fa fa-check"></i>Walkthrough 3: Using School-Level Aggregate Data to Illuminate Educational Inequities</a><ul>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#vocabulary-2"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#chapter-overview-4"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#background-2"><i class="fa fa-check"></i>Background</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#data-sources-2"><i class="fa fa-check"></i>Data Sources</a><ul>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#methods-2"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#load-packages-2"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#import-data-2"><i class="fa fa-check"></i>Import Data</a></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#view-data-1"><i class="fa fa-check"></i>View Data</a><ul>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#discovering-distributions"><i class="fa fa-check"></i>Discovering Distributions</a></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#analyzing-spread"><i class="fa fa-check"></i>Analyzing Spread</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#analysis-2"><i class="fa fa-check"></i>Analysis</a><ul>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#creating-categories"><i class="fa fa-check"></i>Creating Categories</a></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#reveal-relationships"><i class="fa fa-check"></i>Reveal Relationships</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#results-2"><i class="fa fa-check"></i>Results</a></li>
<li class="chapter" data-level="" data-path="c09.html"><a href="c09.html#conclusion-5"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html"><i class="fa fa-check"></i>Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data</a><ul>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#vocabulary-3"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#chapter-overview-5"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#background-3"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#methods-3"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#load-packages-3"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#import-data-3"><i class="fa fa-check"></i>Import Data</a><ul>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#what-to-download"><i class="fa fa-check"></i>What to Download</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#a-note-on-file-paths"><i class="fa fa-check"></i>A Note on File Paths</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#reading-in-one-dataset"><i class="fa fa-check"></i>Reading in One Dataset</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#reading-in-many-datasets"><i class="fa fa-check"></i>Reading in Many Datasets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#process-data-2"><i class="fa fa-check"></i>Process Data</a><ul>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#fix-the-variable-names-in-the-2016-data"><i class="fa fa-check"></i>Fix the Variable Names in the 2016 Data</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#pick-variables"><i class="fa fa-check"></i>Pick Variables</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#combine-six-datasets-into-one"><i class="fa fa-check"></i>Combine Six Datasets into One</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#filter-for-the-desired-disabilities-and-age-groups"><i class="fa fa-check"></i>Filter for the Desired Disabilities and Age Groups</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#rename-the-variables"><i class="fa fa-check"></i>Rename the Variables</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#clean-state-names"><i class="fa fa-check"></i>Clean State Names</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#tidy-the-dataset"><i class="fa fa-check"></i>Tidy the Dataset</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#convert-data-types"><i class="fa fa-check"></i>Convert Data Types</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#explore-and-address-nas"><i class="fa fa-check"></i>Explore and Address NAs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#analysis-3"><i class="fa fa-check"></i>Analysis</a><ul>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#visualize-the-dataset"><i class="fa fa-check"></i>Visualize the Dataset</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#model-the-dataset"><i class="fa fa-check"></i>Model the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#results-3"><i class="fa fa-check"></i>Results</a></li>
<li class="chapter" data-level="" data-path="c10.html"><a href="c10.html#conclusion-6"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html"><i class="fa fa-check"></i>Walkthrough 5: Text Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#vocabulary-4"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#chapter-overview-6"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#background-4"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#data-source"><i class="fa fa-check"></i>Data Source</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#methods-4"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#load-packages-4"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#import-data-4"><i class="fa fa-check"></i>Import Data</a><ul>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#using-an-api"><i class="fa fa-check"></i>Using an API</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#view-data-2"><i class="fa fa-check"></i>View Data</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#process-data-3"><i class="fa fa-check"></i>Process Data</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#analysis-counting-words"><i class="fa fa-check"></i>Analysis: Counting Words</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#analysis-sentiment-analysis"><i class="fa fa-check"></i>Analysis: Sentiment analysis</a><ul>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#count-positive-words"><i class="fa fa-check"></i>Count Positive Words</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#dataviz-and-other-positive-words"><i class="fa fa-check"></i>Dataviz and Other Positive Words</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#close-read-of-randomly-selected-tweets"><i class="fa fa-check"></i>Close Read of Randomly Selected Tweets</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#conclusion-7"><i class="fa fa-check"></i>Conclusion</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#technical-appendix-accessing-twitter-data"><i class="fa fa-check"></i>Technical Appendix: Accessing Twitter data</a><ul>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#accessing-historical-twitter-data-using-already-collected-status-urls"><i class="fa fa-check"></i>Accessing Historical Twitter Data Using Already-Collected Status URLs</a></li>
<li class="chapter" data-level="" data-path="c11.html"><a href="c11.html#accessing-historical-data-when-you-do-not-have-access-to-status-urls"><i class="fa fa-check"></i>Accessing Historical Data When You Do Not Have Access to Status URLs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html"><i class="fa fa-check"></i>Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#vocabulary-5"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#chapter-overview-7"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#background-5"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#packages-data-sources-and-import-and-methods"><i class="fa fa-check"></i>Packages, Data Sources and Import, and Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#view-data-3"><i class="fa fa-check"></i>View Data</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#process-data-4"><i class="fa fa-check"></i>Process Data</a><ul>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#extracting-mentions"><i class="fa fa-check"></i>Extracting Mentions</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#putting-the-edgelist-together"><i class="fa fa-check"></i>Putting the Edgelist Together</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#analysis-and-results"><i class="fa fa-check"></i>Analysis and Results</a><ul>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#plotting-the-network"><i class="fa fa-check"></i>Plotting the Network</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#conclusion-8"><i class="fa fa-check"></i>Conclusion</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#technical-appendix-influence-and-selection-models"><i class="fa fa-check"></i>Technical Appendix: Influence and Selection Models</a><ul>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#an-example-of-influence"><i class="fa fa-check"></i>An Example of Influence</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#joining-the-data-1"><i class="fa fa-check"></i>Joining the Data</a></li>
<li class="chapter" data-level="" data-path="c12.html"><a href="c12.html#an-example-of-selection"><i class="fa fa-check"></i>An Example of Selection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html"><i class="fa fa-check"></i>Walkthrough 7: The Role (and Usefulness) of Multi-Level Models</a><ul>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#vocabulary-6"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#chapter-overview-8"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#background-6"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#data-source-1"><i class="fa fa-check"></i>Data Source</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#methods-5"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#load-packages-5"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#import-data-5"><i class="fa fa-check"></i>Import Data</a><ul>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#the-role-of-dummy-codes"><i class="fa fa-check"></i>The Role of Dummy Codes</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#using-dummy-codes"><i class="fa fa-check"></i>Using Dummy Codes</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#analysis-4"><i class="fa fa-check"></i>Analysis</a><ul>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#regression-linear-model-analysis-with-dummy-codes"><i class="fa fa-check"></i>Regression (Linear Model) Analysis with Dummy Codes</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#a-deep-dive-into-multi-level-models"><i class="fa fa-check"></i>A Deep-Dive into Multi-Level Models</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#multi-level-model-analysis"><i class="fa fa-check"></i>Multi-level model analysis</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#results-4"><i class="fa fa-check"></i>Results</a></li>
<li class="chapter" data-level="" data-path="c13.html"><a href="c13.html#conclusion-9"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html"><i class="fa fa-check"></i>Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data</a><ul>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#vocabulary-7"><i class="fa fa-check"></i>Vocabulary</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#chapter-overview-9"><i class="fa fa-check"></i>Chapter Overview</a><ul>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#background-7"><i class="fa fa-check"></i>Background</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#data-sources-3"><i class="fa fa-check"></i>Data Sources</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#methods-6"><i class="fa fa-check"></i>Methods</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#load-packages-6"><i class="fa fa-check"></i>Load Packages</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#import-and-view-data"><i class="fa fa-check"></i>Import and View Data</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#process-data-5"><i class="fa fa-check"></i>Process Data</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#analysis-5"><i class="fa fa-check"></i>Analysis</a><ul>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#use-of-caret"><i class="fa fa-check"></i>Use of {caret}</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#tuning-the-random-forest-model"><i class="fa fa-check"></i>Tuning the random forest model</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#examining-predictive-accuracy-on-the-test-data-set"><i class="fa fa-check"></i>Examining predictive accuracy on the test data set</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#results-5"><i class="fa fa-check"></i>Results</a><ul>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#variable-importance-measures"><i class="fa fa-check"></i>Variable Importance Measures</a></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#comparing-a-random-forest-to-a-regression"><i class="fa fa-check"></i>Comparing a random forest to a regression</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c14.html"><a href="c14.html#conclusion-10"><i class="fa fa-check"></i>Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html"><i class="fa fa-check"></i>Introducing Data Science Tools To Your Education Job</a><ul>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#introduction"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#the-gift-of-speed-and-scale"><i class="fa fa-check"></i>The Gift of Speed and Scale</a><ul>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#working-with-data-faster"><i class="fa fa-check"></i>Working With Data Faster</a></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#working-with-more-data"><i class="fa fa-check"></i>Working With More Data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#other-ways-to-reimagine-the-scale-of-your-work"><i class="fa fa-check"></i>Other Ways to Reimagine the Scale of Your Work</a><ul>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#reflect-on-your-current-scale-then-push-to-the-next-level"><i class="fa fa-check"></i>Reflect on your current scale, then push to the next level</a></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#look-for-lots-of-similarly-structured-data"><i class="fa fa-check"></i>Look for lots of similarly structured data</a></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#cleaning-data"><i class="fa fa-check"></i>Cleaning data</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#solving-problems-together"><i class="fa fa-check"></i>Solving Problems Together</a><ul>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#data-science-in-education-and-empathy"><i class="fa fa-check"></i>Data Science in Education and Empathy</a></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#create-a-daily-practice-commitment-that-answers-someone-elses-question"><i class="fa fa-check"></i>Create a Daily Practice Commitment That Answers Someone Else’s Question</a></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#build-your-network"><i class="fa fa-check"></i>Build Your Network</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c15.html"><a href="c15.html#for-k-12-teachers"><i class="fa fa-check"></i>For K-12 Teachers</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html"><i class="fa fa-check"></i>Teaching Data Science</a><ul>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#the-pedagogical-principles-this-book-is-based-upon"><i class="fa fa-check"></i>The pedagogical principles this book is based upon</a><ul>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#problem-based-learning"><i class="fa fa-check"></i>Problem-based learning</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#differentiation"><i class="fa fa-check"></i>Differentiation</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#universal-design"><i class="fa fa-check"></i>Universal Design</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#working-in-the-open"><i class="fa fa-check"></i>Working in the Open</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#strategies-for-teaching-data-science"><i class="fa fa-check"></i>Strategies for teaching data science</a><ul>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#provide-a-home-base-for-learners-to-access-resources-and-to-learn-more"><i class="fa fa-check"></i>Provide a home base for learners to access resources (and to learn more)</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#when-it-comes-to-writing-code-think-early-and-often"><i class="fa fa-check"></i>When it comes to writing code, think early and often</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#dont-touch-that-keyboard"><i class="fa fa-check"></i>Don’t touch that keyboard!</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#anticipate-issues-and-sacrifice-accuracy-for-clarity"><i class="fa fa-check"></i>Anticipate issues (and sacrifice accuracy for clarity)</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#start-lessons-or-activities-with-visualizing-data"><i class="fa fa-check"></i>Start lessons or activities with visualizing data</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#consider-representation-in-the-data-and-examples-you-use"><i class="fa fa-check"></i>Consider representation in the data and examples you use</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#draw-on-other-resources"><i class="fa fa-check"></i>Draw on other resources</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#general-strategies-related-to-teaching-and-learning"><i class="fa fa-check"></i>General strategies related to teaching and learning</a><ul>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#teaching-and-learning-are-complex"><i class="fa fa-check"></i>Teaching and learning are complex</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#learners-learn-many-different-things-consciously-and-unconsciously"><i class="fa fa-check"></i>Learners learn many different things (consciously and unconsciously)</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#metacognition-is-important-even-though-it-sounds-more-sophisticated-than-it-is"><i class="fa fa-check"></i>Metacognition is important (even though it sounds more sophisticated than it is!)</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#learning-strategies-matter"><i class="fa fa-check"></i>Learning strategies matter</a></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#educators-can-help-students-to-learn"><i class="fa fa-check"></i>Educators can help students to learn</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c16.html"><a href="c16.html#summary"><i class="fa fa-check"></i>Summary</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html"><i class="fa fa-check"></i>Learning More</a><ul>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#introduction-1"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#adopt-a-growth-mindset"><i class="fa fa-check"></i>Adopt a Growth Mindset</a></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#discover-new-information"><i class="fa fa-check"></i>Discover New Information</a></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#ask-for-help"><i class="fa fa-check"></i>Ask for Help</a><ul>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#discussion-forums"><i class="fa fa-check"></i>Discussion forums</a></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#github-repositories"><i class="fa fa-check"></i>GitHub repositories</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#share-what-youve-learned"><i class="fa fa-check"></i>Share what you’ve learned</a><ul>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#where-to-share"><i class="fa fa-check"></i>Where to share</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c17.html"><a href="c17.html#welcome-others"><i class="fa fa-check"></i>Welcome others</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html"><i class="fa fa-check"></i>Additional Resources</a><ul>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#chapter-overview-10"><i class="fa fa-check"></i>Chapter Overview</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#data-science-courses"><i class="fa fa-check"></i>Data science courses</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#workshop-materials"><i class="fa fa-check"></i>Workshop materials</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#data-visualization"><i class="fa fa-check"></i>Data visualization</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#books-related-to-data-science-in-education"><i class="fa fa-check"></i>Books related to data science in education</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#articles-related-to-data-science-in-education"><i class="fa fa-check"></i>Articles related to data science in education</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#programming-with-r"><i class="fa fa-check"></i>Programming with R</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#package-vignettes-and-descriptions-of-packages"><i class="fa fa-check"></i>Package vignettes and descriptions of packages</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#statistics"><i class="fa fa-check"></i>Statistics</a><ul>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#introductory-statistics"><i class="fa fa-check"></i>Introductory Statistics</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#advanced-statistics"><i class="fa fa-check"></i>Advanced Statistics</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#r-packages-and-statistical-software-development"><i class="fa fa-check"></i>R packages and statistical software development</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#a-career-in-data-science"><i class="fa fa-check"></i>A career in data science</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#places-to-share-your-work"><i class="fa fa-check"></i>Places to share your work</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#cheat-sheets"><i class="fa fa-check"></i>Cheat Sheets</a></li>
<li class="chapter" data-level="" data-path="c18.html"><a href="c18.html#learning-communities"><i class="fa fa-check"></i>Learning communities</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="c19.html"><a href="c19.html"><i class="fa fa-check"></i>Conclusion: Where to next?</a><ul>
<li class="chapter" data-level="" data-path="c19.html"><a href="c19.html#learn-in-the-context-of-education"><i class="fa fa-check"></i>Learn in the Context of Education</a></li>
<li class="chapter" data-level="" data-path="c19.html"><a href="c19.html#learn-to-collaborate-with-others"><i class="fa fa-check"></i>Learn to Collaborate With Others</a></li>
<li class="chapter" data-level="" data-path="c19.html"><a href="c19.html#learn-every-time-you-code"><i class="fa fa-check"></i>Learn Every Time You Code</a></li>
<li class="chapter" data-level="" data-path="c19.html"><a href="c19.html#learn-to-take-strategic-breaks-to-help-solve-problems"><i class="fa fa-check"></i>Learn to Take Strategic Breaks to Help Solve Problems</a></li>
<li class="chapter" data-level="" data-path="c19.html"><a href="c19.html#learn-more-meaningfully-by-knowing-your-why"><i class="fa fa-check"></i>Learn More Meaningfully By Knowing Your Why</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://www.emilybovee.com/">Emily A. Bovee</a></li>
<li><a href="https://ryanestrellado.netlify.com/">Ryan A. Estrellado</a></li>
<li><a href="https://www.jessemaegan.com/">Jesse Mostipak</a></li>
<li><a href="https://joshuamrosenberg.com/">Joshua M. Rosenberg</a></li>
<li><a href="https://ivelasq.rbind.io/">Isabella C. Velásquez</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science in Education Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c12" class="section level1">
<h1>Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data</h1>
<div id="vocabulary-5" class="section level2">
<h2>Vocabulary</h2>
<ul>
<li>Application Programming Interface (API)</li>
<li>edgelist</li>
<li>edge</li>
<li>influence model</li>
<li>regex</li>
<li>selection model</li>
<li>social network analysis</li>
<li>sociogram</li>
<li>vertex</li>
</ul>
</div>
<div id="chapter-overview-7" class="section level2">
<h2>Chapter Overview</h2>
<p>This chapter builds upon [Walkthrough 5/Chapter 11]](#c11) of #tidytuesday data. Whereas the previous chapter was focused on using text analysis to understand the <em>content</em> of tweets, this chapter focuses on the <em>interactions</em> between #tidytuesday participants. Thus, this chapter explores the use of social network analysis techniques. We note that this chapter, like the previous chapter, includes a technical appendix: This chapter’s technical appendix is focused on two social network processes, selection and influence, that are not the focus of this chapter, but are feasible to investigate using R, and so are, we think, worth introducing as a topic for further reading and study.</p>
<div id="background-5" class="section level3">
<h3>Background</h3>
<p>There are a few reasons to be interested in social media. For example, if you work in a school district, you may be interested in who is interacting with the content you share. If you are a researcher, you may wish to investigate what teachers, administrators, and others do through state-based hashtags (e.g., <span class="citation">Rosenberg et al. (<a href="references.html#ref-rosenberg2016">2016</a>)</span>). Social media-based data can also be interesting because it provides new contexts for learning to take place, such as professional learning networks <span class="citation">(Trust et al., <a href="references.html#ref-trust2016">2016</a>)</span>.</p>
<p>In the past, if a teacher wanted advice about how to plan a unit or to design a lesson, they would likely turn to a trusted peer in their building or district <span class="citation">(Spillane et al., <a href="references.html#ref-spillane2012">2012</a>)</span>. In the present, though, they are as likely to turn to someone in a social media-based network. Thus, while the kinds of interactions that take place through #tidytuesday do represent a new context for individuals to communicate and share, it is the kind of network that is becoming increasingly common in education, and, so, being able to use a data science approach to understand the nature of the activity that takes places through #tidytuesday is a potentially valuable capability.</p>
</div>
<div id="packages-data-sources-and-import-and-methods" class="section level3">
<h3>Packages, Data Sources and Import, and Methods</h3>
<p>In this chapter, we access data using the {rtweet} package <span class="citation">(Kearney, <a href="references.html#ref-kearney2016">2016</a>)</span>. Through {rtweet}, it is easy to access data from Twitter as long as one has a Twitter account. We will load the {tidyverse} and {rtweet} packages to get started. Here is an example of searching the most recent 1,000 tweets which include the hashtag #rstats. When you run this code, you will be prompted to authenticate your access via Twitter. We will also load other packages that we will be using in this analysis, including two packages related to social network analysis <span class="citation">(<span class="citeproc-not-found" data-reference-id="R-tidygraph"><strong>???</strong></span>, <span class="citation">@R-ggraph</span>)</span> as well as one that will help us to use not-anonymized names in a savvy way <span class="citation">(<span class="citeproc-not-found" data-reference-id="R-randomNames"><strong>???</strong></span>)</span>.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb279-2" title="2"><span class="kw">library</span>(rtweet)</a>
<a class="sourceLine" id="cb279-3" title="3"><span class="kw">library</span>(dataedu)</a>
<a class="sourceLine" id="cb279-4" title="4"><span class="kw">library</span>(randomNames)</a>
<a class="sourceLine" id="cb279-5" title="5"><span class="kw">library</span>(tidygraph)</a>
<a class="sourceLine" id="cb279-6" title="6"><span class="kw">library</span>(ggraph)</a></code></pre></div>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb280-1" title="1">rstats_tweets &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb280-2" title="2"><span class="st">  </span><span class="kw">search_tweets</span>(<span class="st">&quot;#rstats&quot;</span>)</a></code></pre></div>
<p>As described in <a href="c11.html#c11">the previous chapter</a>, the search term can be easily changed to other hashtags - or other terms. To search for #tidytuesday tweets, we can simply replace #rstats with #tidytuesday.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1">tidytuesday_tweets &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb281-2" title="2"><span class="st">  </span><span class="kw">search_tweets</span>(<span class="st">&quot;#tidytuesday&quot;</span>)</a></code></pre></div>
</div>
</div>
<div id="view-data-3" class="section level2">
<h2>View Data</h2>
<p>We can see that there are <em>many</em> rows for the data:</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb282-1" title="1">tt_tweets</a></code></pre></div>
<pre><code>#&gt; # A tibble: 4,418 x 90
#&gt;    user_id status_id created_at          screen_name text  source
#&gt;    &lt;chr&gt;   &lt;chr&gt;     &lt;dttm&gt;              &lt;chr&gt;       &lt;chr&gt; &lt;chr&gt; 
#&gt;  1 115921… 11631542… 2019-08-18 18:22:42 MKumarYYC   &quot;Fir… Twitt…
#&gt;  2 107332… 11632475… 2019-08-19 00:33:11 cizzart     &quot;El … Twitt…
#&gt;  3 107332… 11450435… 2019-06-29 18:57:17 cizzart     &quot;Pro… Twitt…
#&gt;  4 107332… 11168648… 2019-04-13 00:45:15 cizzart     &quot;#Ar… Twitt…
#&gt;  5 107332… 11228824… 2019-04-29 15:17:02 cizzart     &quot;Pes… Twitt…
#&gt;  6 107332… 11176387… 2019-04-15 04:00:17 cizzart     &quot;Dat… Twitt…
#&gt;  7 107332… 11245531… 2019-05-04 05:55:32 cizzart     &quot;El … Twitt…
#&gt;  8 107332… 11407021… 2019-06-17 19:25:50 cizzart     &quot;#da… Twitt…
#&gt;  9 107332… 11325299… 2019-05-26 06:12:46 cizzart     &quot;El … Twitt…
#&gt; 10 107332… 11233585… 2019-04-30 22:48:43 cizzart     &quot;Vis… Twitt…
#&gt; # … with 4,408 more rows, and 84 more variables: display_text_width &lt;dbl&gt;,
#&gt; #   reply_to_status_id &lt;chr&gt;, reply_to_user_id &lt;chr&gt;,
#&gt; #   reply_to_screen_name &lt;chr&gt;, is_quote &lt;lgl&gt;, is_retweet &lt;lgl&gt;,
#&gt; #   favorite_count &lt;int&gt;, retweet_count &lt;int&gt;, quote_count &lt;int&gt;,
#&gt; #   reply_count &lt;int&gt;, hashtags &lt;list&gt;, symbols &lt;list&gt;, urls_url &lt;list&gt;,
#&gt; #   urls_t.co &lt;list&gt;, urls_expanded_url &lt;list&gt;, media_url &lt;list&gt;,
#&gt; #   media_t.co &lt;list&gt;, media_expanded_url &lt;list&gt;, media_type &lt;list&gt;,
#&gt; #   ext_media_url &lt;list&gt;, ext_media_t.co &lt;list&gt;, ext_media_expanded_url &lt;list&gt;,
#&gt; #   ext_media_type &lt;chr&gt;, mentions_user_id &lt;list&gt;, mentions_screen_name &lt;list&gt;,
#&gt; #   lang &lt;chr&gt;, quoted_status_id &lt;chr&gt;, quoted_text &lt;chr&gt;,
#&gt; #   quoted_created_at &lt;dttm&gt;, quoted_source &lt;chr&gt;, quoted_favorite_count &lt;int&gt;,
#&gt; #   quoted_retweet_count &lt;int&gt;, quoted_user_id &lt;chr&gt;, quoted_screen_name &lt;chr&gt;,
#&gt; #   quoted_name &lt;chr&gt;, quoted_followers_count &lt;int&gt;,
#&gt; #   quoted_friends_count &lt;int&gt;, quoted_statuses_count &lt;int&gt;,
#&gt; #   quoted_location &lt;chr&gt;, quoted_description &lt;chr&gt;, quoted_verified &lt;lgl&gt;,
#&gt; #   retweet_status_id &lt;chr&gt;, retweet_text &lt;chr&gt;, retweet_created_at &lt;dttm&gt;,
#&gt; #   retweet_source &lt;chr&gt;, retweet_favorite_count &lt;int&gt;,
#&gt; #   retweet_retweet_count &lt;int&gt;, retweet_user_id &lt;chr&gt;,
#&gt; #   retweet_screen_name &lt;chr&gt;, retweet_name &lt;chr&gt;,
#&gt; #   retweet_followers_count &lt;int&gt;, retweet_friends_count &lt;int&gt;,
#&gt; #   retweet_statuses_count &lt;int&gt;, retweet_location &lt;chr&gt;,
#&gt; #   retweet_description &lt;chr&gt;, retweet_verified &lt;lgl&gt;, place_url &lt;chr&gt;,
#&gt; #   place_name &lt;chr&gt;, place_full_name &lt;chr&gt;, place_type &lt;chr&gt;, country &lt;chr&gt;,
#&gt; #   country_code &lt;chr&gt;, geo_coords &lt;list&gt;, coords_coords &lt;list&gt;,
#&gt; #   bbox_coords &lt;list&gt;, status_url &lt;chr&gt;, name &lt;chr&gt;, location &lt;chr&gt;,
#&gt; #   description &lt;chr&gt;, url &lt;chr&gt;, protected &lt;lgl&gt;, followers_count &lt;int&gt;,
#&gt; #   friends_count &lt;int&gt;, listed_count &lt;int&gt;, statuses_count &lt;int&gt;,
#&gt; #   favourites_count &lt;int&gt;, account_created_at &lt;dttm&gt;, verified &lt;lgl&gt;,
#&gt; #   profile_url &lt;chr&gt;, profile_expanded_url &lt;chr&gt;, account_lang &lt;lgl&gt;,
#&gt; #   profile_banner_url &lt;chr&gt;, profile_background_url &lt;chr&gt;,
#&gt; #   profile_image_url &lt;chr&gt;</code></pre>
</div>
<div id="process-data-4" class="section level2">
<h2>Process Data</h2>
<p>Network data, in general, and network data from Twitter, particularly, requires some processing before it can be used in subsequent analyses. In particular, we are going to create an edgelist, a data structure that is especially helpful for understanding the nature of relationships.</p>
<p>An edgelist looks like the following, where the sender denotes who is initiating the interaction or relationship, and the receiver is who is the recipient of it:</p>
<pre><code>#&gt; # A tibble: 12 x 2
#&gt;    sender             receiver           
#&gt;    &lt;chr&gt;              &lt;chr&gt;              
#&gt;  1 Pham, Pa Nhia      Wojtowick, Gary    
#&gt;  2 Davis, Segan       Duenez, Aureliano  
#&gt;  3 Davis, Segan       Cox, Mariah        
#&gt;  4 al-Muhammed, Ulyaa Duenez, Aureliano  
#&gt;  5 al-Muhammed, Ulyaa Wojtowick, Gary    
#&gt;  6 al-Muhammed, Ulyaa Labishak, Aiyana   
#&gt;  7 Lowe, Rafael       Cox, Mariah        
#&gt;  8 Lowe, Rafael       Olson, Jeremy      
#&gt;  9 Lowe, Rafael       Labishak, Aiyana   
#&gt; 10 Wilson, James      Bannister, Kenaniah
#&gt; 11 Tarrant, Shontae   Cox, Mariah        
#&gt; 12 Tarrant, Shontae   Bannister, Kenaniah</code></pre>
<p>In this edgelist, the sender could indicate, for example, someone who nominates someone else (the receiver) as someone they go to for help. The sender could also indicate someone who interacted with the receiver, such as by recognizing one of their tweets with a favorite (or a mention). In the following steps, we will work to create an edgelist from the data from #tidytuesday on Twitter.</p>
<div id="extracting-mentions" class="section level3">
<h3>Extracting Mentions</h3>
<p>Let’s extract the mentions. There is a lot going on in the code below; let’s break it down line-by-line, starting with the <code>mutate()</code>:</p>
<ul>
<li><code>mutate(all_mentions = str_extract_all(text, regex))</code>: this line uses a regex, or regular expression, to identify all of the usernames in the tweet (<em>note</em>: the regex comes from from <a href="https://stackoverflow.com/questions/18164839/get-twitter-username-with-regex-in-r">this page</a>)</li>
<li><code>unnest(all_mentions)</code> this line uses a tidyr function, <code>unnest()</code> to move every mention to its own line, while keeping all of the other information the same (see more about <code>unnest()</code> here: <a href="https://tidyr.tidyverse.org/reference/unnest.html" class="uri">https://tidyr.tidyverse.org/reference/unnest.html</a>)).</li>
</ul>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb285-1" title="1">regex &lt;-<span class="st"> &quot;@([A-Za-z]+[A-Za-z0-9_]+)(?![A-Za-z0-9_]*</span><span class="ch">\\</span><span class="st">.)&quot;</span></a>
<a class="sourceLine" id="cb285-2" title="2"></a>
<a class="sourceLine" id="cb285-3" title="3">tt_tweets &lt;-</a>
<a class="sourceLine" id="cb285-4" title="4"><span class="st">  </span>tt_tweets <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb285-5" title="5"><span class="st">  </span><span class="co"># Use regular expression to identify all the usernames in a tweet</span></a>
<a class="sourceLine" id="cb285-6" title="6"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">all_mentions =</span> <span class="kw">str_extract_all</span>(text, regex)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb285-7" title="7"><span class="st">  </span><span class="kw">unnest</span>(all_mentions)</a></code></pre></div>
<p>Let’s put these into their own data frame, called <code>mentions</code>.</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb286-1" title="1">mentions &lt;-</a>
<a class="sourceLine" id="cb286-2" title="2"><span class="st">  </span>tt_tweets <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">all_mentions =</span> <span class="kw">str_trim</span>(all_mentions)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb286-4" title="4"><span class="st">  </span><span class="kw">select</span>(<span class="dt">sender =</span> screen_name, all_mentions)</a></code></pre></div>
</div>
<div id="putting-the-edgelist-together" class="section level3">
<h3>Putting the Edgelist Together</h3>
<p>An edgelist is a common social network analysis data structure that has columns for the “sender” and “receiver” of interactions, or relations. For example, someone “sends” the mention to someone who is mentioned, who can be considered to “receive” it. This will require one last processing step. Let’s look at our data as it is now.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb287-1" title="1">mentions</a></code></pre></div>
<pre><code>#&gt; # A tibble: 2,447 x 2
#&gt;    sender  all_mentions    
#&gt;    &lt;chr&gt;   &lt;chr&gt;           
#&gt;  1 cizzart @eldestapeweb   
#&gt;  2 cizzart @INDECArgentina 
#&gt;  3 cizzart @ENACOMArgentina
#&gt;  4 cizzart @tribunalelecmns
#&gt;  5 cizzart @CamaraElectoral
#&gt;  6 cizzart @INDECArgentina 
#&gt;  7 cizzart @tribunalelecmns
#&gt;  8 cizzart @CamaraElectoral
#&gt;  9 cizzart @AgroMnes       
#&gt; 10 cizzart @AgroindustriaAR
#&gt; # … with 2,437 more rows</code></pre>
<p>What needs to happen to these to make them easier to work with in an edgelist? One step is to remove the “@” symbol from the columns we created and to save the results to a new tibble, <code>edgelist</code>.</p>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb289-1" title="1">edgelist &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb289-2" title="2"><span class="st">  </span>mentions <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb289-3" title="3"><span class="st">  </span><span class="co"># remove &quot;@&quot; from all_mentions column</span></a>
<a class="sourceLine" id="cb289-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">all_mentions =</span> <span class="kw">str_sub</span>(all_mentions, <span class="dt">start =</span> <span class="dv">2</span>)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb289-5" title="5"><span class="st">  </span><span class="co"># rename all_mentions to receiver</span></a>
<a class="sourceLine" id="cb289-6" title="6"><span class="st">  </span><span class="kw">select</span>(sender, <span class="dt">receiver =</span> all_mentions)</a></code></pre></div>
</div>
</div>
<div id="analysis-and-results" class="section level2">
<h2>Analysis and Results</h2>
<p>Now that we have our edgelist, it is straightforward to plot the network. We’ll use the {tidygraph} and {ggraph} packages to visualize the data.</p>
<div id="plotting-the-network" class="section level3">
<h3>Plotting the Network</h3>
<p>Because large networks (like this one) can present challenges, it is common to filter them to only include some individuals. Let’s explore how many interactions each individual in the network sent.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb290-1" title="1">interactions_sent &lt;-<span class="st"> </span>edgelist <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb290-2" title="2"><span class="st">  </span><span class="co"># this counts how many times each sender appears in the data frame, effectively counting how many interactions each individual sent </span></a>
<a class="sourceLine" id="cb290-3" title="3"><span class="st">  </span><span class="kw">count</span>(sender) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb290-4" title="4"><span class="st">  </span><span class="co"># arranges the data frame in descending order of the number of interactions sent</span></a>
<a class="sourceLine" id="cb290-5" title="5"><span class="st">  </span><span class="kw">arrange</span>(<span class="kw">desc</span>(n))</a>
<a class="sourceLine" id="cb290-6" title="6"></a>
<a class="sourceLine" id="cb290-7" title="7">interactions_sent</a></code></pre></div>
<pre><code>#&gt; # A tibble: 618 x 2
#&gt;    sender            n
#&gt;    &lt;chr&gt;         &lt;int&gt;
#&gt;  1 thomas_mock     347
#&gt;  2 R4DScommunity    78
#&gt;  3 WireMonkey       52
#&gt;  4 CedScherer       41
#&gt;  5 allison_horst    37
#&gt;  6 mjhendrickson    34
#&gt;  7 kigtembu         27
#&gt;  8 WeAreRLadies     25
#&gt;  9 PBecciu          23
#&gt; 10 sil_aarts        23
#&gt; # … with 608 more rows</code></pre>
<p>618 senders of interactions is a lot! What if we focused on only those who sent more than one interaction?</p>
<div class="sourceCode" id="cb292"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb292-1" title="1">interactions_sent &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb292-2" title="2"><span class="st">  </span>interactions_sent <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb292-3" title="3"><span class="st">  </span><span class="kw">filter</span>(n <span class="op">&gt;</span><span class="st"> </span><span class="dv">1</span>)</a></code></pre></div>
<p>That leaves us with only 349, perhaps a more reasonable number.</p>
<p>We now need to filter the edgelist to only include these 349 individuals. The following code simply uses the <code>filter()</code> function combined with the <code>%in%</code> operator to do this:</p>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb293-1" title="1">edgelist &lt;-<span class="st"> </span>edgelist <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb293-2" title="2"><span class="st">  </span><span class="co"># the first of the two lines below filters to include only senders in the interactions_sent data frame</span></a>
<a class="sourceLine" id="cb293-3" title="3"><span class="st">  </span><span class="co"># the second line does the same, for receivers</span></a>
<a class="sourceLine" id="cb293-4" title="4"><span class="st">  </span><span class="kw">filter</span>(sender <span class="op">%in%</span><span class="st"> </span>interactions_sent<span class="op">$</span>sender,</a>
<a class="sourceLine" id="cb293-5" title="5">         receiver <span class="op">%in%</span><span class="st"> </span>interactions_sent<span class="op">$</span>sender)</a></code></pre></div>
<p>We’ll use the <code>as_tbl_graph()</code> function, which (by default) identified the first column as the “sender” and the second as the “receiver.” Let’s look at the object it creates, too.</p>
<div class="sourceCode" id="cb294"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb294-1" title="1">g &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb294-2" title="2"><span class="st">  </span><span class="kw">as_tbl_graph</span>(edgelist)</a>
<a class="sourceLine" id="cb294-3" title="3"></a>
<a class="sourceLine" id="cb294-4" title="4">g</a></code></pre></div>
<pre><code>#&gt; # A tbl_graph: 267 nodes and 975 edges
#&gt; #
#&gt; # A directed multigraph with 7 components
#&gt; #
#&gt; # Node Data: 267 x 1 (active)
#&gt;   name           
#&gt;   &lt;chr&gt;          
#&gt; 1 dgwinfred      
#&gt; 2 datawookie     
#&gt; 3 jvaghela4      
#&gt; 4 FournierJohanie
#&gt; 5 JonTheGeek     
#&gt; 6 jakekaupp      
#&gt; # … with 261 more rows
#&gt; #
#&gt; # Edge Data: 975 x 2
#&gt;    from    to
#&gt;   &lt;int&gt; &lt;int&gt;
#&gt; 1     1    32
#&gt; 2     1    36
#&gt; 3     2   120
#&gt; # … with 972 more rows</code></pre>
<p>We can see that the network now consists of 267 individuals - the 267 who sent more than one interaction.</p>
<p>Next, we’ll use the <code>ggraph()</code> function:</p>
<div class="sourceCode" id="cb296"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb296-1" title="1">g <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb296-2" title="2"><span class="st">  </span><span class="co"># we chose the kk layout as it created a graph which was easy-to-interpret, but others are available; see ?ggraph</span></a>
<a class="sourceLine" id="cb296-3" title="3"><span class="st">  </span><span class="kw">ggraph</span>(<span class="dt">layout =</span> <span class="st">&quot;kk&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb296-4" title="4"><span class="st">  </span><span class="co"># this adds the points to the graph</span></a>
<a class="sourceLine" id="cb296-5" title="5"><span class="st">  </span><span class="kw">geom_node_point</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb296-6" title="6"><span class="st">  </span><span class="co"># this adds the links, or the edges; alpha = .2 makes it so that the lines are partially transparent</span></a>
<a class="sourceLine" id="cb296-7" title="7"><span class="st">  </span><span class="kw">geom_edge_link</span>(<span class="dt">alpha =</span> <span class="fl">.2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb296-8" title="8"><span class="st">  </span><span class="co"># this last line of code adds a ggplot2 theme suitable for network graphs</span></a>
<a class="sourceLine" id="cb296-9" title="9"><span class="st">  </span><span class="kw">theme_graph</span>()</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-16"></span>
<img src="figures/unnamed-chunk-16-1.png" alt="Network Graph" width="100%" />
<p class="caption">
Figure 16: Network Graph
</p>
</div>
<p>Finally, let’s size the points based on a measure of centrality, typically a measure of how (potentially) influence an individual may be, based on the interactions observed.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb297-1" title="1">g <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb297-2" title="2"><span class="st">  </span><span class="co"># this calculates the centrality of each individual using the built-in centrality_authority() function</span></a>
<a class="sourceLine" id="cb297-3" title="3"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">centrality =</span> <span class="kw">centrality_authority</span>()) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb297-4" title="4"><span class="st">  </span><span class="kw">ggraph</span>(<span class="dt">layout =</span> <span class="st">&quot;kk&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb297-5" title="5"><span class="st">  </span><span class="kw">geom_node_point</span>(<span class="kw">aes</span>(<span class="dt">size =</span> centrality, <span class="dt">color =</span> centrality)) <span class="op">+</span></a>
<a class="sourceLine" id="cb297-6" title="6"><span class="st">  </span><span class="co"># this line colors the points based upon their centrality</span></a>
<a class="sourceLine" id="cb297-7" title="7"><span class="st">  </span><span class="kw">scale_color_continuous</span>(<span class="dt">guide =</span> <span class="st">&#39;legend&#39;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb297-8" title="8"><span class="st">  </span><span class="kw">geom_edge_link</span>(<span class="dt">alpha =</span> <span class="fl">.2</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb297-9" title="9"><span class="st">  </span><span class="kw">theme_graph</span>()</a></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-18"></span>
<img src="figures/unnamed-chunk-18-1.png" alt="Network Graph with Centrality" width="100%" />
<p class="caption">
Figure 18: Network Graph with Centrality
</p>
</div>
<p>There is much more you can do with {ggraph} (and {tidygraph}); check out the {ggraph} tutorial here: <a href="https://ggraph.data-imaginist.com/" class="uri">https://ggraph.data-imaginist.com/</a></p>
</div>
</div>
<div id="conclusion-8" class="section level2">
<h2>Conclusion</h2>
<p>In this chapter, we used social media data (from the #tidytuesday hashtag) to prepare and visualize social network data. This is a powerful technique; one that can reveal who is interacting with whom, and one that can begin to suggest why.</p>
<!-- Wondering if we need to do more with the visualizations do begin so that this can be more warranted. -->
<p>Behind these visualizations, though, there are also statistical models and methods that can help to understand what is going on with respect to particular relationships in a network in additional ways.</p>
<p>One way to consider these models and methods is in terms of two <em>processes</em> at play in our relationships (cite). These two processes are commonly (though not exclusively) the focus of statistical analyses of networks. In addition to not being exclusive, they do not interact independently: they affect each other reciprocally (Xu, Frank, &amp; Penuel, 2018). They are:</p>
<ul>
<li><em>Selection</em>: the processes regarding who chooses to have a relationship with whom</li>
<li><em>Influence</em>: the processes regarding how who we have relationships with affects our behavior</li>
</ul>
<p>While these are complex, they can be studied with the type of data collected from asking people about their relationships (and possibly asking them about or studying their behavior–or measuring some outcome). Happily, the use of these methods has expanded along with R: many of the best tools for studying social networks are in the form of long-standing R packages. Additionally, while there are many potential nuances to studying selection and influence, these are models that can fundamentally be carried out with regression, or the linear model (or extensions of it). We describe these in the <em>Technical Appendix</em> for this chapter, as they do not use the tidytuesday dataset and are likely to be of interest to readers only after having mastered preparing and visualizing network data.</p>
</div>
<div id="technical-appendix-influence-and-selection-models" class="section level2">
<h2>Technical Appendix: Influence and Selection Models</h2>
<p>As noted above, there is much more to understanding interactions, and network analysis, beyond creating edgelists and visualizing network data (through the use of an edgelist). Two processes that are particularly important (and able to be studied with network data using R) are for influence and selection.</p>
<div id="an-example-of-influence" class="section level3">
<h3>An Example of Influence</h3>
<p>First, let’s look at an example of influence. To do so, let’s create three different data frames. Here is what they should, at the end of the process, contain:</p>
<ul>
<li>A data frame indicating who the <em>nominator</em> and <em>nominee</em> for the relation (i.e., if Stefanie says that José is her friend, then Stefanie is the nominator and José the nominee) - as well as an optional variable indicating the weight, or strength, of their relation.</li>
<li>This data frame and its type can be considered the basis for many types of social network analysis and is a common structure for network data: it is an <em>edgelist</em>.</li>
<li>Data frames indicating the values of some behavior - an outcome - at two different time points.</li>
</ul>
<p>In this example, we create some example data that can be used to explore questions about how influence works.</p>
<p>Let’s take a look at the merged data. What this data now contains is the first data frame, <code>data1</code>, with each nominees’ outcome at time 1 (<code>yvar1</code>). Note that we will find each nominators’ outcome at time 2 later on.</p>
<div class="sourceCode" id="cb298"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb298-1" title="1">data1 &lt;-</a>
<a class="sourceLine" id="cb298-2" title="2"><span class="st">  </span><span class="kw">data.frame</span>(</a>
<a class="sourceLine" id="cb298-3" title="3">    <span class="dt">nominator =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">6</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">4</span>, <span class="dv">3</span>, <span class="dv">4</span>),</a>
<a class="sourceLine" id="cb298-4" title="4">    <span class="dt">nominee =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">6</span>),</a>
<a class="sourceLine" id="cb298-5" title="5">    <span class="dt">relate =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb298-6" title="6">  )</a>
<a class="sourceLine" id="cb298-7" title="7"></a>
<a class="sourceLine" id="cb298-8" title="8">data2 &lt;-</a>
<a class="sourceLine" id="cb298-9" title="9"><span class="st">  </span><span class="kw">data.frame</span>(<span class="dt">nominee =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>),</a>
<a class="sourceLine" id="cb298-10" title="10">             <span class="dt">yvar1 =</span> <span class="kw">c</span>(<span class="fl">2.4</span>, <span class="fl">2.6</span>, <span class="fl">1.1</span>, <span class="fl">-0.5</span>, <span class="dv">-3</span>, <span class="dv">-1</span>))</a>
<a class="sourceLine" id="cb298-11" title="11"></a>
<a class="sourceLine" id="cb298-12" title="12">data3 &lt;-</a>
<a class="sourceLine" id="cb298-13" title="13"><span class="st">  </span><span class="kw">data.frame</span>(<span class="dt">nominator =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>),</a>
<a class="sourceLine" id="cb298-14" title="14">             <span class="dt">yvar2 =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>, <span class="fl">-0.5</span>, <span class="dv">-2</span>, <span class="fl">-0.5</span>))</a></code></pre></div>
</div>
<div id="joining-the-data-1" class="section level3">
<h3>Joining the Data</h3>
<p>Next, we’ll join the data into one data frame. Note that while this is sometimes tedious and time-consuming, especially with large sources of network data, it is a key step for being able to carry out network analysis - often, even for creating visualizations that are informative.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb299-1" title="1">data &lt;-</a>
<a class="sourceLine" id="cb299-2" title="2"><span class="st">  </span><span class="kw">left_join</span>(data1, data2, <span class="dt">by =</span> <span class="st">&quot;nominee&quot;</span>)</a>
<a class="sourceLine" id="cb299-3" title="3"></a>
<a class="sourceLine" id="cb299-4" title="4">data &lt;-</a>
<a class="sourceLine" id="cb299-5" title="5"><span class="st">  </span>data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb299-6" title="6"><span class="st">  </span><span class="co"># this makes merging later easier</span></a>
<a class="sourceLine" id="cb299-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">nominee =</span> <span class="kw">as.character</span>(nominee)) </a>
<a class="sourceLine" id="cb299-8" title="8"></a>
<a class="sourceLine" id="cb299-9" title="9"><span class="co"># calculate indegree in tempdata and merge with data</span></a>
<a class="sourceLine" id="cb299-10" title="10">tempdata &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="kw">table</span>(data<span class="op">$</span>nominee))</a>
<a class="sourceLine" id="cb299-11" title="11"></a>
<a class="sourceLine" id="cb299-12" title="12">tempdata &lt;-</a>
<a class="sourceLine" id="cb299-13" title="13"><span class="st">  </span>tempdata <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb299-14" title="14"><span class="st">  </span><span class="kw">rename</span>(</a>
<a class="sourceLine" id="cb299-15" title="15">    <span class="co"># rename the column &quot;Var1&quot; to &quot;nominee&quot; </span></a>
<a class="sourceLine" id="cb299-16" title="16">    <span class="st">&quot;nominee&quot;</span> =<span class="st"> &quot;Var1&quot;</span>, </a>
<a class="sourceLine" id="cb299-17" title="17">    <span class="co"># rename the column &quot;Freq&quot; to &quot;indegree&quot;</span></a>
<a class="sourceLine" id="cb299-18" title="18">    <span class="st">&quot;indegree&quot;</span> =<span class="st"> &quot;Freq&quot;</span></a>
<a class="sourceLine" id="cb299-19" title="19">    ) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb299-20" title="20"><span class="st">  </span><span class="co"># makes nominee a character data type, instead of a factor, which can cause problems</span></a>
<a class="sourceLine" id="cb299-21" title="21"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">nominee =</span> <span class="kw">as.character</span>(nominee))</a>
<a class="sourceLine" id="cb299-22" title="22"></a>
<a class="sourceLine" id="cb299-23" title="23">data &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb299-24" title="24"><span class="st">  </span><span class="kw">left_join</span>(data, tempdata, <span class="dt">by =</span> <span class="st">&quot;nominee&quot;</span>)</a></code></pre></div>
<div id="calculating-an-exposure-term" class="section level4">
<h4>Calculating an Exposure Term</h4>
<p>This is the key step that makes this model - a regression, or linear, model - one that is special. It is creating an exposure term. The idea is that the exposure term “captures” how your interactions with someone, over some period of time (between the first and second time points) impact some outcome. This model accounts for an individual’s initial report of the outcome, i.e., their time 1 prior value, so it is a model for <em>change</em> in some outcome.</p>
<div class="sourceCode" id="cb300"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb300-1" title="1"><span class="co"># Calculating exposure</span></a>
<a class="sourceLine" id="cb300-2" title="2">data &lt;-</a>
<a class="sourceLine" id="cb300-3" title="3"><span class="st">  </span>data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb300-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">exposure =</span> relate <span class="op">*</span><span class="st"> </span>yvar1)</a>
<a class="sourceLine" id="cb300-5" title="5"></a>
<a class="sourceLine" id="cb300-6" title="6"><span class="co"># Calculating mean exposure</span></a>
<a class="sourceLine" id="cb300-7" title="7">mean_exposure &lt;-</a>
<a class="sourceLine" id="cb300-8" title="8"><span class="st">  </span>data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb300-9" title="9"><span class="st">  </span><span class="kw">group_by</span>(nominator) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb300-10" title="10"><span class="st">  </span><span class="kw">summarize</span>(<span class="dt">exposure_mean =</span> <span class="kw">mean</span>(exposure))</a></code></pre></div>
<p>What this data frame - <code>mean_exposure</code> - contains is the mean of the outcome (in this case, <code>yvar1</code>) for all of the individuals the nominator had a relation with.</p>
<p>As we need a final data set with <code>mean_exposure</code>,<code>degree</code>, <code>yvar1</code>, and <code>yvar2</code> added, we’ll process the data a bit more.</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb301-1" title="1">data2 &lt;-</a>
<a class="sourceLine" id="cb301-2" title="2"><span class="st">  </span>data2 <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb301-3" title="3"><span class="st">  </span><span class="co"># rename nominee as nominator to merge these</span></a>
<a class="sourceLine" id="cb301-4" title="4"><span class="st">  </span><span class="kw">rename</span>(<span class="st">&quot;nominator&quot;</span> =<span class="st"> &quot;nominee&quot;</span>) </a>
<a class="sourceLine" id="cb301-5" title="5"></a>
<a class="sourceLine" id="cb301-6" title="6">final_data &lt;-</a>
<a class="sourceLine" id="cb301-7" title="7"><span class="st">  </span><span class="kw">left_join</span>(mean_exposure, data2, <span class="dt">by =</span> <span class="st">&quot;nominator&quot;</span>)</a>
<a class="sourceLine" id="cb301-8" title="8"></a>
<a class="sourceLine" id="cb301-9" title="9">final_data &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb301-10" title="10"><span class="st">  </span><span class="co"># data3 already has nominator, so no need to change</span></a>
<a class="sourceLine" id="cb301-11" title="11"><span class="st">  </span><span class="kw">left_join</span>(final_data, data3, <span class="dt">by =</span> <span class="st">&quot;nominator&quot;</span>) </a></code></pre></div>
</div>
<div id="regression-linear-model" class="section level4">
<h4>Regression (Linear Model)</h4>
<p>Calculating the exposure term is the most distinctive and important step in carrying out influence models. Now, we can simply use a linear model to find out how much relations - as captured by the influence term - affect some outcome.</p>
<div class="sourceCode" id="cb302"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb302-1" title="1">model1 &lt;-</a>
<a class="sourceLine" id="cb302-2" title="2"><span class="st">  </span><span class="kw">lm</span>(yvar2 <span class="op">~</span><span class="st"> </span>yvar1 <span class="op">+</span><span class="st"> </span>exposure_mean, <span class="dt">data =</span> final_data)</a>
<a class="sourceLine" id="cb302-3" title="3"></a>
<a class="sourceLine" id="cb302-4" title="4"><span class="kw">summary</span>(model1)</a></code></pre></div>
<pre><code>#&gt; 
#&gt; Call:
#&gt; lm(formula = yvar2 ~ yvar1 + exposure_mean, data = final_data)
#&gt; 
#&gt; Residuals:
#&gt;       1       2       3       4       5       6 
#&gt;  0.0295 -0.0932  0.0943 -0.0273 -0.0255  0.0222 
#&gt; 
#&gt; Coefficients:
#&gt;               Estimate Std. Error t value Pr(&gt;|t|)    
#&gt; (Intercept)     0.1161     0.0345    3.37    0.043 *  
#&gt; yvar1           0.6760     0.0241   28.09  9.9e-05 ***
#&gt; exposure_mean   0.1254     0.0361    3.47    0.040 *  
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
#&gt; 
#&gt; Residual standard error: 0.0823 on 3 degrees of freedom
#&gt; Multiple R-squared:  0.998,  Adjusted R-squared:  0.997 
#&gt; F-statistic:  945 on 2 and 3 DF,  p-value: 6.31e-05</code></pre>
<p>So, the influence model is used to study a key process for social network analysis, but it is one that is useful, because you can quantify, given what you measure and how you measure it, <em>the network effect</em>, something that is sometimes not considered, especially in education (Frank, 2009). It’s also fundamentally a regression. That’s really it, as the majority of the work goes into calculating the exposure term.</p>
</div>
</div>
<div id="an-example-of-selection" class="section level3">
<h3>An Example of Selection</h3>
<p>Selection models are also commonly used - and are commonly of interest not only to researchers but also to administrators and teachers (and even to youth and students).</p>
<p>Here, we briefly describe a few possible approaches for using a selection model.</p>
<p>At its core, the selection model is a regression - albeit, one that is a generalization of one, namely, a logistic regression (sometimes termed a generalized linear model, because it is <em>basically</em> a regression but is one with an outcome that consists just of 0’s and 1’s). Thus, the most straight-away way to use a selection model is to use a logistic regression where all of the relations (note the <code>relate</code> variable in <code>data1</code> above) are indicated with a 1. But, here is the important and challenging step: all of the <em>possible relations</em> (i.e., all of the relations that are possible between all of the individuals in a network) are indicated with a 0 in an edgelist. Note that, again, an edgelist is the preferred data structure for carrying out this analysis. This step involves some data wrangling, especially the idea of widening or lengthening a data frame.</p>
<p>Once all of the relations are indicated with a 1 or a 0, then a simple linear regression can be used. Imagine that we are interested in whether individuals from the <em>same</em> group are more or less likely to interact than those from different groups; same could be created in the data frame based upon knowing which group both nominator and nominee are from:</p>
<div class="sourceCode" id="cb304"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb304-1" title="1">m_selection &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb304-2" title="2"><span class="st">  </span><span class="kw">glm</span>(relate <span class="op">~</span><span class="st"> </span><span class="dv">1</span> <span class="op">+</span><span class="st"> </span>same, <span class="dt">data =</span> edgelist1)</a></code></pre></div>
<p>While this is a straightforward way to carry out a selection model, there are some limitations to it. Namely, it does not account for individuals who send more (or less) nominations overall–and not considering this may mean other effects, like the one associated with being from the <em>same</em> group, are not accurate. A few extensions of the linear model - including those that can use data for which relationships are indicated with weights, not just 1’s and 0’s, have been developed.</p>
<p>One type of selection model extends the logistic regression. The {amen} <span class="citation">(<span class="citeproc-not-found" data-reference-id="R-amen"><strong>???</strong></span>)</span> package can be used for data that is not only 1ss and 0s - like a logistic regression - but also data that is normally distributed. Another extension is an Exponential Random Graph Model, or ERGM. The {ergm} R package makes it easy to use these kinds of selection models. {ergm} <span class="citation">(<span class="citeproc-not-found" data-reference-id="R-ergm"><strong>???</strong></span>)</span> is itself a part of a powerful and often-used collection of packages for social network analysis, {statnet} <span class="citation">(<span class="citeproc-not-found" data-reference-id="R-statnet"><strong>???</strong></span>)</span>. These packages collectively begin to illustrate the richness of the packages available within R for using social network analysis models and methods; moreover, as developments in social network analysis methods continue to be made, cutting-edge techniques are likely to continue to be available (through R packages) to those using R for these types of analyses.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c11.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c13.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/data-edu/data-science-in-education/edit/master/12-wt-social-network-analysis.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

</body>

</html>
