<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>14 Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data | Data Science in Education Using R</title>
  <meta name="description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="14 Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data | Data Science in Education Using R" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="datascienceineducation.com/" />
  
  <meta property="og:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="github-repo" content="data-edu/data-science-in-education" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="14 Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data | Data Science in Education Using R" />
  
  <meta name="twitter:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  

<meta name="author" content="Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
<link rel="prev" href="c13.html"/>
<link rel="next" href="c15.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-156454511-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-156454511-1');
</script>


<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Data Science in Education Using R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Welcome</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#prologue"><i class="fa fa-check"></i>Prologue</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#dedications"><i class="fa fa-check"></i>Dedications</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#citation"><i class="fa fa-check"></i>Citation</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="c01.html"><a href="c01.html"><i class="fa fa-check"></i><b>1</b> Introduction: Data Science in Education - You’re Invited to the Party!</a><ul>
<li class="chapter" data-level="1.1" data-path="c01.html"><a href="c01.html#learning-data-science-in-education"><i class="fa fa-check"></i><b>1.1</b> Learning Data Science in Education</a></li>
<li class="chapter" data-level="1.2" data-path="c01.html"><a href="c01.html#making-the-path-a-little-clearer"><i class="fa fa-check"></i><b>1.2</b> Making the Path a Little Clearer</a></li>
<li class="chapter" data-level="1.3" data-path="c01.html"><a href="c01.html#conventions-used-in-the-book"><i class="fa fa-check"></i><b>1.3</b> Conventions Used in the Book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="c02.html"><a href="c02.html"><i class="fa fa-check"></i><b>2</b> How to Use this Book</a><ul>
<li class="chapter" data-level="2.1" data-path="c02.html"><a href="c02.html#different-strokes-for-different-data-scientists-in-education"><i class="fa fa-check"></i><b>2.1</b> Different Strokes for Different Data Scientists in Education</a><ul>
<li class="chapter" data-level="2.1.1" data-path="c02.html"><a href="c02.html#read-the-book-cover-to-cover-and-how-to-keep-going"><i class="fa fa-check"></i><b>2.1.1</b> Read the Book Cover to Cover (and How to Keep Going)</a></li>
<li class="chapter" data-level="2.1.2" data-path="c02.html"><a href="c02.html#pick-a-chapter-of-interest-and-start-there"><i class="fa fa-check"></i><b>2.1.2</b> Pick a Chapter of Interest and Start There</a></li>
<li class="chapter" data-level="2.1.3" data-path="c02.html"><a href="c02.html#read-through-the-walkthroughs-and-run-the-code"><i class="fa fa-check"></i><b>2.1.3</b> Read Through the Walkthroughs and Run the Code</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="c02.html"><a href="c02.html#a-note-on-statistics"><i class="fa fa-check"></i><b>2.2</b> A Note on Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="c02.html"><a href="c02.html#what-this-book-is-not-about"><i class="fa fa-check"></i><b>2.3</b> What This Book Is Not About</a></li>
<li class="chapter" data-level="2.4" data-path="c02.html"><a href="c02.html#supporting-the-book"><i class="fa fa-check"></i><b>2.4</b> Supporting the Book</a></li>
<li class="chapter" data-level="2.5" data-path="c02.html"><a href="c02.html#contributing-to-the-book"><i class="fa fa-check"></i><b>2.5</b> Contributing to the Book</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="c03.html"><a href="c03.html"><i class="fa fa-check"></i><b>3</b> What Does Data Science in Education Look Like?</a><ul>
<li class="chapter" data-level="3.1" data-path="c03.html"><a href="c03.html#data-roles-in-education"><i class="fa fa-check"></i><b>3.1</b> Data Roles in Education</a><ul>
<li class="chapter" data-level="3.1.1" data-path="c03.html"><a href="c03.html#building-systems-that-get-data-to-the-right-people"><i class="fa fa-check"></i><b>3.1.1</b> Building Systems That Get Data to the Right People</a></li>
<li class="chapter" data-level="3.1.2" data-path="c03.html"><a href="c03.html#measuring-the-impact-of-our-work-on-the-student-experience"><i class="fa fa-check"></i><b>3.1.2</b> Measuring the Impact of Our Work on the Student Experience</a></li>
<li class="chapter" data-level="3.1.3" data-path="c03.html"><a href="c03.html#looking-for-patterns-in-student-data"><i class="fa fa-check"></i><b>3.1.3</b> Looking for Patterns in Student Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="c03.html"><a href="c03.html#improving-how-we-use-statistical-models-in-education"><i class="fa fa-check"></i><b>3.1.4</b> Improving How We Use Statistical Models in Education</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="c03.html"><a href="c03.html#common-activities-of-data-scientists"><i class="fa fa-check"></i><b>3.2</b> Common Activities of Data Scientists</a><ul>
<li class="chapter" data-level="3.2.1" data-path="c03.html"><a href="c03.html#processing-data"><i class="fa fa-check"></i><b>3.2.1</b> Processing Data</a></li>
<li class="chapter" data-level="3.2.2" data-path="c03.html"><a href="c03.html#doing-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Doing Analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="c03.html"><a href="c03.html#sharing-results"><i class="fa fa-check"></i><b>3.2.3</b> Sharing Results</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="c03.html"><a href="c03.html#who-we-are-and-what-we-do"><i class="fa fa-check"></i><b>3.3</b> Who We Are and What We Do</a></li>
<li class="chapter" data-level="3.4" data-path="c03.html"><a href="c03.html#next-steps-for-data-science-in-education"><i class="fa fa-check"></i><b>3.4</b> Next Steps for Data Science in Education</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="c04.html"><a href="c04.html"><i class="fa fa-check"></i><b>4</b> Special Considerations</a><ul>
<li class="chapter" data-level="4.1" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-any-domain"><i class="fa fa-check"></i><b>4.1</b> Things to Consider when Doing Data Science in any Domain</a><ul>
<li class="chapter" data-level="4.1.1" data-path="c04.html"><a href="c04.html#learning-to-code"><i class="fa fa-check"></i><b>4.1.1</b> Learning to Code</a></li>
<li class="chapter" data-level="4.1.2" data-path="c04.html"><a href="c04.html#addressing-ambiguity-a-reproducible-approach"><i class="fa fa-check"></i><b>4.1.2</b> Addressing Ambiguity: A Reproducible Approach</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="c04.html"><a href="c04.html#things-to-consider-when-doing-data-science-in-education"><i class="fa fa-check"></i><b>4.2</b> Things to Consider when Doing Data Science in Education</a><ul>
<li class="chapter" data-level="4.2.1" data-path="c04.html"><a href="c04.html#addressing-organizational-resistance-a-self-driven-analytic-approach"><i class="fa fa-check"></i><b>4.2.1</b> Addressing Organizational Resistance: A Self-Driven Analytic Approach</a></li>
<li class="chapter" data-level="4.2.2" data-path="c04.html"><a href="c04.html#lack-of-processes-and-guidelines"><i class="fa fa-check"></i><b>4.2.2</b> Lack of Processes and Guidelines</a></li>
<li class="chapter" data-level="4.2.3" data-path="c04.html"><a href="c04.html#limited-training-and-educational-opportunities"><i class="fa fa-check"></i><b>4.2.3</b> Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="4.2.4" data-path="c04.html"><a href="c04.html#limited-training-and-educational-opportunities-1"><i class="fa fa-check"></i><b>4.2.4</b> Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="4.2.5" data-path="c04.html"><a href="c04.html#advancing-equity"><i class="fa fa-check"></i><b>4.2.5</b> Advancing Equity</a></li>
<li class="chapter" data-level="4.2.6" data-path="c04.html"><a href="c04.html#the-complex-nature-of-education-data"><i class="fa fa-check"></i><b>4.2.6</b> The Complex Nature of Education Data</a></li>
<li class="chapter" data-level="4.2.7" data-path="c04.html"><a href="c04.html#ethical-and-legal-concerns"><i class="fa fa-check"></i><b>4.2.7</b> Ethical and Legal Concerns</a></li>
<li class="chapter" data-level="4.2.8" data-path="c04.html"><a href="c04.html#analytic-considerations"><i class="fa fa-check"></i><b>4.2.8</b> Analytic Considerations</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="c04.html"><a href="c04.html#conclusion"><i class="fa fa-check"></i><b>4.3</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="c05.html"><a href="c05.html"><i class="fa fa-check"></i><b>5</b> Getting Started with R and RStudio</a><ul>
<li class="chapter" data-level="5.1" data-path="c05.html"><a href="c05.html#chapter-overview"><i class="fa fa-check"></i><b>5.1</b> Chapter Overview</a></li>
<li class="chapter" data-level="5.2" data-path="c05.html"><a href="c05.html#downloading-r-and-rstudio"><i class="fa fa-check"></i><b>5.2</b> Downloading R and RStudio</a><ul>
<li class="chapter" data-level="5.2.1" data-path="c05.html"><a href="c05.html#to-download-r"><i class="fa fa-check"></i><b>5.2.1</b> To Download R:</a></li>
<li class="chapter" data-level="5.2.2" data-path="c05.html"><a href="c05.html#to-download-rstudio"><i class="fa fa-check"></i><b>5.2.2</b> To Download RStudio:</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="c05.html"><a href="c05.html#rstudio-layout-and-customization-getting-to-know-r-through-rstudio"><i class="fa fa-check"></i><b>5.3</b> RStudio Layout and Customization: Getting to Know R through RStudio</a><ul>
<li class="chapter" data-level="5.3.1" data-path="c05.html"><a href="c05.html#rstudio-layout"><i class="fa fa-check"></i><b>5.3.1</b> RStudio Layout</a></li>
<li class="chapter" data-level="5.3.2" data-path="c05.html"><a href="c05.html#customizing-rstudio"><i class="fa fa-check"></i><b>5.3.2</b> Customizing RStudio</a></li>
<li class="chapter" data-level="5.3.3" data-path="c05.html"><a href="c05.html#minimized-and-missing-panes"><i class="fa fa-check"></i><b>5.3.3</b> Minimized and Missing Panes</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="c05.html"><a href="c05.html#writing-and-running-code-in-rstudio"><i class="fa fa-check"></i><b>5.4</b> Writing and Running Code in RStudio</a><ul>
<li class="chapter" data-level="5.4.1" data-path="c05.html"><a href="c05.html#writing-code-in-the-console"><i class="fa fa-check"></i><b>5.4.1</b> Writing Code in the Console</a></li>
<li class="chapter" data-level="5.4.2" data-path="c05.html"><a href="c05.html#writing-code-in-an-r-script"><i class="fa fa-check"></i><b>5.4.2</b> Writing Code in an R Script</a></li>
<li class="chapter" data-level="5.4.3" data-path="c05.html"><a href="c05.html#commenting-your-code-in-r"><i class="fa fa-check"></i><b>5.4.3</b> Commenting Your Code in R</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="c05.html"><a href="c05.html#installing-the-dataedu-package"><i class="fa fa-check"></i><b>5.5</b> Installing the {dataedu} Package</a></li>
<li class="chapter" data-level="5.6" data-path="c05.html"><a href="c05.html#exploring-r-with-the-swirl-package"><i class="fa fa-check"></i><b>5.6</b> Exploring R with the {swirl} Package</a></li>
<li class="chapter" data-level="5.7" data-path="c05.html"><a href="c05.html#conclusion-1"><i class="fa fa-check"></i><b>5.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="c06.html"><a href="c06.html"><i class="fa fa-check"></i><b>6</b> Foundational Skills</a><ul>
<li class="chapter" data-level="6.1" data-path="c06.html"><a href="c06.html#chapter-overview-1"><i class="fa fa-check"></i><b>6.1</b> Chapter Overview</a></li>
<li class="chapter" data-level="6.2" data-path="c06.html"><a href="c06.html#foundational-skills-framework"><i class="fa fa-check"></i><b>6.2</b> Foundational Skills Framework</a><ul>
<li class="chapter" data-level="6.2.1" data-path="c06.html"><a href="c06.html#projects"><i class="fa fa-check"></i><b>6.2.1</b> Projects</a></li>
<li class="chapter" data-level="6.2.2" data-path="c06.html"><a href="c06.html#functions"><i class="fa fa-check"></i><b>6.2.2</b> Functions</a></li>
<li class="chapter" data-level="6.2.3" data-path="c06.html"><a href="c06.html#packages"><i class="fa fa-check"></i><b>6.2.3</b> Packages</a></li>
<li class="chapter" data-level="6.2.4" data-path="c06.html"><a href="c06.html#the-relationship-between-packages-and-functions"><i class="fa fa-check"></i><b>6.2.4</b> The Relationship Between Packages and Functions</a></li>
<li class="chapter" data-level="6.2.5" data-path="c06.html"><a href="c06.html#data"><i class="fa fa-check"></i><b>6.2.5</b> Data</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="c06.html"><a href="c06.html#introduction-to-help-documentation"><i class="fa fa-check"></i><b>6.3</b> Introduction to Help Documentation</a></li>
<li class="chapter" data-level="6.4" data-path="c06.html"><a href="c06.html#steps-for-working-through-new-and-unfamiliar-content"><i class="fa fa-check"></i><b>6.4</b> Steps for Working Through New and Unfamiliar Content</a><ul>
<li class="chapter" data-level="6.4.1" data-path="c06.html"><a href="c06.html#activate-prior-knowledge"><i class="fa fa-check"></i><b>6.4.1</b> Activate Prior Knowledge</a></li>
<li class="chapter" data-level="6.4.2" data-path="c06.html"><a href="c06.html#look-for-context-clues"><i class="fa fa-check"></i><b>6.4.2</b> Look for Context Clues</a></li>
<li class="chapter" data-level="6.4.3" data-path="c06.html"><a href="c06.html#check-the-help-documentation"><i class="fa fa-check"></i><b>6.4.3</b> Check the Help Documentation</a></li>
<li class="chapter" data-level="6.4.4" data-path="c06.html"><a href="c06.html#find-the-limits"><i class="fa fa-check"></i><b>6.4.4</b> Find the Limits</a></li>
<li class="chapter" data-level="6.4.5" data-path="c06.html"><a href="c06.html#test-and-refine-your-understanding"><i class="fa fa-check"></i><b>6.4.5</b> Test (and Refine) Your Understanding</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="c06.html"><a href="c06.html#bringing-it-all-together-getting-started-coding-walkthrough"><i class="fa fa-check"></i><b>6.5</b> Bringing It All Together: Getting Started Coding Walkthrough</a><ul>
<li class="chapter" data-level="6.5.1" data-path="c06.html"><a href="c06.html#creating-a-project-and-an-.r-script-and-setting-up-our-rstudio-environment"><i class="fa fa-check"></i><b>6.5.1</b> Creating a Project and an <code>.R</code> Script, and Setting Up Our RStudio Environment</a></li>
<li class="chapter" data-level="6.5.2" data-path="c06.html"><a href="c06.html#loading-data-from-dataedu-into-our-r-environment"><i class="fa fa-check"></i><b>6.5.2</b> Loading Data from {dataedu} into our R Environment</a></li>
<li class="chapter" data-level="6.5.3" data-path="c06.html"><a href="c06.html#exploring-our-data-and-common-errors"><i class="fa fa-check"></i><b>6.5.3</b> Exploring Our Data and Common Errors</a></li>
<li class="chapter" data-level="6.5.4" data-path="c06.html"><a href="c06.html#exploring-our-data-with-the-pipe-operator"><i class="fa fa-check"></i><b>6.5.4</b> Exploring Our Data with the Pipe Operator</a></li>
<li class="chapter" data-level="6.5.5" data-path="c06.html"><a href="c06.html#exploring-assignment-vs.-equality"><i class="fa fa-check"></i><b>6.5.5</b> Exploring Assignment vs. Equality</a></li>
<li class="chapter" data-level="6.5.6" data-path="c06.html"><a href="c06.html#basics-of-object-and-variable-names"><i class="fa fa-check"></i><b>6.5.6</b> Basics of Object and Variable Names</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="c06.html"><a href="c06.html#conclusion-2"><i class="fa fa-check"></i><b>6.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="c07.html"><a href="c07.html"><i class="fa fa-check"></i><b>7</b> Walkthrough 1: The Education Data Science Pipeline With Online Science Class Data</a><ul>
<li class="chapter" data-level="7.1" data-path="c07.html"><a href="c07.html#topics-covered"><i class="fa fa-check"></i><b>7.1</b> Topics Covered</a></li>
<li class="chapter" data-level="7.2" data-path="c07.html"><a href="c07.html#functions-introduced"><i class="fa fa-check"></i><b>7.2</b> Functions Introduced</a></li>
<li class="chapter" data-level="7.3" data-path="c07.html"><a href="c07.html#introduction-to-the-walkthroughs"><i class="fa fa-check"></i><b>7.3</b> Introduction to the walkthroughs</a></li>
<li class="chapter" data-level="7.4" data-path="c07.html"><a href="c07.html#vocabulary"><i class="fa fa-check"></i><b>7.4</b> Vocabulary</a></li>
<li class="chapter" data-level="7.5" data-path="c07.html"><a href="c07.html#chapter-overview-2"><i class="fa fa-check"></i><b>7.5</b> Chapter Overview</a><ul>
<li class="chapter" data-level="7.5.1" data-path="c07.html"><a href="c07.html#background"><i class="fa fa-check"></i><b>7.5.1</b> Background</a></li>
<li class="chapter" data-level="7.5.2" data-path="c07.html"><a href="c07.html#data-sources"><i class="fa fa-check"></i><b>7.5.2</b> Data Sources</a></li>
<li class="chapter" data-level="7.5.3" data-path="c07.html"><a href="c07.html#data-source-2-log-trace-data"><i class="fa fa-check"></i><b>7.5.3</b> Data Source #2: Log-Trace Data</a></li>
<li class="chapter" data-level="7.5.4" data-path="c07.html"><a href="c07.html#data-source-3-academic-achievement-and-gradebook-data"><i class="fa fa-check"></i><b>7.5.4</b> Data Source #3: Academic Achievement and Gradebook Data</a></li>
<li class="chapter" data-level="7.5.5" data-path="c07.html"><a href="c07.html#data-source-4-discussion-board-data"><i class="fa fa-check"></i><b>7.5.5</b> Data Source #4: Discussion Board Data</a></li>
<li class="chapter" data-level="7.5.6" data-path="c07.html"><a href="c07.html#methods"><i class="fa fa-check"></i><b>7.5.6</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="c07.html"><a href="c07.html#load-packages"><i class="fa fa-check"></i><b>7.6</b> Load Packages</a></li>
<li class="chapter" data-level="7.7" data-path="c07.html"><a href="c07.html#import-data"><i class="fa fa-check"></i><b>7.7</b> Import Data</a></li>
<li class="chapter" data-level="7.8" data-path="c07.html"><a href="c07.html#view-data"><i class="fa fa-check"></i><b>7.8</b> View Data</a></li>
<li class="chapter" data-level="7.9" data-path="c07.html"><a href="c07.html#process-data"><i class="fa fa-check"></i><b>7.9</b> Process Data</a><ul>
<li class="chapter" data-level="7.9.1" data-path="c07.html"><a href="c07.html#processing-the-course-data"><i class="fa fa-check"></i><b>7.9.1</b> Processing the Course Data</a></li>
<li class="chapter" data-level="7.9.2" data-path="c07.html"><a href="c07.html#joining-the-data"><i class="fa fa-check"></i><b>7.9.2</b> Joining the Data</a></li>
<li class="chapter" data-level="7.9.3" data-path="c07.html"><a href="c07.html#finding-distinct-cases-at-the-student-level"><i class="fa fa-check"></i><b>7.9.3</b> Finding Distinct Cases at the Student-Level</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="c07.html"><a href="c07.html#analysis"><i class="fa fa-check"></i><b>7.10</b> Analysis</a><ul>
<li class="chapter" data-level="7.10.1" data-path="c07.html"><a href="c07.html#about-ggplot2"><i class="fa fa-check"></i><b>7.10.1</b> About {ggplot2}</a></li>
<li class="chapter" data-level="7.10.2" data-path="c07.html"><a href="c07.html#the-relationship-between-time-spent-on-course-and-final-grade"><i class="fa fa-check"></i><b>7.10.2</b> The Relationship between Time Spent on Course and Final Grade</a></li>
<li class="chapter" data-level="7.10.3" data-path="c07.html"><a href="c07.html#linear-model-regression"><i class="fa fa-check"></i><b>7.10.3</b> Linear Model (Regression)</a></li>
</ul></li>
<li class="chapter" data-level="7.11" data-path="c07.html"><a href="c07.html#results"><i class="fa fa-check"></i><b>7.11</b> Results</a></li>
<li class="chapter" data-level="7.12" data-path="c07.html"><a href="c07.html#conclusion-3"><i class="fa fa-check"></i><b>7.12</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="c08.html"><a href="c08.html"><i class="fa fa-check"></i><b>8</b> Walkthrough 2: Approaching Gradebook Data From a Data Science Perspective</a><ul>
<li class="chapter" data-level="8.1" data-path="c08.html"><a href="c08.html#topics-covered-1"><i class="fa fa-check"></i><b>8.1</b> Topics Covered</a></li>
<li class="chapter" data-level="8.2" data-path="c08.html"><a href="c08.html#vocabulary-1"><i class="fa fa-check"></i><b>8.2</b> Vocabulary</a></li>
<li class="chapter" data-level="8.3" data-path="c08.html"><a href="c08.html#chapter-overview-3"><i class="fa fa-check"></i><b>8.3</b> Chapter Overview</a><ul>
<li class="chapter" data-level="8.3.1" data-path="c08.html"><a href="c08.html#background-1"><i class="fa fa-check"></i><b>8.3.1</b> Background</a></li>
<li class="chapter" data-level="8.3.2" data-path="c08.html"><a href="c08.html#data-sources-1"><i class="fa fa-check"></i><b>8.3.2</b> Data Sources</a></li>
<li class="chapter" data-level="8.3.3" data-path="c08.html"><a href="c08.html#methods-1"><i class="fa fa-check"></i><b>8.3.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="c08.html"><a href="c08.html#load-packages-1"><i class="fa fa-check"></i><b>8.4</b> Load Packages</a></li>
<li class="chapter" data-level="8.5" data-path="c08.html"><a href="c08.html#import-data-1"><i class="fa fa-check"></i><b>8.5</b> Import Data</a><ul>
<li class="chapter" data-level="8.5.1" data-path="c08.html"><a href="c08.html#import-using-a-file-path"><i class="fa fa-check"></i><b>8.5.1</b> Import Using a File Path</a></li>
<li class="chapter" data-level="8.5.2" data-path="c08.html"><a href="c08.html#import-using-here"><i class="fa fa-check"></i><b>8.5.2</b> Import Using <code>here()</code></a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="c08.html"><a href="c08.html#process-data-1"><i class="fa fa-check"></i><b>8.6</b> Process Data</a><ul>
<li class="chapter" data-level="8.6.1" data-path="c08.html"><a href="c08.html#tidy-data"><i class="fa fa-check"></i><b>8.6.1</b> Tidy Data</a></li>
<li class="chapter" data-level="8.6.2" data-path="c08.html"><a href="c08.html#about-janitor"><i class="fa fa-check"></i><b>8.6.2</b> About {janitor}</a></li>
<li class="chapter" data-level="8.6.3" data-path="c08.html"><a href="c08.html#create-new-variables-and-further-process-the-data"><i class="fa fa-check"></i><b>8.6.3</b> Create New Variables and Further Process the Data</a></li>
</ul></li>
<li class="chapter" data-level="8.7" data-path="c08.html"><a href="c08.html#analysis-1"><i class="fa fa-check"></i><b>8.7</b> Analysis</a><ul>
<li class="chapter" data-level="8.7.1" data-path="c08.html"><a href="c08.html#visualize-data"><i class="fa fa-check"></i><b>8.7.1</b> Visualize Data</a></li>
<li class="chapter" data-level="8.7.2" data-path="c08.html"><a href="c08.html#model-data"><i class="fa fa-check"></i><b>8.7.2</b> Model Data</a></li>
<li class="chapter" data-level="8.7.3" data-path="c08.html"><a href="c08.html#correlation-analysis"><i class="fa fa-check"></i><b>8.7.3</b> Correlation Analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="c08.html"><a href="c08.html#results-1"><i class="fa fa-check"></i><b>8.8</b> Results</a></li>
<li class="chapter" data-level="8.9" data-path="c08.html"><a href="c08.html#conclusion-4"><i class="fa fa-check"></i><b>8.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="c09.html"><a href="c09.html"><i class="fa fa-check"></i><b>9</b> Walkthrough 3: Using School-Level Aggregate Data to Illuminate Educational Inequities</a><ul>
<li class="chapter" data-level="9.1" data-path="c09.html"><a href="c09.html#topics-covered-2"><i class="fa fa-check"></i><b>9.1</b> Topics Covered</a></li>
<li class="chapter" data-level="9.2" data-path="c09.html"><a href="c09.html#functions-introduced-2"><i class="fa fa-check"></i><b>9.2</b> Functions Introduced</a></li>
<li class="chapter" data-level="9.3" data-path="c09.html"><a href="c09.html#vocabulary-2"><i class="fa fa-check"></i><b>9.3</b> Vocabulary</a></li>
<li class="chapter" data-level="9.4" data-path="c09.html"><a href="c09.html#chapter-overview-4"><i class="fa fa-check"></i><b>9.4</b> Chapter Overview</a><ul>
<li class="chapter" data-level="9.4.1" data-path="c09.html"><a href="c09.html#background-2"><i class="fa fa-check"></i><b>9.4.1</b> Background</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="c09.html"><a href="c09.html#data-sources-2"><i class="fa fa-check"></i><b>9.5</b> Data Sources</a><ul>
<li class="chapter" data-level="9.5.1" data-path="c09.html"><a href="c09.html#methods-2"><i class="fa fa-check"></i><b>9.5.1</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="c09.html"><a href="c09.html#load-packages-2"><i class="fa fa-check"></i><b>9.6</b> Load Packages</a></li>
<li class="chapter" data-level="9.7" data-path="c09.html"><a href="c09.html#import-data-2"><i class="fa fa-check"></i><b>9.7</b> Import Data</a></li>
<li class="chapter" data-level="9.8" data-path="c09.html"><a href="c09.html#view-data-1"><i class="fa fa-check"></i><b>9.8</b> View Data</a><ul>
<li class="chapter" data-level="9.8.1" data-path="c09.html"><a href="c09.html#discovering-distributions"><i class="fa fa-check"></i><b>9.8.1</b> Discovering Distributions</a></li>
<li class="chapter" data-level="9.8.2" data-path="c09.html"><a href="c09.html#analyzing-spread"><i class="fa fa-check"></i><b>9.8.2</b> Analyzing Spread</a></li>
</ul></li>
<li class="chapter" data-level="9.9" data-path="c09.html"><a href="c09.html#analysis-2"><i class="fa fa-check"></i><b>9.9</b> Analysis</a><ul>
<li class="chapter" data-level="9.9.1" data-path="c09.html"><a href="c09.html#creating-categories"><i class="fa fa-check"></i><b>9.9.1</b> Creating Categories</a></li>
<li class="chapter" data-level="9.9.2" data-path="c09.html"><a href="c09.html#reveal-relationships"><i class="fa fa-check"></i><b>9.9.2</b> Reveal Relationships</a></li>
</ul></li>
<li class="chapter" data-level="9.10" data-path="c09.html"><a href="c09.html#results-2"><i class="fa fa-check"></i><b>9.10</b> Results</a></li>
<li class="chapter" data-level="9.11" data-path="c09.html"><a href="c09.html#conclusion-5"><i class="fa fa-check"></i><b>9.11</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="c10.html"><a href="c10.html"><i class="fa fa-check"></i><b>10</b> Walkthrough 4: Longitudinal Analysis With Federal Students With Disabilities Data</a><ul>
<li class="chapter" data-level="10.1" data-path="c10.html"><a href="c10.html#topics-covered-3"><i class="fa fa-check"></i><b>10.1</b> Topics Covered</a></li>
<li class="chapter" data-level="10.2" data-path="c10.html"><a href="c10.html#functions-introduced-3"><i class="fa fa-check"></i><b>10.2</b> Functions Introduced</a></li>
<li class="chapter" data-level="10.3" data-path="c10.html"><a href="c10.html#vocabulary-3"><i class="fa fa-check"></i><b>10.3</b> Vocabulary</a></li>
<li class="chapter" data-level="10.4" data-path="c10.html"><a href="c10.html#chapter-overview-5"><i class="fa fa-check"></i><b>10.4</b> Chapter Overview</a><ul>
<li class="chapter" data-level="10.4.1" data-path="c10.html"><a href="c10.html#background-3"><i class="fa fa-check"></i><b>10.4.1</b> Background</a></li>
<li class="chapter" data-level="10.4.2" data-path="c10.html"><a href="c10.html#methods-3"><i class="fa fa-check"></i><b>10.4.2</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="c10.html"><a href="c10.html#load-packages-3"><i class="fa fa-check"></i><b>10.5</b> Load Packages</a></li>
<li class="chapter" data-level="10.6" data-path="c10.html"><a href="c10.html#import-data-3"><i class="fa fa-check"></i><b>10.6</b> Import Data</a><ul>
<li class="chapter" data-level="10.6.1" data-path="c10.html"><a href="c10.html#what-to-download"><i class="fa fa-check"></i><b>10.6.1</b> What to Download</a></li>
<li class="chapter" data-level="10.6.2" data-path="c10.html"><a href="c10.html#a-note-on-file-paths"><i class="fa fa-check"></i><b>10.6.2</b> A Note on File Paths</a></li>
<li class="chapter" data-level="10.6.3" data-path="c10.html"><a href="c10.html#how-to-download-the-files"><i class="fa fa-check"></i><b>10.6.3</b> How to Download the Files</a></li>
<li class="chapter" data-level="10.6.4" data-path="c10.html"><a href="c10.html#reading-in-one-dataset"><i class="fa fa-check"></i><b>10.6.4</b> Reading in One Dataset</a></li>
<li class="chapter" data-level="10.6.5" data-path="c10.html"><a href="c10.html#reading-in-many-datasets"><i class="fa fa-check"></i><b>10.6.5</b> Reading in Many Datasets</a></li>
<li class="chapter" data-level="10.6.6" data-path="c10.html"><a href="c10.html#loading-the-data-from-dataedu"><i class="fa fa-check"></i><b>10.6.6</b> Loading the data from {dataedu}</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="c10.html"><a href="c10.html#process-data-2"><i class="fa fa-check"></i><b>10.7</b> Process Data</a><ul>
<li class="chapter" data-level="10.7.1" data-path="c10.html"><a href="c10.html#fix-the-variable-names-in-the-2016-data"><i class="fa fa-check"></i><b>10.7.1</b> Fix the Variable Names in the 2016 Data</a></li>
<li class="chapter" data-level="10.7.2" data-path="c10.html"><a href="c10.html#pick-variables"><i class="fa fa-check"></i><b>10.7.2</b> Pick Variables</a></li>
<li class="chapter" data-level="10.7.3" data-path="c10.html"><a href="c10.html#combine-six-datasets-into-one"><i class="fa fa-check"></i><b>10.7.3</b> Combine Six Datasets into One</a></li>
<li class="chapter" data-level="10.7.4" data-path="c10.html"><a href="c10.html#importing-the-data-from-the-dataedu-package"><i class="fa fa-check"></i><b>10.7.4</b> Importing the data from the {dataedu} package</a></li>
<li class="chapter" data-level="10.7.5" data-path="c10.html"><a href="c10.html#filter-for-the-desired-disabilities-and-age-groups"><i class="fa fa-check"></i><b>10.7.5</b> Filter for the Desired Disabilities and Age Groups</a></li>
<li class="chapter" data-level="10.7.6" data-path="c10.html"><a href="c10.html#rename-the-variables"><i class="fa fa-check"></i><b>10.7.6</b> Rename the Variables</a></li>
<li class="chapter" data-level="10.7.7" data-path="c10.html"><a href="c10.html#clean-state-names"><i class="fa fa-check"></i><b>10.7.7</b> Clean State Names</a></li>
<li class="chapter" data-level="10.7.8" data-path="c10.html"><a href="c10.html#tidy-the-dataset"><i class="fa fa-check"></i><b>10.7.8</b> Tidy the Dataset</a></li>
<li class="chapter" data-level="10.7.9" data-path="c10.html"><a href="c10.html#convert-data-types"><i class="fa fa-check"></i><b>10.7.9</b> Convert Data Types</a></li>
<li class="chapter" data-level="10.7.10" data-path="c10.html"><a href="c10.html#explore-and-address-nas"><i class="fa fa-check"></i><b>10.7.10</b> Explore and Address NAs</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="c10.html"><a href="c10.html#analysis-3"><i class="fa fa-check"></i><b>10.8</b> Analysis</a><ul>
<li class="chapter" data-level="10.8.1" data-path="c10.html"><a href="c10.html#visualize-the-dataset"><i class="fa fa-check"></i><b>10.8.1</b> Visualize the Dataset</a></li>
<li class="chapter" data-level="10.8.2" data-path="c10.html"><a href="c10.html#model-the-dataset"><i class="fa fa-check"></i><b>10.8.2</b> Model the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="10.9" data-path="c10.html"><a href="c10.html#results-3"><i class="fa fa-check"></i><b>10.9</b> Results</a></li>
<li class="chapter" data-level="10.10" data-path="c10.html"><a href="c10.html#conclusion-6"><i class="fa fa-check"></i><b>10.10</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="c11.html"><a href="c11.html"><i class="fa fa-check"></i><b>11</b> Walkthrough 5: Text Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="11.1" data-path="c11.html"><a href="c11.html#vocabulary-4"><i class="fa fa-check"></i><b>11.1</b> Vocabulary</a></li>
<li class="chapter" data-level="11.2" data-path="c11.html"><a href="c11.html#chapter-overview-6"><i class="fa fa-check"></i><b>11.2</b> Chapter Overview</a><ul>
<li class="chapter" data-level="11.2.1" data-path="c11.html"><a href="c11.html#background-4"><i class="fa fa-check"></i><b>11.2.1</b> Background</a></li>
<li class="chapter" data-level="11.2.2" data-path="c11.html"><a href="c11.html#data-source"><i class="fa fa-check"></i><b>11.2.2</b> Data Source</a></li>
<li class="chapter" data-level="11.2.3" data-path="c11.html"><a href="c11.html#methods-4"><i class="fa fa-check"></i><b>11.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="c11.html"><a href="c11.html#load-packages-4"><i class="fa fa-check"></i><b>11.3</b> Load Packages</a></li>
<li class="chapter" data-level="11.4" data-path="c11.html"><a href="c11.html#import-data-4"><i class="fa fa-check"></i><b>11.4</b> Import Data</a><ul>
<li class="chapter" data-level="11.4.1" data-path="c11.html"><a href="c11.html#using-an-application-programming-interface-or-api"><i class="fa fa-check"></i><b>11.4.1</b> Using an Application Programming Interface (or API)</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="c11.html"><a href="c11.html#view-data-2"><i class="fa fa-check"></i><b>11.5</b> View Data</a></li>
<li class="chapter" data-level="11.6" data-path="c11.html"><a href="c11.html#process-data-3"><i class="fa fa-check"></i><b>11.6</b> Process Data</a></li>
<li class="chapter" data-level="11.7" data-path="c11.html"><a href="c11.html#analysis-counting-words"><i class="fa fa-check"></i><b>11.7</b> Analysis: Counting Words</a></li>
<li class="chapter" data-level="11.8" data-path="c11.html"><a href="c11.html#analysis-sentiment-analysis"><i class="fa fa-check"></i><b>11.8</b> Analysis: Sentiment analysis</a><ul>
<li class="chapter" data-level="11.8.1" data-path="c11.html"><a href="c11.html#count-positive-words"><i class="fa fa-check"></i><b>11.8.1</b> Count Positive Words</a></li>
<li class="chapter" data-level="11.8.2" data-path="c11.html"><a href="c11.html#dataviz-and-other-positive-words"><i class="fa fa-check"></i><b>11.8.2</b> “Dataviz” and Other Positive Words</a></li>
<li class="chapter" data-level="11.8.3" data-path="c11.html"><a href="c11.html#taking-a-close-read-of-randomly-selected-tweets"><i class="fa fa-check"></i><b>11.8.3</b> Taking A Close Read of Randomly Selected Tweets</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="c11.html"><a href="c11.html#conclusion-7"><i class="fa fa-check"></i><b>11.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="c12.html"><a href="c12.html"><i class="fa fa-check"></i><b>12</b> Walkthrough 6: Exploring Relationships Using Social Network Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="12.1" data-path="c12.html"><a href="c12.html#vocabulary-5"><i class="fa fa-check"></i><b>12.1</b> Vocabulary</a></li>
<li class="chapter" data-level="12.2" data-path="c12.html"><a href="c12.html#chapter-overview-7"><i class="fa fa-check"></i><b>12.2</b> Chapter Overview</a><ul>
<li class="chapter" data-level="12.2.1" data-path="c12.html"><a href="c12.html#background-5"><i class="fa fa-check"></i><b>12.2.1</b> Background</a></li>
<li class="chapter" data-level="12.2.2" data-path="c12.html"><a href="c12.html#packages-data-sources-and-import-and-methods"><i class="fa fa-check"></i><b>12.2.2</b> Packages, Data Sources and Import, and Methods</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="c12.html"><a href="c12.html#view-data-3"><i class="fa fa-check"></i><b>12.3</b> View Data</a></li>
<li class="chapter" data-level="12.4" data-path="c12.html"><a href="c12.html#process-data-4"><i class="fa fa-check"></i><b>12.4</b> Process Data</a><ul>
<li class="chapter" data-level="12.4.1" data-path="c12.html"><a href="c12.html#extracting-mentions"><i class="fa fa-check"></i><b>12.4.1</b> Extracting Mentions</a></li>
<li class="chapter" data-level="12.4.2" data-path="c12.html"><a href="c12.html#putting-the-edgelist-together"><i class="fa fa-check"></i><b>12.4.2</b> Putting the Edgelist Together</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="c12.html"><a href="c12.html#analysis-and-results"><i class="fa fa-check"></i><b>12.5</b> Analysis and Results</a><ul>
<li class="chapter" data-level="12.5.1" data-path="c12.html"><a href="c12.html#plotting-the-network"><i class="fa fa-check"></i><b>12.5.1</b> Plotting the Network</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="c12.html"><a href="c12.html#conclusion-8"><i class="fa fa-check"></i><b>12.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="c13.html"><a href="c13.html"><i class="fa fa-check"></i><b>13</b> Walkthrough 7: The Role (and Usefulness) of Multilevel Models</a><ul>
<li class="chapter" data-level="13.1" data-path="c13.html"><a href="c13.html#vocabulary-6"><i class="fa fa-check"></i><b>13.1</b> Vocabulary</a></li>
<li class="chapter" data-level="13.2" data-path="c13.html"><a href="c13.html#chapter-overview-8"><i class="fa fa-check"></i><b>13.2</b> Chapter Overview</a><ul>
<li class="chapter" data-level="13.2.1" data-path="c13.html"><a href="c13.html#background-6"><i class="fa fa-check"></i><b>13.2.1</b> Background</a></li>
<li class="chapter" data-level="13.2.2" data-path="c13.html"><a href="c13.html#data-source-1"><i class="fa fa-check"></i><b>13.2.2</b> Data Source</a></li>
<li class="chapter" data-level="13.2.3" data-path="c13.html"><a href="c13.html#methods-5"><i class="fa fa-check"></i><b>13.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="c13.html"><a href="c13.html#load-packages-5"><i class="fa fa-check"></i><b>13.3</b> Load Packages</a></li>
<li class="chapter" data-level="13.4" data-path="c13.html"><a href="c13.html#the-role-of-dummy-codes"><i class="fa fa-check"></i><b>13.4</b> The Role of Dummy Codes</a></li>
<li class="chapter" data-level="13.5" data-path="c13.html"><a href="c13.html#import-data-5"><i class="fa fa-check"></i><b>13.5</b> Import Data</a></li>
<li class="chapter" data-level="13.6" data-path="c13.html"><a href="c13.html#analysis-4"><i class="fa fa-check"></i><b>13.6</b> Analysis</a><ul>
<li class="chapter" data-level="13.6.1" data-path="c13.html"><a href="c13.html#regression-linear-model-analysis-with-dummy-codes"><i class="fa fa-check"></i><b>13.6.1</b> Regression (Linear Model) Analysis with Dummy Codes</a></li>
<li class="chapter" data-level="13.6.2" data-path="c13.html"><a href="c13.html#a-deep-dive-into-multilevel-models"><i class="fa fa-check"></i><b>13.6.2</b> A Deep-Dive into Multilevel Models</a></li>
<li class="chapter" data-level="13.6.3" data-path="c13.html"><a href="c13.html#multilevel-model-analysis"><i class="fa fa-check"></i><b>13.6.3</b> Multilevel Model Analysis</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="c13.html"><a href="c13.html#results-4"><i class="fa fa-check"></i><b>13.7</b> Results</a><ul>
<li class="chapter" data-level="13.7.1" data-path="c13.html"><a href="c13.html#adding-additional-levels"><i class="fa fa-check"></i><b>13.7.1</b> Adding Additional Levels</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="c13.html"><a href="c13.html#conclusion-9"><i class="fa fa-check"></i><b>13.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="c14.html"><a href="c14.html"><i class="fa fa-check"></i><b>14</b> Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data</a><ul>
<li class="chapter" data-level="14.1" data-path="c14.html"><a href="c14.html#vocabulary-7"><i class="fa fa-check"></i><b>14.1</b> Vocabulary</a></li>
<li class="chapter" data-level="14.2" data-path="c14.html"><a href="c14.html#chapter-overview-9"><i class="fa fa-check"></i><b>14.2</b> Chapter Overview</a><ul>
<li class="chapter" data-level="14.2.1" data-path="c14.html"><a href="c14.html#background-7"><i class="fa fa-check"></i><b>14.2.1</b> Background</a></li>
<li class="chapter" data-level="14.2.2" data-path="c14.html"><a href="c14.html#data-sources-3"><i class="fa fa-check"></i><b>14.2.2</b> Data Sources</a></li>
<li class="chapter" data-level="14.2.3" data-path="c14.html"><a href="c14.html#methods-6"><i class="fa fa-check"></i><b>14.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="c14.html"><a href="c14.html#load-packages-6"><i class="fa fa-check"></i><b>14.3</b> Load Packages</a></li>
<li class="chapter" data-level="14.4" data-path="c14.html"><a href="c14.html#import-and-view-data"><i class="fa fa-check"></i><b>14.4</b> Import and View Data</a></li>
<li class="chapter" data-level="14.5" data-path="c14.html"><a href="c14.html#process-data-5"><i class="fa fa-check"></i><b>14.5</b> Process Data</a></li>
<li class="chapter" data-level="14.6" data-path="c14.html"><a href="c14.html#analysis-5"><i class="fa fa-check"></i><b>14.6</b> Analysis</a><ul>
<li class="chapter" data-level="14.6.1" data-path="c14.html"><a href="c14.html#use-of-caret"><i class="fa fa-check"></i><b>14.6.1</b> Use of {caret}</a></li>
<li class="chapter" data-level="14.6.2" data-path="c14.html"><a href="c14.html#tuning-the-random-forest-model"><i class="fa fa-check"></i><b>14.6.2</b> Tuning the Random Forest Model</a></li>
<li class="chapter" data-level="14.6.3" data-path="c14.html"><a href="c14.html#examining-predictive-accuracy-on-the-test-data-set"><i class="fa fa-check"></i><b>14.6.3</b> Examining Predictive Accuracy on the Test Data Set</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="c14.html"><a href="c14.html#results-5"><i class="fa fa-check"></i><b>14.7</b> Results</a><ul>
<li class="chapter" data-level="14.7.1" data-path="c14.html"><a href="c14.html#variable-importance"><i class="fa fa-check"></i><b>14.7.1</b> Variable Importance</a></li>
<li class="chapter" data-level="14.7.2" data-path="c14.html"><a href="c14.html#comparing-random-forest-to-regression"><i class="fa fa-check"></i><b>14.7.2</b> Comparing Random Forest to Regression</a></li>
</ul></li>
<li class="chapter" data-level="14.8" data-path="c14.html"><a href="c14.html#conclusion-10"><i class="fa fa-check"></i><b>14.8</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="c15.html"><a href="c15.html"><i class="fa fa-check"></i><b>15</b> Introducing Data Science Tools To Your Education Job</a><ul>
<li class="chapter" data-level="15.1" data-path="c15.html"><a href="c15.html#chapter-overview-10"><i class="fa fa-check"></i><b>15.1</b> Chapter Overview</a></li>
<li class="chapter" data-level="15.2" data-path="c15.html"><a href="c15.html#the-gift-of-speed-and-scale"><i class="fa fa-check"></i><b>15.2</b> The Gift of Speed and Scale</a><ul>
<li class="chapter" data-level="15.2.1" data-path="c15.html"><a href="c15.html#working-with-data-faster"><i class="fa fa-check"></i><b>15.2.1</b> Working With Data Faster</a></li>
<li class="chapter" data-level="15.2.2" data-path="c15.html"><a href="c15.html#working-with-more-data"><i class="fa fa-check"></i><b>15.2.2</b> Working With More Data</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="c15.html"><a href="c15.html#other-ways-to-reimagine-the-scale-of-your-work"><i class="fa fa-check"></i><b>15.3</b> Other Ways to Reimagine the Scale of Your Work</a><ul>
<li class="chapter" data-level="15.3.1" data-path="c15.html"><a href="c15.html#reflect-on-your-current-scale-then-push-to-the-next-llevel"><i class="fa fa-check"></i><b>15.3.1</b> Reflect on your Current Scale, Then Push to the Next lLevel</a></li>
<li class="chapter" data-level="15.3.2" data-path="c15.html"><a href="c15.html#look-for-lots-of-similarly-structured-data"><i class="fa fa-check"></i><b>15.3.2</b> Look for Lots of Similarly Structured Data</a></li>
<li class="chapter" data-level="15.3.3" data-path="c15.html"><a href="c15.html#cleaning-data"><i class="fa fa-check"></i><b>15.3.3</b> Cleaning Data</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="c15.html"><a href="c15.html#solving-problems-together"><i class="fa fa-check"></i><b>15.4</b> Solving Problems Together</a><ul>
<li class="chapter" data-level="15.4.1" data-path="c15.html"><a href="c15.html#data-science-in-education-and-empathy"><i class="fa fa-check"></i><b>15.4.1</b> Data Science in Education and Empathy</a></li>
<li class="chapter" data-level="15.4.2" data-path="c15.html"><a href="c15.html#create-a-daily-practice-commitment-that-answers-someone-elses-question"><i class="fa fa-check"></i><b>15.4.2</b> Create a Daily Practice Commitment That Answers Someone Else’s Question</a></li>
<li class="chapter" data-level="15.4.3" data-path="c15.html"><a href="c15.html#build-your-network"><i class="fa fa-check"></i><b>15.4.3</b> Build Your Network</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="c15.html"><a href="c15.html#for-k-12-teachers"><i class="fa fa-check"></i><b>15.5</b> For K-12 Teachers</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="c16.html"><a href="c16.html"><i class="fa fa-check"></i><b>16</b> Teaching Data Science</a><ul>
<li class="chapter" data-level="16.1" data-path="c16.html"><a href="c16.html#chapter-overview-11"><i class="fa fa-check"></i><b>16.1</b> Chapter Overview</a></li>
<li class="chapter" data-level="16.2" data-path="c16.html"><a href="c16.html#the-pedagogical-principles-this-book-is-based-upon"><i class="fa fa-check"></i><b>16.2</b> 1. The Pedagogical Principles This Book is Based Upon</a><ul>
<li class="chapter" data-level="16.2.1" data-path="c16.html"><a href="c16.html#problem-based-learning"><i class="fa fa-check"></i><b>16.2.1</b> Problem-based learning</a></li>
<li class="chapter" data-level="16.2.2" data-path="c16.html"><a href="c16.html#differentiation"><i class="fa fa-check"></i><b>16.2.2</b> Differentiation</a></li>
<li class="chapter" data-level="16.2.3" data-path="c16.html"><a href="c16.html#working-in-the-open"><i class="fa fa-check"></i><b>16.2.3</b> Working in the Open</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="c16.html"><a href="c16.html#building-mental-models"><i class="fa fa-check"></i><b>16.3</b> Building Mental Models</a><ul>
<li class="chapter" data-level="16.3.1" data-path="c16.html"><a href="c16.html#universal-design"><i class="fa fa-check"></i><b>16.3.1</b> Universal Design</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="c16.html"><a href="c16.html#strategies-for-teaching-data-science"><i class="fa fa-check"></i><b>16.4</b> 2. Strategies for Teaching Data Science</a><ul>
<li class="chapter" data-level="16.4.1" data-path="c16.html"><a href="c16.html#provide-a-home-base-for-learners-to-access-resources-and-to-learn-more"><i class="fa fa-check"></i><b>16.4.1</b> Provide a Home Base for Learners to Access Resources (and to Learn More)</a></li>
<li class="chapter" data-level="16.4.2" data-path="c16.html"><a href="c16.html#when-it-comes-to-writing-code-think-early-and-often"><i class="fa fa-check"></i><b>16.4.2</b> When it Comes to Writing Code, Think Early and Often</a></li>
<li class="chapter" data-level="16.4.3" data-path="c16.html"><a href="c16.html#dont-touch-that-keyboard"><i class="fa fa-check"></i><b>16.4.3</b> Don’t Touch That Keyboard!</a></li>
<li class="chapter" data-level="16.4.4" data-path="c16.html"><a href="c16.html#anticipate-ussues-and-sacrifice-accuracy-for-clarity"><i class="fa fa-check"></i><b>16.4.4</b> Anticipate Ussues (and Sacrifice Accuracy for Clarity)</a></li>
<li class="chapter" data-level="16.4.5" data-path="c16.html"><a href="c16.html#start-lessons-or-activities-with-visualizing-data"><i class="fa fa-check"></i><b>16.4.5</b> Start Lessons or Activities With Visualizing Data</a></li>
<li class="chapter" data-level="16.4.6" data-path="c16.html"><a href="c16.html#consider-representation-and-inclusion-in-the-data-and-examples-you-use"><i class="fa fa-check"></i><b>16.4.6</b> Consider Representation and Inclusion in the Data and Examples You Use</a></li>
<li class="chapter" data-level="16.4.7" data-path="c16.html"><a href="c16.html#draw-on-other-resources"><i class="fa fa-check"></i><b>16.4.7</b> Draw on Other Resources</a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="c16.html"><a href="c16.html#general-strategies-related-to-teaching-and-learning"><i class="fa fa-check"></i><b>16.5</b> 3. General Strategies Related to Teaching and Learning</a><ul>
<li class="chapter" data-level="16.5.1" data-path="c16.html"><a href="c16.html#teaching-and-learning-are-complex"><i class="fa fa-check"></i><b>16.5.1</b> Teaching and Learning are Complex</a></li>
<li class="chapter" data-level="16.5.2" data-path="c16.html"><a href="c16.html#learners-learn-many-different-things-consciously-and-unconsciously"><i class="fa fa-check"></i><b>16.5.2</b> Learners Learn Many Different Things (Consciously and Unconsciously)</a></li>
<li class="chapter" data-level="16.5.3" data-path="c16.html"><a href="c16.html#meta-cognition-is-important-even-though-it-sounds-more-sophisticated-than-it-is"><i class="fa fa-check"></i><b>16.5.3</b> Meta-cognition is Important (Even Though it Sounds More Sophisticated Than it is!)</a></li>
<li class="chapter" data-level="16.5.4" data-path="c16.html"><a href="c16.html#learning-strategies-matter"><i class="fa fa-check"></i><b>16.5.4</b> Learning Strategies Matter</a></li>
<li class="chapter" data-level="16.5.5" data-path="c16.html"><a href="c16.html#educators-can-help-students-to-learn"><i class="fa fa-check"></i><b>16.5.5</b> Educators can help students to learn</a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="c16.html"><a href="c16.html#summary"><i class="fa fa-check"></i><b>16.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="c17.html"><a href="c17.html"><i class="fa fa-check"></i><b>17</b> Learning More</a><ul>
<li class="chapter" data-level="17.1" data-path="c17.html"><a href="c17.html#introduction"><i class="fa fa-check"></i><b>17.1</b> Introduction</a></li>
<li class="chapter" data-level="17.2" data-path="c17.html"><a href="c17.html#adopt-a-growth-mindset"><i class="fa fa-check"></i><b>17.2</b> Adopt a Growth Mindset</a></li>
<li class="chapter" data-level="17.3" data-path="c17.html"><a href="c17.html#discover-new-information"><i class="fa fa-check"></i><b>17.3</b> Discover New Information</a></li>
<li class="chapter" data-level="17.4" data-path="c17.html"><a href="c17.html#ask-for-help"><i class="fa fa-check"></i><b>17.4</b> Ask for Help</a><ul>
<li class="chapter" data-level="17.4.1" data-path="c17.html"><a href="c17.html#discussion-forums"><i class="fa fa-check"></i><b>17.4.1</b> Discussion Forums</a></li>
<li class="chapter" data-level="17.4.2" data-path="c17.html"><a href="c17.html#github-repositories"><i class="fa fa-check"></i><b>17.4.2</b> GitHub Repositories</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="c17.html"><a href="c17.html#share-what-youve-learned"><i class="fa fa-check"></i><b>17.5</b> Share What You’ve Learned</a><ul>
<li class="chapter" data-level="17.5.1" data-path="c17.html"><a href="c17.html#where-to-share"><i class="fa fa-check"></i><b>17.5.1</b> Where to Share</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="c17.html"><a href="c17.html#welcome-others"><i class="fa fa-check"></i><b>17.6</b> Welcome Others</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="c18.html"><a href="c18.html"><i class="fa fa-check"></i><b>18</b> Additional Resources</a><ul>
<li class="chapter" data-level="18.1" data-path="c18.html"><a href="c18.html#chapter-overview-12"><i class="fa fa-check"></i><b>18.1</b> Chapter Overview</a></li>
<li class="chapter" data-level="18.2" data-path="c18.html"><a href="c18.html#data-science-courses"><i class="fa fa-check"></i><b>18.2</b> Data Science Courses</a></li>
<li class="chapter" data-level="18.3" data-path="c18.html"><a href="c18.html#workshop-materials"><i class="fa fa-check"></i><b>18.3</b> Workshop Materials</a></li>
<li class="chapter" data-level="18.4" data-path="c18.html"><a href="c18.html#data-visualization"><i class="fa fa-check"></i><b>18.4</b> Data Visualization</a></li>
<li class="chapter" data-level="18.5" data-path="c18.html"><a href="c18.html#books-related-to-data-science-in-education"><i class="fa fa-check"></i><b>18.5</b> Books Related to Data Science in Education</a></li>
<li class="chapter" data-level="18.6" data-path="c18.html"><a href="c18.html#articles-related-to-data-science-in-education"><i class="fa fa-check"></i><b>18.6</b> Articles Related to Data Science in Education</a></li>
<li class="chapter" data-level="18.7" data-path="c18.html"><a href="c18.html#programming-with-r"><i class="fa fa-check"></i><b>18.7</b> Programming with R</a></li>
<li class="chapter" data-level="18.8" data-path="c18.html"><a href="c18.html#statistics"><i class="fa fa-check"></i><b>18.8</b> Statistics</a><ul>
<li class="chapter" data-level="18.8.1" data-path="c18.html"><a href="c18.html#introductory-statistics"><i class="fa fa-check"></i><b>18.8.1</b> Introductory Statistics</a></li>
<li class="chapter" data-level="18.8.2" data-path="c18.html"><a href="c18.html#advanced-statistics"><i class="fa fa-check"></i><b>18.8.2</b> Advanced Statistics</a></li>
</ul></li>
<li class="chapter" data-level="18.9" data-path="c18.html"><a href="c18.html#r-packages-and-statistical-software-development"><i class="fa fa-check"></i><b>18.9</b> R packages and Statistical Software Development</a></li>
<li class="chapter" data-level="18.10" data-path="c18.html"><a href="c18.html#a-career-in-data-science"><i class="fa fa-check"></i><b>18.10</b> A Career in Data Science</a></li>
<li class="chapter" data-level="18.11" data-path="c18.html"><a href="c18.html#places-to-share-your-work"><i class="fa fa-check"></i><b>18.11</b> Places to Share Your Work</a></li>
<li class="chapter" data-level="18.12" data-path="c18.html"><a href="c18.html#cheat-sheets"><i class="fa fa-check"></i><b>18.12</b> Cheat Sheets</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="c19.html"><a href="c19.html"><i class="fa fa-check"></i><b>19</b> Conclusion: Where to Next?</a><ul>
<li class="chapter" data-level="19.1" data-path="c19.html"><a href="c19.html#learn-in-the-context-of-education"><i class="fa fa-check"></i><b>19.1</b> Learn in the Context of Education</a></li>
<li class="chapter" data-level="19.2" data-path="c19.html"><a href="c19.html#learn-to-collaborate-with-others"><i class="fa fa-check"></i><b>19.2</b> Learn to Collaborate With Others</a></li>
<li class="chapter" data-level="19.3" data-path="c19.html"><a href="c19.html#learn-every-time-you-code"><i class="fa fa-check"></i><b>19.3</b> Learn Every Time You Code</a></li>
<li class="chapter" data-level="19.4" data-path="c19.html"><a href="c19.html#learn-to-take-strategic-breaks-to-help-solve-problems"><i class="fa fa-check"></i><b>19.4</b> Learn to Take Strategic Breaks to Help Solve Problems</a></li>
<li class="chapter" data-level="19.5" data-path="c19.html"><a href="c19.html#learn-more-meaningfully-by-knowing-your-why"><i class="fa fa-check"></i><b>19.5</b> Learn More Meaningfully By Knowing Your Why</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="c20.html"><a href="c20.html"><i class="fa fa-check"></i><b>20</b> Appendices</a><ul>
<li class="chapter" data-level="20.1" data-path="c20.html"><a href="c20.html#c20a"><i class="fa fa-check"></i><b>20.1</b> Appendix A: Importing Data</a><ul>
<li class="chapter" data-level="20.1.1" data-path="c20.html"><a href="c20.html#using-functions-to-import-data"><i class="fa fa-check"></i><b>20.1.1</b> Using Functions to Import Data</a></li>
<li class="chapter" data-level="20.1.2" data-path="c20.html"><a href="c20.html#saving-a-file-from-the-internet"><i class="fa fa-check"></i><b>20.1.2</b> Saving a File from the Internet</a></li>
<li class="chapter" data-level="20.1.3" data-path="c20.html"><a href="c20.html#loading-a-.csv-file"><i class="fa fa-check"></i><b>20.1.3</b> Loading a <code>.csv</code> File</a></li>
<li class="chapter" data-level="20.1.4" data-path="c20.html"><a href="c20.html#saving-files"><i class="fa fa-check"></i><b>20.1.4</b> Saving Files</a></li>
<li class="chapter" data-level="20.1.5" data-path="c20.html"><a href="c20.html#loading-excel-files"><i class="fa fa-check"></i><b>20.1.5</b> Loading Excel Files</a></li>
<li class="chapter" data-level="20.1.6" data-path="c20.html"><a href="c20.html#loading-sav-files"><i class="fa fa-check"></i><b>20.1.6</b> Loading SAV Files</a></li>
<li class="chapter" data-level="20.1.7" data-path="c20.html"><a href="c20.html#google-sheets"><i class="fa fa-check"></i><b>20.1.7</b> Google Sheets</a></li>
</ul></li>
<li class="chapter" data-level="20.2" data-path="c20.html"><a href="c20.html#appendix-b-accessing-twitter-data-c20b"><i class="fa fa-check"></i><b>20.2</b> Appendix B: Accessing Twitter Data {c20b}</a><ul>
<li class="chapter" data-level="20.2.1" data-path="c20.html"><a href="c20.html#accessing-historical-twitter-data-using-already-collected-status-urls"><i class="fa fa-check"></i><b>20.2.1</b> Accessing Historical Twitter Data Using Already-Collected Status URLs</a></li>
<li class="chapter" data-level="20.2.2" data-path="c20.html"><a href="c20.html#accessing-historical-data-when-you-do-not-have-access-to-status-urls"><i class="fa fa-check"></i><b>20.2.2</b> Accessing Historical Data When You Do Not Have Access to Status URLs</a></li>
</ul></li>
<li class="chapter" data-level="20.3" data-path="c20.html"><a href="c20.html#c20c"><i class="fa fa-check"></i><b>20.3</b> Appendix C: Social Network Influence and Selection Models</a><ul>
<li class="chapter" data-level="20.3.1" data-path="c20.html"><a href="c20.html#an-example-of-influence"><i class="fa fa-check"></i><b>20.3.1</b> An Example of Influence</a></li>
<li class="chapter" data-level="20.3.2" data-path="c20.html"><a href="c20.html#joining-the-data-1"><i class="fa fa-check"></i><b>20.3.2</b> Joining the Data</a></li>
<li class="chapter" data-level="20.3.3" data-path="c20.html"><a href="c20.html#an-example-of-selection"><i class="fa fa-check"></i><b>20.3.3</b> An Example of Selection</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="c20.html"><a href="c20.html#appendix-d-colophon"><i class="fa fa-check"></i><b>20.4</b> Appendix D: Colophon</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://www.emilybovee.com/">Emily A. Bovee</a></li>
<li><a href="https://ryanestrellado.netlify.com/">Ryan A. Estrellado</a></li>
<li><a href="https://www.jessemaegan.com/">Jesse Mostipak</a></li>
<li><a href="https://joshuamrosenberg.com/">Joshua M. Rosenberg</a></li>
<li><a href="https://ivelasq.rbind.io/">Isabella C. Velásquez</a></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science in Education Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="c14" class="section level1">
<h1><span class="header-section-number">14</span> Walkthrough 8: Predicting Students’ Final Grades Using Machine Learning Methods with Online Course Data</h1>
<div id="vocabulary-7" class="section level2">
<h2><span class="header-section-number">14.1</span> Vocabulary</h2>
<ul>
<li>listwise deletion</li>
<li>machine learning</li>
<li>parameters</li>
<li>random forest</li>
<li>research question</li>
<li>resampling</li>
<li>Root Mean Square Error</li>
<li>rsquared</li>
<li>training data</li>
<li>test data</li>
<li>tuning parameter</li>
<li>variable importance</li>
</ul>
</div>
<div id="chapter-overview-9" class="section level2">
<h2><span class="header-section-number">14.2</span> Chapter Overview</h2>
<p>In this chapter, we use the same dataset used in <a href="c07.html#c07">Walkthrough 1/Chapter 7</a> and <a href="c13.html#c13">Walkthrough 7/Chapter 13</a>, but pursue a new aim. We focus on <em>predicting</em> an outcome, final grade, more than <em>explaining</em> how variables relate to an outcome, such as how the amount of time students spend on the course relate to their final grade. We illustrate a common but powerful machine learning method, random forests. We’ll explore their use in-depth rather than providing a more general overview of other machine learning methods. Though we focus on the use of random forests, many of the ideas explored in this chapter will likely extend and prove useful for other machine learning methods. Our goal is for you to finish this final walkthrough with the confidence to explore using machine learning to answer a question or to solve a problem of your own with respect to teaching, learning, and educational systems.</p>
<div id="background-7" class="section level3">
<h3><span class="header-section-number">14.2.1</span> Background</h3>
<p>One area of interest for data scientists in education is the delivery of online instruction, which is becoming more prevalent: in 2007, over 3.9 million U.S. students were enrolled one or more online courses <span class="citation">(Allen &amp; Seaman, <a href="references.html#ref-allen2008">2008</a>)</span>. With the growth of online learning comes an abundance of new educational tools to facilitate that learning. Online learning platforms are used to submit assignments and quizzes in courses in which students and instructor meet face-to-face, but these interfaces are also used in fully online courses to deliver instruction and assessment.</p>
<p>In a face-to-face classroom, an educator might count on behavioral cues to help them effectively deliver instruction. Online, educators do not readily have access to the behavioral cues essential for effective face-to-face instruction. For example, in a face-to-face classroom, cues such as a student missing class repeatedly or many students seeming distracted during a lecture can trigger a shift in the delivery of instruction. Many educators find themselves looking for ways to understand and support students online in the same way that face-to-face instructors would. Educational technology affords unique opportunities to support student success online because it provides new methods of collecting and storing data.</p>
<p>Online learning management systems often automatically track several types of student interactions with the system and feed that data back to the course instructor. For example, an instructor might be able to quickly see how many students logged into their course on a certain day, or they might see how long students engaged with a posted video before pausing it or logging out. The collection of this data is met with mixed reactions from educators. Some are concerned that data collection in this manner is intrusive but others see a new opportunity to support students in online contexts in new ways. As long as data are collected and utilized responsibly, data collection can support student success.</p>
<p>One meaningful perspective from which to consider students’ engagement with online courses is related to their motivation to achieve. It is important to consider how and why students are engaging with the course. Considering the psychological mechanisms behind achievement is valuable because they may help identify meaningful points of intervention. Educators, researchers, and administrators in both online <em>and</em> face-to-face courses can analyze and use the intersection between behavioral measures and students’ motivational and emotional experiences in courses.</p>
<p>In this walkthrough, we examine the educational experiences of students attending online science courses at a virtual middle school in order to characterize their motivation to achieve and their tangible engagement with the course. We use a dataset that includes self-reported motivation as well as behavioral trace data collected from a learning management system (LMS) to identify predictors of final course grade. Our work examines educational success in terms of student interactions with an online science course.</p>
<p>We explore the following four questions:</p>
<ol style="list-style-type: decimal">
<li>Is motivation more predictive of course grades as compared to other online indicators of engagement?</li>
<li>Which types of motivation are most predictive of achievement?</li>
<li>Which types of trace measures are most predictive of achievement?</li>
<li>How does a random forest compare to a simple linear model (regression)?</li>
</ol>
</div>
<div id="data-sources-3" class="section level3">
<h3><span class="header-section-number">14.2.2</span> Data Sources</h3>
<p>This dataset came from 499 students enrolled in online middle school science courses in 2015-2016. The data were originally collected for use as a part of a research study, though the findings have not been published yet.</p>
<p>The setting of this study was a public provider of individual online courses in a Midwestern state. In particular, the context was two semesters (Fall and Spring) of offerings of five online science courses (Anatomy &amp; Physiology, Forensic Science, Oceanography, Physics, and Biology), with a total of 36 classes.</p>
<p>Specific information in the dataset included:</p>
<ul>
<li>a pre-course survey students completed about their self-reported motivation in science — in particular, their perceived competence, utility value, and interest</li>
<li>the time students spent on the course (obtained from the learning management system (LMS), Blackboard</li>
<li>students’ final course grades</li>
<li>students’ involvement in discussion forums</li>
</ul>
<p>For discussion board responses, we were interested in calculating the number of posts per student and understanding the emotional tone of the discussion board posts. We used the Linguistic Inquiry and Word Count (LIWC; Pennebaker, Boyd, Jordan, &amp; Blackburn, 2015) tool to calculate the number of posts per student and to categorize the emotional tone (positive or negative) and topics of those posts. Those linguistic categorization was conducted after the data was gathered from the discussion posts, but is not replicated here to protect the privacy of the students’ posts. Instead, we present the already-categorized discussion board data, in its ready-to-use format. In the dataset used in this walkthrough, we will see pre-created variables for the mean levels of students’ cognitive processing, positive emotions, negative emotions, and social-related discourse.</p>
<p>At the beginning of the semester, students were asked to complete the pre-course survey about their perceived competence, utility value, and interest. At the end of the semester, the time students spent on the course, their final course grades, and the contents of the discussion forums were collected.</p>
</div>
<div id="methods-6" class="section level3">
<h3><span class="header-section-number">14.2.3</span> Methods</h3>
<p><strong>Defining a Research Question</strong></p>
<p>When you begin a new project, there are often many approaches to analyzing data and answering questions you might have about it. Some projects have a clearly defined scope and question to answer. This type of project is characterized by 1) a defined number of variables (data inputs) and 2) specific directional hypotheses. For example, if we are studying the effect of drinking coffee after dinner on ability to quickly fall asleep, we might have a very specific directional hypothesis: we expect that drinking coffee after dinner would decrease the ability to fall asleep quickly. In this case, we might collect data by having some people drink coffee and having other people drink nothing or an herbal tea before bed. We could monitor how quickly people from each group fall asleep. Since we collected data from two clearly defined groups, we can then do a statistical analysis that compares the amount of time it takes to fall asleep for each group. One option would be a test called a t-test, which we could use to see if there is a significant difference in the average amount of minutes to fall asleep for the group. This approach works very well in controlled experimental situations, especially when we can change only one thing at a time (in our coffee example, the only thing we changed was the coffee-drinking behavior of our participants - all other life conditions were held equal for both groups). Rarely are educational data projects as clear-cut and simple.</p>
<p>For this walkthrough, we have many sources of data - survey data, learning management system data, discussion forum data, and academic achievement data as measured by final course grades. Luckily, having too much data is what we call a “good problem.” In our coffee example above, we had one really specific idea that we wanted to investigate - does coffee affect time taken to fall asleep? In this walkthrough we have many ideas we are curious to explore: the relationships among motivation, engagement in the course (discussion boards, time spent online in the course site), and academic achievement. If we wanted to tackle a simpler problem, we could choose just one of these relationships. For example, we could measure whether students with high motivation earn higher grades than students with low motivation. However, we are being a bit more ambitious than that here - we are interested in understanding the complex relationships among the different types of motivation. Rather than simply exploring whether A affects B, we are interested in the nuances. We suspect that <em>many</em> factors affect B, and we would like to see which of those factors has most relative importance. To explore this idea, we will use a machine learning approach.</p>
<p><strong>Predictive Analytics and Machine Learning</strong></p>
<p>A buzzword in education software spheres these days is “predictive analytics.” Administrators and educators alike are interested in applying the methods long utilized by marketers and other business professionals to try to determine what a person will want, need, or do next. “Predictive analytics” is a blanket term that can be used to describe any statistical approach that yields a prediction. We could ask a predictive model: “What is the likelihood that my cat will sit on my keyboard today?” and, given enough past information about your cat’s computer-sitting behavior, the model could give you a probability of that computer-sitting happening today. Under the hood, some predictive models are not very complex. If we have an outcome with two possibilities, a logistic regression model could be fit to the data in order to help us answer the cat-keyboard question. In this chapter, we’ll compare a machine learning model to another type of regression: multiple regression. We want to make sure to fit the simplest model as possible to our data. After all, the effectiveness in predicting the outcome is really the most important thing, not the fanciness of the model.</p>
<p>Data collection is an essential first step in any type of machine learning or predictive analytics. It is important to note here that machine learning only works effectively when (1) a person selects variables to include in the model that are anticipated to be related to the outcome and (2) a person correctly interprets the model’s findings. There is an adage that goes, “garbage in, garbage out.” This holds true here. If we do not feel confident that the data we collected are accurate, we will not be able to be confident in our conclusions no matter what model we build. To collect good data, we must first clarify what it is that we want to know (i.e., what question are we really asking?) and what information we would need in order to effectively answer that question. Sometimes, people approach analysis from the opposite direction - they might look at the data they have and ask what questions could be answered based on that data. That approach is okay, as long as you are willing to acknowledge that sometimes the pre-existing dataset may <em>not</em> contain all the information you need, and you might need to go out and find additional information to add to your dataset to truly answer your question.</p>
<p>When people talk about “machine learning,” you might get the image in your head of a desktop computer learning how to spell. You might picture your favorite social media site showing you advertisements that are just a little too accurate. At its core, machine learning is the process of “showing” your statistical model only some of the data at once and training the model to predict accurately on that training dataset (this is the “learning” part of machine learning). Then, the model as developed on the training data is shown new data - data you had all along, but hid from your computer initially - and you see how well the model that you developed on the training data performs on this new testing data. Eventually, you might use the model on entirely new data.</p>
<p><strong>Random Forest</strong></p>
<p>For our analyses, we use Random Forest modeling <span class="citation">(Breiman, <a href="references.html#ref-breiman2001">2001</a>)</span>. Random forest is an extension of decision tree modeling, whereby a collection of decision trees are simultaneously “grown” and are evaluated based on out-of-sample predictive accuracy <span class="citation">(Breiman, <a href="references.html#ref-breiman2001">2001</a>)</span>. Random forest is random in two main ways: first, each tree is only allowed to “see” and split on a limited number of predictors instead of all the predictors in the parameter space; second, a random subsample of the data is used to grow each individual tree, such that no individual case is weighted too heavily in the final prediction.</p>
<p>One thing about random forest that makes it quite different from other types of analysis we might do is that here, we are giving the computer a large amount of information and asking it to find connections that might not be immediately visible to the naked human eye. This is great for a couple of reasons. First, while humans are immensely creative and clever, we are not immune to biases. If we are exploring a dataset, we usually come in with some predetermined notions about what we think is true, and we might (consciously or unconsciously) seek evidence that supports the hypothesis we privately hold. By setting the computer loose on some data, we can learn that there are connections between areas that we did not expect. We must also be ready for our hypotheses to not be supported! Random forest is particularly well-suited to the research questions explored here because we do not have specific directional hypotheses. Machine learning researchers talk about this as “exploring the parameter space” - we want to see what connections exist, and we acknowledge that we might not be able to accurately predict all the possible connections. Indeed, we expect - and hope - that we will find surprising connections.</p>
<p>Whereas some machine learning approaches (e.g., boosted trees) use an iterative model-building approach, random forest estimates all the decision trees at once. This way, each tree is independent of every other tree. The random forest algorithm provides a regression approach that is distinct from other modeling approaches. The final random forest model aggregates the findings across all the separate trees in the forest in order to offer a collection of “most important” variables as well as a percent variance explained for the final model.</p>
<p>500 trees are grown as part of our random forest. We partitioned the data before conducting the main analysis so that neither the training nor the testing data set would be disproportionately representative of high-achieving or low-achieving students. The training data set consisted of 80% of the original data (<em>n</em> = 400 cases), whereas the testing data set consisted of 20% of the original data (<em>n</em> = 99 cases). We built our random forest model on the training data set, and then evaluated the model on the testing data set. Three variables were tried at each node.</p>
<p>Note that the random forest algorithm does not accept cases with missing data, so we delete cases listwise (that is, an entire row is deleted if any single value is missing). This decision eliminated 60 cases from our original data set to bring us to our final sample size of 464 unique students. If you have a very small dataset with a lot of missing data, the random forest approach may not be well suited for your goals – you might consider a linear regression instead.</p>
<p>A random forest is well suited to the research questions that we had here because it allows for nonlinear modeling. We hypothesized complex relationships between students’ motivation, their engagement with the online courses, and their achievement. For this reason, a traditional regressive or structural equation model would have been insufficient to model the parameter space we were interesting in modeling. Our random forest model had one outcome and eleven predictors.</p>
<p>One term you will hear used in machine learning is “tuning parameter.” People often think of tuning parameters as knobs or dials on a radio: they are features of the model that can be adjusted to get the clearest signal. A common tuning parameter for machine learning models is the number of variables considered at each split <span class="citation">(Kuhn &amp; others, <a href="references.html#ref-kuhn2008">2008</a>)</span>; we considered three variables at each split for this analysis.</p>
<p>The outcome was the final course grade that the student earned. The predictor variables included motivation variables (interest value, utility value, and science perceived competence) and trace variables (the amount of time spent in the course, the course name, the number of discussion board posts over the course of the semester, the mean level of cognitive processing evident in discussion board posts, the positive emotions evident in discussion board posts, the negative emotions evident in discussion board posts, and the social-related discourse evident in their discussion board posts). We used this random forest model to address all three of our research questions.</p>
<p>To interpret our findings, we will consider three main factors: (1) predictive accuracy of the random forest model, (2) variable importance, and (3) variance explained by the final random forest model. In this walkthrough, we will use the R package {caret} <span class="citation">(Kuhn, <a href="references.html#ref-R-caret">2020</a>)</span> to carry out the analysis. We also use the {tidylog} package <span class="citation">(Elbers, <a href="references.html#ref-R-tidylog">2020</a>)</span> to help us to understand how the data processing steps we take have the desired effect.</p>
</div>
</div>
<div id="load-packages-6" class="section level2">
<h2><span class="header-section-number">14.3</span> Load Packages</h2>
<p>First, we will load the data. Our data is stored in the {dataedu} package that is part of this book. Within that package, the data is stored as an <code>.rda</code> file. We note that this data is augmented to have some other - and additional - variables that the <code>sci_mo_processed</code> data used in <a href="#c7">Chapter 7</a> does not.</p>
</div>
<div id="import-and-view-data" class="section level2">
<h2><span class="header-section-number">14.4</span> Import and View Data</h2>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb309-1" title="1"><span class="co"># Loading the data from the .rda file and storing it as an object named &#39;data&#39;</span></a>
<a class="sourceLine" id="cb309-2" title="2">df &lt;-<span class="st"> </span>dataedu<span class="op">::</span>sci_mo_with_text</a></code></pre></div>
<p>It’s a good practice to take a look at the data and make sure it looks the way you expect it to look. R is pretty smart, but sometimes we run into issues like column headers being read as datapoints. By using the <code>glimpse()</code> function from the {dplyr} package, we can quickly skim our data and see whether we have all the right variables and values. Remember that the {dplyr} package loads automatically when we load the {tidyverse} library, so there is no need to call the {dplyr} package separately. Now, we’ll glimpse the data.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb310-1" title="1"><span class="kw">glimpse</span>(df)</a></code></pre></div>
<pre><code>## Rows: 606
## Columns: 74
## $ student_id            &lt;dbl&gt; 43146, 44638, 47448, 47979, 48797, 51943, 52326…
## $ course_id             &lt;chr&gt; &quot;FrScA-S216-02&quot;, &quot;OcnA-S116-01&quot;, &quot;FrScA-S216-01…
## $ total_points_possible &lt;dbl&gt; 3280, 3531, 2870, 4562, 2207, 4208, 4325, 2086,…
## $ total_points_earned   &lt;dbl&gt; 2220, 2672, 1897, 3090, 1910, 3596, 2255, 1719,…
## $ percentage_earned     &lt;dbl&gt; 0.6768293, 0.7567261, 0.6609756, 0.6773345, 0.8…
## $ subject               &lt;chr&gt; &quot;FrScA&quot;, &quot;OcnA&quot;, &quot;FrScA&quot;, &quot;OcnA&quot;, &quot;PhysA&quot;, &quot;FrS…
## $ semester              &lt;chr&gt; &quot;S216&quot;, &quot;S116&quot;, &quot;S216&quot;, &quot;S216&quot;, &quot;S116&quot;, &quot;S216&quot;,…
## $ section               &lt;chr&gt; &quot;02&quot;, &quot;01&quot;, &quot;01&quot;, &quot;01&quot;, &quot;01&quot;, &quot;03&quot;, &quot;01&quot;, &quot;01&quot;,…
## $ Gradebook_Item        &lt;chr&gt; &quot;POINTS EARNED &amp; TOTAL COURSE POINTS&quot;, &quot;ATTEMPT…
## $ Grade_Category        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
## $ final_grade           &lt;dbl&gt; 93.45372, 81.70184, 88.48758, 81.85260, 84.0000…
## $ Points_Possible       &lt;dbl&gt; 5, 10, 10, 5, 438, 5, 10, 10, 443, 5, 12, 10, 5…
## $ Points_Earned         &lt;dbl&gt; NA, 10.00, NA, 4.00, 399.00, NA, NA, 10.00, 425…
## $ Gender                &lt;chr&gt; &quot;M&quot;, &quot;F&quot;, &quot;M&quot;, &quot;M&quot;, &quot;F&quot;, &quot;F&quot;, &quot;M&quot;, &quot;F&quot;, &quot;F&quot;, &quot;M…
## $ q1                    &lt;dbl&gt; 5, 4, 5, 5, 4, NA, 5, 3, 4, NA, NA, 4, 3, 5, NA…
## $ q2                    &lt;dbl&gt; 4, 4, 4, 5, 3, NA, 5, 3, 3, NA, NA, 5, 3, 3, NA…
## $ q3                    &lt;dbl&gt; 4, 3, 4, 3, 3, NA, 3, 3, 3, NA, NA, 3, 3, 5, NA…
## $ q4                    &lt;dbl&gt; 5, 4, 5, 5, 4, NA, 5, 3, 4, NA, NA, 5, 3, 5, NA…
## $ q5                    &lt;dbl&gt; 5, 4, 5, 5, 4, NA, 5, 3, 4, NA, NA, 5, 4, 5, NA…
## $ q6                    &lt;dbl&gt; 5, 4, 4, 5, 4, NA, 5, 4, 3, NA, NA, 5, 3, 5, NA…
## $ q7                    &lt;dbl&gt; 5, 4, 4, 4, 4, NA, 4, 3, 3, NA, NA, 5, 3, 5, NA…
## $ q8                    &lt;dbl&gt; 5, 5, 5, 5, 4, NA, 5, 3, 4, NA, NA, 4, 3, 5, NA…
## $ q9                    &lt;dbl&gt; 4, 4, 3, 5, NA, NA, 5, 3, 2, NA, NA, 5, 2, 2, N…
## $ q10                   &lt;dbl&gt; 5, 4, 5, 5, 3, NA, 5, 3, 5, NA, NA, 4, 4, 5, NA…
## $ time_spent            &lt;dbl&gt; 1555.1667, 1382.7001, 860.4335, 1598.6166, 1481…
## $ TimeSpent_hours       &lt;dbl&gt; 25.91944500, 23.04500167, 14.34055833, 26.64361…
## $ TimeSpent_std         &lt;dbl&gt; -0.18051496, -0.30780313, -0.69325954, -0.14844…
## $ int                   &lt;dbl&gt; 5.0, 4.2, 5.0, 5.0, 3.8, 4.6, 5.0, 3.0, 4.2, NA…
## $ pc                    &lt;dbl&gt; 4.50, 3.50, 4.00, 3.50, 3.50, 4.00, 3.50, 3.00,…
## $ uv                    &lt;dbl&gt; 4.333333, 4.000000, 3.666667, 5.000000, 3.50000…
## $ enrollment_status     &lt;chr&gt; &quot;Approved/Enrolled&quot;, &quot;Approved/Enrolled&quot;, &quot;Appr…
## $ enrollment_reason     &lt;chr&gt; &quot;Course Unavailable at Local School&quot;, &quot;Course U…
## $ cogproc               &lt;dbl&gt; 15.069737, 7.106667, 15.165854, 14.508000, 16.6…
## $ male                  &lt;dbl&gt; 0.51210526, 0.00000000, 0.11121951, 0.00000000,…
## $ female                &lt;dbl&gt; 0.16657895, 0.00000000, 0.15219512, 0.00000000,…
## $ friend                &lt;dbl&gt; 0.00000000, 0.00000000, 0.01268293, 0.00000000,…
## $ family                &lt;dbl&gt; 0.006052632, 0.000000000, 0.084878049, 0.000000…
## $ social                &lt;dbl&gt; 6.200526, 6.140000, 5.052927, 6.133000, 7.53400…
## $ sad                   &lt;dbl&gt; 0.18078947, 0.00000000, 0.09097561, 0.00000000,…
## $ anger                 &lt;dbl&gt; 0.41868421, 0.00000000, 0.14097561, 0.10800000,…
## $ anx                   &lt;dbl&gt; 0.080000000, 0.000000000, 0.275365854, 0.788000…
## $ negemo                &lt;dbl&gt; 1.1363158, 0.0000000, 1.4187805, 1.1520000, 1.2…
## $ posemo                &lt;dbl&gt; 3.555526, 19.010000, 2.906098, 5.591000, 3.7940…
## $ affect                &lt;dbl&gt; 4.756053, 19.010000, 4.330732, 6.743000, 5.0750…
## $ quant                 &lt;dbl&gt; 2.046842, 2.743333, 3.245366, 3.214000, 2.55100…
## $ number                &lt;dbl&gt; 0.9131579, 3.4733333, 2.3065854, 0.2570000, 0.2…
## $ interrog              &lt;dbl&gt; 1.2857895, 0.4433333, 1.7868293, 1.1030000, 1.7…
## $ compare               &lt;dbl&gt; 2.4213158, 4.1466667, 3.9021951, 2.6990000, 3.9…
## $ adj                   &lt;dbl&gt; 5.106842, 5.480000, 5.614390, 5.213000, 4.61800…
## $ verb                  &lt;dbl&gt; 18.11368, 11.02333, 16.34366, 16.31100, 17.1170…
## $ negate                &lt;dbl&gt; 1.2060526, 0.0000000, 1.6809756, 1.1300000, 0.7…
## $ conj                  &lt;dbl&gt; 5.565526, 6.660000, 5.370244, 6.203000, 7.24400…
## $ adverb                &lt;dbl&gt; 6.243421, 6.660000, 5.824878, 5.314000, 6.49200…
## $ auxverb               &lt;dbl&gt; 11.298421, 9.246667, 10.226341, 8.890000, 9.494…
## $ prep                  &lt;dbl&gt; 12.301579, 11.850000, 12.132927, 13.626000, 12.…
## $ article               &lt;dbl&gt; 7.828947, 2.223333, 6.767805, 9.119000, 9.83000…
## $ ipron                 &lt;dbl&gt; 6.936316, 2.743333, 5.145122, 4.335000, 7.84100…
## $ they                  &lt;dbl&gt; 1.01026316, 0.00000000, 0.84341463, 1.86300000,…
## $ shehe                 &lt;dbl&gt; 0.54342105, 0.00000000, 0.16951220, 0.00000000,…
## $ you                   &lt;dbl&gt; 1.7442105, 3.4733333, 1.1487805, 2.0490000, 2.6…
## $ we                    &lt;dbl&gt; 0.06578947, 0.00000000, 0.03317073, 0.30200000,…
## $ i                     &lt;dbl&gt; 3.646579, 7.993333, 4.689268, 3.449000, 3.14200…
## $ ppron                 &lt;dbl&gt; 7.010000, 11.470000, 6.882927, 7.662000, 6.7790…
## $ pronoun               &lt;dbl&gt; 13.98868, 14.20667, 12.02756, 12.21900, 14.6190…
## $ `function`            &lt;dbl&gt; 55.15447, 44.63000, 49.40293, 53.12700, 57.5090…
## $ Dic                   &lt;dbl&gt; 86.27895, 86.31000, 80.72220, 86.49700, 90.4870…
## $ Sixltr                &lt;dbl&gt; 20.89316, 22.20333, 20.80780, 21.80200, 15.3060…
## $ WPS                   &lt;dbl&gt; 17.413947, 9.833333, 17.922439, 18.824000, 15.6…
## $ Tone                  &lt;dbl&gt; 56.62395, 96.38000, 49.41610, 78.36900, 55.3840…
## $ Authentic             &lt;dbl&gt; 44.13079, 70.25333, 41.22366, 49.03800, 42.2500…
## $ Clout                 &lt;dbl&gt; 49.52079, 53.58333, 40.11024, 53.08800, 54.0850…
## $ Analytic              &lt;dbl&gt; 55.70316, 56.04000, 58.98098, 69.95700, 55.8200…
## $ WC                    &lt;dbl&gt; 88.31579, 34.66667, 69.34146, 61.20000, 47.1000…
## $ n                     &lt;dbl&gt; 38, 3, 41, 10, 10, 2, 21, 18, 31, 37, 37, 18, 1…</code></pre>
<p>Scanning the data we glimpsed, we see that we have 606 observations and 74 variables. Many of these variables - everything below <code>WC</code> except the variable <code>n</code> - are related to the text content of the discussion board posts. Our analysis here is not focused on the specifics of the discussion board posts, so we will select just a few variables from the LIWC analysis. If you’re interested in learning more about analyzing text, the text analysis walkthrough in <a href="c11.html#c11">Chapter 11</a> would be a good place to start.</p>
<p>As is the case with many datasets you’ll work with in education contexts, there is lots of great information in this dataset - but we won’t need all of it. Even if your dataset has many variables, for most analyses you will find that you are only interested in some of them. There are statistical reasons not to include twenty or more variables in a data analysis as well. At a certain point, adding more variables will <em>appear</em> to make your analysis more accurate, but will in fact obscure the truth from you. It’s generally a good practice to select a few variables you are interested in and go from there. As we discussed above, the way to do this is to start with the research questions you are trying to answer.</p>
</div>
<div id="process-data-5" class="section level2">
<h2><span class="header-section-number">14.5</span> Process Data</h2>
<p>Since we are interested in data from one specific semester, we’ll need to narrow down the data to make sure that we only include datapoints relevant to that semester. For each step, we save over the previous version of the “df” object so that our working environment doesn’t get cluttered with each new version of the dataset. Keep in mind that the original data will stay intact, and that any changes we make to it within R will not overwrite that original data (unless we tell R to specifically save out a new file with exactly the same name as the original file). Changes we make within our working environment are all totally reversible.</p>
<p>Below, we <em>filter</em> to remove all the datapoints from the spring 2017 semester (indicated by a value of <code>S217</code> for the <code>semester</code> variable). We use the <code>!</code> to indicate that we want to keep all datapoints EXCEPT the datapoints that have a value of <code>S217</code> for the semester variable. Then, we will <em>select</em> only the variables we are interested in: motivation, time spent in the course, grade in the course, subject, enrollment information, positive and negative emotions, cognitive processing, and the number of discussion board posts. After this step, we see that 60 variables have been removed from the dataset.</p>
<div class="sourceCode" id="cb312"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb312-1" title="1"><span class="co">#filtering the data to only include 2016 data. </span></a>
<a class="sourceLine" id="cb312-2" title="2"></a>
<a class="sourceLine" id="cb312-3" title="3">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb312-4" title="4"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb312-5" title="5"><span class="st">    </span><span class="kw">filter</span>(semester <span class="op">!=</span><span class="st"> &quot;S217&quot;</span>)</a></code></pre></div>
<pre><code>## filter: no rows removed</code></pre>
<div class="sourceCode" id="cb314"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb314-1" title="1"><span class="co">#selecting only the variables we are interested in: </span></a>
<a class="sourceLine" id="cb314-2" title="2">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb314-3" title="3"><span class="st">    </span>df <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb314-4" title="4"><span class="st">    </span><span class="kw">select</span>(</a>
<a class="sourceLine" id="cb314-5" title="5">        int,</a>
<a class="sourceLine" id="cb314-6" title="6">        uv,</a>
<a class="sourceLine" id="cb314-7" title="7">        pc,</a>
<a class="sourceLine" id="cb314-8" title="8">        time_spent,</a>
<a class="sourceLine" id="cb314-9" title="9">        final_grade,</a>
<a class="sourceLine" id="cb314-10" title="10">        subject,</a>
<a class="sourceLine" id="cb314-11" title="11">        enrollment_reason,</a>
<a class="sourceLine" id="cb314-12" title="12">        semester,</a>
<a class="sourceLine" id="cb314-13" title="13">        enrollment_status,</a>
<a class="sourceLine" id="cb314-14" title="14">        cogproc,</a>
<a class="sourceLine" id="cb314-15" title="15">        social,</a>
<a class="sourceLine" id="cb314-16" title="16">        posemo,</a>
<a class="sourceLine" id="cb314-17" title="17">        negemo,</a>
<a class="sourceLine" id="cb314-18" title="18">        n</a>
<a class="sourceLine" id="cb314-19" title="19">    )</a></code></pre></div>
<pre><code>## select: dropped 60 variables (student_id, course_id, total_points_possible, total_points_earned, percentage_earned, …)</code></pre>
</div>
<div id="analysis-5" class="section level2">
<h2><span class="header-section-number">14.6</span> Analysis</h2>
<div id="use-of-caret" class="section level3">
<h3><span class="header-section-number">14.6.1</span> Use of {caret}</h3>
<p>Here, we remove observations with missing data (per our note above about random forests requiring complete cases).</p>
<div class="sourceCode" id="cb316"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb316-1" title="1"><span class="co"># checking how many rows are in our dataset</span></a>
<a class="sourceLine" id="cb316-2" title="2"><span class="co"># we see that we have 606 rows</span></a>
<a class="sourceLine" id="cb316-3" title="3"><span class="kw">nrow</span>(df)</a></code></pre></div>
<pre><code>## [1] 606</code></pre>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb318-1" title="1"><span class="co"># calling the na.omit function to eliminate ANY rows that have ANY missing data</span></a>
<a class="sourceLine" id="cb318-2" title="2">df &lt;-<span class="st"> </span><span class="kw">na.omit</span>(df)</a></code></pre></div>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb319-1" title="1"><span class="co"># checking whether our na.omit call worked as expected</span></a>
<a class="sourceLine" id="cb319-2" title="2"><span class="co"># after running the code above, we see that we now have 464 rows</span></a>
<a class="sourceLine" id="cb319-3" title="3"><span class="kw">nrow</span>(df)</a></code></pre></div>
<pre><code>## [1] 464</code></pre>
<p>Machine learning methods often involve using a large number of variables. Some of these variables will not be suitable to use: they may be highly correlated with other variables or may have very little - or no - variability. For the data set used in this study, one variable has the same (character string) value for all of the observations. We can detect this variable and any others using the following function:</p>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb321-1" title="1"><span class="co"># run the nearZeroVar function to determine </span></a>
<a class="sourceLine" id="cb321-2" title="2"><span class="co"># if there are variables with NO variability</span></a>
<a class="sourceLine" id="cb321-3" title="3"><span class="kw">nearZeroVar</span>(df, <span class="dt">saveMetrics =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<pre><code>##                   freqRatio percentUnique zeroVar   nzv
## int                1.314815     9.0517241   FALSE FALSE
## uv                 1.533333     6.4655172   FALSE FALSE
## pc                 1.488372     3.8793103   FALSE FALSE
## time_spent         1.000000   100.0000000   FALSE FALSE
## final_grade        1.333333    93.1034483   FALSE FALSE
## subject            1.648649     1.0775862   FALSE FALSE
## enrollment_reason  3.154762     1.0775862   FALSE FALSE
## semester           1.226601     0.6465517   FALSE FALSE
## enrollment_status  0.000000     0.2155172    TRUE  TRUE
## cogproc            1.000000    96.9827586   FALSE FALSE
## social             1.500000    96.1206897   FALSE FALSE
## posemo             1.000000    96.7672414   FALSE FALSE
## negemo            13.000000    90.7327586   FALSE FALSE
## n                  1.333333    10.1293103   FALSE FALSE</code></pre>
<p>After conducting our zero variance check, we want to scan the <code>zeroVar</code> column to see if any of our variables failed this check. If we see any <code>TRUE</code> values for <code>zeroVar</code>, that means we should look more closely at that variable.</p>
<p>In the nearZeroVar() function we just ran, we see a result in the ZeroVar column of <code>TRUE</code> for the <code>enrollment_status</code> variable. If we look at <code>enrollment_status</code>, we will see that it is “Approved/Enrolled” for <em>all</em> of the students. Using variables with no variability in certain models may cause problems, and so we remove them first.</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb323-1" title="1"><span class="co"># taking the dataset and re-saving it as the same dataset, </span></a>
<a class="sourceLine" id="cb323-2" title="2"><span class="co"># but without the enrollment status variable</span></a>
<a class="sourceLine" id="cb323-3" title="3">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb323-4" title="4"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb323-5" title="5"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>enrollment_status)</a></code></pre></div>
<pre><code>## select: dropped one variable (enrollment_status)</code></pre>
<p>As we have discussed elsewhere in the book, the data will often come to you in a format that is not ready for immediate analysis. You may wish to pre-process the variables, such as by centering or scaling them. For our current dataset, we can work on pre-processing with code below. We set this next code chunk up to not run here (if you are viewing the book online), as we will do this analysis with the variables’ original values.</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb325-1" title="1"><span class="co"># example pre-processing step: manipulating the dataset &#39;df&#39; </span></a>
<a class="sourceLine" id="cb325-2" title="2"><span class="co"># so that if a variable is numeric, its format will now be scale</span></a>
<a class="sourceLine" id="cb325-3" title="3">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb325-4" title="4"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb325-5" title="5"><span class="st">    </span><span class="kw">mutate_if</span>(is.numeric, scale)</a></code></pre></div>
<p>As another pre-processing step, we want to make sure our text data is in a format that we can then evaluate. To facilitate that, we change character string variables into factors. Factors store data as categorical variables, each with its own levels. Because categorical variables are used in statistical models differently than continuous variables, storing data as factors ensures that the modeling functions will treat them correctly.</p>
<div class="sourceCode" id="cb326"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb326-1" title="1"><span class="co"># converting the text (character) variables in our dataset into factors</span></a>
<a class="sourceLine" id="cb326-2" title="2">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb326-3" title="3"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb326-4" title="4"><span class="st">    </span><span class="kw">mutate_if</span>(is.character, as.factor)</a></code></pre></div>
<pre><code>## mutate_if: converted &#39;subject&#39; from character to factor (0 new NA)</code></pre>
<pre><code>##            converted &#39;enrollment_reason&#39; from character to factor (0 new NA)</code></pre>
<pre><code>##            converted &#39;semester&#39; from character to factor (0 new NA)</code></pre>
<p>Now we will prepare the <strong>train</strong> and <strong>test</strong> datasets, using the {caret} function for creating data partitions. Here, the <strong>p</strong> argument specifies what proportion of the data we want to be in the <strong>training</strong> partition. Note that this function splits the data based upon the outcome, so that the training and test data sets will both have comparable values for the outcome. This means that since our outcome is final grade, we are making sure that we don’t have either a training or testing dataset that has too many good grades <em>or</em> too many bad grades. Note the <code>times = 1</code> argument. This parameter can be used to create <em>multiple</em> train and test sets, something we will describe in more detail later. Before we create our training and testing datasets, we want to “set the seed” (introduced in <a href="c11.html#c11">Chapter 11</a>). Setting the seed ensures that if we run this same code again, we will get the same results in terms of the data partition. The seed can be any number that you like - some people choose their birthday or another meaningful number. The only constraint is that when you open the same code file again to run in the future, you do not change the number you selected for your seed. This enables your code to be reproducible. If anyone runs the same code file on any computer, anywhere, they will get the same result.</p>
<p>Now try running the code chunk below. Be sure to read the messages that R gives you to see what is happening with each step!</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb330-1" title="1"><span class="co"># First, we set a seed to ensure the reproducibility of our data partition.</span></a>
<a class="sourceLine" id="cb330-2" title="2"><span class="kw">set.seed</span>(<span class="dv">2020</span>)</a>
<a class="sourceLine" id="cb330-3" title="3"></a>
<a class="sourceLine" id="cb330-4" title="4"><span class="co"># we create a new object called trainIndex that will take 80 percent of the data</span></a>
<a class="sourceLine" id="cb330-5" title="5">trainIndex &lt;-<span class="st"> </span><span class="kw">createDataPartition</span>(df<span class="op">$</span>final_grade,</a>
<a class="sourceLine" id="cb330-6" title="6">                                  <span class="dt">p =</span> <span class="fl">.8</span>, </a>
<a class="sourceLine" id="cb330-7" title="7">                                  <span class="dt">list =</span> <span class="ot">FALSE</span>,</a>
<a class="sourceLine" id="cb330-8" title="8">                                  <span class="dt">times =</span> <span class="dv">1</span>)</a>
<a class="sourceLine" id="cb330-9" title="9"></a>
<a class="sourceLine" id="cb330-10" title="10"><span class="co"># We add a new variable to our dataset, temporarily:</span></a>
<a class="sourceLine" id="cb330-11" title="11"><span class="co"># this will let us select our rows according to their row number</span></a>
<a class="sourceLine" id="cb330-12" title="12"><span class="co"># we populate the rows with the numbers 1:464, in order</span></a>
<a class="sourceLine" id="cb330-13" title="13"></a>
<a class="sourceLine" id="cb330-14" title="14">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb330-15" title="15"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb330-16" title="16"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">temp_id =</span> <span class="dv">1</span><span class="op">:</span><span class="dv">464</span>)</a></code></pre></div>
<pre><code>## mutate: new variable &#39;temp_id&#39; with 464 unique values and 0% NA</code></pre>
<div class="sourceCode" id="cb332"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb332-1" title="1"><span class="co"># we filter our dataset so that we get only the </span></a>
<a class="sourceLine" id="cb332-2" title="2"><span class="co"># rows indicated by our &quot;trainIndex&quot; vector</span></a>
<a class="sourceLine" id="cb332-3" title="3">df_train &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb332-4" title="4"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb332-5" title="5"><span class="st">    </span><span class="kw">filter</span>(temp_id <span class="op">%in%</span><span class="st"> </span>trainIndex)</a></code></pre></div>
<pre><code>## filter: removed 92 rows (20%), 372 rows remaining</code></pre>
<div class="sourceCode" id="cb334"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb334-1" title="1"><span class="co"># we filter our dataset in a different way so that we get only the rows </span></a>
<a class="sourceLine" id="cb334-2" title="2"><span class="co"># NOT in our &quot;trainIndex&quot; vector </span></a>
<a class="sourceLine" id="cb334-3" title="3"><span class="co"># adding the ! before the temp_id variable achieves the opposite of </span></a>
<a class="sourceLine" id="cb334-4" title="4"><span class="co"># what we did in the line of code above</span></a>
<a class="sourceLine" id="cb334-5" title="5"></a>
<a class="sourceLine" id="cb334-6" title="6">df_test &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb334-7" title="7"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb334-8" title="8"><span class="st">    </span><span class="kw">filter</span>(<span class="op">!</span>temp_id <span class="op">%in%</span><span class="st"> </span>trainIndex)</a></code></pre></div>
<pre><code>## filter: removed 372 rows (80%), 92 rows remaining</code></pre>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb336-1" title="1"><span class="co"># We delete the temp_id variable from (1) the original data, </span></a>
<a class="sourceLine" id="cb336-2" title="2"><span class="co"># (2) the portion of the original data we marked as training, and </span></a>
<a class="sourceLine" id="cb336-3" title="3"><span class="co"># (3) the portion of the original data we marked as testing, </span></a>
<a class="sourceLine" id="cb336-4" title="4"><span class="co"># as we no longer need that variable</span></a>
<a class="sourceLine" id="cb336-5" title="5"></a>
<a class="sourceLine" id="cb336-6" title="6">df &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb336-7" title="7"><span class="st">    </span>df <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb336-8" title="8"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>temp_id)</a></code></pre></div>
<pre><code>## select: dropped one variable (temp_id)</code></pre>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb338-1" title="1">df_train &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb338-2" title="2"><span class="st">    </span>df_train <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb338-3" title="3"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>temp_id)</a></code></pre></div>
<pre><code>## select: dropped one variable (temp_id)</code></pre>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb340-1" title="1">df_test &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb340-2" title="2"><span class="st">    </span>df_test <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb340-3" title="3"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span>temp_id)</a></code></pre></div>
<pre><code>## select: dropped one variable (temp_id)</code></pre>
<p>Finally, we will estimate the models. We will use the train function, passing <em>all</em> of the variables in the data frame (except for the outcome, or dependent variable, <code>final_grade</code>) as predictors.</p>
<p>The predictor variables include three indicators of motivation: interest in the course (<code>int</code>), perceived utility value of the course (<code>uv</code>), and perceived competence for the subject matter (<code>pc</code>). There are a few predictor variables that help differentiate between the different courses in the dataset: subject matter of the course (<code>subject</code>), reason the student enrolled in the course (<code>enrollment_reason</code>), and semester in which the course took place (<code>semester</code>). We have a predictor variable that indicates the amount of time each student spent engaging with the online learning platform of the course (<code>time_spent</code>).</p>
<p>We also have a number of variables associated with the discussion board posts from the course. Specifically, the variables include the average level of cognitive processing in the discussion board posts (<code>cogproc</code>), the average level of social (rather than academic) content in the discussion board posts (<code>social</code>), the positive and negative emotions evident in the discussion board posts (<code>posemo</code> and <code>negemo</code>), and finally, the number of discussion board posts in total (<code>n</code>). We are using all those variables discussed in this paragraph to predict the outcome of the final grade in the course (<code>final_grade</code>).</p>
<p>Note that you can read more about the specific random forest implementation chosen in <a href="http://topepo.github.io/caret/train-models-by-tag.html#random-forest">the {caret} bookdown page</a> (http<a href=""></a>://topepo.github.io/caret/train-models-by-tag.html#random-forest). To specify that we want to predict the outcome using every variable except the outcome itself, we use the formulation <code>outcome ~ .</code>. R interprets this code as: predict the outcome using all the variables except outcome itself. The outcome always comes before the <code>~</code>, and the <code>.</code> that we see after the <code>~</code> means that we want to use all the rest of the variables. An alternative specification of this model would be to write <code>outcome ~ predictor1, predictor2</code>. Anything that follows the <code>~</code> and precedes the comma is treated as predictors of the outcome.</p>
<p>We set the seed again to ensure that our analysis is reproducible. This step of setting the seed is especially important due to the “random” elements of random forest, because it’s likely that the findings would change (just slightly) if the seed were not set. As we get into random forest modeling, you might notice that the code takes a bit longer to run. This is normal - just think of the number of decision trees that are “growing”!</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb342-1" title="1"><span class="co"># setting a seed for reproducibility</span></a>
<a class="sourceLine" id="cb342-2" title="2"><span class="kw">set.seed</span>(<span class="dv">2020</span>)</a>
<a class="sourceLine" id="cb342-3" title="3"></a>
<a class="sourceLine" id="cb342-4" title="4"><span class="co"># we run the model here</span></a>
<a class="sourceLine" id="cb342-5" title="5">rf_fit &lt;-<span class="st"> </span><span class="kw">train</span>(final_grade <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb342-6" title="6">                <span class="dt">data =</span> df_train,</a>
<a class="sourceLine" id="cb342-7" title="7">                <span class="dt">method =</span> <span class="st">&quot;ranger&quot;</span>)</a>
<a class="sourceLine" id="cb342-8" title="8"></a>
<a class="sourceLine" id="cb342-9" title="9"><span class="co"># here, we get a summary of the model we just built</span></a>
<a class="sourceLine" id="cb342-10" title="10">rf_fit</a></code></pre></div>
<pre><code>## Random Forest 
## 
## 372 samples
##  12 predictor
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 372, 372, 372, 372, 372, 372, ... 
## Resampling results across tuning parameters:
## 
##   mtry  splitrule   RMSE      Rsquared   MAE      
##    2    variance    15.26965  0.5646105  11.182943
##    2    extratrees  16.99412  0.5228177  12.064817
##   10    variance    13.96625  0.5926815  10.144724
##   10    extratrees  13.87205  0.6205291  10.068379
##   19    variance    14.05020  0.5886314  10.023326
##   19    extratrees  13.41310  0.6319288   9.766645
## 
## Tuning parameter &#39;min.node.size&#39; was held constant at a value of 5
## RMSE was used to select the optimal model using the smallest value.
## The final values used for the model were mtry = 19, splitrule = extratrees
##  and min.node.size = 5.</code></pre>
<p>We have some results! First, we see that we have 372 samples, or 372 observations, the number in the train data set. No pre-processing steps were specified in the model fitting, but note that the output of <code>preProcess</code> can be passed to <code>train()</code> to center, scale, and transform the data in many other ways. Next, we used a resampling technique. This resampling is not for validating the model but is rather for selecting the tuning parameters - the options that need to be specified as a part of the modeling. These parameters can be manually provided, or can be estimated via strategies such as the bootstrap resample or <em>k</em>-folds cross validation.</p>
<p>As we interpret these findings, we are looking to minimize the Root Mean Square Error (RMSE) and maximize the variance explained (rsquared).</p>
<p>It appears that the model with the value of the <code>mtry</code> tuning parameter equal to 19 seemed to explain the data best, the <code>splitrule</code> being “extratrees”, and <code>min.node.size</code> held constant at a value of 5. We know this model fits best because the RMSE is the lowest of the options (12.76) and the Rsquared is the highest of the options (0.65).</p>
<p>The value of resampling here is that it allows for higher accuracy of the model <span class="citation">(James et al., <a href="references.html#ref-james2013">2013</a>)</span>. Without resampling (bootstrapping or cross-validation), the variance would be higher and the predictive accuracy of the model would be lower.</p>
<p>Let’s see if we end up with slightly different values if we change the resampling technique to cross-validation, instead of bootstrap resampling. We set a seed again here, for reproducibility.</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb344-1" title="1"><span class="kw">set.seed</span>(<span class="dv">2020</span>)</a>
<a class="sourceLine" id="cb344-2" title="2"></a>
<a class="sourceLine" id="cb344-3" title="3">train_control &lt;-</a>
<a class="sourceLine" id="cb344-4" title="4"><span class="st">    </span><span class="kw">trainControl</span>(<span class="dt">method =</span> <span class="st">&quot;repeatedcv&quot;</span>,</a>
<a class="sourceLine" id="cb344-5" title="5">                 <span class="dt">number =</span> <span class="dv">10</span>,</a>
<a class="sourceLine" id="cb344-6" title="6">                 <span class="dt">repeats =</span> <span class="dv">10</span>)</a>
<a class="sourceLine" id="cb344-7" title="7"></a>
<a class="sourceLine" id="cb344-8" title="8">rf_fit1 &lt;-</a>
<a class="sourceLine" id="cb344-9" title="9"><span class="st">    </span><span class="kw">train</span>(final_grade <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb344-10" title="10">          <span class="dt">data =</span> df_train,</a>
<a class="sourceLine" id="cb344-11" title="11">          <span class="dt">method =</span> <span class="st">&quot;ranger&quot;</span>,</a>
<a class="sourceLine" id="cb344-12" title="12">          <span class="dt">trControl =</span> train_control)</a>
<a class="sourceLine" id="cb344-13" title="13"></a>
<a class="sourceLine" id="cb344-14" title="14">rf_fit1</a></code></pre></div>
<pre><code>## Random Forest 
## 
## 372 samples
##  12 predictor
## 
## No pre-processing
## Resampling: Cross-Validated (10 fold, repeated 10 times) 
## Summary of sample sizes: 335, 334, 334, 336, 334, 334, ... 
## Resampling results across tuning parameters:
## 
##   mtry  splitrule   RMSE      Rsquared   MAE      
##    2    variance    14.64664  0.5896743  10.965898
##    2    extratrees  16.24513  0.5854833  11.787050
##   10    variance    13.29633  0.6181503   9.829458
##   10    extratrees  13.00986  0.6599769   9.655362
##   19    variance    13.25465  0.6167849   9.683722
##   19    extratrees  12.59520  0.6635394   9.363926
## 
## Tuning parameter &#39;min.node.size&#39; was held constant at a value of 5
## RMSE was used to select the optimal model using the smallest value.
## The final values used for the model were mtry = 19, splitrule = extratrees
##  and min.node.size = 5.</code></pre>
</div>
<div id="tuning-the-random-forest-model" class="section level3">
<h3><span class="header-section-number">14.6.2</span> Tuning the Random Forest Model</h3>
<p>When we look at this output, we are looking to see which values of the various tuning parameters were selected. We see at the bottom of the output above that the value of <code>mtry</code> was 19, the split rule was “extratrees,” and the minimum node size is 5. We let this model explore which value of <code>mtry</code> was best and to explore whether extra trees or variance was a better split rule, but we forced all iterations of the model to a minimum node size of five (so that minimum node size value in the output shouldn’t be a surprise to us). When we look at the bottom row of the output, it shows the final values selected for the model. We see also that this row has the lowest RMSE and highest Rsquared value, which means it has the lowest error and highest predictive power.</p>
<p>We won’t dive into the specifics of the statistics behind these decisions right now, but next we will try adjusting a few different parts of the model to see whether our performance improves. For a detailed statistical explanation of random forest modeling, including more about <code>mtry</code> and tuning a model, please see Chapter 8 in the book “An Introduction to Statistical Learning with Applications in R” <span class="citation">(James et al., <a href="references.html#ref-james2013">2013</a>)</span>.</p>
<p>What would happen if we do not fix <code>min.node.size</code> to five? We’re going to let <code>min.node.size</code> change and let <code>mtry</code> change as well.</p>
<p>Let’s create our own grid of values to test for <code>mtry</code> and <code>min.node.size</code>. We’ll stick with the default bootstrap resampling method to choose the best model. We will randomly choose some values to use for <code>mtry</code>, including the three that were used previously (2, 10, and 19). Let’s try 2, 3, 7, 10, and 19.</p>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb346-1" title="1"><span class="co"># setting a seed for reproducibility</span></a>
<a class="sourceLine" id="cb346-2" title="2"><span class="kw">set.seed</span>(<span class="dv">2020</span>)</a>
<a class="sourceLine" id="cb346-3" title="3"></a>
<a class="sourceLine" id="cb346-4" title="4"><span class="co"># Create a grid of different values of mtry, different splitrules, and different minimum node sizes to test</span></a>
<a class="sourceLine" id="cb346-5" title="5">tune_grid &lt;-</a>
<a class="sourceLine" id="cb346-6" title="6"><span class="st">    </span><span class="kw">expand.grid</span>(</a>
<a class="sourceLine" id="cb346-7" title="7">        <span class="dt">mtry =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">10</span>, <span class="dv">19</span>),</a>
<a class="sourceLine" id="cb346-8" title="8">        <span class="dt">splitrule =</span> <span class="kw">c</span>(<span class="st">&quot;variance&quot;</span>, <span class="st">&quot;extratrees&quot;</span>),</a>
<a class="sourceLine" id="cb346-9" title="9">        <span class="dt">min.node.size =</span> <span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>, <span class="dv">20</span>)</a>
<a class="sourceLine" id="cb346-10" title="10">    )</a>
<a class="sourceLine" id="cb346-11" title="11"></a>
<a class="sourceLine" id="cb346-12" title="12"><span class="co"># Fit a new model, using the tuning grid we created above</span></a>
<a class="sourceLine" id="cb346-13" title="13">rf_fit2 &lt;-</a>
<a class="sourceLine" id="cb346-14" title="14"><span class="st">    </span><span class="kw">train</span>(final_grade <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb346-15" title="15">          <span class="dt">data =</span> df_train,</a>
<a class="sourceLine" id="cb346-16" title="16">          <span class="dt">method =</span> <span class="st">&quot;ranger&quot;</span>,</a>
<a class="sourceLine" id="cb346-17" title="17">          <span class="dt">tuneGrid =</span> tune_grid)</a>
<a class="sourceLine" id="cb346-18" title="18"></a>
<a class="sourceLine" id="cb346-19" title="19">rf_fit2</a></code></pre></div>
<pre><code>## Random Forest 
## 
## 372 samples
##  12 predictor
## 
## No pre-processing
## Resampling: Bootstrapped (25 reps) 
## Summary of sample sizes: 372, 372, 372, 372, 372, 372, ... 
## Resampling results across tuning parameters:
## 
##   mtry  splitrule   min.node.size  RMSE      Rsquared   MAE      
##    2    variance     1             15.21257  0.5640999  11.115597
##    2    variance     5             15.26810  0.5638393  11.181907
##    2    variance    10             15.45130  0.5541338  11.348051
##    2    variance    15             15.56036  0.5497028  11.445290
##    2    variance    20             15.72194  0.5426742  11.573521
##    2    extratrees   1             16.92739  0.5217704  11.959970
##    2    extratrees   5             17.02815  0.5177077  12.076823
##    2    extratrees  10             17.28776  0.5060890  12.265775
##    2    extratrees  15             17.44764  0.5016608  12.390719
##    2    extratrees  20             17.67751  0.4891901  12.556140
##    3    variance     1             14.65669  0.5738730  10.730009
##    3    variance     5             14.71055  0.5718560  10.796714
##    3    variance    10             14.84534  0.5667383  10.938649
##    3    variance    15             15.01766  0.5573860  11.077530
##    3    variance    20             15.17448  0.5497694  11.222043
##    3    extratrees   1             15.73859  0.5602534  11.197195
##    3    extratrees   5             15.87463  0.5561978  11.312669
##    3    extratrees  10             16.18226  0.5450388  11.578177
##    3    extratrees  15             16.41014  0.5386357  11.749329
##    3    extratrees  20             16.64769  0.5297996  11.902915
##    7    variance     1             14.06354  0.5891298  10.265146
##    7    variance     5             14.05089  0.5901984  10.256999
##    7    variance    10             14.17334  0.5839552  10.372204
##    7    variance    15             14.24620  0.5806848  10.456265
##    7    variance    20             14.36375  0.5755600  10.560296
##    7    extratrees   1             14.27671  0.6067836  10.306448
##    7    extratrees   5             14.37512  0.6034048  10.371551
##    7    extratrees  10             14.54903  0.6000708  10.539154
##    7    extratrees  15             14.73613  0.5956554  10.679249
##    7    extratrees  20             14.99862  0.5858391  10.874959
##   10    variance     1             13.94020  0.5933172  10.118910
##   10    variance     5             13.95884  0.5925954  10.130894
##   10    variance    10             13.99612  0.5912951  10.177994
##   10    variance    15             14.06937  0.5871199  10.264013
##   10    variance    20             14.12505  0.5849011  10.326244
##   10    extratrees   1             13.81434  0.6225194  10.002114
##   10    extratrees   5             13.87943  0.6192667  10.082908
##   10    extratrees  10             14.07823  0.6131080  10.220691
##   10    extratrees  15             14.29597  0.6060346  10.383784
##   10    extratrees  20             14.42182  0.6028746  10.489607
##   19    variance     1             14.01330  0.5904613   9.988716
##   19    variance     5             14.04655  0.5882967  10.010647
##   19    variance    10             14.05683  0.5881496  10.029118
##   19    variance    15             14.07198  0.5876164  10.069665
##   19    variance    20             14.09864  0.5865583  10.079718
##   19    extratrees   1             13.35989  0.6335635   9.729254
##   19    extratrees   5             13.39873  0.6325685   9.746579
##   19    extratrees  10             13.51532  0.6285967   9.834457
##   19    extratrees  15             13.59740  0.6260692   9.903994
##   19    extratrees  20             13.74330  0.6213098  10.014353
## 
## RMSE was used to select the optimal model using the smallest value.
## The final values used for the model were mtry = 19, splitrule = extratrees
##  and min.node.size = 1.</code></pre>
<p>The model with the same values as identified before for <code>mtry</code> (19) and <code>splitrule</code> (extratrees), but with <code>min.node.size</code> equal to 1 (not 5, as before) seems to fit best. We know this model fits best because the RMSE is lowest (13.36) and the variance explained is highest (0.63) for this model, though the improvement seems to be fairly small relative to the difference the other tuning parameters seem to make.</p>
<p>While the output above gives us a good summary of the model, we might want to look more closely at what we found with our <code>rf_fit2</code> model. The code below is a way for us to zoom in and look specifically at the <em>final</em> random forest model generated by our <code>rf_fit2.</code></p>
<p>In the code chunk below, you’ll notice we are selecting the “finalModel” output using a <code>$</code> operator rather than the familiar <code>select</code>. We cannot use {dplyr} and the tidyverse here because of the structure of the <code>rf_fit2</code> object - we have stored a random forest model as a model, so it’s not a normal data frame. So, we extract with a <code>$</code>. We want to select only the final model used and not worry about the prior iterations of the model.</p>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb348-1" title="1"><span class="co">#Here, we select the &quot;finalModel&quot; output from the rf_fit2 model</span></a>
<a class="sourceLine" id="cb348-2" title="2">rf_fit2<span class="op">$</span>finalModel</a></code></pre></div>
<pre><code>## Ranger result
## 
## Call:
##  ranger::ranger(dependent.variable.name = &quot;.outcome&quot;, data = x,      mtry = min(param$mtry, ncol(x)), min.node.size = param$min.node.size,      splitrule = as.character(param$splitrule), write.forest = TRUE,      probability = classProbs, ...) 
## 
## Type:                             Regression 
## Number of trees:                  500 
## Sample size:                      372 
## Number of independent variables:  19 
## Mtry:                             19 
## Target node size:                 1 
## Variable importance mode:         none 
## Splitrule:                        extratrees 
## Number of random splits:          1 
## OOB prediction error (MSE):       159.8603 
## R squared (OOB):                  0.6599865</code></pre>
<p>In looking at this output, we see the same parameters we noted above: <code>mtry</code> is 19, the node size is 1, and the split rule is extra trees. We can also note the <em>OOB prediction error (MSE)</em>, of 159.86, and the proportion of the variance explained, or R squared, of 0.66. As before, we want the error to be low and the variance explained to be high.</p>
<p>Now that we understand how to develop a basic machine learning model and how to use different tuning parameters (such as node size and the splitting rule), we can explore some other related themes. We might wonder about how we could examine the predictive accuracy of the random forest model we just developed.</p>
</div>
<div id="examining-predictive-accuracy-on-the-test-data-set" class="section level3">
<h3><span class="header-section-number">14.6.3</span> Examining Predictive Accuracy on the Test Data Set</h3>
<p>What if we use the test data set - data not used to train the model? Below, we’ll create a new object that uses the <code>rf_fit2</code> model we developed above. We will put our testing data through the model, and assign the predicted values to a column called <code>pred</code>. At the same, time, we’ll make a column called <code>obs</code> that includes the real final grades that students earned. Later, we’ll compare these predicted and observed values to see how well our model did.</p>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb350-1" title="1"><span class="co"># setting a seed for reproducibility</span></a>
<a class="sourceLine" id="cb350-2" title="2"><span class="kw">set.seed</span>(<span class="dv">2020</span>)</a>
<a class="sourceLine" id="cb350-3" title="3"></a>
<a class="sourceLine" id="cb350-4" title="4"><span class="co"># Create a new object for the testing data including predicted values </span></a>
<a class="sourceLine" id="cb350-5" title="5">df_test_augmented &lt;-</a>
<a class="sourceLine" id="cb350-6" title="6"><span class="st">    </span>df_test <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb350-7" title="7"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">predict</span>(rf_fit2, df_test),</a>
<a class="sourceLine" id="cb350-8" title="8">           <span class="dt">obs =</span> final_grade)</a></code></pre></div>
<pre><code>## mutate: new variable &#39;pred&#39; with 92 unique values and 0% NA</code></pre>
<pre><code>##         new variable &#39;obs&#39; with 90 unique values and 0% NA</code></pre>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb353-1" title="1"><span class="co"># Transform this new object into a data frame</span></a>
<a class="sourceLine" id="cb353-2" title="2"><span class="kw">defaultSummary</span>(<span class="kw">as.data.frame</span>(df_test_augmented))</a></code></pre></div>
<pre><code>##       RMSE   Rsquared        MAE 
## 12.9821088  0.5517269  9.9735400</code></pre>
<p>We can compare this to the values above to see how our model performs when given data that was not used to train the model. Comparing the RMSE values, we see that the RMSE is about the same when we use the model on the test data as it was on the training data. We get a value of 12.98 on the test data here, and it was 13.36 on the training data. The Rsquared value is 0.55 here, as compared to the 0.63 we got when we passed the training data through <code>rf_fit2</code> earlier.</p>
<p>While we might have expected that the model performance would be worse for the testing data as compared to the training data, we actually are seeing marginal improvements here: the model does better with the test data than with the training data. These results suggest to us that the model is able to handle new data, as we get comparable - in fact, improved - results when running the model on data it has never “seen” before (the testing data). This is good news!</p>
</div>
</div>
<div id="results-5" class="section level2">
<h2><span class="header-section-number">14.7</span> Results</h2>
<div id="variable-importance" class="section level3">
<h3><span class="header-section-number">14.7.1</span> Variable Importance</h3>
<p>One helpful characteristic of random forest models is that we can learn about which variables contributed most strongly to the predictions in our model, across all the trees in our forest.</p>
<p>We can examine two different variable importance measures using the <strong>ranger</strong> method in {caret}.</p>
<p>Note that importance values are not calculated automatically, but that “impurity” or “permutation” can be passed to the <code>importance</code> argument in <code>train()</code>. See more on <a href="https://alexisperrier.com/datascience/2015/08/27/feature-importance-random-forests-gini-accuracy.html">this website</a> (https<a href=""></a>://alexisperrier.com/datascience/2015/08/27/feature-importance-random-forests-gini-accuracy.html).</p>
<p>We’ll re-run the <code>rf_fit2</code> model with the same specifications as before, but this time we will add an argument to call the variable importance metric.</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb355-1" title="1"><span class="co"># setting a seed for reproducibility</span></a>
<a class="sourceLine" id="cb355-2" title="2"><span class="kw">set.seed</span>(<span class="dv">2020</span>)</a>
<a class="sourceLine" id="cb355-3" title="3"></a>
<a class="sourceLine" id="cb355-4" title="4"><span class="co"># Specify the same model as earlier in the chapter (rf_fit2) with the addition of the variable importance metric</span></a>
<a class="sourceLine" id="cb355-5" title="5">rf_fit2_imp &lt;-</a>
<a class="sourceLine" id="cb355-6" title="6"><span class="st">    </span><span class="kw">train</span>(</a>
<a class="sourceLine" id="cb355-7" title="7">        final_grade <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb355-8" title="8">        <span class="dt">data =</span> df_train,</a>
<a class="sourceLine" id="cb355-9" title="9">        <span class="dt">method =</span> <span class="st">&quot;ranger&quot;</span>,</a>
<a class="sourceLine" id="cb355-10" title="10">        <span class="dt">tuneGrid =</span> tune_grid,</a>
<a class="sourceLine" id="cb355-11" title="11">        <span class="dt">importance =</span> <span class="st">&quot;permutation&quot;</span></a>
<a class="sourceLine" id="cb355-12" title="12">    )</a>
<a class="sourceLine" id="cb355-13" title="13"></a>
<a class="sourceLine" id="cb355-14" title="14"><span class="co"># Extract the variable importance from this new model</span></a>
<a class="sourceLine" id="cb355-15" title="15"><span class="kw">varImp</span>(rf_fit2_imp)</a></code></pre></div>
<pre><code>## ranger variable importance
## 
##                                                      Overall
## n                                                   100.0000
## subjectFrScA                                         20.8268
## time_spent                                           13.6802
## subjectPhysA                                          5.2882
## semesterS216                                          4.0628
## negemo                                                3.1369
## pc                                                    2.5582
## social                                                2.3604
## posemo                                                1.7236
## int                                                   0.9332
## cogproc                                               0.7290
## enrollment_reasonScheduling Conflict                  0.5157
## enrollment_reasonLearning Preference of the Student   0.4661
## enrollment_reasonOther                                0.4123
## uv                                                    0.3871
## enrollment_reasonCredit Recovery                      0.2332
## semesterT116                                          0.2124
## subjectOcnA                                           0.1797
## subjectBioA                                           0.0000</code></pre>
<p>Our results here give us a ranked order list of the variables in the order of their importance. Variables that appear at the top of the list are more important, and variables that appear at the bottom of the list are less important in the specification of our final random forest model. Remember that we are predicting final grade in the course, so this list will tell us which factors were most important in predicting final grade in online science courses. It can be a bit hard to visually scan a variable importance list, so we might be interested in doing a data visualization.</p>
<p>We can visualize this variable importance list with {ggplot2}.</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb357-1" title="1"><span class="kw">varImp</span>(rf_fit2_imp) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb357-2" title="2"><span class="st">    </span><span class="kw">pluck</span>(<span class="dv">1</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb357-3" title="3"><span class="st">    </span><span class="kw">rownames_to_column</span>(<span class="st">&quot;var&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb357-4" title="4"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="kw">reorder</span>(var, Overall), <span class="dt">y =</span> Overall)) <span class="op">+</span></a>
<a class="sourceLine" id="cb357-5" title="5"><span class="st">    </span><span class="kw">geom_col</span>(<span class="dt">fill =</span> <span class="kw">dataedu_colors</span>(<span class="st">&quot;darkblue&quot;</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb357-6" title="6"><span class="st">    </span><span class="kw">coord_flip</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb357-7" title="7"><span class="st">    </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<div class="figure"><span id="fig:fig14-1"></span>
<img src="14-wt-machine-learning_files/figure-html/fig14-1-1.png" alt="Variable Importance" width="672" />
<p class="caption">
Figure 14.1: Variable Importance
</p>
</div>
<p>Cool! We can now visualize which variables are most important in predicting final grade.</p>
<p>The first thing we notice is that the variable <code>n</code> is the most important. This variable indicates how much students write in their discussion posts. The second most important variable is the amount of time students spend in their course. The third most important variable is <code>subjectFrScA.</code> This is the course subject forensic science. Being enrolled in the forensic science course has a large impact on final grade. That would indicate to us that the forensic science course - more than the other science subjects in this dataset - is strongly correlated with students’ final course grades. We can keep scanning down the list to see the other variables that were indicated as less and less important for the model’s predictions. Variable importance can help us to better understand the inner workings of a random forest model.</p>
<p>Overall, there are some subject level differences in terms of how predictive subject is. Biology (<code>subjectBioA</code>) shows up pretty far down the list, whereas Physiology is in the middle (<code>subjPhysA</code>) and forensic science is towards the top (<code>subjectFrScA</code>). What this tells us is that the course students are in seems to have a different effect on final grade, depending on the course. Perhaps grades should be normalized within subject: would this still be an important predictor if we did that? We won’t dive into that question here, but you can see how the line of research inquiry might progress as you start to explore your data with a machine learning model.</p>
<p>A quick statistical note: above, we selected our variable importance method to be “permutation” for our demonstrative example. There are other options available in the {caret} package if you would like to explore those in your analyses.</p>
</div>
<div id="comparing-random-forest-to-regression" class="section level3">
<h3><span class="header-section-number">14.7.2</span> Comparing Random Forest to Regression</h3>
<p>You may be curious about comparing the predictive accuracy of the model to a linear model (a regression). Below, we’ll specify a linear model and check out how the linear model performs in terms of predicting the real outcomes. We’ll compare this with the random forest model’s performance (<code>rf_fit2</code>). Note that we are not actually re-running our random forest model here, but instead we are just making a dataset that includes the values that the <code>rf_fit2</code> model predicted as well as the actual <code>rf_fit2</code> values.</p>
<div class="sourceCode" id="cb358"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb358-1" title="1"><span class="co"># Make sure all variables stored as characters are converted to factors</span></a>
<a class="sourceLine" id="cb358-2" title="2">df_train_lm &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb358-3" title="3"><span class="st">    </span>df_train <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb358-4" title="4"><span class="st">    </span><span class="kw">mutate_if</span>(is.character, as.factor) </a></code></pre></div>
<pre><code>## mutate_if: no changes</code></pre>
<div class="sourceCode" id="cb360"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb360-1" title="1"><span class="co"># Create a linear regression model, </span></a>
<a class="sourceLine" id="cb360-2" title="2"><span class="co"># using the same formula approach as in the random forest: ~ .</span></a>
<a class="sourceLine" id="cb360-3" title="3">lm_fit &lt;-</a>
<a class="sourceLine" id="cb360-4" title="4"><span class="st">    </span><span class="kw">train</span>(final_grade <span class="op">~</span><span class="st"> </span>.,</a>
<a class="sourceLine" id="cb360-5" title="5">          <span class="dt">data =</span> df_train_lm,</a>
<a class="sourceLine" id="cb360-6" title="6">          <span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>)</a>
<a class="sourceLine" id="cb360-7" title="7"></a>
<a class="sourceLine" id="cb360-8" title="8"><span class="co"># Append the predicted values to the training dataset for the linear model, </span></a>
<a class="sourceLine" id="cb360-9" title="9"><span class="co"># so we can see both the predicted and the actual values</span></a>
<a class="sourceLine" id="cb360-10" title="10">df_train_lm &lt;-</a>
<a class="sourceLine" id="cb360-11" title="11"><span class="st">    </span>df_train <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb360-12" title="12"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">obs =</span> final_grade,</a>
<a class="sourceLine" id="cb360-13" title="13">           <span class="dt">pred =</span> <span class="kw">predict</span>(lm_fit, df_train_lm))</a></code></pre></div>
<pre><code>## mutate: new variable &#39;obs&#39; with 354 unique values and 0% NA</code></pre>
<pre><code>##         new variable &#39;pred&#39; with 372 unique values and 0% NA</code></pre>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb363-1" title="1"><span class="co"># Append the predicted values to the training dataset for the random forest</span></a>
<a class="sourceLine" id="cb363-2" title="2">df_train_randomfor &lt;-</a>
<a class="sourceLine" id="cb363-3" title="3"><span class="st">    </span>df_train <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb363-4" title="4"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">pred =</span> <span class="kw">predict</span>(rf_fit2, df_train),</a>
<a class="sourceLine" id="cb363-5" title="5">           <span class="dt">obs =</span> final_grade)</a></code></pre></div>
<pre><code>## mutate: new variable &#39;pred&#39; with 372 unique values and 0% NA</code></pre>
<pre><code>##         new variable &#39;obs&#39; with 354 unique values and 0% NA</code></pre>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb366-1" title="1"><span class="co"># Summarize, as data frames, the training data with the predicted </span></a>
<a class="sourceLine" id="cb366-2" title="2"><span class="co"># and the actual values for both the linear model</span></a>
<a class="sourceLine" id="cb366-3" title="3"><span class="kw">defaultSummary</span>(<span class="kw">as.data.frame</span>(df_train_lm))</a></code></pre></div>
<pre><code>##       RMSE   Rsquared        MAE 
## 14.4343171  0.5556582 10.8476760</code></pre>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb368-1" title="1"><span class="co"># and the random forest</span></a>
<a class="sourceLine" id="cb368-2" title="2"><span class="kw">defaultSummary</span>(<span class="kw">as.data.frame</span>(df_train_randomfor))</a></code></pre></div>
<pre><code>##      RMSE  Rsquared       MAE 
## 4.6020505 0.9678801 3.3933523</code></pre>
<p>Our output will come in the order we wrote the code, so the linear model output is displayed above the random forest output.</p>
<p>We can see that the random forest technique seems to perform better than regression. Specifically, the RMSE is lower for the random forest (13.36 as compared to 14.43 for the linear model). Second, the variance explained (<code>Rsquared</code>) is higher in the random forest (0.63 as compared to 0.56 for the linear model).</p>
<p>It may be interesting to compare the results from the random forest to a more sophisticated model as well, like one using deep learning. As you expand your skills, you can explore and find out.</p>
</div>
</div>
<div id="conclusion-10" class="section level2">
<h2><span class="header-section-number">14.8</span> Conclusion</h2>
<p>In this chapter, we introduced both general machine learning ideas, like training and test datasets and evaluating the importance of specific variables, and specific ideas, like how a random forest works and how to tune specific parameters so that the model is as effective as possible at predicting an outcome. Like many of the topics in this book - but, perhaps <em>particularly</em> so for machine learning - there is much more to discover on the topic, and we encourage you to consult the books and resources in the <a href="c17.html#c17">Learning More chapter</a> to learn about further applications of machine learning methods.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="c13.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="c15.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/data-edu/data-science-in-education/edit/master/14-wt-machine-learning.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"fig_height": 5.3,
"fig_width": 8.5
});
});
</script>

</body>

</html>
