<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>8 Education Dataset Analysis Pipeline: Walkthrough #1 | Data Science in Education Using R</title>
  <meta name="description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="generator" content="bookdown 0.16.5 and GitBook 2.6.7" />

  <meta property="og:title" content="8 Education Dataset Analysis Pipeline: Walkthrough #1 | Data Science in Education Using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="github-repo" content="data-edu/data-science-in-education" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="8 Education Dataset Analysis Pipeline: Walkthrough #1 | Data Science in Education Using R" />
  
  <meta name="twitter:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  

<meta name="author" content="Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="include-at-end-of-chapter.html"/>
<link rel="next" href="walkthrough-1b.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction: Data Science in Education–You’re Invited!</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#learning-data-science-in-education"><i class="fa fa-check"></i><b>1.1</b> Learning Data Science in Education</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#making-the-path-a-little-clearer"><i class="fa fa-check"></i><b>1.2</b> Making the Path a Little Clearer</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i><b>2</b> How to Use this Book</a><ul>
<li class="chapter" data-level="2.1" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#different-strokes-for-different-data-scientists-in-education"><i class="fa fa-check"></i><b>2.1</b> Different Strokes for Different Data Scientists in Education</a><ul>
<li class="chapter" data-level="2.1.1" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#read-the-book-cover-to-cover-and-how-to-keep-going"><i class="fa fa-check"></i><b>2.1.1</b> Read the Book Cover to Cover (and How to Keep Going)</a></li>
<li class="chapter" data-level="2.1.2" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#pick-a-chapter-of-interest-and-start-there"><i class="fa fa-check"></i><b>2.1.2</b> Pick a Chapter of Interest and Start There</a></li>
<li class="chapter" data-level="2.1.3" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#read-through-the-walkthroughs-and-run-the-code"><i class="fa fa-check"></i><b>2.1.3</b> Read Through the Walkthroughs and Run the Code</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#a-note-on-statistics"><i class="fa fa-check"></i><b>2.2</b> A Note on Statistics</a></li>
<li class="chapter" data-level="2.3" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#what-this-book-is-not-about"><i class="fa fa-check"></i><b>2.3</b> What This Book Is Not About</a></li>
<li class="chapter" data-level="2.4" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#contributing-to-the-book"><i class="fa fa-check"></i><b>2.4</b> Contributing to the Book</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html"><i class="fa fa-check"></i><b>3</b> What is a Data Scientist in Education?</a><ul>
<li class="chapter" data-level="3.1" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#data-roles-in-education"><i class="fa fa-check"></i><b>3.1</b> Data Roles in Education</a><ul>
<li class="chapter" data-level="3.1.1" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#building-systems-that-get-data-to-the-right-people"><i class="fa fa-check"></i><b>3.1.1</b> Building Systems That Get Data to the Right People</a></li>
<li class="chapter" data-level="3.1.2" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#measuring-the-impact-of-our-work-on-the-student-experience"><i class="fa fa-check"></i><b>3.1.2</b> Measuring the Impact of Our Work on the Student Experience</a></li>
<li class="chapter" data-level="3.1.3" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#looking-for-patterns-in-student-data"><i class="fa fa-check"></i><b>3.1.3</b> Looking for Patterns in Student Data</a></li>
<li class="chapter" data-level="3.1.4" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#improving-how-we-use-statistical-models-in-education"><i class="fa fa-check"></i><b>3.1.4</b> Improving How We Use Statistical Models in Education</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#common-activities-of-data-scientists"><i class="fa fa-check"></i><b>3.2</b> Common Activities of Data Scientists</a><ul>
<li class="chapter" data-level="3.2.1" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#processing-data"><i class="fa fa-check"></i><b>3.2.1</b> Processing Data</a></li>
<li class="chapter" data-level="3.2.2" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#doing-analysis"><i class="fa fa-check"></i><b>3.2.2</b> Doing Analysis</a></li>
<li class="chapter" data-level="3.2.3" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#sharing-results"><i class="fa fa-check"></i><b>3.2.3</b> Sharing Results</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html#who-we-are-and-what-we-do"><i class="fa fa-check"></i><b>3.3</b> Who We Are and What We Do</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="unique-challenges.html"><a href="unique-challenges.html"><i class="fa fa-check"></i><b>4</b> Unique Challenges</a><ul>
<li class="chapter" data-level="4.1" data-path="unique-challenges.html"><a href="unique-challenges.html#challenges-common-to-doing-data-science-in-any-domain"><i class="fa fa-check"></i><b>4.1</b> Challenges Common to Doing Data Science in any Domain</a><ul>
<li class="chapter" data-level="4.1.1" data-path="unique-challenges.html"><a href="unique-challenges.html#a-new-field"><i class="fa fa-check"></i><b>4.1.1</b> A New Field</a></li>
<li class="chapter" data-level="4.1.2" data-path="unique-challenges.html"><a href="unique-challenges.html#addressing-ambiguity-a-reproducible-approach"><i class="fa fa-check"></i><b>4.1.2</b> Addressing Ambiguity: A Reproducible Approach</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="unique-challenges.html"><a href="unique-challenges.html#challenges-common-to-doing-data-science-in-education"><i class="fa fa-check"></i><b>4.2</b> Challenges Common to Doing Data Science in Education</a><ul>
<li class="chapter" data-level="4.2.1" data-path="unique-challenges.html"><a href="unique-challenges.html#addressing-organizational-resistance-a-self-driven-analytic-approach"><i class="fa fa-check"></i><b>4.2.1</b> Addressing organizational resistance: A self-driven analytic approach</a></li>
<li class="chapter" data-level="4.2.2" data-path="unique-challenges.html"><a href="unique-challenges.html#lack-of-processes-and-guidelines"><i class="fa fa-check"></i><b>4.2.2</b> Lack of Processes and Guidelines</a></li>
<li class="chapter" data-level="4.2.3" data-path="unique-challenges.html"><a href="unique-challenges.html#limited-training-and-educational-opportunities"><i class="fa fa-check"></i><b>4.2.3</b> Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="4.2.4" data-path="unique-challenges.html"><a href="unique-challenges.html#the-complex-and-messy-nature-of-education-data"><i class="fa fa-check"></i><b>4.2.4</b> The Complex and Messy Nature of Education Data</a></li>
<li class="chapter" data-level="4.2.5" data-path="unique-challenges.html"><a href="unique-challenges.html#ethical-and-legal-concerns"><i class="fa fa-check"></i><b>4.2.5</b> Ethical and Legal Concerns</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="unique-challenges.html"><a href="unique-challenges.html#analytic-challenges"><i class="fa fa-check"></i><b>4.3</b> Analytic Challenges</a></li>
<li class="chapter" data-level="4.4" data-path="unique-challenges.html"><a href="unique-challenges.html#not-just-challenges"><i class="fa fa-check"></i><b>4.4</b> Not Just Challenges</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html"><i class="fa fa-check"></i><b>5</b> Getting Started with R and RStudio</a><ul>
<li class="chapter" data-level="5.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#chapter-overview"><i class="fa fa-check"></i><b>5.1</b> Chapter overview</a></li>
<li class="chapter" data-level="5.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-started"><i class="fa fa-check"></i><b>5.2</b> Getting Started</a></li>
<li class="chapter" data-level="5.3" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#downloading-r-and-rstudio"><i class="fa fa-check"></i><b>5.3</b> Downloading R and RStudio</a><ul>
<li class="chapter" data-level="5.3.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#to-download-r"><i class="fa fa-check"></i><b>5.3.1</b> To download R:</a></li>
<li class="chapter" data-level="5.3.2" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#to-download-rstudio"><i class="fa fa-check"></i><b>5.3.2</b> To download RStudio:</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-to-know-r-through-rstudio"><i class="fa fa-check"></i><b>5.4</b> Getting to know R through RStudio</a><ul>
<li class="chapter" data-level="5.4.1" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#getting-to-know-r-challenge-questions"><i class="fa fa-check"></i><b>5.4.1</b> Getting to Know R: Challenge Questions</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#diving-a-little-deeper-into-r-with-swirl"><i class="fa fa-check"></i><b>5.5</b> Diving a little deeper into R with <code>swirl</code></a></li>
<li class="chapter" data-level="5.6" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#introduction-to-help-documentation"><i class="fa fa-check"></i><b>5.6</b> Introduction to Help Documentation</a></li>
<li class="chapter" data-level="5.7" data-path="getting-started-with-r-and-rstudio.html"><a href="getting-started-with-r-and-rstudio.html#downloading-and-accessing-the-data-sets-used-in-this-book"><i class="fa fa-check"></i><b>5.7</b> Downloading and accessing the data sets used in this book</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="foundational-skills.html"><a href="foundational-skills.html"><i class="fa fa-check"></i><b>6</b> Foundational Skills</a><ul>
<li class="chapter" data-level="6.1" data-path="foundational-skills.html"><a href="foundational-skills.html#chapter-overview-1"><i class="fa fa-check"></i><b>6.1</b> Chapter overview</a></li>
<li class="chapter" data-level="6.2" data-path="foundational-skills.html"><a href="foundational-skills.html#foundational-skills-framework"><i class="fa fa-check"></i><b>6.2</b> Foundational Skills Framework</a></li>
<li class="chapter" data-level="6.3" data-path="foundational-skills.html"><a href="foundational-skills.html#setting-up-your-project"><i class="fa fa-check"></i><b>6.3</b> Setting up your Project</a><ul>
<li class="chapter" data-level="6.3.1" data-path="foundational-skills.html"><a href="foundational-skills.html#coding-in-rstudio"><i class="fa fa-check"></i><b>6.3.1</b> Coding in RStudio</a></li>
<li class="chapter" data-level="6.3.2" data-path="foundational-skills.html"><a href="foundational-skills.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>6.3.2</b> Installing and Loading Packages</a></li>
<li class="chapter" data-level="6.3.3" data-path="foundational-skills.html"><a href="foundational-skills.html#running-functions-from-packages"><i class="fa fa-check"></i><b>6.3.3</b> Running Functions from Packages</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="foundational-skills.html"><a href="foundational-skills.html#code-for-foundational-skills"><i class="fa fa-check"></i><b>6.4</b> Code for Foundational Skills</a><ul>
<li class="chapter" data-level="6.4.1" data-path="foundational-skills.html"><a href="foundational-skills.html#see-ryans-work-on-prefacing-functions---need-to-preface-dplyrarrange"><i class="fa fa-check"></i><b>6.4.1</b> See Ryan’s work on prefacing functions - need to preface dplyr::arrange()!</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="foundational-skills.html"><a href="foundational-skills.html#packages-and-functions"><i class="fa fa-check"></i><b>6.5</b> Packages and Functions</a></li>
<li class="chapter" data-level="6.6" data-path="foundational-skills.html"><a href="foundational-skills.html#installing-and-loading-a-package"><i class="fa fa-check"></i><b>6.6</b> Installing and loading a package</a><ul>
<li class="chapter" data-level="6.6.1" data-path="foundational-skills.html"><a href="foundational-skills.html#recognizing-a-function"><i class="fa fa-check"></i><b>6.6.1</b> Recognizing a function</a></li>
<li class="chapter" data-level="6.6.2" data-path="foundational-skills.html"><a href="foundational-skills.html#running-code-in-r"><i class="fa fa-check"></i><b>6.6.2</b> Running code in R</a></li>
<li class="chapter" data-level="6.6.3" data-path="foundational-skills.html"><a href="foundational-skills.html#run-this-code"><i class="fa fa-check"></i><b>6.6.3</b> Run this code</a></li>
<li class="chapter" data-level="6.6.4" data-path="foundational-skills.html"><a href="foundational-skills.html#how-to-find-a-package"><i class="fa fa-check"></i><b>6.6.4</b> How to find a package</a></li>
<li class="chapter" data-level="6.6.5" data-path="foundational-skills.html"><a href="foundational-skills.html#how-to-learn-more-about-a-package"><i class="fa fa-check"></i><b>6.6.5</b> How to learn more about a package</a></li>
<li class="chapter" data-level="6.6.6" data-path="foundational-skills.html"><a href="foundational-skills.html#function-conflicts-between-packages-between-base-r-and-loaded-packages"><i class="fa fa-check"></i><b>6.6.6</b> Function conflicts: between packages, between base R and loaded packages</a></li>
<li class="chapter" data-level="6.6.7" data-path="foundational-skills.html"><a href="foundational-skills.html#commenting-in-r"><i class="fa fa-check"></i><b>6.6.7</b> Commenting in R</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="foundational-skills.html"><a href="foundational-skills.html#using-functions-to-import-data"><i class="fa fa-check"></i><b>6.7</b> Using functions to import data</a><ul>
<li class="chapter" data-level="6.7.1" data-path="foundational-skills.html"><a href="foundational-skills.html#run-this-code-1"><i class="fa fa-check"></i><b>6.7.1</b> Run this code</a></li>
<li class="chapter" data-level="6.7.2" data-path="foundational-skills.html"><a href="foundational-skills.html#the-assignment-operator"><i class="fa fa-check"></i><b>6.7.2</b> The assignment operator</a></li>
<li class="chapter" data-level="6.7.3" data-path="foundational-skills.html"><a href="foundational-skills.html#the-here-package"><i class="fa fa-check"></i><b>6.7.3</b> The <code>here</code> package</a></li>
<li class="chapter" data-level="6.7.4" data-path="foundational-skills.html"><a href="foundational-skills.html#data-types"><i class="fa fa-check"></i><b>6.7.4</b> Data types</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="foundational-skills.html"><a href="foundational-skills.html#datasets-and-variables"><i class="fa fa-check"></i><b>6.8</b> Datasets and variables</a><ul>
<li class="chapter" data-level="6.8.1" data-path="foundational-skills.html"><a href="foundational-skills.html#run-the-following-code"><i class="fa fa-check"></i><b>6.8.1</b> Run the following code</a></li>
<li class="chapter" data-level="6.8.2" data-path="foundational-skills.html"><a href="foundational-skills.html#tibbles-and-dataframes-oh-my"><i class="fa fa-check"></i><b>6.8.2</b> Tibbles and dataframes, oh my!</a></li>
<li class="chapter" data-level="6.8.3" data-path="foundational-skills.html"><a href="foundational-skills.html#the-operator"><i class="fa fa-check"></i><b>6.8.3</b> The <code>$</code> operator</a></li>
<li class="chapter" data-level="6.8.4" data-path="foundational-skills.html"><a href="foundational-skills.html#spaces-in-variable-names"><i class="fa fa-check"></i><b>6.8.4</b> Spaces in variable names</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="foundational-skills.html"><a href="foundational-skills.html#the-pipe-operator"><i class="fa fa-check"></i><b>6.9</b> The pipe operator</a><ul>
<li class="chapter" data-level="6.9.1" data-path="foundational-skills.html"><a href="foundational-skills.html#piping-practices"><i class="fa fa-check"></i><b>6.9.1</b> Piping practices</a></li>
<li class="chapter" data-level="6.9.2" data-path="foundational-skills.html"><a href="foundational-skills.html#closing-your-parentheses"><i class="fa fa-check"></i><b>6.9.2</b> Closing your parentheses</a></li>
</ul></li>
<li class="chapter" data-level="6.10" data-path="foundational-skills.html"><a href="foundational-skills.html#finicky-functions-rename-this-section"><i class="fa fa-check"></i><b>6.10</b> Finicky functions (rename this section)</a><ul>
<li class="chapter" data-level="6.10.1" data-path="foundational-skills.html"><a href="foundational-skills.html#when-functions-need-arguments-and-when-they-dont"><i class="fa fa-check"></i><b>6.10.1</b> When functions need arguments and when they don’t</a></li>
<li class="chapter" data-level="6.10.2" data-path="foundational-skills.html"><a href="foundational-skills.html#functions-within-functions"><i class="fa fa-check"></i><b>6.10.2</b> Functions within functions</a></li>
<li class="chapter" data-level="6.10.3" data-path="foundational-skills.html"><a href="foundational-skills.html#the-difference-between-and"><i class="fa fa-check"></i><b>6.10.3</b> The difference between <code>=</code> and <code>==</code></a></li>
<li class="chapter" data-level="6.10.4" data-path="foundational-skills.html"><a href="foundational-skills.html#writing-your-own-functions"><i class="fa fa-check"></i><b>6.10.4</b> Writing your own functions</a></li>
</ul></li>
<li class="chapter" data-level="6.11" data-path="foundational-skills.html"><a href="foundational-skills.html#section-on-c-and-in"><i class="fa fa-check"></i><b>6.11</b> SECTION ON c() and %in%</a></li>
<li class="chapter" data-level="6.12" data-path="foundational-skills.html"><a href="foundational-skills.html#creating-objects"><i class="fa fa-check"></i><b>6.12</b> Creating objects</a><ul>
<li class="chapter" data-level="6.12.1" data-path="foundational-skills.html"><a href="foundational-skills.html#object-oriented-programming-oop"><i class="fa fa-check"></i><b>6.12.1</b> Object-oriented programming (OOP)</a></li>
<li class="chapter" data-level="6.12.2" data-path="foundational-skills.html"><a href="foundational-skills.html#analysis-vs.-development"><i class="fa fa-check"></i><b>6.12.2</b> Analysis vs. development</a></li>
</ul></li>
<li class="chapter" data-level="6.13" data-path="foundational-skills.html"><a href="foundational-skills.html#creating-projects"><i class="fa fa-check"></i><b>6.13</b> Creating Projects</a><ul>
<li class="chapter" data-level="6.13.1" data-path="foundational-skills.html"><a href="foundational-skills.html#track-two-welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>6.13.1</b> Track Two: Welcome to the Tidyverse</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html"><i class="fa fa-check"></i><b>7</b> Include at end of chapter!</a><ul>
<li class="chapter" data-level="7.1" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#loading-data-from-excel-sav-and-google-sheets"><i class="fa fa-check"></i><b>7.1</b> Loading Data from Excel, SAV, and Google Sheets</a><ul>
<li class="chapter" data-level="7.1.1" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#loading-excel-files"><i class="fa fa-check"></i><b>7.1.1</b> Loading Excel Files</a></li>
<li class="chapter" data-level="7.1.2" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#loading-sav-files"><i class="fa fa-check"></i><b>7.1.2</b> Loading SAV Files</a></li>
<li class="chapter" data-level="7.1.3" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#google-sheets"><i class="fa fa-check"></i><b>7.1.3</b> Google Sheets</a></li>
<li class="chapter" data-level="7.1.4" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#saving-a-file-from-the-web"><i class="fa fa-check"></i><b>7.1.4</b> Saving a File from the Web</a></li>
<li class="chapter" data-level="7.1.5" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#loading-a-.csv-file"><i class="fa fa-check"></i><b>7.1.5</b> Loading a <code>.csv</code> File</a></li>
<li class="chapter" data-level="7.1.6" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#saving-files"><i class="fa fa-check"></i><b>7.1.6</b> Saving Files</a></li>
<li class="chapter" data-level="7.1.7" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#conclusion"><i class="fa fa-check"></i><b>7.1.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#processing-data-1"><i class="fa fa-check"></i><b>7.2</b> Processing Data</a></li>
<li class="chapter" data-level="7.3" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#communicating-sharing-results"><i class="fa fa-check"></i><b>7.3</b> Communicating / Sharing Results</a><ul>
<li class="chapter" data-level="7.3.1" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#miscellaneous-from-import"><i class="fa fa-check"></i><b>7.3.1</b> miscellaneous from import</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#old-text---keep-until-reincorporatedreaddressed"><i class="fa fa-check"></i><b>7.4</b> Old text - keep until reincorporated//readdressed</a></li>
<li class="chapter" data-level="7.5" data-path="include-at-end-of-chapter.html"><a href="include-at-end-of-chapter.html#may-not-need"><i class="fa fa-check"></i><b>7.5</b> May not need</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html"><i class="fa fa-check"></i><b>8</b> Education Dataset Analysis Pipeline: Walkthrough #1</a><ul>
<li class="chapter" data-level="8.1" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#background-and-purpose"><i class="fa fa-check"></i><b>8.1</b> Background and Purpose</a><ul>
<li class="chapter" data-level="8.1.1" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#data-source-1-self-report-survey"><i class="fa fa-check"></i><b>8.1.1</b> Data Source #1: Self-report survey</a></li>
<li class="chapter" data-level="8.1.2" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#data-source-2-log-trace-data"><i class="fa fa-check"></i><b>8.1.2</b> Data source #2: Log-trace data</a></li>
<li class="chapter" data-level="8.1.3" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#data-source-3-achievement-related-and-gradebook-data"><i class="fa fa-check"></i><b>8.1.3</b> Data source #3: Achievement-related and gradebook data</a></li>
<li class="chapter" data-level="8.1.4" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#data-source-4-discussion-board-data"><i class="fa fa-check"></i><b>8.1.4</b> Data source #4: Discussion board data</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#processing-the-data"><i class="fa fa-check"></i><b>8.2</b> Processing the data</a></li>
<li class="chapter" data-level="8.3" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#viewing-the-data"><i class="fa fa-check"></i><b>8.3</b> Viewing the data</a></li>
<li class="chapter" data-level="8.4" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#processing-the-pre-survey-data"><i class="fa fa-check"></i><b>8.4</b> Processing the pre-survey data</a></li>
<li class="chapter" data-level="8.5" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#processing-the-course-data"><i class="fa fa-check"></i><b>8.5</b> Processing the course data</a></li>
<li class="chapter" data-level="8.6" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#joining-the-data"><i class="fa fa-check"></i><b>8.6</b> Joining the data</a></li>
<li class="chapter" data-level="8.7" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#finding-distinct-cases-at-the-student-level"><i class="fa fa-check"></i><b>8.7</b> Finding distinct cases at the student-level</a></li>
<li class="chapter" data-level="8.8" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#visualizations-and-models"><i class="fa fa-check"></i><b>8.8</b> Visualizations and Models</a><ul>
<li class="chapter" data-level="8.8.1" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#the-relationship-between-time-spent-on-course-and-percentage-of-points-earned"><i class="fa fa-check"></i><b>8.8.1</b> The relationship between time spent on course and percentage of points earned</a></li>
</ul></li>
<li class="chapter" data-level="8.9" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#linear-model-regression"><i class="fa fa-check"></i><b>8.9</b> Linear model (regression)</a></li>
<li class="chapter" data-level="8.10" data-path="education-dataset-analysis-pipeline-walkthrough-1.html"><a href="education-dataset-analysis-pipeline-walkthrough-1.html#what-is-next"><i class="fa fa-check"></i><b>8.10</b> What is next?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="walkthrough-1b.html"><a href="walkthrough-1b.html"><i class="fa fa-check"></i><b>9</b> Walkthrough #1B</a><ul>
<li class="chapter" data-level="9.1" data-path="walkthrough-1b.html"><a href="walkthrough-1b.html#but-what-about-different-courses"><i class="fa fa-check"></i><b>9.1</b> But what about different courses?</a><ul>
<li class="chapter" data-level="9.1.1" data-path="walkthrough-1b.html"><a href="walkthrough-1b.html#the-role-of-dummy-codes"><i class="fa fa-check"></i><b>9.1.1</b> The role of dummy codes</a></li>
<li class="chapter" data-level="9.1.2" data-path="walkthrough-1b.html"><a href="walkthrough-1b.html#using-dummy-codes"><i class="fa fa-check"></i><b>9.1.2</b> Using dummy codes</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="walkthrough-1b.html"><a href="walkthrough-1b.html#toward-multi-level-models"><i class="fa fa-check"></i><b>9.2</b> Toward multi-level models</a></li>
<li class="chapter" data-level="9.3" data-path="walkthrough-1b.html"><a href="walkthrough-1b.html#other-groups"><i class="fa fa-check"></i><b>9.3</b> Other groups</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html"><i class="fa fa-check"></i><b>10</b> Walkthrough 02: Title Here</a><ul>
<li class="chapter" data-level="10.1" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#introduction"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#data-sources"><i class="fa fa-check"></i><b>10.2</b> Data Sources</a></li>
<li class="chapter" data-level="10.3" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#load-packages"><i class="fa fa-check"></i><b>10.3</b> Load Packages</a></li>
<li class="chapter" data-level="10.4" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#import-data"><i class="fa fa-check"></i><b>10.4</b> Import Data</a></li>
<li class="chapter" data-level="10.5" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#tidy-data"><i class="fa fa-check"></i><b>10.5</b> Tidy Data</a></li>
<li class="chapter" data-level="10.6" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#process-data"><i class="fa fa-check"></i><b>10.6</b> Process Data</a></li>
<li class="chapter" data-level="10.7" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#visualize-data"><i class="fa fa-check"></i><b>10.7</b> Visualize Data</a></li>
<li class="chapter" data-level="10.8" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#model-data"><i class="fa fa-check"></i><b>10.8</b> Model Data</a><ul>
<li class="chapter" data-level="10.8.1" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#deciding-an-analysis"><i class="fa fa-check"></i><b>10.8.1</b> Deciding an Analysis</a></li>
<li class="chapter" data-level="10.8.2" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#visualize-data-to-check-assumptions"><i class="fa fa-check"></i><b>10.8.2</b> Visualize Data to Check Assumptions</a></li>
<li class="chapter" data-level="10.8.3" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#correlation-analysis"><i class="fa fa-check"></i><b>10.8.3</b> Correlation Analysis</a></li>
<li class="chapter" data-level="10.8.4" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#build-linear-model"><i class="fa fa-check"></i><b>10.8.4</b> Build Linear Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html"><i class="fa fa-check"></i><b>11</b> Walkthrough 4: Text Analysis With Social Media Data</a><ul>
<li class="chapter" data-level="11.1" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#vocabulary"><i class="fa fa-check"></i><b>11.1</b> Vocabulary</a></li>
<li class="chapter" data-level="11.2" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#introduction-1"><i class="fa fa-check"></i><b>11.2</b> Introduction</a><ul>
<li class="chapter" data-level="11.2.1" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#background"><i class="fa fa-check"></i><b>11.2.1</b> Background</a></li>
<li class="chapter" data-level="11.2.2" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#data-source"><i class="fa fa-check"></i><b>11.2.2</b> Data Source</a></li>
<li class="chapter" data-level="11.2.3" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#methods"><i class="fa fa-check"></i><b>11.2.3</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#load-packages-1"><i class="fa fa-check"></i><b>11.3</b> Load Packages</a></li>
<li class="chapter" data-level="11.4" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#import-data-1"><i class="fa fa-check"></i><b>11.4</b> Import Data</a><ul>
<li class="chapter" data-level="11.4.1" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#using-an-api"><i class="fa fa-check"></i><b>11.4.1</b> Using an API</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#view-data"><i class="fa fa-check"></i><b>11.5</b> View Data</a></li>
<li class="chapter" data-level="11.6" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#process-data-1"><i class="fa fa-check"></i><b>11.6</b> Process Data</a></li>
<li class="chapter" data-level="11.7" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#analysis-counting-words"><i class="fa fa-check"></i><b>11.7</b> Analysis: Counting Words</a></li>
<li class="chapter" data-level="11.8" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#analysis-sentiment-analysis"><i class="fa fa-check"></i><b>11.8</b> Analysis: Sentiment analysis</a><ul>
<li class="chapter" data-level="11.8.1" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#tweets-associated-with-positive"><i class="fa fa-check"></i><b>11.8.1</b> Tweets associated with positive</a></li>
<li class="chapter" data-level="11.8.2" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#dataviz-and-other-positive-words"><i class="fa fa-check"></i><b>11.8.2</b> Dataviz and other positive words</a></li>
<li class="chapter" data-level="11.8.3" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#close-read-of-randomly-selected-tweets"><i class="fa fa-check"></i><b>11.8.3</b> Close read of randomly selected tweets</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="walkthrough-4-text-analysis-with-social-media-data.html"><a href="walkthrough-4-text-analysis-with-social-media-data.html#conclusion-1"><i class="fa fa-check"></i><b>11.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html"><i class="fa fa-check"></i><b>12</b> 16-walkthrough-sna</a><ul>
<li class="chapter" data-level="12.1" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#accessing-data"><i class="fa fa-check"></i><b>12.1</b> Accessing data</a></li>
<li class="chapter" data-level="12.2" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#preparing-the-data-for-the-analysis"><i class="fa fa-check"></i><b>12.2</b> Preparing the data for the analysis</a></li>
<li class="chapter" data-level="12.3" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#extracting-mentions"><i class="fa fa-check"></i><b>12.3</b> Extracting mentions</a></li>
<li class="chapter" data-level="12.4" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#putting-the-edgelist-together"><i class="fa fa-check"></i><b>12.4</b> Putting the edgelist together</a></li>
<li class="chapter" data-level="12.5" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#plotting-the-network"><i class="fa fa-check"></i><b>12.5</b> Plotting the network</a></li>
<li class="chapter" data-level="12.6" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#selection-and-influence-models"><i class="fa fa-check"></i><b>12.6</b> Selection and influence models</a></li>
<li class="chapter" data-level="12.7" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#appendix-a"><i class="fa fa-check"></i><b>12.7</b> Appendix A</a><ul>
<li class="chapter" data-level="12.7.1" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#accessing-historical-data-using-status-urls"><i class="fa fa-check"></i><b>12.7.1</b> Accessing historical data using status URLs</a></li>
<li class="chapter" data-level="12.7.2" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#accessing-historical-data-when-you-do-not-have-access-to-status-urls"><i class="fa fa-check"></i><b>12.7.2</b> Accessing historical data when you do not have access to status URLs</a></li>
</ul></li>
<li class="chapter" data-level="12.8" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#appendix-b"><i class="fa fa-check"></i><b>12.8</b> Appendix B</a><ul>
<li class="chapter" data-level="12.8.1" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#an-example-of-influence"><i class="fa fa-check"></i><b>12.8.1</b> An example of influence</a></li>
<li class="chapter" data-level="12.8.2" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#joining-the-data-1"><i class="fa fa-check"></i><b>12.8.2</b> Joining the data</a></li>
<li class="chapter" data-level="12.8.3" data-path="walkthrough-sna.html"><a href="walkthrough-sna.html#an-example-of-selection"><i class="fa fa-check"></i><b>12.8.3</b> An example of selection</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html"><i class="fa fa-check"></i><b>13</b> Walkthrough 05: Introduction to Aggregate Data</a><ul>
<li class="chapter" data-level="13.1" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#introduction-2"><i class="fa fa-check"></i><b>13.1</b> Introduction</a><ul>
<li class="chapter" data-level="13.1.1" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#background-1"><i class="fa fa-check"></i><b>13.1.1</b> Background</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#data-sources-1"><i class="fa fa-check"></i><b>13.2</b> Data Sources</a><ul>
<li class="chapter" data-level="13.2.1" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#methods-1"><i class="fa fa-check"></i><b>13.2.1</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#load-packages-2"><i class="fa fa-check"></i><b>13.3</b> Load Packages</a></li>
<li class="chapter" data-level="13.4" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#import-data-2"><i class="fa fa-check"></i><b>13.4</b> Import Data</a></li>
<li class="chapter" data-level="13.5" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#view-data-1"><i class="fa fa-check"></i><b>13.5</b> View Data</a><ul>
<li class="chapter" data-level="13.5.1" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#discovering-distributions"><i class="fa fa-check"></i><b>13.5.1</b> Discovering Distributions</a></li>
<li class="chapter" data-level="13.5.2" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#anayzing-spread"><i class="fa fa-check"></i><b>13.5.2</b> Anayzing Spread</a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#analysis"><i class="fa fa-check"></i><b>13.6</b> Analysis</a><ul>
<li class="chapter" data-level="13.6.1" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#creating-categories"><i class="fa fa-check"></i><b>13.6.1</b> Creating Categories</a></li>
<li class="chapter" data-level="13.6.2" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#reveal-relationships"><i class="fa fa-check"></i><b>13.6.2</b> Reveal Relationships</a></li>
</ul></li>
<li class="chapter" data-level="13.7" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#results"><i class="fa fa-check"></i><b>13.7</b> Results</a></li>
<li class="chapter" data-level="13.8" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#conclusion-2"><i class="fa fa-check"></i><b>13.8</b> Conclusion</a></li>
<li class="chapter" data-level="13.9" data-path="walkthrough-05-introduction-to-aggregate-data.html"><a href="walkthrough-05-introduction-to-aggregate-data.html#references"><i class="fa fa-check"></i><b>13.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><i class="fa fa-check"></i><b>14</b> Walkthrough 13: Longitudinal Analysis With Federal Students With Disabilities Data</a><ul>
<li class="chapter" data-level="14.1" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#vocabulary-1"><i class="fa fa-check"></i><b>14.1</b> Vocabulary</a></li>
<li class="chapter" data-level="14.2" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#introduction-3"><i class="fa fa-check"></i><b>14.2</b> Introduction</a><ul>
<li class="chapter" data-level="14.2.1" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#background-2"><i class="fa fa-check"></i><b>14.2.1</b> Background</a></li>
<li class="chapter" data-level="14.2.2" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#methods-2"><i class="fa fa-check"></i><b>14.2.2</b> Methods</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#load-packages-3"><i class="fa fa-check"></i><b>14.3</b> Load Packages</a></li>
<li class="chapter" data-level="14.4" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#import-data-3"><i class="fa fa-check"></i><b>14.4</b> Import Data</a><ul>
<li class="chapter" data-level="14.4.1" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#reading-in-one-dataset"><i class="fa fa-check"></i><b>14.4.1</b> Reading In One Dataset</a></li>
<li class="chapter" data-level="14.4.2" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#reading-in-many-datasets"><i class="fa fa-check"></i><b>14.4.2</b> Reading In Many Datasets</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#process-data-2"><i class="fa fa-check"></i><b>14.5</b> Process Data</a><ul>
<li class="chapter" data-level="14.5.1" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#fix-the-variable-names-in-the-2016-data"><i class="fa fa-check"></i><b>14.5.1</b> Fix the variable names in the 2016 data</a></li>
<li class="chapter" data-level="14.5.2" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#pick-variables"><i class="fa fa-check"></i><b>14.5.2</b> Pick variables</a></li>
<li class="chapter" data-level="14.5.3" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#combine-six-datasets-into-one"><i class="fa fa-check"></i><b>14.5.3</b> Combine six datasets into one</a></li>
<li class="chapter" data-level="14.5.4" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#filter-for-the-desired-disabilities-and-age-groups"><i class="fa fa-check"></i><b>14.5.4</b> Filter for the desired disabilities and age groups</a></li>
<li class="chapter" data-level="14.5.5" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#rename-the-variables"><i class="fa fa-check"></i><b>14.5.5</b> Rename the variables</a></li>
<li class="chapter" data-level="14.5.6" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#clean-state-names"><i class="fa fa-check"></i><b>14.5.6</b> Clean state names</a></li>
<li class="chapter" data-level="14.5.7" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#tidy-the-dataset"><i class="fa fa-check"></i><b>14.5.7</b> Tidy the dataset</a></li>
<li class="chapter" data-level="14.5.8" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#convert-data-types"><i class="fa fa-check"></i><b>14.5.8</b> Convert data types</a></li>
<li class="chapter" data-level="14.5.9" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#explore-and-address-nas"><i class="fa fa-check"></i><b>14.5.9</b> Explore and address NAs</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#analysis-how-have-child-counts-changed-over-time"><i class="fa fa-check"></i><b>14.6</b> Analysis: How Have Child Counts Changed Over Time?</a><ul>
<li class="chapter" data-level="14.6.1" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#visualize-the-dataset"><i class="fa fa-check"></i><b>14.6.1</b> Visualize the Dataset</a></li>
<li class="chapter" data-level="14.6.2" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#model-the-dataset"><i class="fa fa-check"></i><b>14.6.2</b> Model the Dataset</a></li>
</ul></li>
<li class="chapter" data-level="14.7" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#results-1"><i class="fa fa-check"></i><b>14.7</b> Results</a></li>
<li class="chapter" data-level="14.8" data-path="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html"><a href="walkthrough-13-longitudinal-analysis-with-federal-students-with-disabilities-data.html#conclusion-aggregate-data-as-context-for-student-data"><i class="fa fa-check"></i><b>14.8</b> Conclusion: Aggregate Data as Context for Student Data</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html"><i class="fa fa-check"></i><b>15</b> Introducing Data Science Tools To Your Education Job</a><ul>
<li class="chapter" data-level="15.1" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#introduction-4"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#the-gift-of-speed-and-scale"><i class="fa fa-check"></i><b>15.2</b> The Gift of Speed and Scale</a><ul>
<li class="chapter" data-level="15.2.1" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#working-with-data-faster"><i class="fa fa-check"></i><b>15.2.1</b> Working With Data Faster</a></li>
<li class="chapter" data-level="15.2.2" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#working-with-more-data"><i class="fa fa-check"></i><b>15.2.2</b> Working With More Data</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#other-ways-to-reimagine-the-scale-of-your-work"><i class="fa fa-check"></i><b>15.3</b> Other Ways to Reimagine the Scale of Your Work</a><ul>
<li class="chapter" data-level="15.3.1" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#reflect-on-your-current-scale-then-push-to-the-next-level"><i class="fa fa-check"></i><b>15.3.1</b> Reflect on your current scale, then push to the next level</a></li>
<li class="chapter" data-level="15.3.2" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#look-for-lots-of-similarly-structured-data"><i class="fa fa-check"></i><b>15.3.2</b> Look for lots of similarly structured data</a></li>
<li class="chapter" data-level="15.3.3" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#cleaning-data"><i class="fa fa-check"></i><b>15.3.3</b> Cleaning data</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#solving-problems-together"><i class="fa fa-check"></i><b>15.4</b> Solving Problems Together</a><ul>
<li class="chapter" data-level="15.4.1" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#data-science-in-education-and-empathy"><i class="fa fa-check"></i><b>15.4.1</b> Data Science in Education and Empathy</a></li>
<li class="chapter" data-level="15.4.2" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#create-a-daily-practice-commitment-that-answers-someone-elses-question"><i class="fa fa-check"></i><b>15.4.2</b> Create a Daily Practice Commitment That Answers Someone Else’s Question</a></li>
<li class="chapter" data-level="15.4.3" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#build-your-network"><i class="fa fa-check"></i><b>15.4.3</b> Build Your Network</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="introducing-data-science-tools-to-your-education-job.html"><a href="introducing-data-science-tools-to-your-education-job.html#for-k-12-teachers"><i class="fa fa-check"></i><b>15.5</b> For K-12 Teachers</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="teaching-data-science.html"><a href="teaching-data-science.html"><i class="fa fa-check"></i><b>16</b> Teaching Data Science</a><ul>
<li class="chapter" data-level="16.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#the-pedagogical-principles-this-book-is-based-upon"><i class="fa fa-check"></i><b>16.1</b> The pedagogical principles this book is based upon</a><ul>
<li class="chapter" data-level="16.1.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#problem-based-learning"><i class="fa fa-check"></i><b>16.1.1</b> Problem-based learning</a></li>
<li class="chapter" data-level="16.1.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#differentiation"><i class="fa fa-check"></i><b>16.1.2</b> Differentiation</a></li>
<li class="chapter" data-level="16.1.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#universal-design"><i class="fa fa-check"></i><b>16.1.3</b> Universal Design</a></li>
<li class="chapter" data-level="16.1.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#working-in-the-open"><i class="fa fa-check"></i><b>16.1.4</b> Working in the Open</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#strategies-for-teaching-data-science"><i class="fa fa-check"></i><b>16.2</b> Strategies for teaching data science</a><ul>
<li class="chapter" data-level="16.2.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#provide-a-home-base-for-learners-to-access-resources-and-to-learn-more"><i class="fa fa-check"></i><b>16.2.1</b> Provide a home base for learners to access resources (and to learn more)</a></li>
<li class="chapter" data-level="16.2.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#when-it-comes-to-writing-code-think-early-and-often"><i class="fa fa-check"></i><b>16.2.2</b> When it comes to writing code, think early and often</a></li>
<li class="chapter" data-level="16.2.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#dont-touch-that-keyboard"><i class="fa fa-check"></i><b>16.2.3</b> Don’t touch that keyboard!</a></li>
<li class="chapter" data-level="16.2.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#anticipate-issues-and-sacrifice-accuracy-for-clarity"><i class="fa fa-check"></i><b>16.2.4</b> Anticipate issues (and sacrifice accuracy for clarity)</a></li>
<li class="chapter" data-level="16.2.5" data-path="teaching-data-science.html"><a href="teaching-data-science.html#start-lessons-or-activities-with-visualizing-data"><i class="fa fa-check"></i><b>16.2.5</b> Start lessons or activities with visualizing data</a></li>
<li class="chapter" data-level="16.2.6" data-path="teaching-data-science.html"><a href="teaching-data-science.html#consider-representation-in-the-data-and-examples-you-use"><i class="fa fa-check"></i><b>16.2.6</b> Consider representation in the data and examples you use</a></li>
<li class="chapter" data-level="16.2.7" data-path="teaching-data-science.html"><a href="teaching-data-science.html#draw-on-other-resources"><i class="fa fa-check"></i><b>16.2.7</b> Draw on other resources</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#general-strategies-related-to-teaching-and-learning"><i class="fa fa-check"></i><b>16.3</b> General strategies related to teaching and learning</a><ul>
<li class="chapter" data-level="16.3.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#teaching-and-learning-are-complex"><i class="fa fa-check"></i><b>16.3.1</b> Teaching and learning are complex</a></li>
<li class="chapter" data-level="16.3.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#learners-learn-many-different-things-consciously-and-unconsciously"><i class="fa fa-check"></i><b>16.3.2</b> Learners learn many different things (consciously and unconsciously)</a></li>
<li class="chapter" data-level="16.3.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#metacognition-is-important-even-though-it-sounds-more-sophisticated-than-it-is"><i class="fa fa-check"></i><b>16.3.3</b> Metacognition is important (even though it sounds more sophisticated than it is!)</a></li>
<li class="chapter" data-level="16.3.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#learning-strategies-matter"><i class="fa fa-check"></i><b>16.3.4</b> Learning strategies matter</a></li>
<li class="chapter" data-level="16.3.5" data-path="teaching-data-science.html"><a href="teaching-data-science.html#educators-can-help-students-to-learn"><i class="fa fa-check"></i><b>16.3.5</b> Educators can help students to learn</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#summary"><i class="fa fa-check"></i><b>16.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="learning-more.html"><a href="learning-more.html"><i class="fa fa-check"></i><b>17</b> Learning More</a><ul>
<li class="chapter" data-level="17.1" data-path="learning-more.html"><a href="learning-more.html#introduction-5"><i class="fa fa-check"></i><b>17.1</b> Introduction</a></li>
<li class="chapter" data-level="17.2" data-path="learning-more.html"><a href="learning-more.html#adopt-a-growth-mindset"><i class="fa fa-check"></i><b>17.2</b> Adopt a growth mindset</a></li>
<li class="chapter" data-level="17.3" data-path="learning-more.html"><a href="learning-more.html#discover-new-information"><i class="fa fa-check"></i><b>17.3</b> Discover new information</a></li>
<li class="chapter" data-level="17.4" data-path="learning-more.html"><a href="learning-more.html#ask-for-help"><i class="fa fa-check"></i><b>17.4</b> Ask for help</a><ul>
<li class="chapter" data-level="17.4.1" data-path="learning-more.html"><a href="learning-more.html#discussion-forums"><i class="fa fa-check"></i><b>17.4.1</b> Discussion forums</a></li>
<li class="chapter" data-level="17.4.2" data-path="learning-more.html"><a href="learning-more.html#github-repositories"><i class="fa fa-check"></i><b>17.4.2</b> GitHub repositories</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="learning-more.html"><a href="learning-more.html#share-what-youve-learned"><i class="fa fa-check"></i><b>17.5</b> Share what you’ve learned</a><ul>
<li class="chapter" data-level="17.5.1" data-path="learning-more.html"><a href="learning-more.html#where-to-share"><i class="fa fa-check"></i><b>17.5.1</b> Where to share</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="learning-more.html"><a href="learning-more.html#welcome-others"><i class="fa fa-check"></i><b>17.6</b> Welcome others</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="additional-resources.html"><a href="additional-resources.html"><i class="fa fa-check"></i><b>18</b> Additional Resources</a><ul>
<li class="chapter" data-level="18.1" data-path="additional-resources.html"><a href="additional-resources.html#data-science-courses"><i class="fa fa-check"></i><b>18.1</b> Data science courses</a></li>
<li class="chapter" data-level="18.2" data-path="additional-resources.html"><a href="additional-resources.html#workshop-materials"><i class="fa fa-check"></i><b>18.2</b> Workshop materials</a></li>
<li class="chapter" data-level="18.3" data-path="additional-resources.html"><a href="additional-resources.html#education-resources"><i class="fa fa-check"></i><b>18.3</b> Education resources</a></li>
<li class="chapter" data-level="18.4" data-path="additional-resources.html"><a href="additional-resources.html#data-visualization"><i class="fa fa-check"></i><b>18.4</b> Data visualization</a></li>
<li class="chapter" data-level="18.5" data-path="additional-resources.html"><a href="additional-resources.html#books-related-to-data-science-in-education"><i class="fa fa-check"></i><b>18.5</b> Books related to data science in education</a></li>
<li class="chapter" data-level="18.6" data-path="additional-resources.html"><a href="additional-resources.html#articles-related-to-data-science-in-education"><i class="fa fa-check"></i><b>18.6</b> Articles related to data science in education</a></li>
<li class="chapter" data-level="18.7" data-path="additional-resources.html"><a href="additional-resources.html#programming-with-r"><i class="fa fa-check"></i><b>18.7</b> Programming with R</a></li>
<li class="chapter" data-level="18.8" data-path="additional-resources.html"><a href="additional-resources.html#helpful-package-vignettes-and-descriptions-of-packages"><i class="fa fa-check"></i><b>18.8</b> Helpful package vignettes and descriptions of packages</a></li>
<li class="chapter" data-level="18.9" data-path="additional-resources.html"><a href="additional-resources.html#statistics"><i class="fa fa-check"></i><b>18.9</b> Statistics</a><ul>
<li class="chapter" data-level="18.9.1" data-path="additional-resources.html"><a href="additional-resources.html#introductory"><i class="fa fa-check"></i><b>18.9.1</b> Introductory</a></li>
<li class="chapter" data-level="18.9.2" data-path="additional-resources.html"><a href="additional-resources.html#advanced"><i class="fa fa-check"></i><b>18.9.2</b> Advanced</a></li>
</ul></li>
<li class="chapter" data-level="18.10" data-path="additional-resources.html"><a href="additional-resources.html#software-and-r-packages"><i class="fa fa-check"></i><b>18.10</b> Software and R Packages</a></li>
<li class="chapter" data-level="18.11" data-path="additional-resources.html"><a href="additional-resources.html#a-career-in-data-science"><i class="fa fa-check"></i><b>18.11</b> A career in data science</a></li>
<li class="chapter" data-level="18.12" data-path="additional-resources.html"><a href="additional-resources.html#places-to-share-your-work"><i class="fa fa-check"></i><b>18.12</b> Places to share your work</a></li>
<li class="chapter" data-level="18.13" data-path="additional-resources.html"><a href="additional-resources.html#cheat-sheets"><i class="fa fa-check"></i><b>18.13</b> Cheat Sheets</a></li>
<li class="chapter" data-level="18.14" data-path="additional-resources.html"><a href="additional-resources.html#learning-communities"><i class="fa fa-check"></i><b>18.14</b> Learning communities</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="conclusion-to-where-next.html"><a href="conclusion-to-where-next.html"><i class="fa fa-check"></i><b>19</b> Conclusion: To where next?</a><ul>
<li class="chapter" data-level="19.1" data-path="conclusion-to-where-next.html"><a href="conclusion-to-where-next.html#take-on-challenges"><i class="fa fa-check"></i><b>19.1</b> Take on challenges</a></li>
<li class="chapter" data-level="19.2" data-path="conclusion-to-where-next.html"><a href="conclusion-to-where-next.html#know-when-to-turn-to-something-else"><i class="fa fa-check"></i><b>19.2</b> Know when to turn to something else</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science in Education Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="education-dataset-analysis-pipeline-walkthrough-1" class="section level1">
<h1><span class="header-section-number">8</span> Education Dataset Analysis Pipeline: Walkthrough #1</h1>
<div id="background-and-purpose" class="section level2">
<h2><span class="header-section-number">8.1</span> Background and Purpose</h2>
<p>In the 2015-2016 and 2016-2017 school years, researchers carried out a study on students’ motivation to learn in online science classes. The online science classes were part of a statewide online course provider designed to supplement(and not replace) students’ enrollment in their local school. For example, students may choose to enroll in an online physics class because one was not offered at their school (or they were not able to take it given their schedule).</p>
<p>The study involved a number of different data sources which were explored to understand students’ motivation:</p>
<ol style="list-style-type: decimal">
<li>A self-report survey for three distinct but related aspects of students’ motivation</li>
<li>Log-trace data, such as data output from the learning management system</li>
<li>Discussion board data (not used in this walkthrough)</li>
<li>Achievement-related (i.e., final grade) data</li>
</ol>
<p>Our <em>purpose</em> for this walkthrough is to begin to understand what explains students’ performance in these online courses. To do so, we will focus on a variable that was available through the learning management system used for the courses, on he amount of time sudents’ spent on the course. We will also explore how different (science) subjects as well as being in a particular class may help to explain student performance.</p>
<p>First, these different data sources will be described in terms of how they were provided by the school.</p>
<div id="data-source-1-self-report-survey" class="section level3">
<h3><span class="header-section-number">8.1.1</span> Data Source #1: Self-report survey</h3>
<p>This was data collected before the start of the course via self-report survey. The survey included 10 items, each corresponding to one of three <em>measures</em>, namely, for interest, utility value, and perceived competence:</p>
<ol style="list-style-type: decimal">
<li>I think this course is an interesting subject. (Interest)</li>
<li>What I am learning in this class is relevant to my life. (Utility value)</li>
<li>I consider this topic to be one of my best subjects. (Perceived competence)</li>
<li>I am not interested in this course. (Interest - reverse coded)</li>
<li>I think I will like learning about this topic. (Interest)</li>
<li>I think what we are studying in this course is useful for me to know.
(Utility value)</li>
<li>I don’t feel comfortable when it comes to answering questions in this area.
(Perceived competence)</li>
<li>I think this subject is interesting. (Interest)</li>
<li>I find the content of this course to be personally meaningful. (Utility
value)</li>
<li>I’ve always wanted to learn more about this subject. (Interest)</li>
</ol>
</div>
<div id="data-source-2-log-trace-data" class="section level3">
<h3><span class="header-section-number">8.1.2</span> Data source #2: Log-trace data</h3>
<p><em>Log-trace data</em> is data generated from our interactions with digital
technologies, such as archived data from social media postings (see Chapter XXX and XXX). In education, an increasingly common source of log-trace data is that generated from interactions with learning management systems and other digital tools <span class="citation">(Siemens and Baker <a href="#ref-siemens2012">2012</a>)</span>. The data for this walk-through is a <em>summary of</em> log-trace data, namely, the number of minutes students spent on the course. Thus, while this data is rich, you can imagine even more complex sources of log-trace data (i.e.
timestamps associated with when students started and stopped accessing the course!).</p>
</div>
<div id="data-source-3-achievement-related-and-gradebook-data" class="section level3">
<h3><span class="header-section-number">8.1.3</span> Data source #3: Achievement-related and gradebook data</h3>
<p>This is a common source of data, namely, one associated with graded assignments
students completed. In this walkthrough, we just examine students’ final grade.</p>
</div>
<div id="data-source-4-discussion-board-data" class="section level3">
<h3><span class="header-section-number">8.1.4</span> Data source #4: Discussion board data</h3>
<p>Discussion board data is both rich and unstructured, in that it is primarily in
the form of written text. We collected discussion board data, too, and highlight
this as a potentially very rich data source.</p>
</div>
</div>
<div id="processing-the-data" class="section level2">
<h2><span class="header-section-number">8.2</span> Processing the data</h2>
<p>This analysis uses R packages, which are collections of R code that help users
code more efficiently, as you wil recall from Chapter INTRODUCTORY. We load
these packages with the function <code>library</code>. In particular, the packages we’ll
use will help us load Excel files, organize the structure of the data, work with
dates in the data, and navigate file directories.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw">library</span>(readxl)</a>
<a class="sourceLine" id="cb44-2" title="2"><span class="kw">library</span>(tidyverse)</a>
<a class="sourceLine" id="cb44-3" title="3"><span class="kw">library</span>(lubridate)</a>
<a class="sourceLine" id="cb44-4" title="4"><span class="kw">library</span>(here)</a>
<a class="sourceLine" id="cb44-5" title="5"><span class="kw">library</span>(dataedu)</a>
<a class="sourceLine" id="cb44-6" title="6"><span class="kw">library</span>(apaTables)</a>
<a class="sourceLine" id="cb44-7" title="7"><span class="kw">library</span>(sjPlot)</a></code></pre></div>
<p>This code chunk loads the log trace data using the <code>read_csv</code> function. Note that we call <code>read_csv</code> three times, once for each of the three logtrace
datasets. We assign each of the datasets a name using <code>&lt;-</code>.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="co"># Gradebook and log-trace data for F15 and S16 semesters</span></a>
<a class="sourceLine" id="cb45-2" title="2">s12_course_data &lt;-</a>
<a class="sourceLine" id="cb45-3" title="3"><span class="st">  </span><span class="kw">read_csv</span>(<span class="kw">here</span>(</a>
<a class="sourceLine" id="cb45-4" title="4">    <span class="st">&quot;data&quot;</span>,</a>
<a class="sourceLine" id="cb45-5" title="5">    <span class="st">&quot;online-science-motivation&quot;</span>,</a>
<a class="sourceLine" id="cb45-6" title="6">    <span class="st">&quot;raw&quot;</span>,</a>
<a class="sourceLine" id="cb45-7" title="7">    <span class="st">&quot;s12-course-data.csv&quot;</span></a>
<a class="sourceLine" id="cb45-8" title="8">  ))</a>
<a class="sourceLine" id="cb45-9" title="9"></a>
<a class="sourceLine" id="cb45-10" title="10"><span class="co"># Pre-survey for the F15 and S16 semesters</span></a>
<a class="sourceLine" id="cb45-11" title="11"></a>
<a class="sourceLine" id="cb45-12" title="12">s12_pre_survey &lt;-</a>
<a class="sourceLine" id="cb45-13" title="13"><span class="st">  </span><span class="kw">read_csv</span>(<span class="kw">here</span>(</a>
<a class="sourceLine" id="cb45-14" title="14">    <span class="st">&quot;data&quot;</span>,</a>
<a class="sourceLine" id="cb45-15" title="15">    <span class="st">&quot;online-science-motivation&quot;</span>,</a>
<a class="sourceLine" id="cb45-16" title="16">    <span class="st">&quot;raw&quot;</span>,</a>
<a class="sourceLine" id="cb45-17" title="17">    <span class="st">&quot;s12-pre-survey.csv&quot;</span></a>
<a class="sourceLine" id="cb45-18" title="18">  ))</a>
<a class="sourceLine" id="cb45-19" title="19"></a>
<a class="sourceLine" id="cb45-20" title="20"><span class="co"># Log-trace data for F15 and S16 semesters - this is for time spent</span></a>
<a class="sourceLine" id="cb45-21" title="21"></a>
<a class="sourceLine" id="cb45-22" title="22">s12_time_spent &lt;-</a>
<a class="sourceLine" id="cb45-23" title="23"><span class="st">  </span><span class="kw">read_csv</span>(<span class="kw">here</span>(</a>
<a class="sourceLine" id="cb45-24" title="24">    <span class="st">&quot;data&quot;</span>,</a>
<a class="sourceLine" id="cb45-25" title="25">    <span class="st">&quot;online-science-motivation&quot;</span>,</a>
<a class="sourceLine" id="cb45-26" title="26">    <span class="st">&quot;raw&quot;</span>,</a>
<a class="sourceLine" id="cb45-27" title="27">    <span class="st">&quot;s12-course-minutes.csv&quot;</span></a>
<a class="sourceLine" id="cb45-28" title="28">  ))</a></code></pre></div>
</div>
<div id="viewing-the-data" class="section level2">
<h2><span class="header-section-number">8.3</span> Viewing the data</h2>
<p>Now that we’ve successfully loaded all three logtrace datasets, we can visually inspect the data by typing the names that we assigned to each dataset.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1">s12_pre_survey</a></code></pre></div>
<pre><code>## # A tibble: 1,102 x 16
##    RespondentId StartDate CompletedDate LanguageCode opdata_CourseID
##           &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;        &lt;chr&gt;          
##  1       426746 2015.08.… &lt;NA&gt;          en           FrScA-S116-01  
##  2       426775 2015.08.… 2015.08.24 1… en           BioA-S116-01   
##  3       427483 2015.08.… &lt;NA&gt;          en           OcnA-S116-03   
##  4       429883 2015.09.… 2015.09.02 1… en           AnPhA-S116-01  
##  5       430158 2015.09.… 2015.09.03 9… en           AnPhA-S116-01  
##  6       430161 2015.09.… 2015.09.03 9… en           AnPhA-S116-02  
##  7       430162 2015.09.… 2015.09.03 9… en           AnPhA-T116-01  
##  8       430167 2015.09.… 2015.09.03 9… en           BioA-S116-01   
##  9       430170 2015.09.… 2015.09.03 9… en           BioA-T116-01   
## 10       430172 2015.09.… 2015.09.03 9… en           PhysA-S116-01  
## # … with 1,092 more rows, and 11 more variables: opdata_username &lt;chr&gt;,
## #   Q1MaincellgroupRow1 &lt;dbl&gt;, Q1MaincellgroupRow2 &lt;dbl&gt;,
## #   Q1MaincellgroupRow3 &lt;dbl&gt;, Q1MaincellgroupRow4 &lt;dbl&gt;,
## #   Q1MaincellgroupRow5 &lt;dbl&gt;, Q1MaincellgroupRow6 &lt;dbl&gt;,
## #   Q1MaincellgroupRow7 &lt;dbl&gt;, Q1MaincellgroupRow8 &lt;dbl&gt;,
## #   Q1MaincellgroupRow9 &lt;dbl&gt;, Q1MaincellgroupRow10 &lt;dbl&gt;</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1">s12_course_data</a></code></pre></div>
<pre><code>## # A tibble: 29,711 x 16
##    CourseSectionOr… Bb_UserPK EnrollmentStatus EnrollmentReason Gender
##    &lt;chr&gt;                &lt;dbl&gt; &lt;chr&gt;            &lt;chr&gt;            &lt;chr&gt; 
##  1 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  2 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  3 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  4 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  5 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  6 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  7 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  8 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
##  9 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
## 10 AnPhA-S116-01        60186 Approved/Enroll… Course Unavaila… M     
## # … with 29,701 more rows, and 11 more variables: FinalGradeCEMS &lt;dbl&gt;,
## #   Gradebook_Item &lt;chr&gt;, Item_Position &lt;dbl&gt;, Gradebook_Type &lt;chr&gt;,
## #   Gradebook_Date &lt;chr&gt;, Grade_Category &lt;chr&gt;, Status &lt;lgl&gt;,
## #   Points_Earned &lt;chr&gt;, Points_Attempted &lt;dbl&gt;, Points_Possible &lt;dbl&gt;,
## #   last_access_date &lt;time&gt;</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb50-1" title="1">s12_time_spent</a></code></pre></div>
<pre><code>## # A tibble: 598 x 6
##    CourseID CourseSectionID CourseSectionOrigID Bb_UserPK   CUPK TimeSpent
##       &lt;dbl&gt;           &lt;dbl&gt; &lt;chr&gt;                   &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;
##  1       27           17146 OcnA-S116-01            44638 190682     1383.
##  2       27           17146 OcnA-S116-01            54346 194259     1191.
##  3       27           17146 OcnA-S116-01            57981 196014     3343.
##  4       27           17146 OcnA-S116-01            66740 190463      965.
##  5       27           17146 OcnA-S116-01            67920 191593     4095.
##  6       27           17146 OcnA-S116-01            85355 190104      595.
##  7       27           17146 OcnA-S116-01            85644 190685     1632.
##  8       27           17146 OcnA-S116-01            86349 191713     1601.
##  9       27           17146 OcnA-S116-01            86460 191887     1891.
## 10       27           17146 OcnA-S116-01            87970 194256     3123.
## # … with 588 more rows</code></pre>
</div>
<div id="processing-the-pre-survey-data" class="section level2">
<h2><span class="header-section-number">8.4</span> Processing the pre-survey data</h2>
<p>Often, survey data needs to be processed in order to be (most) useful. Here, we
process the self-report items into three scales, for: interest, self-efficacy,
and utility value. We do this by</p>
<ul>
<li>Renaming the question variables to something more managable</li>
<li>Reversing the response scales on questions 4 and 7</li>
<li>Categorizing each question into a measure</li>
<li>Computing the mean of each measure</li>
</ul>
<p>Let’s take these steps in order:</p>
<ol style="list-style-type: decimal">
<li>Rename the question columns to something much simpler:</li>
</ol>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1">s12_pre_survey  &lt;-</a>
<a class="sourceLine" id="cb52-2" title="2"><span class="st">  </span>s12_pre_survey  <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb52-3" title="3"><span class="st">  </span><span class="co"># Rename the qustions something easier to work with because R is case sensitive</span></a>
<a class="sourceLine" id="cb52-4" title="4"><span class="st">  </span><span class="co"># and working with variable names in mix case is prone to error</span></a>
<a class="sourceLine" id="cb52-5" title="5"><span class="st">  </span><span class="kw">rename</span>(</a>
<a class="sourceLine" id="cb52-6" title="6">    <span class="dt">q1 =</span> Q1MaincellgroupRow1,</a>
<a class="sourceLine" id="cb52-7" title="7">    <span class="dt">q2 =</span> Q1MaincellgroupRow2,</a>
<a class="sourceLine" id="cb52-8" title="8">    <span class="dt">q3 =</span> Q1MaincellgroupRow3,</a>
<a class="sourceLine" id="cb52-9" title="9">    <span class="dt">q4 =</span> Q1MaincellgroupRow4,</a>
<a class="sourceLine" id="cb52-10" title="10">    <span class="dt">q5 =</span> Q1MaincellgroupRow5,</a>
<a class="sourceLine" id="cb52-11" title="11">    <span class="dt">q6 =</span> Q1MaincellgroupRow6,</a>
<a class="sourceLine" id="cb52-12" title="12">    <span class="dt">q7 =</span> Q1MaincellgroupRow7,</a>
<a class="sourceLine" id="cb52-13" title="13">    <span class="dt">q8 =</span> Q1MaincellgroupRow8,</a>
<a class="sourceLine" id="cb52-14" title="14">    <span class="dt">q9 =</span> Q1MaincellgroupRow9,</a>
<a class="sourceLine" id="cb52-15" title="15">    <span class="dt">q10 =</span> Q1MaincellgroupRow10</a>
<a class="sourceLine" id="cb52-16" title="16">  ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb52-17" title="17"><span class="st">  </span><span class="co"># Convert all question responses to numeric</span></a>
<a class="sourceLine" id="cb52-18" title="18"><span class="st">  </span><span class="kw">mutate_at</span>(<span class="kw">vars</span>(q1<span class="op">:</span>q10), <span class="kw">list</span>( <span class="op">~</span><span class="st"> </span><span class="kw">as.numeric</span>(.)))</a></code></pre></div>
<p>Let’s take a moment to discuss the <code>dplyr</code> function <code>mutate_at</code>. <code>mutate_at</code> is a version of <code>mutate</code>, which changes the values in an existing column or creates new columns. It’s useful in education datasets because you’ll often need to transform your data before analyzing it. Try this example, where we create a new <code>total_students</code> column by adding the number of <code>male</code> students and <code>female</code> students:</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb53-1" title="1"><span class="co"># Dataset of students</span></a>
<a class="sourceLine" id="cb53-2" title="2">df &lt;-<span class="st"> </span><span class="kw">tibble</span>(</a>
<a class="sourceLine" id="cb53-3" title="3">  <span class="dt">male =</span> <span class="dv">5</span>, </a>
<a class="sourceLine" id="cb53-4" title="4">  <span class="dt">female =</span> <span class="dv">5</span></a>
<a class="sourceLine" id="cb53-5" title="5">)</a>
<a class="sourceLine" id="cb53-6" title="6"></a>
<a class="sourceLine" id="cb53-7" title="7">df <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">mutate</span>(<span class="dt">total_students =</span> male <span class="op">+</span><span class="st"> </span>female)</a></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##    male female total_students
##   &lt;dbl&gt;  &lt;dbl&gt;          &lt;dbl&gt;
## 1     5      5             10</code></pre>
<p><code>mutate_at</code> is a special version of <code>mutate</code>, which conveniently changes the values of multiple columns. In our dataset <code>s_12_pre_survey</code>, we let <code>mutate</code> know we want to change the variables <code>q1</code> through <code>q10</code>. We do this with the argument <code>vars(q1:q10)</code></p>
<ol start="2" style="list-style-type: decimal">
<li>Next we’ll reverse the scale of the survey responses on questions 4 and 7 so
the responses for all questions can be interpreted in the same way. Rather
than write a lot of code once to reverse the scales for question 4 then
writing it again to reverse the scales on question 7, we’ll build a function
that does that job for us. Then we’ll use the same function for question 4
and question 7. This will result in much less code, plus it will make it
easier for us to change in the future.</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1"><span class="co"># This part of the code is where we write the function:</span></a>
<a class="sourceLine" id="cb55-2" title="2"><span class="co"># Function for reversing scales </span></a>
<a class="sourceLine" id="cb55-3" title="3">reverse_scale &lt;-<span class="st"> </span><span class="cf">function</span>(question) {</a>
<a class="sourceLine" id="cb55-4" title="4">  <span class="co"># Reverses the response scales for consistency</span></a>
<a class="sourceLine" id="cb55-5" title="5">  <span class="co">#   Args:</span></a>
<a class="sourceLine" id="cb55-6" title="6">  <span class="co">#     question: survey question</span></a>
<a class="sourceLine" id="cb55-7" title="7">  <span class="co">#   Returns: a numeric converted response</span></a>
<a class="sourceLine" id="cb55-8" title="8">  <span class="co"># Note: even though 3 is not transformed, case_when expects a match for all</span></a>
<a class="sourceLine" id="cb55-9" title="9">  <span class="co"># possible conditions, so it&#39;s best practice to label each possible input</span></a>
<a class="sourceLine" id="cb55-10" title="10">  <span class="co"># and use TRUE ~ as the final statement returning NA for unexpected inputs</span></a>
<a class="sourceLine" id="cb55-11" title="11">  x &lt;-<span class="st"> </span><span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb55-12" title="12">    question <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">~</span><span class="st"> </span><span class="dv">5</span>,</a>
<a class="sourceLine" id="cb55-13" title="13">    question <span class="op">==</span><span class="st"> </span><span class="dv">2</span> <span class="op">~</span><span class="st"> </span><span class="dv">4</span>,</a>
<a class="sourceLine" id="cb55-14" title="14">    question <span class="op">==</span><span class="st"> </span><span class="dv">4</span> <span class="op">~</span><span class="st"> </span><span class="dv">2</span>,</a>
<a class="sourceLine" id="cb55-15" title="15">    question <span class="op">==</span><span class="st"> </span><span class="dv">5</span> <span class="op">~</span><span class="st"> </span><span class="dv">1</span>,</a>
<a class="sourceLine" id="cb55-16" title="16">    question <span class="op">==</span><span class="st"> </span><span class="dv">3</span> <span class="op">~</span><span class="st"> </span><span class="dv">3</span>,</a>
<a class="sourceLine" id="cb55-17" title="17">    <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">NA_real_</span></a>
<a class="sourceLine" id="cb55-18" title="18">  )</a>
<a class="sourceLine" id="cb55-19" title="19">  x</a>
<a class="sourceLine" id="cb55-20" title="20">}</a>
<a class="sourceLine" id="cb55-21" title="21"></a>
<a class="sourceLine" id="cb55-22" title="22"><span class="co"># And here&#39;s where we use that function to reverse the scales</span></a>
<a class="sourceLine" id="cb55-23" title="23"><span class="co"># Reverse scale for questions 4 and 7</span></a>
<a class="sourceLine" id="cb55-24" title="24">s12_pre_survey &lt;-</a>
<a class="sourceLine" id="cb55-25" title="25"><span class="st">  </span>s12_pre_survey <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb55-26" title="26"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">q4 =</span> <span class="kw">reverse_scale</span>(q4),</a>
<a class="sourceLine" id="cb55-27" title="27">         <span class="dt">q7 =</span> <span class="kw">reverse_scale</span>(q7))</a></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li>We’ll accomplish the last two steps in one chunk of code. First we’ll create a column called <code>measure</code> and we’ll fill that column with one of three question categories:</li>
</ol>
<ul>
<li><code>int</code>: interest</li>
<li><code>uv</code>: utility value</li>
<li><code>pc</code>: self efficacy</li>
</ul>
<p>After that we’ll find the mean response of each category using <code>mean</code> function.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="co"># Add measure variable </span></a>
<a class="sourceLine" id="cb56-2" title="2">s12_measure_mean &lt;-</a>
<a class="sourceLine" id="cb56-3" title="3"><span class="st">  </span>s12_pre_survey <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb56-4" title="4"><span class="st">  </span><span class="co"># Gather questions and responses</span></a>
<a class="sourceLine" id="cb56-5" title="5"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> q1<span class="op">:</span>q10,</a>
<a class="sourceLine" id="cb56-6" title="6">               <span class="dt">names_to =</span> <span class="st">&quot;question&quot;</span>,</a>
<a class="sourceLine" id="cb56-7" title="7">               <span class="dt">values_to =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb56-8" title="8"><span class="st">  </span><span class="co"># Here&#39;s where we make the column of question categories</span></a>
<a class="sourceLine" id="cb56-9" title="9"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb56-10" title="10">    <span class="dt">measure =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb56-11" title="11">      question <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;q1&quot;</span>, <span class="st">&quot;q4&quot;</span>, <span class="st">&quot;q5&quot;</span>, <span class="st">&quot;q8&quot;</span>, <span class="st">&quot;q10&quot;</span>) <span class="op">~</span><span class="st"> &quot;int&quot;</span>,</a>
<a class="sourceLine" id="cb56-12" title="12">      question <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;q2&quot;</span>, <span class="st">&quot;q6&quot;</span>, <span class="st">&quot;q9&quot;</span>) <span class="op">~</span><span class="st"> &quot;uv&quot;</span>,</a>
<a class="sourceLine" id="cb56-13" title="13">      question <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;q3&quot;</span>, <span class="st">&quot;q7&quot;</span>) <span class="op">~</span><span class="st"> &quot;pc&quot;</span>,</a>
<a class="sourceLine" id="cb56-14" title="14">      <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">NA_character_</span></a>
<a class="sourceLine" id="cb56-15" title="15">    )</a>
<a class="sourceLine" id="cb56-16" title="16">  ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb56-17" title="17"><span class="st">  </span><span class="kw">group_by</span>(measure) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb56-18" title="18"><span class="st">  </span><span class="kw">summarise</span>(<span class="co"># Here&#39;s where we compute the mean of the responses</span></a>
<a class="sourceLine" id="cb56-19" title="19">    <span class="co"># Mean response for each measure</span></a>
<a class="sourceLine" id="cb56-20" title="20">    <span class="dt">mean_response =</span> <span class="kw">mean</span>(response, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb56-21" title="21">    <span class="co"># Percent of each measure that had NAs in the response field</span></a>
<a class="sourceLine" id="cb56-22" title="22">    <span class="dt">percent_NA =</span> <span class="kw">mean</span>(<span class="kw">is.na</span>(response)))</a>
<a class="sourceLine" id="cb56-23" title="23"></a>
<a class="sourceLine" id="cb56-24" title="24">s12_measure_mean</a></code></pre></div>
<pre><code>## # A tibble: 3 x 3
##   measure mean_response percent_NA
##   &lt;chr&gt;           &lt;dbl&gt;      &lt;dbl&gt;
## 1 int              4.26      0.171
## 2 pc               3.65      0.170
## 3 uv               3.76      0.170</code></pre>
<p>We will use a similar process later to calculate these variables’ correlations.</p>
</div>
<div id="processing-the-course-data" class="section level2">
<h2><span class="header-section-number">8.5</span> Processing the course data</h2>
<p>We also can process the course data in order to create new variables which we
can use in analyses. This led to pulling out the subject, semester, and section
from the course ID; variables that we can use later on.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="co"># split course section into components</span></a>
<a class="sourceLine" id="cb58-2" title="2">s12_course_data &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb58-3" title="3"><span class="st">  </span>s12_course_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb58-4" title="4"><span class="st">  </span><span class="kw">separate</span>(</a>
<a class="sourceLine" id="cb58-5" title="5">    <span class="dt">col =</span> CourseSectionOrigID,</a>
<a class="sourceLine" id="cb58-6" title="6">    <span class="dt">into =</span> <span class="kw">c</span>(<span class="st">&quot;subject&quot;</span>, <span class="st">&quot;semester&quot;</span>, <span class="st">&quot;section&quot;</span>),</a>
<a class="sourceLine" id="cb58-7" title="7">    <span class="dt">sep =</span> <span class="st">&quot;-&quot;</span>,</a>
<a class="sourceLine" id="cb58-8" title="8">    <span class="dt">remove =</span> <span class="ot">FALSE</span></a>
<a class="sourceLine" id="cb58-9" title="9">  )</a></code></pre></div>
</div>
<div id="joining-the-data" class="section level2">
<h2><span class="header-section-number">8.6</span> Joining the data</h2>
<p>To join the course data and pre-survey data, we need to create similar <em>keys</em>.
In other words, our goal here is to have one variable that matches across both
datasets, so that we can merge the datasets on the basis of that variable.</p>
<p>For these data, both have variables for the course and the student, though they
have different names in each. Our first goal will be to rename two variables in
each of our datasets so that they will match. One variable will correspond to
the course, and the other will correspond to the student. We are not changing
anything in the data itself at this step - instead, we are just cleaning it up
so that we can look at the data all in one place.</p>
<p>Let’s start with the pre-survey data. We will rename RespondentID and opdata_CourseID to be student_id and course_id, respectively.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">s12_pre_survey &lt;-</a>
<a class="sourceLine" id="cb59-2" title="2"><span class="st">  </span>s12_pre_survey <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb59-3" title="3"><span class="st">  </span><span class="kw">rename</span>(<span class="dt">student_id =</span> RespondentId,</a>
<a class="sourceLine" id="cb59-4" title="4">         <span class="dt">course_id =</span> opdata_CourseID)</a>
<a class="sourceLine" id="cb59-5" title="5"></a>
<a class="sourceLine" id="cb59-6" title="6">s12_pre_survey</a></code></pre></div>
<pre><code>## # A tibble: 1,102 x 16
##    student_id StartDate CompletedDate LanguageCode course_id opdata_username
##         &lt;dbl&gt; &lt;chr&gt;     &lt;chr&gt;         &lt;chr&gt;        &lt;chr&gt;     &lt;chr&gt;          
##  1     426746 2015.08.… &lt;NA&gt;          en           FrScA-S1… _80624_1       
##  2     426775 2015.08.… 2015.08.24 1… en           BioA-S11… _80623_1       
##  3     427483 2015.08.… &lt;NA&gt;          en           OcnA-S11… _82588_1       
##  4     429883 2015.09.… 2015.09.02 1… en           AnPhA-S1… _80623_1       
##  5     430158 2015.09.… 2015.09.03 9… en           AnPhA-S1… _80624_1       
##  6     430161 2015.09.… 2015.09.03 9… en           AnPhA-S1… _80624_1       
##  7     430162 2015.09.… 2015.09.03 9… en           AnPhA-T1… _80624_1       
##  8     430167 2015.09.… 2015.09.03 9… en           BioA-S11… _80624_1       
##  9     430170 2015.09.… 2015.09.03 9… en           BioA-T11… _80624_1       
## 10     430172 2015.09.… 2015.09.03 9… en           PhysA-S1… _80624_1       
## # … with 1,092 more rows, and 10 more variables: q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;,
## #   q4 &lt;dbl&gt;, q5 &lt;dbl&gt;, q6 &lt;dbl&gt;, q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;</code></pre>
<p>Looks better now!</p>
<p>Let’s proceed to the course data. Our goal is to rename two variables that
correspond to the course and the student so that we can match with the other
variables we just created for the pre-survey data.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb61-1" title="1">s12_course_data &lt;-</a>
<a class="sourceLine" id="cb61-2" title="2"><span class="st">  </span>s12_course_data <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb61-3" title="3"><span class="st">  </span><span class="kw">rename</span>(<span class="dt">student_id =</span> Bb_UserPK,</a>
<a class="sourceLine" id="cb61-4" title="4">         <span class="dt">course_id =</span> CourseSectionOrigID)</a></code></pre></div>
<p>Now that we have two variables that are consistent across both datasets - we have called them “course_id” and “student_id” - we can join these using the <strong>dplyr</strong> function, <code>left_join()</code>.</p>
<p>Let’s save our joined data as a new object called “dat.”</p>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb62-1" title="1">dat &lt;-</a>
<a class="sourceLine" id="cb62-2" title="2"><span class="st">  </span><span class="kw">left_join</span>(s12_course_data,</a>
<a class="sourceLine" id="cb62-3" title="3">            s12_pre_survey,</a>
<a class="sourceLine" id="cb62-4" title="4">            <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;student_id&quot;</span>, <span class="st">&quot;course_id&quot;</span>))</a>
<a class="sourceLine" id="cb62-5" title="5">dat</a></code></pre></div>
<pre><code>## # A tibble: 29,711 x 33
##    course_id subject semester section student_id EnrollmentStatus
##    &lt;chr&gt;     &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;           
##  1 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  2 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  3 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  4 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  5 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  6 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  7 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  8 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  9 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
## 10 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
## # … with 29,701 more rows, and 27 more variables: EnrollmentReason &lt;chr&gt;,
## #   Gender &lt;chr&gt;, FinalGradeCEMS &lt;dbl&gt;, Gradebook_Item &lt;chr&gt;,
## #   Item_Position &lt;dbl&gt;, Gradebook_Type &lt;chr&gt;, Gradebook_Date &lt;chr&gt;,
## #   Grade_Category &lt;chr&gt;, Status &lt;lgl&gt;, Points_Earned &lt;chr&gt;,
## #   Points_Attempted &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, last_access_date &lt;time&gt;,
## #   StartDate &lt;chr&gt;, CompletedDate &lt;chr&gt;, LanguageCode &lt;chr&gt;,
## #   opdata_username &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;,
## #   q6 &lt;dbl&gt;, q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;</code></pre>
<p>Just one more data frame to merge:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb64-1" title="1">s12_time_spent &lt;-</a>
<a class="sourceLine" id="cb64-2" title="2"><span class="st">  </span>s12_time_spent <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb64-3" title="3"><span class="st">  </span><span class="kw">rename</span>(<span class="dt">student_id =</span> Bb_UserPK,</a>
<a class="sourceLine" id="cb64-4" title="4">         <span class="dt">course_id =</span> CourseSectionOrigID)</a>
<a class="sourceLine" id="cb64-5" title="5"></a>
<a class="sourceLine" id="cb64-6" title="6">s12_time_spent &lt;-</a>
<a class="sourceLine" id="cb64-7" title="7"><span class="st">  </span>s12_time_spent <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb64-8" title="8"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">student_id =</span> <span class="kw">as.integer</span>(student_id))</a>
<a class="sourceLine" id="cb64-9" title="9"></a>
<a class="sourceLine" id="cb64-10" title="10">dat &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb64-11" title="11"><span class="st">  </span>dat <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb64-12" title="12"><span class="st">  </span><span class="kw">left_join</span>(s12_time_spent, </a>
<a class="sourceLine" id="cb64-13" title="13">            <span class="dt">by =</span> <span class="kw">c</span>(<span class="st">&quot;student_id&quot;</span>, <span class="st">&quot;course_id&quot;</span>))</a></code></pre></div>
<p>Note that they’re now combined, even though the course data has many more rows: The pre_survey data has been joined for each student by course combination.</p>
<p>We have a pretty large data frame! Let’s take a quick look.</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb65-1" title="1">dat</a></code></pre></div>
<pre><code>## # A tibble: 29,711 x 37
##    course_id subject semester section student_id EnrollmentStatus
##    &lt;chr&gt;     &lt;chr&gt;   &lt;chr&gt;    &lt;chr&gt;        &lt;dbl&gt; &lt;chr&gt;           
##  1 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  2 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  3 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  4 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  5 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  6 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  7 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  8 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
##  9 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
## 10 AnPhA-S1… AnPhA   S116     01           60186 Approved/Enroll…
## # … with 29,701 more rows, and 31 more variables: EnrollmentReason &lt;chr&gt;,
## #   Gender &lt;chr&gt;, FinalGradeCEMS &lt;dbl&gt;, Gradebook_Item &lt;chr&gt;,
## #   Item_Position &lt;dbl&gt;, Gradebook_Type &lt;chr&gt;, Gradebook_Date &lt;chr&gt;,
## #   Grade_Category &lt;chr&gt;, Status &lt;lgl&gt;, Points_Earned &lt;chr&gt;,
## #   Points_Attempted &lt;dbl&gt;, Points_Possible &lt;dbl&gt;, last_access_date &lt;time&gt;,
## #   StartDate &lt;chr&gt;, CompletedDate &lt;chr&gt;, LanguageCode &lt;chr&gt;,
## #   opdata_username &lt;chr&gt;, q1 &lt;dbl&gt;, q2 &lt;dbl&gt;, q3 &lt;dbl&gt;, q4 &lt;dbl&gt;, q5 &lt;dbl&gt;,
## #   q6 &lt;dbl&gt;, q7 &lt;dbl&gt;, q8 &lt;dbl&gt;, q9 &lt;dbl&gt;, q10 &lt;dbl&gt;, CourseID &lt;dbl&gt;,
## #   CourseSectionID &lt;dbl&gt;, CUPK &lt;dbl&gt;, TimeSpent &lt;dbl&gt;</code></pre>
<p>It looks like we have nearly 30,000 observations from 30 variables.</p>
<p>There is one last step to take. Were we interested in a fine-grained analysis of
how students performed (according to the teacher) on different assignments (see
the <code>Gradebook_Item</code> column), we would keep all (29,711 rows of) the data. But,
our goal (for now) is more modest: to calculate the percentage of points
students earned as a measure of their final grade (noting that the teacher may
have assigned a different grade–or weighted their grades in ways not reflected
through the points).</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb67-1" title="1">dat &lt;-</a>
<a class="sourceLine" id="cb67-2" title="2"><span class="st">  </span>dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-3" title="3"><span class="st">  </span><span class="kw">group_by</span>(student_id, course_id) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">Points_Earned =</span> <span class="kw">as.integer</span>(Points_Earned)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-5" title="5"><span class="st">  </span><span class="kw">summarize</span>(</a>
<a class="sourceLine" id="cb67-6" title="6">    <span class="dt">total_points_possible =</span> <span class="kw">sum</span>(Points_Possible, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>),</a>
<a class="sourceLine" id="cb67-7" title="7">    <span class="dt">total_points_earned =</span> <span class="kw">sum</span>(Points_Earned, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb67-8" title="8">  ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-9" title="9"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">percentage_earned =</span> total_points_earned <span class="op">/</span><span class="st"> </span>total_points_possible) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-10" title="10"><span class="st">  </span><span class="kw">ungroup</span>() <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb67-11" title="11"><span class="st">  </span><span class="kw">left_join</span>(dat) <span class="co"># note that we join this back to the original data frame to retain all of the variables</span></a></code></pre></div>
</div>
<div id="finding-distinct-cases-at-the-student-level" class="section level2">
<h2><span class="header-section-number">8.7</span> Finding distinct cases at the student-level</h2>
<p>This last step calculated a new column, for the percentage of points each
student earned. That value is the same for the same student (an easy way we
would potentially use to check this is <code>View()</code>, i.e., <code>View(dat)</code>).
But–because we are not carrying out a finer-grained analysis using the
<code>Gradebook_Item</code>–the duplicate rows are not necessary. We only want variables
at the student-level (and not at the level of different gradebook items). We can
do this using the <code>distinct()</code> function. This function takes the name of the
data frame and the name of the variables used to determine what counts as a
unique case. Another thing to note about <code>distinct()</code> is that it will only
return the variable(s) (we note that you can pass more than one variable to
<code>distinct()</code>) you used to determine uniqueness, <em>unless</em> you include the
argument <code>.keep_all = TRUE</code>. For the sake of making it very easy to view the
output, we omit this argument (only for now).</p>
<p>Were we to run <code>distinct(dat, Gradebook_Item)</code>, what do you think would be
returned?</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb68-1" title="1"><span class="kw">distinct</span>(dat, Gradebook_Item)</a></code></pre></div>
<pre><code>## # A tibble: 222 x 1
##    Gradebook_Item                                             
##    &lt;chr&gt;                                                      
##  1 POINTS EARNED &amp; TOTAL COURSE POINTS                        
##  2 WORK ATTEMPTED                                             
##  3 0-1.1: Intro Assignment - Send a Message to Your Instructor
##  4 0-1.2: Intro Assignment - DB #1                            
##  5 0-1.3: Intro Assignment - Submitting Files                 
##  6 1-1.1: Lesson 1-1 Graphic Organizer                        
##  7 1-2.1: Explore a Career Assignment                         
##  8 1-2.2: Explore a Career DB #2                              
##  9 PROGRESS CHECK 1 @ 02-18-16                                
## 10 1-2.3: Lesson 1-2 Graphic Organizer                        
## # … with 212 more rows</code></pre>
<p>What is every distinct gradebook item is what is returned. You might be
wondering (as we were) whether some gradebook items have the same values across
courses; we can return the unique <em>combination</em> of courses and gradebook items
by simply adding another variable to <code>distinct()</code>:</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb70-1" title="1"><span class="kw">distinct</span>(dat, course_id, Gradebook_Item)</a></code></pre></div>
<pre><code>## # A tibble: 1,269 x 2
##    course_id     Gradebook_Item                                             
##    &lt;chr&gt;         &lt;chr&gt;                                                      
##  1 FrScA-S216-02 POINTS EARNED &amp; TOTAL COURSE POINTS                        
##  2 FrScA-S216-02 WORK ATTEMPTED                                             
##  3 FrScA-S216-02 0-1.1: Intro Assignment - Send a Message to Your Instructor
##  4 FrScA-S216-02 0-1.2: Intro Assignment - DB #1                            
##  5 FrScA-S216-02 0-1.3: Intro Assignment - Submitting Files                 
##  6 FrScA-S216-02 1-1.1: Lesson 1-1 Graphic Organizer                        
##  7 FrScA-S216-02 1-2.1: Explore a Career Assignment                         
##  8 FrScA-S216-02 1-2.2: Explore a Career DB #2                              
##  9 FrScA-S216-02 PROGRESS CHECK 1 @ 02-18-16                                
## 10 FrScA-S216-02 1-2.3: Lesson 1-2 Graphic Organizer                        
## # … with 1,259 more rows</code></pre>
<p>It looks like <em>a lot</em> of gradebook items were repeated - likely across the
different sections of the same course (we would be curious to hear what you find
if you investigate this!).</p>
<p>Let’s use what we just did, but to find the unique values at the student-level.
Thus, instead of exploring unique gradebook items, we will explore unique
students (still accounting for the course, as students could enroll in more than
one course.) This time, we will add the <code>keep_all = TRUE</code> argument.</p>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb72-1" title="1">dat &lt;-</a>
<a class="sourceLine" id="cb72-2" title="2"><span class="st">  </span><span class="kw">distinct</span>(dat, course_id, student_id, <span class="dt">.keep_all =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>This is a much smaller data frame - with one row for each sudnet in the course
(instead of the 29,701 rows which we would be interested in were we analyzing
this data at the level of specific students’ grades for specific gradebook
items). Now that our data are ready to go, we can start to ask some questions of
the data,</p>
</div>
<div id="visualizations-and-models" class="section level2">
<h2><span class="header-section-number">8.8</span> Visualizations and Models</h2>
<div id="the-relationship-between-time-spent-on-course-and-percentage-of-points-earned" class="section level3">
<h3><span class="header-section-number">8.8.1</span> The relationship between time spent on course and percentage of points earned</h3>
<p>One thing we might be wondering is how time spent on course is related to
students’ final grade.</p>
<p>We note that ggplot2, which we use to create these plots, is discussed further in chapter XXX.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb73-1" title="1">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb73-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> TimeSpent, <span class="dt">y =</span> percentage_earned)) <span class="op">+</span><span class="st"> </span><span class="co"># this tells ggplot2 what variables to map to what feature of a plot, here, x- anx y-axis locations</span></a>
<a class="sourceLine" id="cb73-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb73-4" title="4"><span class="st">  </span><span class="co"># creates a point with x- and y-axis coordinates specified above</span></a>
<a class="sourceLine" id="cb73-5" title="5"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="06-wt-multilevel-models-1_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>There appears to be <em>some</em> relationship. What if we added a line of best fit - a linear model?</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb74-1" title="1">dat <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb74-2" title="2"><span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> TimeSpent, <span class="dt">y =</span> percentage_earned)) <span class="op">+</span></a>
<a class="sourceLine" id="cb74-3" title="3"><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="co"># same as above</span></a>
<a class="sourceLine" id="cb74-4" title="4"><span class="st">  </span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb74-5" title="5"><span class="st">  </span><span class="co"># this adds a line of best fit; method = &quot;lm&quot; tells ggplot2 to make the line linear, whereas the default is a smooth like</span></a>
<a class="sourceLine" id="cb74-6" title="6"><span class="st">  </span><span class="kw">theme_dataedu</span>()</a></code></pre></div>
<p><img src="06-wt-multilevel-models-1_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>So, it appeares that the more time students spent on the course, the more points they earned.</p>
</div>
</div>
<div id="linear-model-regression" class="section level2">
<h2><span class="header-section-number">8.9</span> Linear model (regression)</h2>
<p>We can find out exactly what the relationship is using a linear model. We also discuss linear models in walkthrough XXX.</p>
<p>Let’s use this technique to model the relationship between the time spent on the course and the percentage of points earned. Here, we predict <code>percentage_earned</code>, or the percentage of the total points that are possible for a student to earn. Here, percentage earned is the dependent, or <em>y</em>-variable, and so we enter it first, after the <code>lm()</code> command, before the tilde (<code>~</code>) symbol. To the right of the tilde is one independent variable, <code>TimeSpent</code>, or the time that students spent on the course. We also pass the data frame, <code>dat</code>. At this point, we’re ready to run the model. Let’s run this line of code and save the results to an object - we chose <code>m_linear</code>, but any name will work, as well as the <code>summary()</code> function on the output.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb75-1" title="1">m_linear &lt;-</a>
<a class="sourceLine" id="cb75-2" title="2"><span class="st">  </span><span class="kw">lm</span>(percentage_earned <span class="op">~</span><span class="st"> </span>TimeSpent, <span class="dt">data =</span> dat)</a></code></pre></div>
<p>Another way that we can generate table output is with a function from the
<code>sjPlot</code> package, <code>tab_model</code>.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb76-1" title="1">sjPlot<span class="op">::</span><span class="kw">tab_model</span>(m_linear)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
percentage earned
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.62
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.59 – 0.65
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
TimeSpent
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00 – 0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
598
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.191 / 0.189
</td>
</tr>
</table>
<p>This will work well for R Markdown documents (or simply to interpet the model in
R). If you want to save the model for use in a Word document, the
<a href="https://cran.r-project.org/web/packages/apaTables/vignettes/apaTables.html">apaTables</a>
package may be helpful; just pass the name of the regression model, like we did
with <code>sjPlot::tab_model()</code>, as well as a file name that ends in <code>.doc</code> to the
<code>filename</code> argument, i.e.:</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb77-1" title="1">apaTables<span class="op">::</span><span class="kw">apa.reg.table</span>(m_linear)</a></code></pre></div>
<pre><code>## 
## 
## Regression results using percentage_earned as the criterion
##  
## 
##    Predictor      b     b_95%_CI beta  beta_95%_CI sr2 sr2_95%_CI     r
##  (Intercept) 0.62** [0.59, 0.65]                                       
##    TimeSpent 0.00** [0.00, 0.00] 0.44 [0.36, 0.51] .19 [.14, .24] .44**
##                                                                        
##                                                                        
##                                                                        
##              Fit
##                 
##                 
##      R2 = .191**
##  95% CI[.14,.24]
##                 
## 
## Note. A significant b-weight indicates the beta-weight and semi-partial correlation are also significant.
## b represents unstandardized regression weights. beta indicates the standardized regression weights. 
## sr2 represents the semi-partial correlation squared. r represents the zero-order correlation.
## Square brackets are used to enclose the lower and upper limits of a confidence interval.
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
<p>Helpfully, you can save the output to a Word document, by adding a <code>filename</code> argument:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb79-1" title="1">apaTables<span class="op">::</span><span class="kw">apa.reg.table</span>(m_summary, <span class="dt">filename =</span> <span class="st">&quot;regression-table-output.doc&quot;</span>)</a></code></pre></div>
<p>You might be wondering what else the apaTables package does; we encourage you to
read more about the package here:
<a href="https://cran.r-project.org/web/packages/apaTables/index.html" class="uri">https://cran.r-project.org/web/packages/apaTables/index.html</a>. The vignette is
especially helpful. One function that may be useful for writing manuscripts is
the following function for creating correlation tables; the function takes, as
an input, a data frame with the variables for which you wish to calculate
correlations.</p>
<p>Before we proceed to the next code chunk, let’s talk about some functions we’ll be using a lot in this book. <code>filter</code>, <code>group_by</code>, and <code>summarise</code> are functions in the <code>dplyr</code> package that you will see a lot in upcoming chapters.</p>
<ul>
<li><code>filter</code> removes rows from the dataset that don’t match a criteria. Use it for tasks like only keeping records for students in the fifth grade</li>
<li><code>group_by</code> groups records together so you can perform operations on those groups instead of on the entire dataset. Use it for tasks like getting the mean test score of each school instead of a whole school district</li>
<li><code>summarize</code> and <code>summarise</code> reduce your dataset down to a summary statistic. Use it for tasks like turning a datset of student test scores into a datset of grade levels and their mean test score</li>
</ul>
<p>So let’s use these <code>dplyr</code> functions on our survey analysis. We will create the same measures (based on the survey items) that we used earlier to understand how they relate to one another:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb80-1" title="1">survey_responses &lt;-</a>
<a class="sourceLine" id="cb80-2" title="2"><span class="st">  </span>s12_pre_survey <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb80-3" title="3"><span class="st">  </span><span class="co"># Gather questions and responses</span></a>
<a class="sourceLine" id="cb80-4" title="4"><span class="st">  </span><span class="kw">pivot_longer</span>(<span class="dt">cols =</span> q1<span class="op">:</span>q10,</a>
<a class="sourceLine" id="cb80-5" title="5">               <span class="dt">names_to =</span> <span class="st">&quot;question&quot;</span>,</a>
<a class="sourceLine" id="cb80-6" title="6">               <span class="dt">values_to =</span> <span class="st">&quot;response&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb80-7" title="7"><span class="st">  </span><span class="kw">mutate</span>(</a>
<a class="sourceLine" id="cb80-8" title="8">    <span class="co"># Here&#39;s where we make the column of question categories</span></a>
<a class="sourceLine" id="cb80-9" title="9">    <span class="dt">measure =</span> <span class="kw">case_when</span>(</a>
<a class="sourceLine" id="cb80-10" title="10">      question <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;q1&quot;</span>, <span class="st">&quot;q4&quot;</span>, <span class="st">&quot;q5&quot;</span>, <span class="st">&quot;q8&quot;</span>, <span class="st">&quot;q10&quot;</span>) <span class="op">~</span><span class="st"> &quot;int&quot;</span>,</a>
<a class="sourceLine" id="cb80-11" title="11">      question <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;q2&quot;</span>, <span class="st">&quot;q6&quot;</span>, <span class="st">&quot;q9&quot;</span>) <span class="op">~</span><span class="st"> &quot;uv&quot;</span>,</a>
<a class="sourceLine" id="cb80-12" title="12">      question <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;q3&quot;</span>, <span class="st">&quot;q7&quot;</span>) <span class="op">~</span><span class="st"> &quot;pc&quot;</span>,</a>
<a class="sourceLine" id="cb80-13" title="13">      <span class="ot">TRUE</span> <span class="op">~</span><span class="st"> </span><span class="ot">NA_character_</span></a>
<a class="sourceLine" id="cb80-14" title="14">    )</a>
<a class="sourceLine" id="cb80-15" title="15">  ) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb80-16" title="16"><span class="st">  </span><span class="kw">group_by</span>(student_id, measure) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb80-17" title="17"><span class="st">  </span><span class="kw">summarise</span>(<span class="co"># Here&#39;s where we compute the mean of the responses</span></a>
<a class="sourceLine" id="cb80-18" title="18">    <span class="co"># Mean response for each measure</span></a>
<a class="sourceLine" id="cb80-19" title="19">    <span class="dt">mean_response =</span> <span class="kw">mean</span>(response, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb80-20" title="20"><span class="st">  </span><span class="kw">filter</span>(<span class="op">!</span><span class="kw">is.na</span>(mean_response)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb80-21" title="21"><span class="st">  </span><span class="kw">spread</span>(measure, mean_response)</a>
<a class="sourceLine" id="cb80-22" title="22"></a>
<a class="sourceLine" id="cb80-23" title="23">survey_responses</a></code></pre></div>
<pre><code>## # A tibble: 920 x 4
## # Groups:   student_id [920]
##    student_id   int    pc    uv
##         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1     429883   1.8   3    1   
##  2     430158  NA    NA    1   
##  3     430161  NA     1   NA   
##  4     431821   4.4   3.5  4   
##  5     431864   4.4   5    3   
##  6     431889   3.8   3    3.67
##  7     431890   5     4    3.67
##  8     431909   4     3    3   
##  9     431949   3.8   3.5  3.33
## 10     431956   4     4    3.67
## # … with 910 more rows</code></pre>
<p>Now that we’ve prepared the survey responses, we can use the <code>apa.cor.table()</code> function:</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb82-1" title="1">survey_responses <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb82-2" title="2"><span class="st">  </span><span class="kw">apa.cor.table</span>()</a></code></pre></div>
<pre><code>## 
## 
## Means, standard deviations, and correlations with confidence intervals
##  
## 
##   Variable      M         SD       1            2          3         
##   1. student_id 461015.15 29419.03                                   
##                                                                      
##   2. int        4.26      0.63     -.11**                            
##                                    [-.17, -.05]                      
##                                                                      
##   3. pc         3.65      0.72     -.09**       .59**                
##                                    [-.15, -.02] [.55, .63]           
##                                                                      
##   4. uv         3.76      0.81     -.09**       .61**      .52**     
##                                    [-.15, -.02] [.57, .65] [.47, .56]
##                                                                      
## 
## Note. M and SD are used to represent mean and standard deviation, respectively.
## Values in square brackets indicate the 95% confidence interval.
## The confidence interval is a plausible range of population correlations 
## that could have caused the sample correlation (Cumming, 2014).
## * indicates p &lt; .05. ** indicates p &lt; .01.
## </code></pre>
<p>The time spent variable is on a very large scale (minutes); what if we transform
it to represent the number of hours that students spent on the course? Let’s use the <code>mutate()</code> function we used earlier. We’ll end the variable
name in <code>_hours</code>, to represent what this variable means.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb84-1" title="1"><span class="co"># creating a new variable for the amount of time spent in hours</span></a>
<a class="sourceLine" id="cb84-2" title="2">dat &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb84-3" title="3"><span class="st">  </span>dat <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb84-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TimeSpent_hours =</span> TimeSpent <span class="op">/</span><span class="st"> </span><span class="dv">60</span>)</a>
<a class="sourceLine" id="cb84-5" title="5"></a>
<a class="sourceLine" id="cb84-6" title="6"><span class="co"># the same linear model as above, but with the TimeSpent variable in hours</span></a>
<a class="sourceLine" id="cb84-7" title="7">m_linear_<span class="dv">1</span> &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb84-8" title="8"><span class="st">  </span><span class="kw">lm</span>(percentage_earned <span class="op">~</span><span class="st"> </span>TimeSpent_hours, <span class="dt">data =</span> dat)</a>
<a class="sourceLine" id="cb84-9" title="9"></a>
<a class="sourceLine" id="cb84-10" title="10"><span class="co"># viewing the output of the linear model</span></a>
<a class="sourceLine" id="cb84-11" title="11">sjPlot<span class="op">::</span><span class="kw">tab_model</span>(m_linear_<span class="dv">1</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
percentage earned
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.62
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.59 – 0.65
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
TimeSpent_hours
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00 – 0.01
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
598
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.191 / 0.189
</td>
</tr>
</table>
<p>The scale still does not seem quite right. What if we standardized the variable
to have a mean of zero and a standard deviation of one?</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb85-1" title="1"><span class="co"># this is to standardize the TimeSpent variable to have a mean of zero and a standard deviation of 1</span></a>
<a class="sourceLine" id="cb85-2" title="2">dat &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb85-3" title="3"><span class="st">  </span>dat <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb85-4" title="4"><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">TimeSpent_std =</span> <span class="kw">scale</span>(TimeSpent))</a>
<a class="sourceLine" id="cb85-5" title="5"><span class="co"># the same linear model as above, but with the TimeSpent variable standardized</span></a>
<a class="sourceLine" id="cb85-6" title="6">m_linear_<span class="dv">2</span> &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb85-7" title="7"><span class="st">  </span><span class="kw">lm</span>(percentage_earned <span class="op">~</span><span class="st"> </span>TimeSpent_std, <span class="dt">data =</span> dat) </a>
<a class="sourceLine" id="cb85-8" title="8"><span class="co"># viewing the output of the linear model</span></a>
<a class="sourceLine" id="cb85-9" title="9">sjPlot<span class="op">::</span><span class="kw">tab_model</span>(m_linear_<span class="dv">2</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
percentage earned
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.76
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.74 – 0.78
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
TimeSpent_std
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.11
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.09 – 0.13
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
598
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.191 / 0.189
</td>
</tr>
</table>
<p>That seems to make more sense. However, there is a different interpretation
now for the time spent variable: for every one standard deviation increase in
the amount of time spent on the course, the percentage of points a student earns
increases by .11, or 11 percentage points.</p>
<p>Let’s extend our regression model: what other variables may matter? Perhaps
there are differences based on the subject of the course. We can add subject as
a variable easily:it l</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb86-1" title="1"><span class="co"># a linear model with the subject added </span></a>
<a class="sourceLine" id="cb86-2" title="2"><span class="co"># independent variables, such as TimeSpent_std and subject, can simply be separated with a plus symbol:</span></a>
<a class="sourceLine" id="cb86-3" title="3">m_linear_<span class="dv">3</span> &lt;-<span class="st"> </span></a>
<a class="sourceLine" id="cb86-4" title="4"><span class="st">  </span><span class="kw">lm</span>(percentage_earned <span class="op">~</span><span class="st"> </span>TimeSpent_std <span class="op">+</span><span class="st"> </span>subject, <span class="dt">data =</span> dat)</a></code></pre></div>
<p>We can use <code>sjPlot::tab_model()</code> once again to view the results:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb87-1" title="1">sjPlot<span class="op">::</span><span class="kw">tab_model</span>(m_linear_<span class="dv">3</span>)</a></code></pre></div>
<table style="border-collapse:collapse; border:none;">
<tr>
<th style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm;  text-align:left; ">
 
</th>
<th colspan="3" style="border-top: double; text-align:center; font-style:normal; font-weight:bold; padding:0.2cm; ">
percentage earned
</th>
</tr>
<tr>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  text-align:left; ">
Predictors
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
Estimates
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
CI
</td>
<td style=" text-align:center; border-bottom:1px solid; font-style:italic; font-weight:normal;  ">
p
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
(Intercept)
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.70
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.66 – 0.73
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
TimeSpent_std
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.12
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.10 – 0.14
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
subject [BioA]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.08 – 0.07
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.940
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
subject [FrScA]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.11
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.07 – 0.16
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
subject [OcnA]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.00
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
-0.05 – 0.05
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.963
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; ">
subject [PhysA]
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.18
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
0.12 – 0.25
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:center;  ">
<strong>&lt;0.001
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm; border-top:1px solid;">
Observations
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left; border-top:1px solid;" colspan="3">
598
</td>
</tr>
<tr>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; text-align:left; padding-top:0.1cm; padding-bottom:0.1cm;">
R<sup>2</sup> / R<sup>2</sup> adjusted
</td>
<td style=" padding:0.2cm; text-align:left; vertical-align:top; padding-top:0.1cm; padding-bottom:0.1cm; text-align:left;" colspan="3">
0.260 / 0.254
</td>
</tr>
</table>
<p>It looks like subject <code>FrSc</code> - forensic science - and subject <code>Ocn</code> -
oceanography - are associated with a higher percentage of points earned,
overall. This indicates that students in those two classes earned higher grades than students in other science classes in this dataset.</p>
</div>
<div id="what-is-next" class="section level2">
<h2><span class="header-section-number">8.10</span> What is next?</h2>
<p>In the follow-up to this walkthrough (see Chapter XXX), we will focus on
visualizing and then modeling the data using an advanced methodological
technique, multi-level models. Before we go, let’s save the data we processed.</p>
<!-- Not sure how to deal with these paths in the book?!? also the name of the file -->
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb88-1" title="1"><span class="kw">write_csv</span>(dat, <span class="st">&quot;data/online-science-motivation/processed/dat.csv&quot;</span>)</a></code></pre></div>

</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-siemens2012">
<p>Siemens, George, and Ryan SJ d Baker. 2012. “Learning Analytics and Educational Data Mining: Towards Communication and Collaboration.” In <em>Proceedings of the 2nd International Conference on Learning Analytics and Knowledge</em>, 252–54. ACM.</p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="include-at-end-of-chapter.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="walkthrough-1b.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
