<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>25 How Have Child Counts Changed Over Time? | Data Science in Education Using R</title>
  <meta name="description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="generator" content="bookdown 0.14 and GitBook 2.6.7" />

  <meta property="og:title" content="25 How Have Child Counts Changed Over Time? | Data Science in Education Using R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  <meta name="github-repo" content="ivelasq/data-science-in-education" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="25 How Have Child Counts Changed Over Time? | Data Science in Education Using R" />
  
  <meta name="twitter:description" content="Bookdown for ‘Data Science in Education Using R’ by Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez to be published by Routledge in 2020" />
  

<meta name="author" content="Emily A. Bovee, Ryan A. Estrellado, Jesse Mostipak, Joshua M. Rosenberg, and Isabella C. Velásquez" />


<meta name="date" content="2019-12-01" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="cleaning-the-dataset.html"/>
<link rel="next" href="aggregate-data-as-context-for-student-data.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="learning-data-science-in-education.html"><a href="learning-data-science-in-education.html"><i class="fa fa-check"></i><b>2</b> Learning Data Science in Education</a><ul>
<li class="chapter" data-level="2.1" data-path="learning-data-science-in-education.html"><a href="learning-data-science-in-education.html#making-the-path-a-little-clearer"><i class="fa fa-check"></i><b>2.1</b> Making the path a little clearer</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html"><i class="fa fa-check"></i><b>3</b> How to Use this Book</a><ul>
<li class="chapter" data-level="3.1" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#getting-started"><i class="fa fa-check"></i><b>3.1</b> Getting Started</a><ul>
<li class="chapter" data-level="3.1.1" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#read-the-book-cover-to-cover-and-try-all-the-walkthroughs"><i class="fa fa-check"></i><b>3.1.1</b> Read the Book Cover to Cover and Try All the Walkthroughs</a></li>
<li class="chapter" data-level="3.1.2" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#pick-a-chapter-that-is-useful-for-your-level-of-experience-and-start-there"><i class="fa fa-check"></i><b>3.1.2</b> Pick a Chapter That is Useful for Your Level of Experience and Start There</a></li>
<li class="chapter" data-level="3.1.3" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#read-through-the-walkthroughs-and-run-the-code"><i class="fa fa-check"></i><b>3.1.3</b> Read Through the Walkthroughs and Run the Code</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#a-note-on-statistics"><i class="fa fa-check"></i><b>3.2</b> A Note on Statistics</a></li>
<li class="chapter" data-level="3.3" data-path="how-to-use-this-book.html"><a href="how-to-use-this-book.html#contributing-to-the-book"><i class="fa fa-check"></i><b>3.3</b> Contributing to the Book</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="what-is-a-data-scientist-in-education.html"><a href="what-is-a-data-scientist-in-education.html"><i class="fa fa-check"></i><b>4</b> What is a Data Scientist in Education?</a></li>
<li class="chapter" data-level="5" data-path="unique-challenges.html"><a href="unique-challenges.html"><i class="fa fa-check"></i><b>5</b> Unique Challenges</a></li>
<li class="chapter" data-level="6" data-path="challenges-common-to-doing-data-science-in-any-domain.html"><a href="challenges-common-to-doing-data-science-in-any-domain.html"><i class="fa fa-check"></i><b>6</b> Challenges Common to Doing Data Science in any Domain</a><ul>
<li class="chapter" data-level="6.1" data-path="challenges-common-to-doing-data-science-in-any-domain.html"><a href="challenges-common-to-doing-data-science-in-any-domain.html#a-new-field"><i class="fa fa-check"></i><b>6.1</b> A New Field</a></li>
<li class="chapter" data-level="6.2" data-path="challenges-common-to-doing-data-science-in-any-domain.html"><a href="challenges-common-to-doing-data-science-in-any-domain.html#addressing-ambiguity-a-reproducible-approach"><i class="fa fa-check"></i><b>6.2</b> Addressing Ambiguity: A Reproducible Approach</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="challenges-common-to-doing-data-science-in-education.html"><a href="challenges-common-to-doing-data-science-in-education.html"><i class="fa fa-check"></i><b>7</b> Challenges Common to Doing Data Science in Education</a><ul>
<li class="chapter" data-level="7.1" data-path="challenges-common-to-doing-data-science-in-education.html"><a href="challenges-common-to-doing-data-science-in-education.html#addressing-organizational-resistance-a-self-driven-analytic-approach"><i class="fa fa-check"></i><b>7.1</b> Addressing organizational resistance: A self-driven analytic approach</a></li>
<li class="chapter" data-level="7.2" data-path="challenges-common-to-doing-data-science-in-education.html"><a href="challenges-common-to-doing-data-science-in-education.html#lack-of-processes-and-guidelines"><i class="fa fa-check"></i><b>7.2</b> Lack of Processes and Guidelines</a></li>
<li class="chapter" data-level="7.3" data-path="challenges-common-to-doing-data-science-in-education.html"><a href="challenges-common-to-doing-data-science-in-education.html#limited-training-and-educational-opportunities"><i class="fa fa-check"></i><b>7.3</b> Limited Training and Educational Opportunities</a></li>
<li class="chapter" data-level="7.4" data-path="challenges-common-to-doing-data-science-in-education.html"><a href="challenges-common-to-doing-data-science-in-education.html#the-complex-and-messy-nature-of-education-data"><i class="fa fa-check"></i><b>7.4</b> The Complex and Messy Nature of Education Data</a></li>
<li class="chapter" data-level="7.5" data-path="challenges-common-to-doing-data-science-in-education.html"><a href="challenges-common-to-doing-data-science-in-education.html#ethical-and-legal-concerns"><i class="fa fa-check"></i><b>7.5</b> Ethical and Legal Concerns</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="analytic-challenges.html"><a href="analytic-challenges.html"><i class="fa fa-check"></i><b>8</b> Analytic Challenges</a></li>
<li class="chapter" data-level="9" data-path="not-just-challenges.html"><a href="not-just-challenges.html"><i class="fa fa-check"></i><b>9</b> Not Just Challenges</a></li>
<li class="chapter" data-level="10" data-path="foundational-skills.html"><a href="foundational-skills.html"><i class="fa fa-check"></i><b>10</b> Foundational Skills</a><ul>
<li class="chapter" data-level="10.1" data-path="foundational-skills.html"><a href="foundational-skills.html#track-one-getting-started"><i class="fa fa-check"></i><b>10.1</b> Track One: Getting Started</a></li>
<li class="chapter" data-level="10.2" data-path="foundational-skills.html"><a href="foundational-skills.html#downloading-r-and-r-studio"><i class="fa fa-check"></i><b>10.2</b> Downloading R and R Studio</a><ul>
<li class="chapter" data-level="10.2.1" data-path="foundational-skills.html"><a href="foundational-skills.html#to-download-r"><i class="fa fa-check"></i><b>10.2.1</b> To download R:</a></li>
<li class="chapter" data-level="10.2.2" data-path="foundational-skills.html"><a href="foundational-skills.html#to-download-r-studio"><i class="fa fa-check"></i><b>10.2.2</b> To download R Studio:</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="foundational-skills.html"><a href="foundational-skills.html#check-that-it-worked"><i class="fa fa-check"></i><b>10.3</b> Check that it worked</a></li>
<li class="chapter" data-level="10.4" data-path="foundational-skills.html"><a href="foundational-skills.html#help-im-completely-new-to-using-r-r-studio"><i class="fa fa-check"></i><b>10.4</b> Help, I’m completely new to using R / R Studio!</a></li>
<li class="chapter" data-level="10.5" data-path="foundational-skills.html"><a href="foundational-skills.html#creating-projects"><i class="fa fa-check"></i><b>10.5</b> Creating Projects</a></li>
<li class="chapter" data-level="10.6" data-path="foundational-skills.html"><a href="foundational-skills.html#packages"><i class="fa fa-check"></i><b>10.6</b> Packages</a><ul>
<li class="chapter" data-level="10.6.1" data-path="foundational-skills.html"><a href="foundational-skills.html#installing-and-loading-packages"><i class="fa fa-check"></i><b>10.6.1</b> Installing and Loading Packages</a></li>
<li class="chapter" data-level="10.6.2" data-path="foundational-skills.html"><a href="foundational-skills.html#running-functions-from-packages"><i class="fa fa-check"></i><b>10.6.2</b> Running Functions from Packages</a></li>
<li class="chapter" data-level="10.6.3" data-path="foundational-skills.html"><a href="foundational-skills.html#track-two-welcome-to-the-tidyverse"><i class="fa fa-check"></i><b>10.6.3</b> Track Two: Welcome to the Tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="10.7" data-path="foundational-skills.html"><a href="foundational-skills.html#loading-data-from-various-sources"><i class="fa fa-check"></i><b>10.7</b> Loading Data from Various Sources</a><ul>
<li class="chapter" data-level="10.7.1" data-path="foundational-skills.html"><a href="foundational-skills.html#saving-a-file-from-the-web"><i class="fa fa-check"></i><b>10.7.1</b> Saving a File from the Web</a></li>
<li class="chapter" data-level="10.7.2" data-path="foundational-skills.html"><a href="foundational-skills.html#loading-a-csv-file"><i class="fa fa-check"></i><b>10.7.2</b> Loading a CSV File</a></li>
<li class="chapter" data-level="10.7.3" data-path="foundational-skills.html"><a href="foundational-skills.html#loading-excel-files"><i class="fa fa-check"></i><b>10.7.3</b> Loading Excel Files</a></li>
<li class="chapter" data-level="10.7.4" data-path="foundational-skills.html"><a href="foundational-skills.html#loading-sav-files"><i class="fa fa-check"></i><b>10.7.4</b> Loading SAV Files</a></li>
<li class="chapter" data-level="10.7.5" data-path="foundational-skills.html"><a href="foundational-skills.html#google-sheets"><i class="fa fa-check"></i><b>10.7.5</b> Google Sheets</a></li>
<li class="chapter" data-level="10.7.6" data-path="foundational-skills.html"><a href="foundational-skills.html#saving-files"><i class="fa fa-check"></i><b>10.7.6</b> Saving Files</a></li>
<li class="chapter" data-level="10.7.7" data-path="foundational-skills.html"><a href="foundational-skills.html#conclusion"><i class="fa fa-check"></i><b>10.7.7</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10.8" data-path="foundational-skills.html"><a href="foundational-skills.html#processing-data"><i class="fa fa-check"></i><b>10.8</b> Processing Data</a></li>
<li class="chapter" data-level="10.9" data-path="foundational-skills.html"><a href="foundational-skills.html#communicating-sharing-results"><i class="fa fa-check"></i><b>10.9</b> Communicating / Sharing Results</a></li>
<li class="chapter" data-level="10.10" data-path="foundational-skills.html"><a href="foundational-skills.html#other-foundational-notes"><i class="fa fa-check"></i><b>10.10</b> Other Foundational Notes</a><ul>
<li class="chapter" data-level="10.10.1" data-path="foundational-skills.html"><a href="foundational-skills.html#configuring-r-studio"><i class="fa fa-check"></i><b>10.10.1</b> Configuring R Studio</a></li>
<li class="chapter" data-level="10.10.2" data-path="foundational-skills.html"><a href="foundational-skills.html#getting-data-in-and-out"><i class="fa fa-check"></i><b>10.10.2</b> Getting Data In and Out</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html"><i class="fa fa-check"></i><b>11</b> Walkthrough 01: Title Here</a><ul>
<li class="chapter" data-level="11.1" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#introduction-1"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#data-sources"><i class="fa fa-check"></i><b>11.2</b> Data Sources</a><ul>
<li class="chapter" data-level="11.2.1" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#self-report-survey"><i class="fa fa-check"></i><b>11.2.1</b> 1. Self-Report Survey</a></li>
<li class="chapter" data-level="11.2.2" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#log-trace-data"><i class="fa fa-check"></i><b>11.2.2</b> 2. Log-Trace Data</a></li>
<li class="chapter" data-level="11.2.3" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#achievement-related-and-gradebook-data"><i class="fa fa-check"></i><b>11.2.3</b> 3. Achievement-related and gradebook data</a></li>
<li class="chapter" data-level="11.2.4" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#discussion-board-data"><i class="fa fa-check"></i><b>11.2.4</b> 4. Discussion board data</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#load-packages"><i class="fa fa-check"></i><b>11.3</b> Load Packages</a></li>
<li class="chapter" data-level="11.4" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#import-data"><i class="fa fa-check"></i><b>11.4</b> Import Data</a></li>
<li class="chapter" data-level="11.5" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#viewing-the-data"><i class="fa fa-check"></i><b>11.5</b> Viewing the Data</a></li>
<li class="chapter" data-level="11.6" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#process-data"><i class="fa fa-check"></i><b>11.6</b> Process Data</a><ul>
<li class="chapter" data-level="11.6.1" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#self-report-survey-1"><i class="fa fa-check"></i><b>11.6.1</b> 1. Self-Report Survey</a></li>
<li class="chapter" data-level="11.6.2" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#course-data"><i class="fa fa-check"></i><b>11.6.2</b> 2. Course Data</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#joining-the-data"><i class="fa fa-check"></i><b>11.7</b> Joining the Data</a></li>
<li class="chapter" data-level="11.8" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#visualizing-the-data"><i class="fa fa-check"></i><b>11.8</b> Visualizing the Data</a><ul>
<li class="chapter" data-level="11.8.1" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#visualization-of-the-relationship-between-time-spent-on-course-and-percentage-of-points-earned"><i class="fa fa-check"></i><b>11.8.1</b> Visualization of the relationship between time spent on course and percentage of points earned</a></li>
</ul></li>
<li class="chapter" data-level="11.9" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#modeling-the-data"><i class="fa fa-check"></i><b>11.9</b> Modeling the Data</a></li>
<li class="chapter" data-level="11.10" data-path="walkthrough-01-title-here.html"><a href="walkthrough-01-title-here.html#but-what-about-different-courses"><i class="fa fa-check"></i><b>11.10</b> But what about different courses?</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html"><i class="fa fa-check"></i><b>12</b> Walkthrough 02: Title Here</a><ul>
<li class="chapter" data-level="12.1" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#introduction-2"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#data-sources-1"><i class="fa fa-check"></i><b>12.2</b> Data Sources</a></li>
<li class="chapter" data-level="12.3" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#load-packages-1"><i class="fa fa-check"></i><b>12.3</b> Load Packages</a></li>
<li class="chapter" data-level="12.4" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#import-data-1"><i class="fa fa-check"></i><b>12.4</b> Import Data</a></li>
<li class="chapter" data-level="12.5" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#tidy-data"><i class="fa fa-check"></i><b>12.5</b> Tidy Data</a></li>
<li class="chapter" data-level="12.6" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#process-data-1"><i class="fa fa-check"></i><b>12.6</b> Process Data</a></li>
<li class="chapter" data-level="12.7" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#visualize-data"><i class="fa fa-check"></i><b>12.7</b> Visualize Data</a></li>
<li class="chapter" data-level="12.8" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#model-data"><i class="fa fa-check"></i><b>12.8</b> Model Data</a><ul>
<li class="chapter" data-level="12.8.1" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#deciding-an-analysis"><i class="fa fa-check"></i><b>12.8.1</b> Deciding an Analysis</a></li>
<li class="chapter" data-level="12.8.2" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#visualize-data-to-check-assumptions"><i class="fa fa-check"></i><b>12.8.2</b> Visualize Data to Check Assumptions</a></li>
<li class="chapter" data-level="12.8.3" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#correlation-analysis"><i class="fa fa-check"></i><b>12.8.3</b> Correlation Analysis</a></li>
<li class="chapter" data-level="12.8.4" data-path="walkthrough-02-title-here.html"><a href="walkthrough-02-title-here.html#build-linear-model"><i class="fa fa-check"></i><b>12.8.4</b> Build Linear Model</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="walkthrough-03-title-here.html"><a href="walkthrough-03-title-here.html"><i class="fa fa-check"></i><b>13</b> Walkthrough 03: Title Here</a><ul>
<li class="chapter" data-level="13.1" data-path="walkthrough-03-title-here.html"><a href="walkthrough-03-title-here.html#introduction-3"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="data-sources-2.html"><a href="data-sources-2.html"><i class="fa fa-check"></i><b>14</b> Data Sources</a><ul>
<li class="chapter" data-level="14.1" data-path="data-sources-2.html"><a href="data-sources-2.html#information-on-random-forests"><i class="fa fa-check"></i><b>14.1</b> Information on random forests</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="analysis.html"><a href="analysis.html"><i class="fa fa-check"></i><b>15</b> Analysis</a><ul>
<li class="chapter" data-level="15.1" data-path="analysis.html"><a href="analysis.html#use-of-caret"><i class="fa fa-check"></i><b>15.1</b> Use of caret</a></li>
<li class="chapter" data-level="15.2" data-path="analysis.html"><a href="analysis.html#predicted-values"><i class="fa fa-check"></i><b>15.2</b> Predicted values</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="examining-predictive-accuracy-on-the-test-data-set.html"><a href="examining-predictive-accuracy-on-the-test-data-set.html"><i class="fa fa-check"></i><b>16</b> Examining predictive accuracy on the test data set</a><ul>
<li class="chapter" data-level="16.1" data-path="examining-predictive-accuracy-on-the-test-data-set.html"><a href="examining-predictive-accuracy-on-the-test-data-set.html#variable-importance-measures"><i class="fa fa-check"></i><b>16.1</b> Variable importance measures</a></li>
<li class="chapter" data-level="16.2" data-path="examining-predictive-accuracy-on-the-test-data-set.html"><a href="examining-predictive-accuracy-on-the-test-data-set.html#comparing-a-random-forest-to-a-regression"><i class="fa fa-check"></i><b>16.2</b> Comparing a random forest to a regression</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html"><i class="fa fa-check"></i><b>17</b> Walkthrough 5: Title Here</a><ul>
<li class="chapter" data-level="17.1" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#introduction-to-aggregate-data"><i class="fa fa-check"></i><b>17.1</b> Introduction to Aggregate Data</a><ul>
<li class="chapter" data-level="17.1.1" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#disaggregating-aggregated-data"><i class="fa fa-check"></i><b>17.1.1</b> Disaggregating Aggregated Data</a></li>
<li class="chapter" data-level="17.1.2" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#disaggregating-data-and-equity"><i class="fa fa-check"></i><b>17.1.2</b> Disaggregating Data and Equity</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#data"><i class="fa fa-check"></i><b>17.2</b> Data</a></li>
<li class="chapter" data-level="17.3" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#data-selection-and-research-questions"><i class="fa fa-check"></i><b>17.3</b> Data Selection and Research Questions</a><ul>
<li class="chapter" data-level="17.3.1" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#import"><i class="fa fa-check"></i><b>17.3.1</b> Import</a></li>
<li class="chapter" data-level="17.3.2" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#cleaning"><i class="fa fa-check"></i><b>17.3.2</b> Cleaning</a></li>
<li class="chapter" data-level="17.3.3" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#looking-at-missing-data"><i class="fa fa-check"></i><b>17.3.3</b> Looking at missing data</a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#analysis-1"><i class="fa fa-check"></i><b>17.4</b> Analysis</a><ul>
<li class="chapter" data-level="17.4.1" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#discovering-distributions"><i class="fa fa-check"></i><b>17.4.1</b> Discovering Distributions</a></li>
<li class="chapter" data-level="17.4.2" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#making-comparisons"><i class="fa fa-check"></i><b>17.4.2</b> Making Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#ranking"><i class="fa fa-check"></i><b>17.5</b> Ranking</a></li>
<li class="chapter" data-level="17.6" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#results"><i class="fa fa-check"></i><b>17.6</b> Results</a></li>
<li class="chapter" data-level="17.7" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#conclusion-1"><i class="fa fa-check"></i><b>17.7</b> Conclusion</a></li>
<li class="chapter" data-level="17.8" data-path="walkthrough-5-title-here.html"><a href="walkthrough-5-title-here.html#appendix"><i class="fa fa-check"></i><b>17.8</b> Appendix</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="walkthrough-6-title-here.html"><a href="walkthrough-6-title-here.html"><i class="fa fa-check"></i><b>18</b> Walkthrough 6: Title Here</a></li>
<li class="chapter" data-level="19" data-path="vocabulary.html"><a href="vocabulary.html"><i class="fa fa-check"></i><b>19</b> Vocabulary</a></li>
<li class="chapter" data-level="20" data-path="introduction-4.html"><a href="introduction-4.html"><i class="fa fa-check"></i><b>20</b> Introduction</a></li>
<li class="chapter" data-level="21" data-path="special-education-child-count-and-environment-data.html"><a href="special-education-child-count-and-environment-data.html"><i class="fa fa-check"></i><b>21</b> Special Education Child Count and Environment Data</a></li>
<li class="chapter" data-level="22" data-path="reading-in-one-dataset.html"><a href="reading-in-one-dataset.html"><i class="fa fa-check"></i><b>22</b> Reading In One Dataset</a></li>
<li class="chapter" data-level="23" data-path="reading-in-many-datasets.html"><a href="reading-in-many-datasets.html"><i class="fa fa-check"></i><b>23</b> Reading In Many Datasets</a></li>
<li class="chapter" data-level="24" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html"><i class="fa fa-check"></i><b>24</b> Cleaning the Dataset</a><ul>
<li class="chapter" data-level="24.1" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#fix-the-variable-names-in-the-2016-data"><i class="fa fa-check"></i><b>24.1</b> Fix the variable names in the 2016 data</a></li>
<li class="chapter" data-level="24.2" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#pick-variables"><i class="fa fa-check"></i><b>24.2</b> Pick variables</a></li>
<li class="chapter" data-level="24.3" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#combine-six-datasets-into-one"><i class="fa fa-check"></i><b>24.3</b> Combine six datasets into one</a></li>
<li class="chapter" data-level="24.4" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#filter-for-the-desired-disabilities-and-age-groups"><i class="fa fa-check"></i><b>24.4</b> Filter for the desired disabilities and age groups</a></li>
<li class="chapter" data-level="24.5" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#rename-the-variables"><i class="fa fa-check"></i><b>24.5</b> Rename the variables</a></li>
<li class="chapter" data-level="24.6" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#clean-state-names"><i class="fa fa-check"></i><b>24.6</b> Clean state names</a></li>
<li class="chapter" data-level="24.7" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#tidy-the-dataset"><i class="fa fa-check"></i><b>24.7</b> Tidy the dataset</a></li>
<li class="chapter" data-level="24.8" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#convert-data-types"><i class="fa fa-check"></i><b>24.8</b> Convert data types</a></li>
<li class="chapter" data-level="24.9" data-path="cleaning-the-dataset.html"><a href="cleaning-the-dataset.html#explore-and-address-nas"><i class="fa fa-check"></i><b>24.9</b> Explore and address NAs</a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="how-have-child-counts-changed-over-time.html"><a href="how-have-child-counts-changed-over-time.html"><i class="fa fa-check"></i><b>25</b> How Have Child Counts Changed Over Time?</a><ul>
<li class="chapter" data-level="25.1" data-path="how-have-child-counts-changed-over-time.html"><a href="how-have-child-counts-changed-over-time.html#visualize-the-dataset"><i class="fa fa-check"></i><b>25.1</b> Visualize the Dataset</a></li>
<li class="chapter" data-level="25.2" data-path="how-have-child-counts-changed-over-time.html"><a href="how-have-child-counts-changed-over-time.html#model-the-dataset"><i class="fa fa-check"></i><b>25.2</b> Model the Dataset</a><ul>
<li class="chapter" data-level="25.2.1" data-path="how-have-child-counts-changed-over-time.html"><a href="how-have-child-counts-changed-over-time.html#do-we-have-enough-information-for-our-model"><i class="fa fa-check"></i><b>25.2.1</b> Do we have enough information for our model?</a></li>
<li class="chapter" data-level="25.2.2" data-path="how-have-child-counts-changed-over-time.html"><a href="how-have-child-counts-changed-over-time.html#male-to-female-ratio-over-time"><i class="fa fa-check"></i><b>25.2.2</b> Male to Female Ratio Over Time</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="aggregate-data-as-context-for-student-data.html"><a href="aggregate-data-as-context-for-student-data.html"><i class="fa fa-check"></i><b>26</b> Aggregate Data as Context for Student Data</a></li>
<li class="chapter" data-level="27" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>27</b> References</a></li>
<li class="chapter" data-level="28" data-path="walkthrough-7-title-here.html"><a href="walkthrough-7-title-here.html"><i class="fa fa-check"></i><b>28</b> Walkthrough 7: Title Here</a></li>
<li class="chapter" data-level="29" data-path="introduction-5.html"><a href="introduction-5.html"><i class="fa fa-check"></i><b>29</b> Introduction</a></li>
<li class="chapter" data-level="30" data-path="about-our-text-dataset.html"><a href="about-our-text-dataset.html"><i class="fa fa-check"></i><b>30</b> About Our Text Dataset</a></li>
<li class="chapter" data-level="31" data-path="reading-in-the-data.html"><a href="reading-in-the-data.html"><i class="fa fa-check"></i><b>31</b> Reading In the Data</a></li>
<li class="chapter" data-level="32" data-path="reading-the-data.html"><a href="reading-the-data.html"><i class="fa fa-check"></i><b>32</b> Reading the data</a></li>
<li class="chapter" data-level="33" data-path="preparing-the-data-for-the-analysis.html"><a href="preparing-the-data-for-the-analysis.html"><i class="fa fa-check"></i><b>33</b> Preparing the data for the analysis</a></li>
<li class="chapter" data-level="34" data-path="counting-words.html"><a href="counting-words.html"><i class="fa fa-check"></i><b>34</b> Counting words</a></li>
<li class="chapter" data-level="35" data-path="sentiment-analysis.html"><a href="sentiment-analysis.html"><i class="fa fa-check"></i><b>35</b> Sentiment analysis</a><ul>
<li class="chapter" data-level="35.1" data-path="sentiment-analysis.html"><a href="sentiment-analysis.html#tweets-associated-with-positive"><i class="fa fa-check"></i><b>35.1</b> Tweets associated with positive</a></li>
<li class="chapter" data-level="35.2" data-path="sentiment-analysis.html"><a href="sentiment-analysis.html#tweets-associated-with-negative"><i class="fa fa-check"></i><b>35.2</b> Tweets associated with negative</a></li>
<li class="chapter" data-level="35.3" data-path="sentiment-analysis.html"><a href="sentiment-analysis.html#random-review-of-tweets"><i class="fa fa-check"></i><b>35.3</b> Random review of tweets</a></li>
</ul></li>
<li class="chapter" data-level="36" data-path="next-steps.html"><a href="next-steps.html"><i class="fa fa-check"></i><b>36</b> Next steps</a></li>
<li class="chapter" data-level="37" data-path="references-1.html"><a href="references-1.html"><i class="fa fa-check"></i><b>37</b> References</a></li>
<li class="chapter" data-level="38" data-path="solutions.html"><a href="solutions.html"><i class="fa fa-check"></i><b>38</b> Solutions</a><ul>
<li class="chapter" data-level="38.1" data-path="solutions.html"><a href="solutions.html#introduction-6"><i class="fa fa-check"></i><b>38.1</b> Introduction</a></li>
<li class="chapter" data-level="38.2" data-path="solutions.html"><a href="solutions.html#the-gift-of-speed-and-scale"><i class="fa fa-check"></i><b>38.2</b> The Gift of Speed and Scale</a><ul>
<li class="chapter" data-level="38.2.1" data-path="solutions.html"><a href="solutions.html#working-with-data-faster"><i class="fa fa-check"></i><b>38.2.1</b> Working With Data Faster</a></li>
</ul></li>
<li class="chapter" data-level="38.3" data-path="solutions.html"><a href="solutions.html#working-with-more-data"><i class="fa fa-check"></i><b>38.3</b> Working With More Data</a></li>
<li class="chapter" data-level="38.4" data-path="solutions.html"><a href="solutions.html#solving-problems-together"><i class="fa fa-check"></i><b>38.4</b> Solving Problems Together</a></li>
<li class="chapter" data-level="38.5" data-path="solutions.html"><a href="solutions.html#data-science-in-education-and-empathy"><i class="fa fa-check"></i><b>38.5</b> Data Science in Education and Empathy</a></li>
<li class="chapter" data-level="38.6" data-path="solutions.html"><a href="solutions.html#build-your-network"><i class="fa fa-check"></i><b>38.6</b> Build Your Network</a></li>
<li class="chapter" data-level="38.7" data-path="solutions.html"><a href="solutions.html#for-k-12-teachers"><i class="fa fa-check"></i><b>38.7</b> For K-12 Teachers</a></li>
</ul></li>
<li class="chapter" data-level="39" data-path="teaching-data-science.html"><a href="teaching-data-science.html"><i class="fa fa-check"></i><b>39</b> Teaching Data Science</a><ul>
<li class="chapter" data-level="39.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#the-pedagogical-principles-this-book-is-based-upon"><i class="fa fa-check"></i><b>39.1</b> The pedagogical principles this book is based upon</a><ul>
<li class="chapter" data-level="39.1.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#problem-based-learning"><i class="fa fa-check"></i><b>39.1.1</b> Problem-based learning</a></li>
<li class="chapter" data-level="39.1.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#differentiation"><i class="fa fa-check"></i><b>39.1.2</b> Differentiation</a></li>
<li class="chapter" data-level="39.1.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#universal-design"><i class="fa fa-check"></i><b>39.1.3</b> Universal Design</a></li>
<li class="chapter" data-level="39.1.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#working-in-the-open"><i class="fa fa-check"></i><b>39.1.4</b> Working in the Open</a></li>
</ul></li>
<li class="chapter" data-level="39.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#strategies-for-teaching-data-science"><i class="fa fa-check"></i><b>39.2</b> Strategies for teaching data science</a><ul>
<li class="chapter" data-level="39.2.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#provide-a-home-base-for-learners-to-access-resources-and-to-learn-more"><i class="fa fa-check"></i><b>39.2.1</b> Provide a home base for learners to access resources (and to learn more)</a></li>
<li class="chapter" data-level="39.2.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#when-it-comes-to-writing-code-think-early-and-often"><i class="fa fa-check"></i><b>39.2.2</b> When it comes to writing code, think early and often</a></li>
<li class="chapter" data-level="39.2.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#dont-touch-that-keyboard"><i class="fa fa-check"></i><b>39.2.3</b> Don’t touch that keyboard!</a></li>
<li class="chapter" data-level="39.2.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#anticipate-issues-and-sacrifice-accuracy-for-clarity"><i class="fa fa-check"></i><b>39.2.4</b> Anticipate issues (and sacrifice accuracy for clarity)</a></li>
<li class="chapter" data-level="39.2.5" data-path="teaching-data-science.html"><a href="teaching-data-science.html#start-lessons-or-activities-with-visualizing-data"><i class="fa fa-check"></i><b>39.2.5</b> Start lessons or activities with visualizing data</a></li>
<li class="chapter" data-level="39.2.6" data-path="teaching-data-science.html"><a href="teaching-data-science.html#consider-representation-in-the-data-and-examples-you-use"><i class="fa fa-check"></i><b>39.2.6</b> Consider representation in the data and examples you use</a></li>
<li class="chapter" data-level="39.2.7" data-path="teaching-data-science.html"><a href="teaching-data-science.html#draw-on-other-resources"><i class="fa fa-check"></i><b>39.2.7</b> Draw on other resources</a></li>
</ul></li>
<li class="chapter" data-level="39.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#general-strategies-related-to-teaching-and-learning"><i class="fa fa-check"></i><b>39.3</b> General strategies related to teaching and learning</a><ul>
<li class="chapter" data-level="39.3.1" data-path="teaching-data-science.html"><a href="teaching-data-science.html#teaching-and-learning-are-complex"><i class="fa fa-check"></i><b>39.3.1</b> Teaching and learning are complex</a></li>
<li class="chapter" data-level="39.3.2" data-path="teaching-data-science.html"><a href="teaching-data-science.html#learners-learn-many-different-things-consciously-and-unconsciously"><i class="fa fa-check"></i><b>39.3.2</b> Learners learn many different things (consciously and unconsciously)</a></li>
<li class="chapter" data-level="39.3.3" data-path="teaching-data-science.html"><a href="teaching-data-science.html#metacognition-is-important-even-though-it-sounds-more-sophisticated-than-it-is"><i class="fa fa-check"></i><b>39.3.3</b> Metacognition is important (even though it sounds more sophisticated than it is!)</a></li>
<li class="chapter" data-level="39.3.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#learning-strategies-matter"><i class="fa fa-check"></i><b>39.3.4</b> Learning strategies matter</a></li>
<li class="chapter" data-level="39.3.5" data-path="teaching-data-science.html"><a href="teaching-data-science.html#educators-can-help-students-to-learn"><i class="fa fa-check"></i><b>39.3.5</b> Educators can help students to learn</a></li>
</ul></li>
<li class="chapter" data-level="39.4" data-path="teaching-data-science.html"><a href="teaching-data-science.html#summary"><i class="fa fa-check"></i><b>39.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="40" data-path="learning-more.html"><a href="learning-more.html"><i class="fa fa-check"></i><b>40</b> Learning More</a><ul>
<li class="chapter" data-level="40.1" data-path="learning-more.html"><a href="learning-more.html#introduction-7"><i class="fa fa-check"></i><b>40.1</b> Introduction</a></li>
<li class="chapter" data-level="40.2" data-path="learning-more.html"><a href="learning-more.html#adopt-a-growth-mindset"><i class="fa fa-check"></i><b>40.2</b> Adopt a growth mindset</a></li>
<li class="chapter" data-level="40.3" data-path="learning-more.html"><a href="learning-more.html#discover-new-information"><i class="fa fa-check"></i><b>40.3</b> Discover new information</a></li>
<li class="chapter" data-level="40.4" data-path="learning-more.html"><a href="learning-more.html#ask-for-help"><i class="fa fa-check"></i><b>40.4</b> Ask for help</a></li>
<li class="chapter" data-level="40.5" data-path="learning-more.html"><a href="learning-more.html#discussion-forums"><i class="fa fa-check"></i><b>40.5</b> Discussion forums</a></li>
<li class="chapter" data-level="40.6" data-path="learning-more.html"><a href="learning-more.html#github-repositories"><i class="fa fa-check"></i><b>40.6</b> GitHub repositories</a></li>
<li class="chapter" data-level="40.7" data-path="learning-more.html"><a href="learning-more.html#share-what-youve-learned"><i class="fa fa-check"></i><b>40.7</b> Share what you’ve learned</a></li>
<li class="chapter" data-level="40.8" data-path="learning-more.html"><a href="learning-more.html#where-to-share"><i class="fa fa-check"></i><b>40.8</b> Where to share</a></li>
<li class="chapter" data-level="40.9" data-path="learning-more.html"><a href="learning-more.html#welcome-others"><i class="fa fa-check"></i><b>40.9</b> Welcome others</a></li>
<li class="chapter" data-level="40.10" data-path="learning-more.html"><a href="learning-more.html#references-2"><i class="fa fa-check"></i><b>40.10</b> References</a></li>
<li class="chapter" data-level="40.11" data-path="learning-more.html"><a href="learning-more.html#data-science-courses"><i class="fa fa-check"></i><b>40.11</b> Data science courses</a></li>
<li class="chapter" data-level="40.12" data-path="learning-more.html"><a href="learning-more.html#education-resources"><i class="fa fa-check"></i><b>40.12</b> Education resources</a></li>
<li class="chapter" data-level="40.13" data-path="learning-more.html"><a href="learning-more.html#data-visualization"><i class="fa fa-check"></i><b>40.13</b> Data visualization</a></li>
<li class="chapter" data-level="40.14" data-path="learning-more.html"><a href="learning-more.html#programming-with-r"><i class="fa fa-check"></i><b>40.14</b> Programming with R</a></li>
<li class="chapter" data-level="40.15" data-path="learning-more.html"><a href="learning-more.html#package-vignettes"><i class="fa fa-check"></i><b>40.15</b> Package vignettes</a></li>
<li class="chapter" data-level="40.16" data-path="learning-more.html"><a href="learning-more.html#statistics"><i class="fa fa-check"></i><b>40.16</b> Statistics</a></li>
<li class="chapter" data-level="40.17" data-path="learning-more.html"><a href="learning-more.html#places-to-share-your-work"><i class="fa fa-check"></i><b>40.17</b> Places to share your work</a></li>
<li class="chapter" data-level="40.18" data-path="learning-more.html"><a href="learning-more.html#learning-communities"><i class="fa fa-check"></i><b>40.18</b> Learning communities</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science in Education Using R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="how-have-child-counts-changed-over-time" class="section level1">
<h1><span class="header-section-number">25</span> How Have Child Counts Changed Over Time?</h1>
<p>In the last section we focused on importing our dataset. In this section, we will turn to exploring it. First, we’ll use visualization to explore the number of students in special education over time. In particular, we’ll compare the count of male and female students. Next, we’ll use what we learn from our visualizations to quantify any differences that we see.</p>
<div id="visualize-the-dataset" class="section level2">
<h2><span class="header-section-number">25.1</span> Visualize the Dataset</h2>
<p>Showing this many states in a plot can be overwhelming, so to start we’ll make a subset of the dataset. We can use a function in the <code>dplyr</code> package called <code>top_n()</code> to help us learn which states have the highest average count of special education students:</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb250-1" title="1">child_counts <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb250-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(state) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb250-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">mean_count =</span> <span class="kw">mean</span>(total)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb250-4" title="4"><span class="st">    </span><span class="kw">top_n</span>(<span class="dv">6</span>, mean_count)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   state                                            mean_count
##   &lt;chr&gt;                                                 &lt;dbl&gt;
## 1 california                                          180879.
## 2 florida                                              92447.
## 3 new york                                            121751.
## 4 pennsylvania                                         76080.
## 5 texas                                               115593.
## 6 us, outlying areas, and freely associated states   1671931.</code></pre>
<p>These six states have the highest mean count of students in special education over the six years we are examining. For reasons we will see in a later visualization, we are going to exclude outlying areas and freely associated states. That leaves us us with five states: California, Florida, New York, Pennsylvania, and Texas. We can remove all other states but these by using <code>filter()</code>. We’ll call this new dataset <code>high_count</code>:</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb252-1" title="1">high_count &lt;-<span class="st"> </span>child_counts <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb252-2" title="2"><span class="st">    </span><span class="kw">filter</span>(state <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;california&quot;</span>, <span class="st">&quot;florida&quot;</span>, <span class="st">&quot;new york&quot;</span>, <span class="st">&quot;pennsylvania&quot;</span>, <span class="st">&quot;texas&quot;</span>))</a></code></pre></div>
<p>Now we can use <code>high_count</code> to do some initial exploration. Our analysis is about comparing counts of male and female students in special education, but visualization is also a great way to explore related curiosities. You may surprise yourself with what you find when visualizing your datasets. You might come up with more interesting hypotheses, find that your initial hypothesis requires more data transformation, or find interesting subsets of the data–we saw a little of that in the surprisingly high <code>mean_count</code> of freely associated states in the <code>state</code> column. Let your curiosity and intuition drive this part of the analysis. It’s one of the activities that makes data analysis a creative process.</p>
<p>In that spirit, we’ll start by visualizing specific genders and age groups. Feel free to try these, but also try the other student groups for practice and more exploration.</p>
<p>Start by copying and running this code in your console to see what it does:</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb253-1" title="1">high_count <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb253-2" title="2"><span class="st">    </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;f&quot;</span>, age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb253-3" title="3"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> total, <span class="dt">color =</span> state)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb253-4" title="4"><span class="st">    </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb253-5" title="5"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Count of female students in special education over time&quot;</span>, </a>
<a class="sourceLine" id="cb253-6" title="6">         <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/total%20female%20students%20over%20time-1.png" width="672" /></p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb254-1" title="1">    <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>That gives us a plot that has the years in the x-axis and a count of female students in the y-axis. Each line takes a different color based on the state it represents.</p>
<p>Let’s look at that closer: We used <code>filter</code> to subset our dataset for students who are female and ages 6 to 21. We used <code>aes</code> to connect visual elements of our plot to our data. We connected the x-axis to <code>year</code>, the y-axis to <code>total</code>, and the color of the line to <code>state</code>.</p>
<p>It’s worth calling out one more thing, since it’s a technique we’ll be using as we explore further. Note here that, instead of storing our new dataset in a new variable, we filter the dataset then use the pipe operator <code>%&gt;%</code> to feed it to <code>ggplot</code>. Since we’re exploring freely, we don’t need to create a lot of new variables we probably won’t need later.</p>
<p>We can also try the same plot, but subsetting for male students instead. We can use the same code we used for the last plot, but filter for the value “m” in the <code>gender</code> field:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb255-1" title="1">high_count <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb255-2" title="2"><span class="st">    </span><span class="kw">filter</span>(gender <span class="op">==</span><span class="st"> &quot;m&quot;</span>, age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb255-3" title="3"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> total, <span class="dt">color =</span> state)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb255-4" title="4"><span class="st">    </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb255-5" title="5"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Count of male students in special education over time&quot;</span>, </a>
<a class="sourceLine" id="cb255-6" title="6">         <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/total%20male%20students%20over%20time-1.png" width="672" /></p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb256-1" title="1">  <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>We’ve looked at each gender separately. What do these lines look like if we visualized the total amount of students each year per state? To do that, we’ll need to add both gender values together and both age group values together. We’ll do this using a very common combination of functions: <code>group_by</code> and <code>summarise</code>.</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb257-1" title="1">high_count <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb257-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(year, state) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb257-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb257-4" title="4"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> n, <span class="dt">color =</span> state)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb257-5" title="5"><span class="st">    </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/total%20students%20over%20time-1.png" width="672" /></p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb258-1" title="1">  <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>So far we’ve looked at a few ways to count students over time. In each plot, we see that while counts have grown overall for all states, each state has different sized populations. Let’s see if we can summarize that difference by looking at the median student count for each state over the years:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb259-1" title="1">high_count <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb259-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(year, state) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb259-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">n =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb259-4" title="4"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> state, <span class="dt">y =</span> n)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb259-5" title="5"><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb259-6" title="6"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Median student count&quot;</span>,</a>
<a class="sourceLine" id="cb259-7" title="7">         <span class="dt">subtitle =</span> <span class="st">&quot;All ages and genders&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/median%20total%20per%20state-1.png" width="672" /></p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb260-1" title="1">  <span class="co">#theme_dataedu() </span></a></code></pre></div>
<p>The boxplots show us what we might have expected from our <code>freqpoly</code> plots before it. The highest median student count over time is California and the lowest is Pennsylvania.</p>
<p>What have we learned about our data so far? The five states in the US with the highest total student counts (not including outlying areas and freely associated states) do not have similar counts to each other. The student counts for each state also appear to have grown over time.</p>
<p>But how can we start comparing the male student count to the female student count? One way is to use a ratio:</p>
<blockquote>
<p>In mathematics, a ratio is a relationship between two numbers indicating how many times the first number contains the second.
Wikpedia</p>
</blockquote>
<p>We can use the count of male students in each state and divide it by the count of each female student. The result is the number of times male students are in special education more or less than the female students in the same state and year. Our coding strategy will be to</p>
<ul>
<li>Use <code>spread</code> to create separate columns for male and female students.</li>
<li>Use <code>mutate</code> to create a new variable called <code>ratio</code>. The values in this column will be the result of dividing the count of male students by the count of female students</li>
</ul>
<p>Note here that we can also accomplish this comparison by dividing the number of female students by the number of male students. In this case, the result would be the number of times female students are in special education more or less than male students.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb261-1" title="1">high_count <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb261-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(year, state, gender) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb261-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">total =</span> <span class="kw">sum</span>(total)) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb261-4" title="4"><span class="st">    </span><span class="co"># Create new columns for male and female student counts</span></a>
<a class="sourceLine" id="cb261-5" title="5"><span class="st">    </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb261-6" title="6"><span class="st">    </span><span class="co"># Create a new ratio column</span></a>
<a class="sourceLine" id="cb261-7" title="7"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">ratio =</span> m <span class="op">/</span><span class="st"> </span>f) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb261-8" title="8"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> ratio, <span class="dt">color =</span> state)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb261-9" title="9"><span class="st">    </span><span class="kw">geom_freqpoly</span>(<span class="dt">stat =</span> <span class="st">&quot;identity&quot;</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb261-10" title="10"><span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="fl">1.5</span>, <span class="fl">2.5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb261-11" title="11"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Male student to female student ratio over time&quot;</span>, </a>
<a class="sourceLine" id="cb261-12" title="12">         <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/male%20to%20female%20ratio%20over%20time-1.png" width="672" /></p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb262-1" title="1">  <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>By visually inspecting, we can hypothesize that there was no significant change in the male to female ratio between the years 2012 and 2017. But very often we want to understand the underlying properties of our education dataset. We can do this by quantifying the relationship between two variables. In the next section, we’ll explore ways to quantify the relationship between male student counts and female student counts.</p>
</div>
<div id="model-the-dataset" class="section level2">
<h2><span class="header-section-number">25.2</span> Model the Dataset</h2>
<p>When you visualize your datasets, you are exploring possible relationships between variables. But sometimes visualizations can be misleading because of the way we perceive graphics. In his book <em>Data Visuzliation: A Practical Introduction</em>, Kieran Healy (2019) teaches us that</p>
<blockquote>
<p>Visualizations encode numbers in lines, shapes, and colors. That means that our interpretation of these encodings is partly conditional on how we perceive geometric shapes and relationships generally.</p>
</blockquote>
<p>What are some ways we can combat these errors of perception and at the same time draw substantive conclusions about our education dataset? When you spot a possible relationship between variables, the relationship between female and male counts for example, you’ll want to quantify that relationship by fitting a statisitcal model. Practically speaking, this means you are selecting a distribution that represents your dataset reasonably well. This distribution will help you quantify and predict relationships between variables. This is an important step in the analytic process, because it acts as a check on what you saw in your exploratory visualizations.</p>
<p>In this example, we’ll follow our intuition about the relationship between male and female student counts in our special education dataset. In particular, we’ll test the hypothesis that this ratio has decreased over the years. Fitting a linear regression model that estimates the year as a predictor of the male to female ratio will help us do just that.</p>
<div id="do-we-have-enough-information-for-our-model" class="section level3">
<h3><span class="header-section-number">25.2.1</span> Do we have enough information for our model?</h3>
<p>At the start of this section, we chose to exclude outlying areas and freely associated states. This visualization suggests that there are some states that have a child count so high it leaves a gap in the x-axis values. This can be problematic when we try to interpret our model later. Here’s a plot of female students compared to male students. Note that the relationship appears linear, but there is a large gap in the distribution of female student counts somewhere bewteen the values of 250,000 and 1,750,000:</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb263-1" title="1">child_counts <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb263-2" title="2"><span class="st">    </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb263-3" title="3"><span class="st">    </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb263-4" title="4"><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> f, <span class="dt">y =</span> m)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb263-5" title="5"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> <span class="fl">.5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb263-6" title="6"><span class="st">    </span><span class="kw">geom_smooth</span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb263-7" title="7"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Comparison of female students to male students in special education&quot;</span>, </a>
<a class="sourceLine" id="cb263-8" title="8">         <span class="dt">subtitle =</span> <span class="st">&quot;Counts of students in each state, ages 6-21&quot;</span>, </a>
<a class="sourceLine" id="cb263-9" title="9">         <span class="dt">x =</span> <span class="st">&quot;Female students&quot;</span>, </a>
<a class="sourceLine" id="cb263-10" title="10">         <span class="dt">y =</span> <span class="st">&quot;Male students&quot;</span>, </a>
<a class="sourceLine" id="cb263-11" title="11">         <span class="dt">caption =</span> <span class="st">&quot;Data: US Dept of Education&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="data-science-in-education_files/figure-html/plot%20female%20students%20to%20male%20students-1.png" width="672" /></p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb265-1" title="1">  <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>If you think of each potential point on the linear regression line as a ratio of male to female students, you’ll notice that we don’t know a whole lot about what happens in states where there are between 250,000 and 1,750,000 female students in any given year.</p>
<p>To learn more about what’s happening in our dataset, we can filter it for only states that have more than 500,000 female students in any year:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb266-1" title="1">child_counts <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb266-2" title="2"><span class="st">    </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb266-3" title="3"><span class="st">    </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb266-4" title="4"><span class="st">    </span><span class="kw">filter</span>(f <span class="op">&gt;</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb266-5" title="5"><span class="st">    </span><span class="kw">select</span>(year, state, age, f, m)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 5
##   year       state                              age                f      m
##   &lt;date&gt;     &lt;chr&gt;                              &lt;chr&gt;          &lt;dbl&gt;  &lt;dbl&gt;
## 1 2012-01-01 us, outlying areas, and freely as… Total, Age … 1933619 3.89e6
## 2 2013-01-01 us, outlying areas, and freely as… Total, Age … 1937726 3.88e6
## 3 2014-01-01 us, outlying areas, and freely as… Total, Age … 1965204 3.92e6
## 4 2015-01-01 us, outlying areas, and freely as… Total, Age … 2007174 3.98e6
## 5 2016-01-01 us, outlying areas, and freely as… Total, Age … 2014120 3.97e6
## 6 2017-01-01 us, outlying areas, and freely as… Total, Age … 2051438 4.02e6</code></pre>
<p>This is where we discover that each of the data points in the upper right hand corner of the plot are from the state value “us, us, outlying areas, and freely associated states”. If we remove these outliers, we have a distribution of female students that looks more complete.</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb268-1" title="1">child_counts <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb268-2" title="2"><span class="st">    </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-3" title="3"><span class="st">    </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb268-4" title="4"><span class="st">    </span><span class="co"># Filter for female student counts less than 500,000</span></a>
<a class="sourceLine" id="cb268-5" title="5"><span class="st">    </span><span class="kw">filter</span>(f <span class="op">&lt;=</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">%&gt;%</span></a>
<a class="sourceLine" id="cb268-6" title="6"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> f, <span class="dt">y =</span> m)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb268-7" title="7"><span class="st">    </span><span class="kw">geom_point</span>(<span class="dt">size =</span> <span class="dv">3</span>, <span class="dt">alpha =</span> <span class="fl">.5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb268-8" title="8"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Comparison of female students to male students in special education&quot;</span>, </a>
<a class="sourceLine" id="cb268-9" title="9">         <span class="dt">subtitle =</span> <span class="st">&quot;Counts of students in each state, ages 6-21.</span><span class="ch">\n</span><span class="st">Does not include outlying areas and freely associated states&quot;</span>, </a>
<a class="sourceLine" id="cb268-10" title="10">         <span class="dt">x =</span> <span class="st">&quot;Female students&quot;</span>, </a>
<a class="sourceLine" id="cb268-11" title="11">         <span class="dt">y =</span> <span class="st">&quot;Male students&quot;</span>, </a>
<a class="sourceLine" id="cb268-12" title="12">         <span class="dt">caption =</span> <span class="st">&quot;Data: US Dept of Education&quot;</span>)</a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/plot%20without%20outliers-1.png" width="672" /></p>
<p>This should allow us to fit a better model for the relationship between male and female student counts, albeit only the ones where the count of female students takes a value between 0 and 500,000.</p>
</div>
<div id="male-to-female-ratio-over-time" class="section level3">
<h3><span class="header-section-number">25.2.2</span> Male to Female Ratio Over Time</h3>
<p>Earlier we asked the question Do we have enough data points for the count of female students to learn about the ratio of female to male students? Similarly, we should ask the question Do we have enough data points across our year variable to learn about how this ratio has changed over time?</p>
<p>To answer that question, let’s start by making a new dataset that excludes any rows where the <code>f</code> variables has a value that is less than or equal to 500000. We’ll convert the <code>year</code> variable to a factor data type–we’ll see how this helps in a bit. We’ll also add a column called <code>ratio</code> that contains the male to female count ratio.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb269-1" title="1">model_data &lt;-<span class="st"> </span>child_counts <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb269-2" title="2"><span class="st">    </span><span class="kw">filter</span>(age <span class="op">==</span><span class="st"> &quot;Total, Age 6-21&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb269-3" title="3"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">year =</span> <span class="kw">as.factor</span>(<span class="kw">year</span>(year))) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb269-4" title="4"><span class="st">    </span><span class="kw">spread</span>(gender, total) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb269-5" title="5"><span class="st">    </span><span class="co"># Exclude outliers</span></a>
<a class="sourceLine" id="cb269-6" title="6"><span class="st">    </span><span class="kw">filter</span>(f <span class="op">&lt;=</span><span class="st"> </span><span class="dv">500000</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb269-7" title="7"><span class="st">    </span><span class="co"># Compute male student to female student ratio </span></a>
<a class="sourceLine" id="cb269-8" title="8"><span class="st">    </span><span class="kw">mutate</span>(<span class="dt">ratio =</span> m <span class="op">/</span><span class="st"> </span>f) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb269-9" title="9"><span class="st">    </span><span class="kw">select</span>(<span class="op">-</span><span class="kw">c</span>(age, disability))</a></code></pre></div>
<p>We can see how much data we have per year by using <code>count</code>:</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb270-1" title="1">model_data <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">count</span>(year)</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year      n
##   &lt;fct&gt; &lt;int&gt;
## 1 2012     59
## 2 2013     56
## 3 2014     56
## 4 2015     58
## 5 2016     57
## 6 2017     55</code></pre>
<p>Let’s visualize the ratio values across all years as an additional check. Note the use of <code>geom_jitter</code> to spread the points horizontally so we can estimate the quantities better:</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb272-1" title="1"><span class="kw">ggplot</span>(<span class="dt">data =</span> model_data, <span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> ratio)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-2" title="2"><span class="st">    </span><span class="kw">geom_jitter</span>(<span class="dt">alpha =</span> <span class="fl">.5</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb272-3" title="3"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Male to female ratio across years (jittered)&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/ratios%20across%20years-1.png" width="672" /></p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb273-1" title="1">  <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>Each year seems to have data points that can be considered when we fit the model. This means that there are enough data points to help us learn how the year variable predicts the ratio variable.</p>
<p>We fit the linear regression model by passing the argument <code>ratio ~ year</code> to the function <code>lm</code>. In R, the <code>~</code> usually indicates a formula. In this case, the formula is the variable <code>year</code> as a predictor of the variable <code>ratio</code>. The final argument we pass to <code>lm</code> is <code>data = model_data</code>, which tells R to look for the variables <code>ratio</code> and <code>year</code> in the dataset <code>model_data</code>. The results of the model are called a “model object.” We’ll store the model object in <code>ratio_year</code>:</p>
<div class="sourceCode" id="cb274"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb274-1" title="1">ratio_year &lt;-<span class="st"> </span><span class="kw">lm</span>(ratio <span class="op">~</span><span class="st"> </span>year, <span class="dt">data =</span> model_data)</a></code></pre></div>
<p>Each model object is filled with all sorts of model information. We can look at this information using the fuction <code>summary</code>:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb275-1" title="1"><span class="kw">summary</span>(ratio_year)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = ratio ~ year, data = model_data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.44025 -0.10138 -0.02810  0.05343  0.75737 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  2.03356    0.02200  92.418   &lt;2e-16 ***
## year2013    -0.01205    0.03153  -0.382   0.7027    
## year2014    -0.02372    0.03153  -0.752   0.4524    
## year2015    -0.03104    0.03125  -0.993   0.3213    
## year2016    -0.03964    0.03139  -1.263   0.2075    
## year2017    -0.05760    0.03168  -1.818   0.0699 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.169 on 335 degrees of freedom
## Multiple R-squared:  0.01215,    Adjusted R-squared:  -0.002594 
## F-statistic: 0.8241 on 5 and 335 DF,  p-value: 0.5332</code></pre>
<p>Here’s how we can interpret the <code>Estimate</code> column: The estimate of the <code>(Intercept)</code> is 2.03356, which is the estimated value of the <code>ratio</code> variable when the <code>year</code> variable is “2012”. Note that the value <code>year2012</code> isn’t present in the in the list of rownames. That’s because the <code>(Intercept)</code> row represents <code>year2012</code>. In linear regression models that use factor variables as predictors, the first level of the factor is the intercept. Sometimes this level is called a “dummy variable”. The remaining rows of the model output show how much each year differs from the intercept, 2012. For example, <code>year2013</code> has an estimate of -0.01205, which suggests that on average the value of <code>ratio</code> is .01205 less than 2.03356. On average, the ratio of <code>year2014</code> is .02372 less than 2.03356. The <code>t value</code> column tells us the size of difference between the estimated value of the ratio for each year and the estimated value of the ratio of the intercept. Generally speaking, the larger the t value, the larger the chance that any difference between the coefficient of a factor level and the intercept are significant.</p>
<p>Though the relationship between <code>year</code> as a preditor of <code>ratio</code> is not linear (recall our previous plot), the linear regression model still gives us useful information. We fit a linear regression model to a factor variable, like <code>year</code>, as a predictor of a continuous variable, like<code>ratio</code>. In doing so, we got the average <code>ratio</code> at every value of <code>year</code>. We can verify this by taking the mean <code>ratio</code> of ever <code>year</code>:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb277-1" title="1">model_data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb277-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb277-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">mean_ratio =</span> <span class="kw">mean</span>(ratio))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year  mean_ratio
##   &lt;fct&gt;      &lt;dbl&gt;
## 1 2012        2.03
## 2 2013        2.02
## 3 2014        2.01
## 4 2015        2.00
## 5 2016        1.99
## 6 2017        1.98</code></pre>
<p>This verifies that our intercept, the value of <code>ratio</code> during the year 2012, is 2.033563 and the value of <code>ratio</code> for 2013 is .01205 less than that of 2012 on average. Fitting the model gives us more details about these mean ratio scores– namely the coefficient, t value, and p value. These values help us apply judgement when deciding if differences in <code>ratio</code> values suggest an underlying difference between years or simply differences you can expect from randomness. In this case, the absence of "*" in all rows except the Intercept row suggest that any differences occuring between years are within the range you’d expect by chance.</p>
<p>If we use <code>summary</code> again on our <code>model_data</code> dataset, we can verify the intercept again:</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb279-1" title="1">model_data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb279-2" title="2"><span class="st">    </span><span class="kw">filter</span>(year <span class="op">==</span><span class="st"> &quot;2012&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb279-3" title="3"><span class="st">    </span><span class="kw">summary</span>()</a></code></pre></div>
<pre><code>##    year       state                 f                m         
##  2012:59   Length:59          Min.   :   208   Min.   :   443  
##  2013: 0   Class :character   1st Qu.:  5606   1st Qu.: 11467  
##  2014: 0   Mode  :character   Median : 22350   Median : 44110  
##  2015: 0                      Mean   : 32773   Mean   : 65934  
##  2016: 0                      3rd Qu.: 38552   3rd Qu.: 77950  
##  2017: 0                      Max.   :198595   Max.   :414466  
##      ratio      
##  Min.   :1.710  
##  1st Qu.:1.927  
##  Median :1.994  
##  Mean   :2.034  
##  3rd Qu.:2.093  
##  Max.   :2.692</code></pre>
<p>The mean value of the <code>ratio</code> column when the <code>year</code> column is 2012 is 2.034, just like in the model output’s intercept row.</p>
<p>Lastly, we may want to communicate to a larger audience that there were roughly twice amount of male students in this datset than female students and that this did not change significantly between the years 2012 and 2017. When you are not communicating to an audience of other data scientists, it’s helpful to illustrate your point without the technical details of the model output. Think of yourself as an interpreter: since you can speak the language of model outputs and the language of data visualization, your challenge is to take what you learned from the model output and tell that story in a way that is meaningful to your non-data scientist audience.</p>
<p>There are many ways to do this, but we’ll choose boxplots to show our audience that there was roughly twice as many male students in special education than female students between 2012 and 2017. For our purposes, let’s verify this by looking at the median male to female ratio for each year:</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb281-1" title="1">model_data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb281-2" title="2"><span class="st">    </span><span class="kw">group_by</span>(year) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb281-3" title="3"><span class="st">    </span><span class="kw">summarise</span>(<span class="dt">median_ratio =</span> <span class="kw">median</span>(ratio))</a></code></pre></div>
<pre><code>## # A tibble: 6 x 2
##   year  median_ratio
##   &lt;fct&gt;        &lt;dbl&gt;
## 1 2012          1.99
## 2 2013          1.99
## 3 2014          1.98
## 4 2015          1.98
## 5 2016          1.97
## 6 2017          1.96</code></pre>
<p>Now let’s visualize this using our boxplots:</p>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb283-1" title="1">model_data <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb283-2" title="2"><span class="st">    </span><span class="kw">gather</span>(gender, students, <span class="kw">c</span>(f, m)) <span class="op">%&gt;%</span><span class="st"> </span></a>
<a class="sourceLine" id="cb283-3" title="3"><span class="st">    </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x =</span> year, <span class="dt">y =</span> students, <span class="dt">color =</span> gender)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb283-4" title="4"><span class="st">    </span><span class="kw">geom_boxplot</span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb283-5" title="5"><span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">labels =</span> scales<span class="op">::</span>comma) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb283-6" title="6"><span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Median male and female student counts in special education&quot;</span>, </a>
<a class="sourceLine" id="cb283-7" title="7">         <span class="dt">subtitle =</span> <span class="st">&quot;Ages 6-21. Does not include outlying areas and freely associated states&quot;</span>, </a>
<a class="sourceLine" id="cb283-8" title="8">         <span class="dt">x =</span> <span class="st">&quot;&quot;</span>, </a>
<a class="sourceLine" id="cb283-9" title="9">         <span class="dt">y =</span> <span class="st">&quot;&quot;</span>, </a>
<a class="sourceLine" id="cb283-10" title="10">         <span class="dt">caption =</span> <span class="st">&quot;Data: US Dept of Education&quot;</span>) <span class="co">#+</span></a></code></pre></div>
<p><img src="data-science-in-education_files/figure-html/visualize%20female%20to%20male%20ratio-1.png" width="672" /></p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb284-1" title="1">  <span class="co">#theme_dataedu()</span></a></code></pre></div>
<p>Once we learned from our model that male to female ratios did not change in any meaningful way from 2012 to 2017 and that the median ratio across states was about 2 male students to every female student, we can present these two ideas using this plot. When discussing the plot, it helps to have your model output in your notes so you can reference specific coefficient estimates when needed.</p>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="cleaning-the-dataset.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="aggregate-data-as-context-for-student-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
